--- 
title: "Learn R through examples"
author: "Xijin Ge, Jianli Qi and Rong Fan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: gexijin/learnR
description: "This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome."
---
   

# Preface{-}
Aimed at total beginners, this book is written based on the philosophy that people learn faster when they are shown examples and case studies. The book largely centers on the analysis of several datasets. We start with small and clean datasets and gradually transition into big, messy ones. With each dataset, we hope to tell a story through the analysis. We invite you, our courageous reader, to take on this journey with us. Motivated readers, such as biologists, could easily work their way through this book and learn by themselves. I would encourage you to type in the example code and see the outputs. And then work on the challnges and exercises. 

It originally started as materials for 2-hour hands-on workshops intended to give a quick introduction/demonstration for students and researchers who are totally new to R. The workshop has been given many times to different audiences ranging from high-school students to mathematicians. For a 2-hour session, I have to keep it gentle, interactive, and fun, sometimes at the expense of rigor. Instead of explaining all the rules, grammar, and syntax, I found it is easier to focus on one dataset and walk them through some of the analyses possible with R. 

This material later evolved into as a one-credit online class and then a three credit class. We stick with the unconventional approach of focusing on datasets and examples. 

Any comments and suggestions to make this book better would be welcome. This includes typos, errors, and organizational issues. The best place to reach out to us is through the [GitHub issues page](https://github.com/gexijin/learnR/issues). If you do not like to create yet another account, you can email us <Xijin.Ge@sdstate.edu>. 


Chapter 1  Step into R program

Chapter 2  Visualizing data set

Chapter 3  Data structures

Chapter 4  Data importing 

Chapter 5  Heart attack data set I

Chapter 6  Heart attack data set II

Chapter 7  Advanced topics

Chapter 8  State data set

Chapter 9  Game sale data set

Chapter 10  Employee salary data set


