<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Learning R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Learning R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learning R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  

<meta name="author" content="Xijin Ge">


<meta name="date" content="2019-01-07">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="analyzing-iris-flower-dataset-i.html">
<link rel="next" href="data-importing.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Index</a></li>
<li class="chapter" data-level="1" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html"><i class="fa fa-check"></i><b>1</b> Analyzing iris flower dataset I</a><ul>
<li class="chapter" data-level="1.1" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#data-frames-have-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.1</b> “Data frames” have rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.2" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.2</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.3" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#students-t-test"><i class="fa fa-check"></i><b>1.3</b> Student’s T-test</a></li>
<li class="chapter" data-level="1.4" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#test-for-normal-distribution"><i class="fa fa-check"></i><b>1.4</b> Test for normal distribution</a></li>
<li class="chapter" data-level="1.5" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#analyzing-a-column-of-categorical-values"><i class="fa fa-check"></i><b>1.5</b> Analyzing a column of categorical values</a></li>
<li class="chapter" data-level="1.6" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#analyzing-the-relationship-between-two-columns-of-numbers"><i class="fa fa-check"></i><b>1.6</b> Analyzing the relationship between two columns of numbers</a><ul>
<li class="chapter" data-level="1.6.1" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#quantitative-analyses-of-correlation"><i class="fa fa-check"></i><b>1.6.1</b> Quantitative analyses of correlation</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#visualizing-and-testing-the-differences-in-groups"><i class="fa fa-check"></i><b>1.7</b> Visualizing and testing the differences in groups</a></li>
<li class="chapter" data-level="1.8" data-path="analyzing-iris-flower-dataset-i.html"><a href="analyzing-iris-flower-dataset-i.html#test-the-difference-among-multiple-groups-analysis-of-variance-anova"><i class="fa fa-check"></i><b>1.8</b> Test the difference among multiple groups (Analysis of Variance: ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html"><i class="fa fa-check"></i><b>2</b> Analyzing iris flower data set II</a><ul>
<li class="chapter" data-level="2.1" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#visualizing-multivariate-data"><i class="fa fa-check"></i><b>2.1</b> Visualizing multivariate data</a><ul>
<li class="chapter" data-level="2.1.1" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#a-matrix-only-contains-numbers"><i class="fa fa-check"></i><b>2.1.1</b> A Matrix only contains numbers</a></li>
<li class="chapter" data-level="2.1.2" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.1.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.1.3" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#heatmap"><i class="fa fa-check"></i><b>2.1.3</b> Heatmap</a></li>
<li class="chapter" data-level="2.1.4" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#star-plot-segment-diagrams"><i class="fa fa-check"></i><b>2.1.4</b> Star plot Segment diagrams</a></li>
<li class="chapter" data-level="2.1.5" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#segment-diagrams"><i class="fa fa-check"></i><b>2.1.5</b> Segment diagrams</a></li>
<li class="chapter" data-level="2.1.6" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#parallel-coordinate-plot"><i class="fa fa-check"></i><b>2.1.6</b> Parallel coordinate plot</a></li>
<li class="chapter" data-level="2.1.7" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#box-plot"><i class="fa fa-check"></i><b>2.1.7</b> Box plot</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#combining-plots"><i class="fa fa-check"></i><b>2.2</b> Combining plots</a></li>
<li class="chapter" data-level="2.3" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#plot-using-principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.3</b> Plot using principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.4" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#first-attempt-at-ggplot2"><i class="fa fa-check"></i><b>2.4</b> First attempt at ggplot2</a></li>
<li class="chapter" data-level="2.5" data-path="analyzing-iris-flower-data-set-ii.html"><a href="analyzing-iris-flower-data-set-ii.html#classification-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.5</b> Classification: Predicting the odds of binary outcomes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-importing.html"><a href="data-importing.html"><i class="fa fa-check"></i><b>3</b> Data importing</a><ul>
<li class="chapter" data-level="3.1" data-path="data-importing.html"><a href="data-importing.html#enter-data-manually"><i class="fa fa-check"></i><b>3.1</b> Enter data manually</a></li>
<li class="chapter" data-level="3.2" data-path="data-importing.html"><a href="data-importing.html#reading-data-from-file-using-import-dataset-in-rstudio"><i class="fa fa-check"></i><b>3.2</b> Reading data from file using Import dataset in Rstudio</a></li>
<li class="chapter" data-level="3.3" data-path="data-importing.html"><a href="data-importing.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>3.3</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="3.4" data-path="data-importing.html"><a href="data-importing.html#reading-file-using-read.table-read.csv-etc."><i class="fa fa-check"></i><b>3.4</b> Reading file using read.table, read.csv, etc.</a></li>
<li class="chapter" data-level="3.5" data-path="data-importing.html"><a href="data-importing.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>3.5</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="3.6" data-path="data-importing.html"><a href="data-importing.html#recommended-workflow-for-every-project"><i class="fa fa-check"></i><b>3.6</b> Recommended workflow for EVERY project</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>4</b> Analyzing heart attack data set I</a><ul>
<li class="chapter" data-level="4.1" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>4.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="4.2" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>4.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="4.3" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>4.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="4.4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>4.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="4.5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>4.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html"><i class="fa fa-check"></i><b>5</b> Analyzing heart attack data set II</a><ul>
<li class="chapter" data-level="5.1" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>5.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="5.2" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>5.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="5.3" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>5.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="5.4" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>5.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="5.5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>5.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html"><i class="fa fa-check"></i><b>6</b> Intruduction to basic R</a><ul>
<li class="chapter" data-level="6.1" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#expressions"><i class="fa fa-check"></i><b>6.1</b> Expressions</a></li>
<li class="chapter" data-level="6.2" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#logical-values"><i class="fa fa-check"></i><b>6.2</b> Logical Values</a></li>
<li class="chapter" data-level="6.3" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#variables"><i class="fa fa-check"></i><b>6.3</b> Variables</a></li>
<li class="chapter" data-level="6.4" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#functions"><i class="fa fa-check"></i><b>6.4</b> Functions</a></li>
<li class="chapter" data-level="6.5" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>6.5</b> Looking for Help and Example Code</a></li>
<li class="chapter" data-level="6.6" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#vectors"><i class="fa fa-check"></i><b>6.6</b> Vectors</a><ul>
<li class="chapter" data-level="6.6.1" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#sequence-vectors"><i class="fa fa-check"></i><b>6.6.1</b> Sequence Vectors</a></li>
<li class="chapter" data-level="6.6.2" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#scatter-plots"><i class="fa fa-check"></i><b>6.6.2</b> Scatter Plots</a></li>
<li class="chapter" data-level="6.6.3" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#missing-data-is-represented-as-na"><i class="fa fa-check"></i><b>6.6.3</b> Missing data is represented as NA</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#lists"><i class="fa fa-check"></i><b>6.7</b> Lists</a></li>
<li class="chapter" data-level="6.8" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>6.8</b> Strings and string vectors</a></li>
<li class="chapter" data-level="6.9" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#matrix-operations"><i class="fa fa-check"></i><b>6.9</b> Matrix operations</a></li>
<li class="chapter" data-level="6.10" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#operations-on-data-frames"><i class="fa fa-check"></i><b>6.10</b> Operations on data frames</a></li>
<li class="chapter" data-level="6.11" data-path="intruduction-to-basic-r.html"><a href="intruduction-to-basic-r.html#for-more-in-depth-exercises"><i class="fa fa-check"></i><b>6.11</b> For more in-depth exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vectors-1.html"><a href="vectors-1.html"><i class="fa fa-check"></i><b>7</b> Vectors</a></li>
<li class="chapter" data-level="8" data-path="matrics-and-arrays.html"><a href="matrics-and-arrays.html"><i class="fa fa-check"></i><b>8</b> Matrics and arrays</a></li>
<li class="chapter" data-level="9" data-path="lists-1.html"><a href="lists-1.html"><i class="fa fa-check"></i><b>9</b> Lists</a></li>
<li class="chapter" data-level="10" data-path="data-frames.html"><a href="data-frames.html"><i class="fa fa-check"></i><b>10</b> Data frames</a></li>
<li class="chapter" data-level="11" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>11</b> Strings</a></li>
<li class="chapter" data-level="12" data-path="functions-1.html"><a href="functions-1.html"><i class="fa fa-check"></i><b>12</b> Functions</a><ul>
<li class="chapter" data-level="12.1" data-path="functions-1.html"><a href="functions-1.html#define-your-very-own-r-function"><i class="fa fa-check"></i><b>12.1</b> Define your very own R function</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html"><i class="fa fa-check"></i><b>13</b> Visualizing cars data set</a><ul>
<li class="chapter" data-level="13.1" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>13.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="13.2" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#plain-vs.refined-graphics"><i class="fa fa-check"></i><b>13.2</b> Plain vs. refined graphics</a></li>
<li class="chapter" data-level="13.3" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#visualizing-the-mtcars-dataset-using-scatter-plot"><i class="fa fa-check"></i><b>13.3</b> Visualizing the mtcars dataset using scatter plot</a></li>
<li class="chapter" data-level="13.4" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#customize-scatterplots"><i class="fa fa-check"></i><b>13.4</b> Customize scatterplots</a></li>
<li class="chapter" data-level="13.5" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#d-scatter-plot"><i class="fa fa-check"></i><b>13.5</b> 3D scatter plot</a></li>
<li class="chapter" data-level="13.6" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#detect-correlations-among-variables"><i class="fa fa-check"></i><b>13.6</b> Detect correlations among variables</a></li>
<li class="chapter" data-level="13.7" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#barplot-with-error-bars"><i class="fa fa-check"></i><b>13.7</b> Barplot with error bars</a></li>
<li class="chapter" data-level="13.8" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#visualizing-correlation-between-categorical-variables"><i class="fa fa-check"></i><b>13.8</b> Visualizing correlation between categorical variables</a></li>
<li class="chapter" data-level="13.9" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#representing-data-using-faces.-serious-scientific-research-only"><i class="fa fa-check"></i><b>13.9</b> Representing data using faces. Serious scientific research only!</a></li>
<li class="chapter" data-level="13.10" data-path="visualizing-cars-data-set.html"><a href="visualizing-cars-data-set.html#hierarchical-clustering"><i class="fa fa-check"></i><b>13.10</b> Hierarchical clustering</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>14</b> Tidyverse</a><ul>
<li class="chapter" data-level="14.1" data-path="tidyverse.html"><a href="tidyverse.html#tidyverse-is-collection-of-powerful-r-packages"><i class="fa fa-check"></i><b>14.1</b> Tidyverse is collection of powerful R packages</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learning R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analyzing-iris-flower-data-set-ii" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Analyzing iris flower data set II</h1>
<div id="visualizing-multivariate-data" class="section level2">
<h2><span class="header-section-number">2.1</span> Visualizing multivariate data</h2>
<div id="a-matrix-only-contains-numbers" class="section level3">
<h3><span class="header-section-number">2.1.1</span> A Matrix only contains numbers</h3>
<p>While data frames can have a mix of numbers and characters in different columns, a <strong>matrix is often only contain numbers</strong>. Let’s extract first 4 columns from the data frame iris and convert to a matrix:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])  <span class="co"># convert to matrix</span>
<span class="kw">colMeans</span>(x)  <span class="co"># column means for matrix</span></code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##     5.843333     3.057333     3.758000     1.199333</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colSums</span>(x)</code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##        876.5        458.6        563.7        179.9</code></pre>
<p>The same thing can be done with rows via <strong>rowMeans(x)</strong> and <strong>rowSums(x)</strong>.</p>
<p>Here are some matrix algebra.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>iris[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]  <span class="co"># extract the first 10 rows of iris data in columns 1 to 4. </span>
y
<span class="kw">t</span>(y)          <span class="co"># transpose </span>
z &lt;-<span class="st"> </span>y <span class="op">+</span><span class="st"> </span><span class="dv">5</span>    <span class="co"># add a number to all numbers in a matrix</span>
z &lt;-<span class="st"> </span>y <span class="op">*</span><span class="st"> </span><span class="fl">1.5</span>  <span class="co"># multiply a factor </span>
z <span class="op">+</span><span class="st"> </span>y         <span class="co"># subtracting corresponding elements </span>
y <span class="op">*</span><span class="st"> </span>z         <span class="co"># multiplying corresponding elements</span>
y &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(y)  <span class="co"># convert the data.frame y to a matrix</span>
z &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(z)  <span class="co"># convert the data.frame z to a matrix</span>
y <span class="op">%*%</span><span class="st"> </span><span class="kw">t</span>(z)         <span class="co"># Matrix multiplication, I never used this.</span></code></pre></div>
</div>
<div id="scatter-plot-matrix" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Scatter plot matrix</h3>
<p>We can generate a matrix of scatter plots simply by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairs</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairs</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="dt">col =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[Species])  <span class="co"># Figure 1.10</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-36"></span>
<img src="book_files/figure-html/unnamed-chunk-36-1.png" alt="Scatter plot matrix." width="672" />
<p class="caption">
Figure 2.1: Scatter plot matrix.
</p>
</div>
<p><strong>Challenge 2a</strong>: Look at this large plot for a moment. What do you see? Provide interpretation of these scatter plots.</p>
</div>
<div id="heatmap" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Heatmap</h3>
<p><strong>Heatmaps</strong> with hierarchical clustering are my favorite way to visualize data matrices. The rows and columns are kept in place, values are coded by colors. Heatmaps can directly visualize millions of numbers in one plot. The hierarchical trees also shows the similarity among rows or columns: closely connected rows or columns are similar.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])   
<span class="kw">heatmap</span>(x, <span class="dt">scale =</span> <span class="st">&quot;column&quot;</span>)  <span class="co"># Heatmap with hierarchical clustering trees.  Numbers are scaled by column.</span></code></pre></div>
<p>If you are a perfectionist, here is how to fine-tune the graph. We define a function called ppc( ). As you may notice R works by calling the name of the function and the input to that function in parentheses. Multiple input parameters are separated by a comma. We also notice that the follow commands span several lines.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ppc &lt;-<span class="st"> </span><span class="cf">function</span>(x, ...){  <span class="co"># A distance function of 1-PPC (Pearson’s correlation coefficient)</span>
       <span class="kw">as.dist</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">cor</span>(<span class="kw">t</span>(x), <span class="dt">method =</span> <span class="st">&quot;pearson&quot;</span>))  
}
<span class="kw">heatmap</span>(x,                   <span class="co"># data, must be a matrix! </span>
        <span class="dt">scale   =</span> <span class="st">&quot;column&quot;</span>,  <span class="co"># transformed to have zero mean and unit standard deviation by column</span>
        <span class="dt">distfun =</span> ppc,       <span class="co"># use custom function to compute similarity between rows and columns</span>
        <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">2</span>),  <span class="co"># define the margins so that the column names show up completely</span>
        <span class="dt">RowSideColors =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[iris<span class="op">$</span>Species])   <span class="co"># add colored bar according to Species</span>
<span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="kw">levels</span>(iris<span class="op">$</span>Species), <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>))  <span class="co"># add legend in a separate line</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-39"></span>
<img src="images/img0207_heatmap.png" alt="Heatmaps and hierarchical clustering is a powerful technique for visualizing data matrix."  />
<p class="caption">
Figure 2.2: Heatmaps and hierarchical clustering is a powerful technique for visualizing data matrix.
</p>
</div>
<p>Note that yellow indicates relatively large numbers and red represents relatively small numbers. Rows or columns that are bracketed closer are more similar. So the trees display a hierarchy of similarities.</p>
<p>More advanced customization can be done with heatmap.2 in the gplots package. Below is another solution for a heatmap of the iris flower data set.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gplots)
hclust2 &lt;-<span class="st"> </span><span class="cf">function</span>(x, ...)
  <span class="kw">hclust</span>(x, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>, ...)
x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>( iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])
x &lt;-<span class="st"> </span><span class="kw">apply</span>(x, <span class="dv">2</span>, <span class="cf">function</span>(y) (y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)))
<span class="kw">heatmap.2</span>(x,    
            <span class="dt">hclustfun =</span> hclust2,  <span class="co"># use average linkage</span>
            <span class="dt">col =</span> <span class="kw">greenred</span>(<span class="dv">75</span>),   <span class="co">#color green red</span>
            <span class="dt">density.info =</span> <span class="st">&quot;none&quot;</span>, 
            <span class="dt">trace =</span> <span class="st">&quot;none&quot;</span>, 
            <span class="dt">scale =</span> <span class="st">&quot;none&quot;</span>, 
            <span class="dt">labRow =</span> <span class="ot">FALSE</span>,   <span class="co"># no row names</span>
            <span class="dt">RowSideColors =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[iris<span class="op">$</span>Species], 
            <span class="dt">srtCol =</span> <span class="dv">45</span>,    <span class="co"># column labels at 45 degree</span>
            <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">10</span>))  <span class="co"># bottom and right margins</span>
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="kw">levels</span>(iris<span class="op">$</span>Species),       
       <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>])</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:12-3"></span>
<img src="book_files/figure-html/12-3-1.png" alt="Heatmap for iris flower dataset." width="672" />
<p class="caption">
Figure 2.3: Heatmap for iris flower dataset.
</p>
</div>
</div>
<div id="star-plot-segment-diagrams" class="section level3">
<h3><span class="header-section-number">2.1.4</span> Star plot Segment diagrams</h3>
<p><strong>Star plot uses stars to visualize multidimensional data.</strong> Radar chart is a useful way to display multivariate observations with an arbitrary number of variables. Each observation is represented as a star-shaped figure with one ray for each variable. For a given observation, the length of each ray is made proportional to the size of that variable. The star plot is first used by Georg von Mayr in 1877!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span>iris [, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]
<span class="kw">stars</span>(x)         <span class="co"># do I see any diamonds?  I want the bigger one!</span>
<span class="kw">stars</span>(x, <span class="dt">key.loc =</span> <span class="kw">c</span>(<span class="dv">17</span>,<span class="dv">0</span>))    <span class="co"># What does this tell you?</span></code></pre></div>
<p><strong>Challenge 2b</strong>: Based on heatmap and the star plot, what is your overall impression regarding the differences among these 3 species of flowers?</p>
</div>
<div id="segment-diagrams" class="section level3">
<h3><span class="header-section-number">2.1.5</span> Segment diagrams</h3>
<p>The stars() function can also be used to generate segment diagrams, where each variable is used to generate colorful segments. The sizes of the segments are proportional to the measurements.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">stars</span>(x, <span class="dt">key.loc =</span> <span class="kw">c</span>(<span class="dv">18</span>,<span class="fl">0.5</span>), <span class="dt">draw.segments =</span> T )    
<span class="kw">stars</span>(state.x77, <span class="dt">draw.segments =</span> T, <span class="dt">key.loc =</span> <span class="kw">c</span>(<span class="dv">13</span>, <span class="fl">1.0</span>))  <span class="co"># Where is South Dakota?</span></code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:12-4"></span>
<img src="images/img1204_starsegment.png" alt="Star plots and segments diagrams."  />
<p class="caption">
Figure 2.4: Star plots and segments diagrams.
</p>
</div>
<p><strong>Challenge 2c</strong>: Re-produce the segments diagram of the state data and offer some interpretation regarding South Dakota compared with other states.</p>
</div>
<div id="parallel-coordinate-plot" class="section level3">
<h3><span class="header-section-number">2.1.6</span> Parallel coordinate plot</h3>
<p>Parallel coordinate plot is a straightforward way of visualizing multivariate data using lines.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span>iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]
<span class="kw">matplot</span>(<span class="kw">t</span>(x), <span class="dt">type =</span> <span class="st">&#39;l&#39;</span>,                <span class="co">#“l” is lower case L for “line”.</span>
        <span class="dt">col =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[iris<span class="op">$</span>Species])  <span class="co"># Species information is color coded</span>
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="kw">levels</span>(iris<span class="op">$</span>Species), <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>))  <span class="co"># add legend to figure.</span>
<span class="kw">text</span>(<span class="kw">c</span>(<span class="fl">1.2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="fl">3.8</span>), <span class="dv">0</span>, <span class="kw">colnames</span>(x))  <span class="co"># manually add names</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:12-5"></span>
<img src="book_files/figure-html/12-5-1.png" alt="Parallel coordinate plots directly visualize high-dimensional data by drawing lines." width="672" />
<p class="caption">
Figure 2.5: Parallel coordinate plots directly visualize high-dimensional data by drawing lines.
</p>
</div>
<p>The result is shown in Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:12-5">2.5</a>. Note that each line represents a flower. The four measurements are used to define the line. We can clearly see that I. setosa have smaller petals.</p>
<p>In addition to this, the “lattice” package has something nicer called “parallelplot”. That function can handle columns with different scales.</p>
</div>
<div id="box-plot" class="section level3">
<h3><span class="header-section-number">2.1.7</span> Box plot</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(x)  <span class="co"># plain version. Column names may not shown properly</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>))  <span class="co"># set figure margins (bottom, left, top, right)</span>
<span class="kw">boxplot</span>(x, <span class="dt">las =</span> <span class="dv">2</span>)   <span class="co"># Figure 2.5</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:12-6"></span>
<img src="book_files/figure-html/12-6-1.png" alt="Box plot of all 4 columns." width="80%" />
<p class="caption">
Figure 2.6: Box plot of all 4 columns.
</p>
</div>
<p>Notice that las = 2 option puts the data labels vertically. The par function sets the bottom, left, top and right margins respectively of the plot region in number of lines of text. Here we set the bottom margins to 8 lines so that the labels can show completely.</p>
<p><strong>Challenge 2d</strong>: Write R code to generate Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:12-7">2.7</a>.</p>

<pre><code>## The following objects are masked from iris (pos = 5):
## 
##     Petal.Length, Petal.Width, Sepal.Length, Sepal.Width, Species</code></pre>
<pre><code>## The following objects are masked from iris (pos = 6):
## 
##     Petal.Length, Petal.Width, Sepal.Length, Sepal.Width, Species</code></pre>
<pre><code>## The following objects are masked from iris (pos = 7):
## 
##     Petal.Length, Petal.Width, Sepal.Length, Sepal.Width, Species</code></pre>
<div class="figure" style="text-align: center"><span id="fig:12-7"></span>
<img src="book_files/figure-html/12-7-1.png" alt="Scatter plot shows the correlation of petal width and petal length." width="80%" />
<p class="caption">
Figure 2.7: Scatter plot shows the correlation of petal width and petal length.
</p>
</div>
<p><strong>Challenge 2e</strong>: Write R code to generate Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:12-8">2.8</a>, which show the means of petal length for each of the species with error bars corresponding to standard deviations. (ref:12-8) Bar plot of average petal lengths for 3 species.</p>
<div class="figure" style="text-align: center"><span id="fig:12-8"></span>
<img src="book_files/figure-html/12-8-1.png" alt="(ref:12-8)" width="80%" />
<p class="caption">
Figure 2.8: (ref:12-8)
</p>
</div>
</div>
</div>
<div id="combining-plots" class="section level2">
<h2><span class="header-section-number">2.2</span> Combining plots</h2>
<p>It is possible to combine multiple plots at the same graphics window.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">op &lt;-<span class="st"> </span><span class="kw">par</span>(<span class="dt">no.readonly =</span> <span class="ot">TRUE</span>)  <span class="co"># get old parameters</span>
<span class="kw">par</span>(<span class="dt">mfrow=</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))  <span class="co"># nrows = 2; ncols= 2</span>
<span class="kw">attach</span>(iris)
<span class="kw">hist</span>(Sepal.Length)
<span class="kw">hist</span>(Sepal.Width)
<span class="kw">hist</span>(Petal.Length)
<span class="kw">hist</span>(Petal.Width)
<span class="kw">par</span>(op)  <span class="co"># restore old parameters; otherwise affect all subsequent plots</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:13-1"></span>
<img src="book_files/figure-html/13-1-1.png" alt="Combine multiple histograms." width="50%" height="50%" />
<p class="caption">
Figure 2.9: Combine multiple histograms.
</p>
</div>
<p>The result is shown in Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:13-1">2.9</a>. This plot gives a good overview of the distribution of multiple variables. We can see that the overall distributions of petal length and petal width are quite unusual.</p>
<p><strong>Challenge 2f</strong>: Create a combined plot for Q-Q plot of the 4 numeric variables in the iris flower data set. Arrange your plots in 1 row and 4 columns. Include straight lines and interpretations.</p>
</div>
<div id="plot-using-principal-component-analysis-pca" class="section level2">
<h2><span class="header-section-number">2.3</span> Plot using principal component analysis (PCA)</h2>
<p>PCA is a linear projection method. As illustrated in Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:13-4">2.10</a>, it tries to define a new set of orthogonal coordinates to represent the dataset such that the new coordinates can be ranked by the amount of variation or information it captures in the dataset. After running PCA, you get many pieces of information:</p>
<p>• How the new coordinates are defined,</p>
<p>• The percentage of variances captured by each of the new coordinates,</p>
<p>• A representation of all the data points onto the new coordinates.</p>

<div class="figure" style="text-align: center"><span id="fig:13-4"></span>
<img src="images/img1304_PCA.png" alt="Concept of PCA. Here the first component x’ gives a relatively accurate representation of the data." width="75%" />
<p class="caption">
Figure 2.10: Concept of PCA. Here the first component x’ gives a relatively accurate representation of the data.
</p>
</div>
<p>Here’s an example of running PCA in R. Note that “scale=T” in the following command means that the data is normalized before conduction PCA so that each variable has unite variance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">? prcomp
pca =<span class="st"> </span><span class="kw">prcomp</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>], <span class="dt">scale =</span> T)   
pca  <span class="co"># Have a look at the results.</span></code></pre></div>
<pre><code>## Standard deviations (1, .., p=4):
## [1] 1.7083611 0.9560494 0.3830886 0.1439265
## 
## Rotation (n x k) = (4 x 4):
##                     PC1         PC2        PC3        PC4
## Sepal.Length  0.5210659 -0.37741762  0.7195664  0.2612863
## Sepal.Width  -0.2693474 -0.92329566 -0.2443818 -0.1235096
## Petal.Length  0.5804131 -0.02449161 -0.1421264 -0.8014492
## Petal.Width   0.5648565 -0.06694199 -0.6342727  0.5235971</code></pre>
<p>Note that the first principal component is positively correlated with Sepal length, petal length, and petal width. Recall that these three variables are highly correlated. Sepal width is the variable that is almost the same across three species with small standard deviation. PC2 is mostly determined by sepal width, less so by sepal length.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pca)  <span class="co"># plot the amount of variance each principal components captures.</span>
<span class="kw">str</span>(pca)   <span class="co"># this shows the structure of the object, listing all parts. </span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(pca<span class="op">$</span>x)  <span class="co"># the new coordinate values for each of the 150 samples</span></code></pre></div>
<pre><code>##         PC1        PC2         PC3          PC4
## 1 -2.257141 -0.4784238  0.12727962  0.024087508
## 2 -2.074013  0.6718827  0.23382552  0.102662845
## 3 -2.356335  0.3407664 -0.04405390  0.028282305
## 4 -2.291707  0.5953999 -0.09098530 -0.065735340
## 5 -2.381863 -0.6446757 -0.01568565 -0.035802870
## 6 -2.068701 -1.4842053 -0.02687825  0.006586116</code></pre>
<p>These numbers can be used to plot the distribution of the 150 data points.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(pca<span class="op">$</span>x[, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dt">pch =</span> <span class="dv">1</span>, <span class="dt">col =</span> iris<span class="op">$</span>Species,
         <span class="dt">xlab =</span> <span class="st">&quot;1st principal component&quot;</span>, 
         <span class="dt">ylab =</span> <span class="st">&quot;2nd Principal Component&quot;</span>)
     <span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="kw">levels</span>(iris<span class="op">$</span>Species), <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>))</code></pre></div>
<p>The result (left side of Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:13-5">2.11</a>) is a projection of the 4-dimensional iris flowering data on 2-dimensional space using the first two principal components. From this I observed that the first principal component alone can be used to distinguish the three species. We could use simple rules like this: If PC1 &lt; -1, then Iris setosa. If PC1 &gt; 1.5 then Iris virginica. If -1 &lt; PC1 &lt; 1, then Iris versicolor.</p>

<div class="figure" style="text-align: center"><span id="fig:13-5"></span>
<img src="book_files/figure-html/13-5-1.png" alt="PCA plot of the iris flower dataset using R base graphics (left) and ggplot2 (right)." width="50%" /><img src="book_files/figure-html/13-5-2.png" alt="PCA plot of the iris flower dataset using R base graphics (left) and ggplot2 (right)." width="50%" />
<p class="caption">
Figure 2.11: PCA plot of the iris flower dataset using R base graphics (left) and ggplot2 (right).
</p>
</div>
</div>
<div id="first-attempt-at-ggplot2" class="section level2">
<h2><span class="header-section-number">2.4</span> First attempt at ggplot2</h2>
<p>There are 3 big plotting systems in R: base graphics, lattice, and ggplot2. Now let’s try ggplot2. First, let’s construct a data frame as demanded by ggplot2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pcaData &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(pca<span class="op">$</span>x[, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>])
pcaData &lt;-<span class="st"> </span><span class="kw">cbind</span>(pcaData, iris<span class="op">$</span>Species) 
<span class="kw">colnames</span>(pcaData) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;PC1&quot;</span>, <span class="st">&quot;PC2&quot;</span>, <span class="st">&quot;Species&quot;</span>)

<span class="co">#install.packages(&quot;ggplot2&quot;)</span>
<span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(pcaData, <span class="kw">aes</span>(PC1, PC2, <span class="dt">color =</span> Species, <span class="dt">shape =</span> Species)) <span class="op">+</span><span class="st">   </span><span class="co"># define plot area</span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>)                                          <span class="co"># adding data points</span></code></pre></div>
<p>Now we have a basic plot. As you could see this plot is very different from those from R base graphics. We are adding elements one by one using the “+” sign at the end of the first line.</p>
<p>We will add details to this plot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">percentVar &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="kw">summary</span>(pca)<span class="op">$</span>importance[<span class="dv">2</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dv">0</span>)     <span class="co"># compute % variances</span>
<span class="kw">ggplot</span>(pcaData, <span class="kw">aes</span>(PC1, PC2, <span class="dt">color =</span> Species, <span class="dt">shape =</span> Species)) <span class="op">+</span><span class="st">  </span><span class="co"># starting ggplot2</span>
<span class="st">         </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st">                                       </span><span class="co"># add data points</span>
<span class="st">         </span><span class="kw">xlab</span>(<span class="kw">paste0</span>(<span class="st">&quot;PC1: &quot;</span>, percentVar[<span class="dv">1</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="op">+</span><span class="st">         </span><span class="co"># x label</span>
<span class="st">         </span><span class="kw">ylab</span>(<span class="kw">paste0</span>(<span class="st">&quot;PC2: &quot;</span>, percentVar[<span class="dv">2</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="op">+</span><span class="st">         </span><span class="co"># y  label</span>
<span class="st">         </span><span class="kw">ggtitle</span>(<span class="st">&quot;Principal component analysis (PCA)&quot;</span>) <span class="op">+</span><span class="st">              </span><span class="co"># title            </span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">aspect.ratio =</span> <span class="dv">1</span>)                                      <span class="co"># width and height ratio             </span></code></pre></div>
<p>The result is shown in right side of Figure <a href="analyzing-iris-flower-data-set-ii.html#fig:13-5">2.11</a>. You can experiment with each of the additional element by commenting out the corresponding line of code. You can also keep adding code to further customize it.</p>
<p><strong>Challenge 2g</strong>: Create PCA plot of the state.x77 data set. Use the state.region information to color code the states. Interpret your results. Use both R base graphics and ggplot2. Hint: do not forget normalization using the scale option.</p>
</div>
<div id="classification-predicting-the-odds-of-binary-outcomes" class="section level2">
<h2><span class="header-section-number">2.5</span> Classification: Predicting the odds of binary outcomes</h2>
<p>It is easy to distinguish <em>I. setosa</em> from the other two species, just based on petal length alone. Here we focus on building a predictive model that can predict between <em>I. versicolor</em> and <em>I. virginica</em>. For this we use the logistic regression to model the odd ratio of being <em>I. virginica</em> as a function of all of the 4 measurements:</p>
<p><span class="math display">\[ln(odds)=ln(\frac{p}{1-p})
                     =a×Sepal.Length + b×Sepal.Width + c×Petal.Length + d×Petal.Width+c+e.\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">iris2 &lt;-<span class="st"> </span>iris[<span class="dv">51</span><span class="op">:</span><span class="dv">150</span>, ]  <span class="co"># removes the first 50 samples, which represent I. setosa</span>
iris2 &lt;-<span class="st"> </span><span class="kw">droplevels</span>(iris2)  <span class="co"># removes setosa, an empty levels of species.</span>
model &lt;-<span class="st"> </span><span class="kw">glm</span>(Species <span class="op">~</span><span class="st"> </span>. , <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&#39;logit&#39;</span>), 
             <span class="dt">data =</span> iris2)  <span class="co"># Species ~ . species as a function of everything else in the dataset</span>
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Species ~ ., family = binomial(link = &quot;logit&quot;), 
##     data = iris2)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.01105  -0.00541  -0.00001   0.00677   1.78065  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   -42.638     25.707  -1.659   0.0972 .
## Sepal.Length   -2.465      2.394  -1.030   0.3032  
## Sepal.Width    -6.681      4.480  -1.491   0.1359  
## Petal.Length    9.429      4.737   1.991   0.0465 *
## Petal.Width    18.286      9.743   1.877   0.0605 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 138.629  on 99  degrees of freedom
## Residual deviance:  11.899  on 95  degrees of freedom
## AIC: 21.899
## 
## Number of Fisher Scoring iterations: 10</code></pre>
<p>Sepal length and width are not useful in distinguishing versicolor from <em>virginica</em>. The most significant (P=0.0465) factor is Petal.Length. One unit increase in petal length will increase the log-odd of being <em>virginica</em> by 9.429. Marginally significant effect is found for Petal.Width.</p>
<p>If you do not fully understand the mathematics behind linear regression or logistic regression, do not worry about it too much. Me either. In this class, I just want to show you how to do these analysis in R and interpret the results. I do not understand how computers work. Yet I <strong>use</strong> it every day.</p>
<p><strong>Challenge 2h</strong>: So far, we used a variety of techniques to investigate the iris flower dataset. Recall that in the very beginning, I asked you to eyeball the data and answer two questions:</p>
<p>• What distinguishes these three species?</p>
<p>• If we have a flower with sepals of 6.5cm long and 3.0cm wide, petals of 6.2cm long, and 2.2cm wide, which species does it most likely belong to?</p>
<p>Review all the analysis we did, examine the raw data, and answer the above questions. Write a paragraph and provide evidence of your thinking. Do more analysis if needed. If you give wrong answer for the 2nd question, you may lose 50% of homework points. So think hard! If you are uncertain, avoid assertive claims.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analyzing-iris-flower-dataset-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-importing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
