<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Learning R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Learning R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learning R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  

<meta name="author" content="Xijin Ge">


<meta name="date" content="2019-01-31">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="analyzing-heart-attack-data-set-i.html">
<link rel="next" href="vectors-1.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.39.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Index</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R program-Analyzing iris flower dataset</a><ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#data-frames-have-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.1</b> Data frames have rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.2</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#students-t-test"><i class="fa fa-check"></i><b>1.3</b> Student’s t-test</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#test-for-normal-distribution"><i class="fa fa-check"></i><b>1.4</b> Test for normal distribution</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-a-column-of-categorical-values"><i class="fa fa-check"></i><b>1.5</b> Analyzing a column of categorical values</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-the-relationship-between-two-columns-of-numbers"><i class="fa fa-check"></i><b>1.6</b> Analyzing the relationship between two columns of numbers</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#visualizing-and-testing-the-differences-in-groups"><i class="fa fa-check"></i><b>1.7</b> Visualizing and testing the differences in groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#testing-the-difference-among-multiple-groups-analysis-of-variance-anova"><i class="fa fa-check"></i><b>1.8</b> Testing the difference among multiple groups (Analysis of Variance: ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><i class="fa fa-check"></i><b>2</b> Visualizing data set-Analyzing cars and iris flower data sets</a><ul>
<li class="chapter" data-level="2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-mtcars-dataset"><i class="fa fa-check"></i><b>2.2</b> Visualizing mtcars dataset</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot"><i class="fa fa-check"></i><b>2.2.1</b> scatter plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#barplot-with-error-bars"><i class="fa fa-check"></i><b>2.2.2</b> Barplot with error bars</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-correlation-between-categorical-variables"><i class="fa fa-check"></i><b>2.2.3</b> Visualizing correlation between categorical variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#detecting-correlations-among-variables"><i class="fa fa-check"></i><b>2.2.4</b> Detecting correlations among variables</a></li>
<li class="chapter" data-level="2.2.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#hierarchical-clustering"><i class="fa fa-check"></i><b>2.2.5</b> Hierarchical clustering</a></li>
<li class="chapter" data-level="2.2.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#representing-data-using-faces.-serious-scientific-research-only"><i class="fa fa-check"></i><b>2.2.6</b> Representing data using faces. Serious scientific research only!</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-iris-data-set"><i class="fa fa-check"></i><b>2.3</b> Visualizing iris data set</a><ul>
<li class="chapter" data-level="2.3.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#a-matrix-only-contains-numbers"><i class="fa fa-check"></i><b>2.3.1</b> A Matrix only contains numbers</a></li>
<li class="chapter" data-level="2.3.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.3.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#heatmap"><i class="fa fa-check"></i><b>2.3.3</b> Heatmap</a></li>
<li class="chapter" data-level="2.3.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#star-plot"><i class="fa fa-check"></i><b>2.3.4</b> Star plot</a></li>
<li class="chapter" data-level="2.3.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#segment-diagrams"><i class="fa fa-check"></i><b>2.3.5</b> Segment diagrams</a></li>
<li class="chapter" data-level="2.3.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#parallel-coordinate-plot"><i class="fa fa-check"></i><b>2.3.6</b> Parallel coordinate plot</a></li>
<li class="chapter" data-level="2.3.7" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#box-plot"><i class="fa fa-check"></i><b>2.3.7</b> Box plot</a></li>
<li class="chapter" data-level="2.3.8" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#bar-plot-with-error-bar"><i class="fa fa-check"></i><b>2.3.8</b> Bar plot with error bar</a></li>
<li class="chapter" data-level="2.3.9" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#combining-plots"><i class="fa fa-check"></i><b>2.3.9</b> Combining plots</a></li>
<li class="chapter" data-level="2.3.10" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#plot-using-principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.3.10</b> Plot using principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.3.11" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#attempt-at-ggplot2"><i class="fa fa-check"></i><b>2.3.11</b> Attempt at ggplot2</a></li>
<li class="chapter" data-level="2.3.12" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#classification-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.3.12</b> Classification: Predicting the odds of binary outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a><ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Looking for Help and Example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrix-operations"><i class="fa fa-check"></i><b>3.2.2</b> Matrix operations</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.3</b> Lists</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#operations-on-data-frames"><i class="fa fa-check"></i><b>3.2.5</b> Operations on data frames</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#for-more-in-depth-exercises"><i class="fa fa-check"></i><b>3.3</b> For more in-depth exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-importing.html"><a href="data-importing.html"><i class="fa fa-check"></i><b>4</b> Data importing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-importing.html"><a href="data-importing.html#enter-data-manually"><i class="fa fa-check"></i><b>4.1</b> Enter data manually</a></li>
<li class="chapter" data-level="4.2" data-path="data-importing.html"><a href="data-importing.html#reading-data-from-file-using-import-dataset-in-rstudio"><i class="fa fa-check"></i><b>4.2</b> Reading data from file using Import dataset in Rstudio</a></li>
<li class="chapter" data-level="4.3" data-path="data-importing.html"><a href="data-importing.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.3</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.4" data-path="data-importing.html"><a href="data-importing.html#reading-file-using-read.table-read.csv-etc."><i class="fa fa-check"></i><b>4.4</b> Reading file using read.table, read.csv, etc.</a></li>
<li class="chapter" data-level="4.5" data-path="data-importing.html"><a href="data-importing.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.5</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.6" data-path="data-importing.html"><a href="data-importing.html#recommended-workflow-for-every-project"><i class="fa fa-check"></i><b>4.6</b> Recommended workflow for EVERY project</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> Analyzing heart attack data set I</a><ul>
<li class="chapter" data-level="5.1" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="5.2" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="5.3" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="5.4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="5.5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html"><i class="fa fa-check"></i><b>6</b> Analyzing heart attack data set II</a><ul>
<li class="chapter" data-level="6.1" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>6.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vectors-1.html"><a href="vectors-1.html"><i class="fa fa-check"></i><b>7</b> Vectors</a></li>
<li class="chapter" data-level="8" data-path="matrics-and-arrays.html"><a href="matrics-and-arrays.html"><i class="fa fa-check"></i><b>8</b> Matrics and arrays</a></li>
<li class="chapter" data-level="9" data-path="lists-1.html"><a href="lists-1.html"><i class="fa fa-check"></i><b>9</b> Lists</a></li>
<li class="chapter" data-level="10" data-path="data-frames.html"><a href="data-frames.html"><i class="fa fa-check"></i><b>10</b> Data frames</a></li>
<li class="chapter" data-level="11" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>11</b> Strings</a></li>
<li class="chapter" data-level="12" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>12</b> Advanced topics</a><ul>
<li class="chapter" data-level="12.1" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>12.1</b> Tidyverse</a></li>
<li class="chapter" data-level="12.2" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps-and-interactive-plots"><i class="fa fa-check"></i><b>12.2</b> Shiny Apps and interactive plots</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="data-exploring-of-state-dataset.html"><a href="data-exploring-of-state-dataset.html"><i class="fa fa-check"></i><b>13</b> Data exploring of state dataset</a><ul>
<li class="chapter" data-level="13.1" data-path="data-exploring-of-state-dataset.html"><a href="data-exploring-of-state-dataset.html#read-in-data-and-manage-data"><i class="fa fa-check"></i><b>13.1</b> Read in data and manage data</a></li>
<li class="chapter" data-level="13.2" data-path="data-exploring-of-state-dataset.html"><a href="data-exploring-of-state-dataset.html#analyzing-each-set-of-data-column-seperately"><i class="fa fa-check"></i><b>13.2</b> Analyzing each set of data column seperately</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="data-exploring-of-game-sale-dataset.html"><a href="data-exploring-of-game-sale-dataset.html"><i class="fa fa-check"></i><b>14</b> Data exploring of game sale dataset</a></li>
<li class="chapter" data-level="15" data-path="data-exploring-of-employee-salary-dataset.html"><a href="data-exploring-of-employee-salary-dataset.html"><i class="fa fa-check"></i><b>15</b> Data exploring of employee salary dataset</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learning R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analyzing-heart-attack-data-set-ii" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Analyzing heart attack data set II</h1>
<p>We continue to investigate the heart attack dataset. First, let’s read the data in again and change several variables to factors. Note that you must set the working directory to where the data file is stored on your computer. I encourage you to define a project associated with a folder.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set working directory, not necessary if loading a project</span>
<span class="co">#setwd(&quot;C:/Ge working/RBook/learnR/datasets&quot;)  </span>
df &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;heartatk4R.txt&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>)  <span class="co"># read data</span>
df<span class="op">$</span>DRG &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df<span class="op">$</span>DRG)  <span class="co"># convert DRG variable to factor</span>
df<span class="op">$</span>DIED &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df<span class="op">$</span>DIED)
df<span class="op">$</span>DIAGNOSIS &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df<span class="op">$</span>DIAGNOSIS)
df<span class="op">$</span>SEX &lt;-<span class="st"> </span><span class="kw">as.factor</span>(df<span class="op">$</span>SEX)
<span class="kw">str</span>(df)  <span class="co"># double check </span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    12844 obs. of  8 variables:
##  $ Patient  : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ DIAGNOSIS: Factor w/ 9 levels &quot;41001&quot;,&quot;41011&quot;,..: 5 5 9 8 9 9 9 9 5 5 ...
##  $ SEX      : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 1 1 2 2 1 1 2 1 ...
##  $ DRG      : Factor w/ 3 levels &quot;121&quot;,&quot;122&quot;,&quot;123&quot;: 2 2 2 2 2 1 1 1 1 3 ...
##  $ DIED     : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ CHARGES  : num  4752 3941 3657 1481 1681 ...
##  $ LOS      : int  10 6 5 2 1 9 15 15 2 1 ...
##  $ AGE      : int  79 34 76 80 55 84 84 70 76 65 ...</code></pre>
<div id="scatter-plot-in-ggplot2" class="section level2">
<h2><span class="header-section-number">6.1</span> Scatter plot in ggplot2</h2>
<p>Hadley Wickham wrote the ggplot2 package in 2005 following Leland Wilkinson’s grammar of graphics, which provides a formal, structured way of visualizing data. Similarly, R was originally written by Robert Gentleman and Ross Ihaka in the 1990s; Linux was developed by Linus Torvalds, a student, at the same period. A few superheroes can make computing much easier for millions of people. ggplot2 uses a different approach to graphics.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#install.packages(&quot;ggplot2&quot;) # install the package</span>
<span class="kw">library</span>(ggplot2)  <span class="co"># load the package</span>
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES))  <span class="co"># Specify data frame and aesthetic mapping</span></code></pre></div>
<p>This line does not finish the plot; it just specifies the name of the data frame, which is the required input data type, and defines the so-called <strong>aesthetic mapping</strong>: LOS maps to x-axis while CHARGES maps to the y-axis. To complete the plot, we use the geom_point function to add data points, which is called <strong>geometric objects</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()   <span class="co"># scatter plot</span></code></pre></div>
<p>Thus, it is a two-step process to generate a scatter plot. This seems cumbersome at first, but it is convenient to add additional features or customize the plot step by step. Let’s add a trend line with a confidence interval.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> lm)</code></pre></div>
<p>As we keep adding elements to the plot, this line of code gets longer. So we break the code into multiple lines as below. The “+” at the end of the lines signifies that the plot is not finished and tell R to keep reading the next line. This code below does the same thing as the above, but it is easier to read. I often use the tab key in the second line to remind myself that it is continued from the above line.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES)) <span class="op">+</span><span class="st">  </span><span class="co"># aesthetic mapping</span>
<span class="st">         </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">                    </span><span class="co"># add data points    </span>
<span class="st">       </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> lm)          <span class="co"># add trend line</span></code></pre></div>
<p>As you can see from this code, it also enables us to add comments for each step, making the code easy to read. This is important, as we often recycle our codes.</p>
<p>We can also customize the plot by adding additional lines of code (Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-1">6.1</a>):</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES)) <span class="op">+</span><span class="st">                 </span><span class="co"># aesthetic mapping</span>
<span class="st">       </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">                                   </span><span class="co"># add data points    </span>
<span class="st">       </span><span class="kw">stat_smooth</span>(<span class="dt">method =</span> lm) <span class="op">+</span><span class="st">                       </span><span class="co"># add trend line</span>
<span class="st">       </span><span class="kw">xlim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="op">+</span><span class="st">                                        </span><span class="co"># change plotting limits of x-axis </span>
<span class="st">       </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Length of stay&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Charges ($)&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="co"># change x and y labels</span>
<span class="st">       </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">3</span>, <span class="dt">y =</span> <span class="dv">45000</span>, <span class="dt">label =</span> (<span class="st">&quot;R = 0.74&quot;</span>))  <span class="co"># add text to plot coordinates</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:15-1"></span>
<img src="book_files/figure-html/15-1-1.png" alt="Scatter plot using ggplot2." width="480" />
<p class="caption">
Figure 6.1: Scatter plot using ggplot2.
</p>
</div>
<p>You can learn other ways to customize your plot by googling. For example, try to find a way to add title to the plot by using keyword “ggplot2 add title to plot”.</p>
<p>It is easy to represent other characteristics of data points (columns) using additional aesthetic mappings, such as linetype, color, size, fill (“inside” color).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()               <span class="co"># basic scatter plot</span>
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES, <span class="dt">color =</span> DRG)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()  <span class="co"># map DRG to color</span></code></pre></div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> LOS, <span class="dt">y =</span> CHARGES, <span class="dt">color =</span> DRG, <span class="dt">shape =</span> SEX)) <span class="op">+</span><span class="st">  </span><span class="co"># map SEX to shape</span>
<span class="st">       </span><span class="kw">geom_point</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:15-2"></span>
<img src="book_files/figure-html/15-2-1.png" alt="Changing color and shape to represent multivariate data in ggplot2." width="576" />
<p class="caption">
Figure 6.2: Changing color and shape to represent multivariate data in ggplot2.
</p>
</div>
<p>At each step, we add additional information about these patients (Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-2">6.2</a>). With ggplot2, we can visualize complex, multivariate data by mapping different columns into diverse types of aesthetics. Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-1">6.1</a> shows a strong positive correlation between charges and length of hospital stay, which is expected as many itemized costs are billed daily. Note there are over 12,000 data points on these plots, many are plotted near or exactly at the same places, especially at the lower left corner. stat_density2d() can be used to color code density.</p>
<p>These plots are big in file size when you save it in a vector format (<strong>metafile</strong>), which often offer higher resolution. If you have many such plots in a paper or thesis, your file size can be big. These problems can be avoided if you use the <strong>bitmap</strong> format.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-342" class="exercise"><strong>Exercise 6.1  </strong></span>Use ggplot2 to generate a scatter plot of age vs. charges in the heart attack dataset. Use different shapes of data points to represent DRG and color-code data points based on diagnosis.
</div>

</div>
<div id="histograms-and-density-plots" class="section level2">
<h2><span class="header-section-number">6.2</span> Histograms and density plots</h2>
<p>In addition to data points(geom_points), there are many other <strong>geometric objects</strong>, such as histogram(geom_histogram), lines (geom_line), and bars (geom_bar), and so on. We can use these geometric objects to generate different types of plots. To plot a basic histogram:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</code></pre></div>
<p>Then we can refine it and add a density curve (Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-3">6.3</a>):</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE, <span class="dt">y =</span> ..density..)) <span class="op">+</span><span class="st"> </span>
<span class="st">       </span><span class="kw">geom_histogram</span>(<span class="dt">fill =</span> <span class="st">&quot;cornsilk&quot;</span>, 
                      <span class="dt">colour =</span> <span class="st">&quot;grey60&quot;</span>, <span class="dt">size =</span> .<span class="dv">2</span>) <span class="op">+</span>
<span class="st">       </span><span class="kw">geom_density</span>()</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:15-3"></span>
<img src="book_files/figure-html/15-3-1.png" alt="Histogram with density curve." width="576" />
<p class="caption">
Figure 6.3: Histogram with density curve.
</p>
</div>
<p>Combined density plots are useful in comparing the distribution of subgroups of data points.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># all data</span></code></pre></div>
<p>Use color to differentiate sex:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE, <span class="dt">color =</span> SEX)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># Figure 5.4A</span></code></pre></div>
<p>Here, we split the dataset into two portions, men and women, and plotted their density distribution on the same plot. Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-4">6.4</a>A shows that age distribution is very different between men and women. Women’s distribution is skewed to the right and they are on average over ten years older than men. This is surprising, given that this dataset contains all heart attack admissions in New York state in 1993.</p>
<p>The fill mapping changes the “inside” color:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE, <span class="dt">fill =</span> SEX)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># Figure 5.4B</span></code></pre></div>
<p>This plot shows the same information. It looks nicer, at least to me. We can <strong>split the plot into multiple facets</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> AGE, <span class="dt">fill =</span> SEX)) <span class="op">+</span><span class="st"> </span>
<span class="st">       </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(DRG <span class="op">~</span>.)  <span class="co"># Figure 5.4C</span></code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:15-4"></span>
<img src="images/img1504_density.png" alt="Density plots." width="640" />
<p class="caption">
Figure 6.4: Density plots.
</p>
</div>
<p>Recall the DRG=121 represents patients who survived but developed complications; DRG=122 denotes those without complications and DRG=123 are patients who did not survive. Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-4">6.4</a>C suggests that women in all three groups are older than men counterparts. If we examine the distribution of male patients’ age distribution across facets, we can see that the distribution is skewed to the right in deceased patients (DRG=123), indicating that perhaps older people are less likely to survive a heart attack. Survivors without complications (DRG= 122) tend to be younger than survivors with complications.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-348" class="exercise"><strong>Exercise 6.2  </strong></span>Create density plots like Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-5">6.5</a> to compare the distribution of length of hospital stay (LOS) for patients with different DRG groups, separately for men and women. Offer interpretation in the context of the dataset. Limit the x-axis to 0 to 20.
</div>


<div class="figure" style="text-align: center"><span id="fig:15-5"></span>
<img src="book_files/figure-html/15-5-1.png" alt="Distribution of LOS by DRG groups grouped by SEX." width="576" />
<p class="caption">
Figure 6.5: Distribution of LOS by DRG groups grouped by SEX.
</p>
</div>
</div>
<div id="box-plots-and-violin-plots" class="section level2">
<h2><span class="header-section-number">6.3</span> Box plots and Violin plots</h2>
<p>We can follow the same rule to generate boxplots using the geom_boxplot ( ). Let’s start with a basic version.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> SEX, <span class="dt">y =</span> AGE)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()  <span class="co"># basic boxplot </span>
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> SEX, <span class="dt">y =</span> AGE)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(DRG <span class="op">~</span><span class="st"> </span>.)  <span class="co"># Figure 5.6A</span>
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> SEX, <span class="dt">y =</span> AGE)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_violin</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(DRG <span class="op">~</span><span class="st"> </span>.)  <span class="co"># Figure 5.6B</span></code></pre></div>
<p>The last version is a violin plot. It shows more details about the distribution as it is essentially density plots on both left and right sides of the violins.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-350" class="exercise"><strong>Exercise 6.3  </strong></span>Generate a violin plot like Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-6">6.6</a>C to compare the distribution of length of hospital stay among patients with different prognosis outcomes (DRG), separately for men and women. Interpret your result. Note the axes labels are customized.
</div>


<div class="figure" style="text-align: center"><span id="fig:15-6"></span>
<img src="images/img1506_boxviolin.png" alt="Boxplot and violin plots using ggplot2." width="640" />
<p class="caption">
Figure 6.6: Boxplot and violin plots using ggplot2.
</p>
</div>
</div>
<div id="bar-plot-with-error-bars" class="section level2">
<h2><span class="header-section-number">6.4</span> Bar plot with error bars</h2>
<p>Suppose we are interested in examining whether people with certain diagnosis codes stays longer or shorter in the hospital after a heart attack. We can, of course, use the aggregate function to generate a table with means LOS by category.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(df, <span class="dt">by =</span> <span class="kw">list</span>(df<span class="op">$</span>DIAGNOSIS), <span class="dt">FUN =</span> mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##   Group.1  Patient DIAGNOSIS SEX DRG DIED   CHARGES      LOS      AGE
## 1   41001 7130.229        NA  NA  NA   NA 10868.030 7.775161 65.56317
## 2   41011 6413.323        NA  NA  NA   NA 10631.803 7.728618 65.81305
## 3   41021 6482.808        NA  NA  NA   NA 10666.687 7.556000 63.96000
## 4   41031 6356.028        NA  NA  NA   NA  9908.118 6.679715 62.93950
## 5   41041 6259.752        NA  NA  NA   NA  9985.722 7.307692 63.73884
## 6   41051 6438.974        NA  NA  NA   NA  9062.423 7.298701 67.22078
## 7   41071 6949.627        NA  NA  NA   NA  9750.309 7.834997 69.01996
## 8   41081 8384.725        NA  NA  NA   NA  9633.123 7.048780 68.04181
## 9   41091 6165.481        NA  NA  NA   NA  9511.093 7.625743 67.10359</code></pre>
<p>We can be happy with this table and call it quits. However, tables are often not as easy to interpret as a nicely formatted graph. Instead of the aggregate function, we use the powerful dplyr package to summarize the data and then to generate a bar plot showing both the means and standard errors. I stole some code and ideas from R graphics cookbook and this website: <a href="http://environmentalcomputing.net/plotting-with-ggplot-bar-plots-with-error-bars/" class="uri">http://environmentalcomputing.net/plotting-with-ggplot-bar-plots-with-error-bars/</a></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#install.packages(&quot;dplyr&quot;) # dplyr package for summary statistics by group</span>
<span class="kw">library</span>(dplyr)  <span class="co"># load the package</span></code></pre></div>
<p>To summarize data by groups/factors, the dplyr package uses a similar type of grammar like ggplot2, where operations are added sequentially. Similar to pipes in Unix, commands separated by “%&gt;%” are executed sequentially where the output of one step becomes the input of the next. The follow 6 lines are part of one command, consisting of three big steps.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># names of the new data frame and the data frame to be summarized</span>
<span class="st">  </span><span class="kw">group_by</span>(DIAGNOSIS) <span class="op">%&gt;%</span><span class="st">  </span><span class="co"># grouping variable</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(LOS),  <span class="co"># mean of each group</span>
            <span class="dt">sd   =</span> <span class="kw">sd</span>(LOS),    <span class="co"># standard deviation of each group</span>
            <span class="dt">n    =</span> <span class="kw">n</span>(),        <span class="co"># sample size per group</span>
            <span class="dt">se   =</span> <span class="kw">sd</span>(LOS) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">n</span>()))  <span class="co"># standard error of each group</span></code></pre></div>
<p>The resultant data frame is a detailed summary of the data by DIAGNOSIS:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats</code></pre></div>
<pre><code>## # A tibble: 9 x 5
##   DIAGNOSIS  mean    sd     n     se
##   &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
## 1 41001      7.78  5.69   467 0.263 
## 2 41011      7.73  5.34  1824 0.125 
## 3 41021      7.56  5.26   250 0.333 
## 4 41031      6.68  4.15   281 0.247 
## 5 41041      7.31  4.75  2665 0.0920
## 6 41051      7.30  4.54   154 0.366 
## 7 41071      7.83  5.28  1703 0.128 
## 8 41081      7.05  5.32   287 0.314 
## 9 41091      7.63  5.14  5213 0.0712</code></pre>
<p>Now we can use ggplot2 to plot these statistics (Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-7">6.7</a>):</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(stats, <span class="kw">aes</span>(<span class="dt">x =</span> DIAGNOSIS, <span class="dt">y =</span> mean)) <span class="op">+</span><span class="st">   </span><span class="co"># data &amp; aesthetic mapping</span>
<span class="st">         </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st">            </span><span class="co"># bars represent average</span>
<span class="st">         </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> mean <span class="op">-</span><span class="st"> </span>se, <span class="dt">ymax =</span> mean <span class="op">+</span><span class="st"> </span>se), <span class="dt">width =</span> <span class="fl">0.2</span>)  <span class="co"># error bars</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:15-7"></span>
<img src="book_files/figure-html/15-7-1.png" alt="Average LOS by DIAGNOSIS group with error bars representing standard error." width="576" />
<p class="caption">
Figure 6.7: Average LOS by DIAGNOSIS group with error bars representing standard error.
</p>
</div>
<p>Note that the mean-se and mean+se refer to the two columns in the stats data frame and defines the error bars. Because we have an extremely large sample size, the standard errors are small. People with a diagnosis of 41031 stays shorter in the hospital. By looking up the IDC code in <a href="http://www.nuemd.com" class="uri">http://www.nuemd.com</a>, we notice that this code represents “Acute myocardial infarction of inferoposterior wall, initial episode of care”, which probably makes sense.</p>
<p>As we did previously, we want to define the LOS bars for men and women separately. We first need to go back and generate different summary statistics.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats2 &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(DIAGNOSIS, SEX) <span class="op">%&gt;%</span><span class="st">   </span><span class="co"># two grouping variables</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(LOS),  
            <span class="dt">sd   =</span> <span class="kw">sd</span>(LOS), 
            <span class="dt">n    =</span> <span class="kw">n</span>(),  
            <span class="dt">se   =</span> <span class="kw">sd</span>(LOS) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">n</span>())) </code></pre></div>
<p>The entire dataset was divided into 18 groups according to all possible combinations of DIAGNOSIS and SEX. For each group, the LOS numbers are summarized in terms of mean, standard deviation (sd), observations (n), and standard errors(se). Below is the resultant data frame with summary statistics:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stats2</code></pre></div>
<pre><code>## # A tibble: 18 x 6
## # Groups:   DIAGNOSIS [?]
##    DIAGNOSIS SEX    mean    sd     n     se
##    &lt;fct&gt;     &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
##  1 41001     F      8.74  6.03   175 0.456 
##  2 41001     M      7.20  5.41   292 0.316 
##  3 41011     F      8.41  6.23   692 0.237 
##  4 41011     M      7.31  4.66  1132 0.139 
##  5 41021     F      8.54  5.82   100 0.582 
##  6 41021     M      6.9   4.76   150 0.389 
##  7 41031     F      6.41  4.67    96 0.477 
##  8 41031     M      6.82  3.86   185 0.283 
##  9 41041     F      7.79  5.18   998 0.164 
## 10 41041     M      7.02  4.45  1667 0.109 
## 11 41051     F      7.93  5.64    69 0.679 
## 12 41051     M      6.79  3.34    85 0.362 
## 13 41071     F      8.65  5.76   727 0.214 
## 14 41071     M      7.23  4.80   976 0.154 
## 15 41081     F      7.58  5.60   130 0.492 
## 16 41081     M      6.61  5.04   157 0.402 
## 17 41091     F      8.34  5.76  2078 0.126 
## 18 41091     M      7.15  4.63  3135 0.0826</code></pre>
<p>Now we are ready to generate bar plot for men and women separately using the fill aesthetic mapping:</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(stats2, <span class="kw">aes</span>(<span class="dt">x =</span> DIAGNOSIS, <span class="dt">y =</span> mean, <span class="dt">fill =</span> SEX)) <span class="op">+</span><span class="st">  </span><span class="co"># mapping</span>
<span class="st">       </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span><span class="st">    </span><span class="co"># bars for mean of LOS</span>
<span class="st">       </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Diagnosis codes&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Length of Stay&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="co"># axes labels</span>
<span class="st">       </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> mean <span class="op">-</span><span class="st"> </span>se, <span class="dt">ymax =</span> mean <span class="op">+</span><span class="st"> </span>se),  <span class="co"># error bars</span>
       <span class="dt">position =</span> <span class="kw">position_dodge</span>(.<span class="dv">9</span>), <span class="dt">width =</span> <span class="fl">0.2</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:15-8"></span>
<img src="book_files/figure-html/15-8-1.png" alt="The length of stay summarized by diagnosis and sex. Error bars represent standard error." width="576" />
<p class="caption">
Figure 6.8: The length of stay summarized by diagnosis and sex. Error bars represent standard error.
</p>
</div>

<div class="figure" style="text-align: center"><span id="fig:15-9"></span>
<img src="book_files/figure-html/15-9-1.png" alt="Mean ages for patients with different diagnosis and treatment outcome." width="576" />
<p class="caption">
Figure 6.9: Mean ages for patients with different diagnosis and treatment outcome.
</p>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-358" class="exercise"><strong>Exercise 6.4  </strong></span>Generate Figure <a href="analyzing-heart-attack-data-set-ii.html#fig:15-9">6.9</a> and offer your interpretation. Hint: Modify both the summarizing script and the plotting script.
</div>

<p>Overall, our investigation reveals that women are much older than men when admitted to hospital for heart attack. Therefore, prognosis is also poor with high mortality and complication rates. It is probably not because they develop heart attack later in life. It seems that symptoms are subtler in women and often get ignored. Heart attack can sometimes manifest as back pain, numbness in the arm, or pain in the jaw or teeth! (Warning: statistics professor is talking about medicine!)</p>
<p>As you could see from these plots, <strong>ggplot2</strong> generates nicely-looking, publication-ready graphics. Moreover, it is a relatively structured way of customizing plots. That is why it is becoming popular among R users. Once again, there are many example codes and answered R coding questions online. Whatever you want to do, you can <strong>google it, try the example code</strong>, and modify it to fit your needs. It is all free! Enjoy coding!</p>
</div>
<div id="statistical-models-are-easy-interpretations-and-verifications-are-not" class="section level2">
<h2><span class="header-section-number">6.5</span> Statistical models are easy; interpretations and verifications are not!</h2>
<p>By using pair-wised correlation analysis, we found that women have a much higher mortality rate than men due to heart attack. We also found that women are much older than men. These are obviously confounding effects.</p>
<p>We need to <strong>delineate the effects of multiple factors using multiple linear regression</strong>. In our model below, we express the charges as a function of all other factors using <strong>multiple linear regression</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">lm</span>(CHARGES <span class="op">~</span><span class="st"> </span>SEX <span class="op">+</span><span class="st"> </span>LOS <span class="op">+</span><span class="st"> </span>AGE <span class="op">+</span><span class="st"> </span>DRG <span class="op">+</span><span class="st"> </span>DIAGNOSIS, <span class="dt">data =</span> df)
<span class="kw">summary</span>(fit) </code></pre></div>
<pre><code>## 
## Call:
## lm(formula = CHARGES ~ SEX + LOS + AGE + DRG + DIAGNOSIS, data = df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -31486  -2453   -674   1766  32979 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     6863.753    314.515  21.823  &lt; 2e-16 ***
## SEXM             183.085     84.131   2.176  0.02956 *  
## LOS              989.717      8.268 119.700  &lt; 2e-16 ***
## AGE              -55.255      3.216 -17.180  &lt; 2e-16 ***
## DRG122          -916.531     86.851 -10.553  &lt; 2e-16 ***
## DRG123          1488.187    141.771  10.497  &lt; 2e-16 ***
## DIAGNOSIS41011  -136.097    230.312  -0.591  0.55458    
## DIAGNOSIS41021   137.118    349.948   0.392  0.69520    
## DIAGNOSIS41031   201.021    334.056   0.602  0.54735    
## DIAGNOSIS41041  -349.932    223.352  -1.567  0.11720    
## DIAGNOSIS41051 -1162.651    408.621  -2.845  0.00444 ** 
## DIAGNOSIS41071  -755.549    233.214  -3.240  0.00120 ** 
## DIAGNOSIS41081  -353.290    332.747  -1.062  0.28838    
## DIAGNOSIS41091 -1042.968    215.038  -4.850 1.25e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4308 on 12131 degrees of freedom
##   (699 observations deleted due to missingness)
## Multiple R-squared:  0.569,  Adjusted R-squared:  0.5685 
## F-statistic:  1232 on 13 and 12131 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As we could see from above, one levels for factors (such as female) is used as a base for comparison, so it does not show. SEXM indicates that being male, we have a marginally significant effect on charges. Everything else being equal, a male patient will incur $183 dollars more cost than female for the hospital stay. This is really small number compared to overall charges and also the p value is just marginally significant for this large sample. This is in contrast to the <strong>t.test(CHARGES ~ SEX)</strong>, when we got the opposite conclusion. This is because we did not control for other factors.</p>
<p>The most pronounced effect is LOS. This is not surprising, as many hospitals have charges on daily basis. Since the p values are cutoff at 2e-16, the <strong>t value</strong> is an indicator of significance. LOS has a t value of 119.7, which is way bigger than all others. If I am an insurance company CEO, I will do anything I can to push the hospitals to discharge patients as early as possible. The coefficients tell us for the average patient, one extra day of stay in the hospital the charges will go up by $989.7. Age has a negative effect, meaning older people actually will be charged less, when other factors are controlled. So there is no reason to charge older people more in terms of insurance premiums. And there is a little evidence to charge female more than males. Compared with patients who had complications (DRG = 121, the baseline), people have no complications (DRG = 122) incurred less charges on average by the amount of $916. Patients who died, on the other hand, are likely to be charged more. People with diagnosis codes 410914, 1051 and 41071 incurred less charges compared with those with 41001.</p>
<p>To investigate mortality, which is a binary outcome, we use <strong>logistic regression</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">glm</span>(DIED <span class="op">~</span><span class="st"> </span>SEX <span class="op">+</span><span class="st"> </span>LOS <span class="op">+</span><span class="st"> </span>AGE <span class="op">+</span><span class="st"> </span>DIAGNOSIS, <span class="dt">family =</span> <span class="kw">binomial</span>( ), <span class="dt">data =</span> df)
<span class="kw">summary</span>(fit)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = DIED ~ SEX + LOS + AGE + DIAGNOSIS, family = binomial(), 
##     data = df)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7745  -0.4583  -0.2813  -0.1517   4.4996  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -5.359769   0.263001 -20.379  &lt; 2e-16 ***
## SEXM           -0.345084   0.064978  -5.311 1.09e-07 ***
## LOS            -0.248553   0.009197 -27.025  &lt; 2e-16 ***
## AGE             0.081122   0.002995  27.082  &lt; 2e-16 ***
## DIAGNOSIS41011 -0.404406   0.157454  -2.568  0.01022 *  
## DIAGNOSIS41021 -0.336452   0.254026  -1.324  0.18534    
## DIAGNOSIS41031 -0.784819   0.262089  -2.994  0.00275 ** 
## DIAGNOSIS41041 -0.991677   0.158059  -6.274 3.52e-10 ***
## DIAGNOSIS41051 -0.235784   0.279752  -0.843  0.39932    
## DIAGNOSIS41071 -1.719416   0.178522  -9.631  &lt; 2e-16 ***
## DIAGNOSIS41081 -0.484542   0.226713  -2.137  0.03258 *  
## DIAGNOSIS41091 -0.677723   0.145463  -4.659 3.18e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8889.4  on 12843  degrees of freedom
## Residual deviance: 6844.2  on 12832  degrees of freedom
## AIC: 6868.2
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Note that DIED is 1 for people died, and 0 otherwise. So a negative coefficient indicates less likely to die, hence more likely to survive. Males are more likely to survive heart attack, compared with females of the same age, and with the same diagnosis. People who stayed longer are less likely to die. Older people are more likely to die. Compared with people with diagnosis code of 41001, those diagnosed with 41071, 41041, and 41091, are more likely to survive.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-361" class="exercise"><strong>Exercise 6.5  </strong></span>Use multiple linear regression to investigate the factors associated with length of stay. Obviously we need to exclude charges in our model. Interpret your results.
</div>

<p>This is not part of the exercise, but another problem we could look into is who are more likely to have complications. We should only focuse on the surviving patients and do logistic regression.</p>
<p>We still need pair-wised examinations, because we cannot put two highly correlated factors in the same model.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analyzing-heart-attack-data-set-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="vectors-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
