<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Learning R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Learning R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learning R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  

<meta name="author" content="Xijin Ge">


<meta name="date" content="2019-03-08">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html">
<link rel="next" href="data-importing.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.39.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Index</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R program-Analyzing iris flower dataset</a><ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#data-frames-have-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.1</b> Data frames have rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.2</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#students-t-test"><i class="fa fa-check"></i><b>1.3</b> Student’s t-test</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#test-for-normal-distribution"><i class="fa fa-check"></i><b>1.4</b> Test for normal distribution</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-a-column-of-categorical-values"><i class="fa fa-check"></i><b>1.5</b> Analyzing a column of categorical values</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-the-relationship-between-two-columns-of-numbers"><i class="fa fa-check"></i><b>1.6</b> Analyzing the relationship between two columns of numbers</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#visualizing-and-testing-the-differences-in-groups"><i class="fa fa-check"></i><b>1.7</b> Visualizing and testing the differences in groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#testing-the-difference-among-multiple-groups-analysis-of-variance-anova"><i class="fa fa-check"></i><b>1.8</b> Testing the difference among multiple groups (Analysis of Variance: ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><i class="fa fa-check"></i><b>2</b> Visualizing data set-Analyzing cars and iris flower data sets</a><ul>
<li class="chapter" data-level="2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-mtcars-dataset"><i class="fa fa-check"></i><b>2.2</b> Visualizing mtcars dataset</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot"><i class="fa fa-check"></i><b>2.2.1</b> scatter plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#barplot-with-error-bars"><i class="fa fa-check"></i><b>2.2.2</b> Barplot with error bars</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-correlation-between-categorical-variables"><i class="fa fa-check"></i><b>2.2.3</b> Visualizing correlation between categorical variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#detecting-correlations-among-variables"><i class="fa fa-check"></i><b>2.2.4</b> Detecting correlations among variables</a></li>
<li class="chapter" data-level="2.2.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#hierarchical-clustering"><i class="fa fa-check"></i><b>2.2.5</b> Hierarchical clustering</a></li>
<li class="chapter" data-level="2.2.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#representing-data-using-faces.-serious-scientific-research-only"><i class="fa fa-check"></i><b>2.2.6</b> Representing data using faces. Serious scientific research only!</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-iris-data-set"><i class="fa fa-check"></i><b>2.3</b> Visualizing iris data set</a><ul>
<li class="chapter" data-level="2.3.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#a-matrix-only-contains-numbers"><i class="fa fa-check"></i><b>2.3.1</b> A Matrix only contains numbers</a></li>
<li class="chapter" data-level="2.3.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.3.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#heatmap"><i class="fa fa-check"></i><b>2.3.3</b> Heatmap</a></li>
<li class="chapter" data-level="2.3.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#star-plot"><i class="fa fa-check"></i><b>2.3.4</b> Star plot</a></li>
<li class="chapter" data-level="2.3.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#segment-diagrams"><i class="fa fa-check"></i><b>2.3.5</b> Segment diagrams</a></li>
<li class="chapter" data-level="2.3.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#parallel-coordinate-plot"><i class="fa fa-check"></i><b>2.3.6</b> Parallel coordinate plot</a></li>
<li class="chapter" data-level="2.3.7" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#box-plot"><i class="fa fa-check"></i><b>2.3.7</b> Box plot</a></li>
<li class="chapter" data-level="2.3.8" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#bar-plot-with-error-bar"><i class="fa fa-check"></i><b>2.3.8</b> Bar plot with error bar</a></li>
<li class="chapter" data-level="2.3.9" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#combining-plots"><i class="fa fa-check"></i><b>2.3.9</b> Combining plots</a></li>
<li class="chapter" data-level="2.3.10" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#plot-using-principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.3.10</b> Plot using principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.3.11" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#attempt-at-ggplot2"><i class="fa fa-check"></i><b>2.3.11</b> Attempt at ggplot2</a></li>
<li class="chapter" data-level="2.3.12" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#classification-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.3.12</b> Classification: Predicting the odds of binary outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a><ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Looking for Help and Example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrix-operations"><i class="fa fa-check"></i><b>3.2.2</b> Matrix operations</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.3</b> Lists</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.4</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.5</b> Strings and string vectors</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#for-more-in-depth-exercises"><i class="fa fa-check"></i><b>3.3</b> For more in-depth exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-importing.html"><a href="data-importing.html"><i class="fa fa-check"></i><b>4</b> Data importing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-importing.html"><a href="data-importing.html#enter-data-manually"><i class="fa fa-check"></i><b>4.1</b> Enter data manually</a></li>
<li class="chapter" data-level="4.2" data-path="data-importing.html"><a href="data-importing.html#reading-data-from-file-using-import-dataset-in-rstudio"><i class="fa fa-check"></i><b>4.2</b> Reading data from file using Import dataset in Rstudio</a></li>
<li class="chapter" data-level="4.3" data-path="data-importing.html"><a href="data-importing.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.3</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.4" data-path="data-importing.html"><a href="data-importing.html#reading-file-using-read.table-read.csv-etc."><i class="fa fa-check"></i><b>4.4</b> Reading file using read.table, read.csv, etc.</a></li>
<li class="chapter" data-level="4.5" data-path="data-importing.html"><a href="data-importing.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.5</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.6" data-path="data-importing.html"><a href="data-importing.html#recommended-workflow-for-every-project"><i class="fa fa-check"></i><b>4.6</b> Recommended workflow for EVERY project</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> Analyzing heart attack data set I</a><ul>
<li class="chapter" data-level="5.1" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="5.2" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="5.3" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="5.4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="5.5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html"><i class="fa fa-check"></i><b>6</b> Analyzing heart attack data set II</a><ul>
<li class="chapter" data-level="6.1" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>6.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a><ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.1</b> Tidyverse</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.2</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-markdown"><i class="fa fa-check"></i><b>7.3</b> Introduction to Markdown</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a><ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package-by-typing-this-in-the-console."><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package by typing this in the console.</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html"><i class="fa fa-check"></i><b>8</b> Exploring of state data set</a><ul>
<li class="chapter" data-level="8.1" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#reading-in-and-manipulating-data"><i class="fa fa-check"></i><b>8.1</b> Reading in and manipulating data</a></li>
<li class="chapter" data-level="8.2" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#basic-information-about-data"><i class="fa fa-check"></i><b>8.2</b> Basic information about data</a></li>
<li class="chapter" data-level="8.3" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#peeking-the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> Peeking the whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#linear-model-anylysis"><i class="fa fa-check"></i><b>8.5</b> Linear model anylysis</a></li>
<li class="chapter" data-level="8.6" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html"><i class="fa fa-check"></i><b>9</b> Exploring of game sale dataset</a><ul>
<li class="chapter" data-level="9.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#reading-in-data-and-manage-data"><i class="fa fa-check"></i><b>9.1</b> Reading in data and manage data</a></li>
<li class="chapter" data-level="9.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a><ul>
<li class="chapter" data-level="9.5.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#effect-of-platform-type-to-priciple-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type to priciple components</a></li>
<li class="chapter" data-level="9.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html"><i class="fa fa-check"></i><b>10</b> Exploring of employee salary data set</a><ul>
<li class="chapter" data-level="10.1" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#read-in-and-clean-data"><i class="fa fa-check"></i><b>10.1</b> Read in and clean data</a><ul>
<li class="chapter" data-level="10.1.1" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#r-raw0---read.csvdatasetsstate_employee_payroll_data_calendar_year_2015_through_present.csv-strraw0-employid---uniqueraw0emplid.empl.rcd-sample---sampleemployid-8500-raw---raw0raw0emplid.empl.rcd-in-sample-droplevels-strraw-write.csvraw-file-datasetsstate_employee_salary_data_2017.csv-row.names-false"><i class="fa fa-check"></i><b>10.1.1</b> <code>{r} raw0 &lt;- read.csv(&quot;datasets/State_Employee_Payroll_Data_Calendar_Year_2015_through_Present.csv&quot;) str(raw0) employID &lt;- unique(raw0$EmplId.Empl.Rcd) sample &lt;- sample(employID, 8500) raw &lt;- raw0[raw0$EmplId.Empl.Rcd %in% sample, ] %&gt;% droplevels() str(raw) write.csv(raw, file = &quot;datasets/state_employee_salary_data_2017.csv&quot;, row.names = FALSE) ###</code></a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#information-about-the-variables"><i class="fa fa-check"></i><b>10.2</b> Information about the variables</a><ul>
<li class="chapter" data-level="10.2.1" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a><ul>
<li class="chapter" data-level="10.3.1" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#analysis-of-gross-income-type"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income type</a><ul>
<li class="chapter" data-level="10.4.1" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#gross-type"><i class="fa fa-check"></i><b>10.4.1</b> Gross Type</a></li>
<li class="chapter" data-level="10.4.2" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#ethnic-and-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> Ethnic and Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learning R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-structures" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Data structures</h1>
<p>R data types and basic expressions<sup>1</sup> : Common <strong>data structures</strong> in R include <strong>scalars, vectors, matrices, factors, data frames</strong>, and <strong>lists</strong>. These data structures can contain one or more individual data elements of several types, namely <strong>numeric</strong> (2.5), <strong>character</strong> (“Go Jacks”), or <strong>logical</strong> (TRUE or FALSE).</p>
<div id="basic-concepts" class="section level2">
<h2><span class="header-section-number">3.1</span> Basic concepts</h2>
<div id="expressions" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Expressions</h3>
<p>Type anything at the prompt, and R will evaluate it and print the answer.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>There’s your result, <strong>2</strong>. It’s printed on the console right after your entry.</p>
<p>Type the string <strong>“Go Jacks”</strong>. (Don’t forget the quotes!)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="st">&quot;Go Jacks&quot;</span></code></pre></div>
<pre><code>## [1] &quot;Go Jacks&quot;</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-115" class="exercise"><strong>Exercise 3.1  </strong></span>Now try multiplying 45.6 by 78.9.
</div>

</div>
<div id="logical-values" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Logical Values</h3>
<p>Some expressions return a “logical value”: <strong>TRUE</strong> or <strong>FALSE</strong>. (Many programming languages refer to these as “boolean” values.) Let’s try typing an expression that gives us a logical value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">3</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>And another logical value (note that you need a double-equals sign to check whether two values are equal - a single-equals sign won’t work):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span><span class="dv">5</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p><strong>T</strong> and <strong>F</strong> are shorthand for <strong>TRUE</strong> and <strong>FALSE</strong>. Try this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">T <span class="op">==</span><span class="st"> </span><span class="ot">TRUE</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
</div>
<div id="variables" class="section level3">
<h3><span class="header-section-number">3.1.3</span> Variables</h3>
<p>As in other programming languages, you can store a value into a variable to access it later. Type <strong>x = 42</strong> to store a value in <strong>x</strong>. x is a <strong>scalar, with only one data element</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span><span class="dv">42</span></code></pre></div>
<p>You can also use the following. This is a conventional, safer way to assign values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">42</span></code></pre></div>
<p>x can now be used in expressions in place of the original result. Try dividing <strong>x</strong> by <strong>2</strong> (<strong>/</strong> is the division operator), and other calculations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x <span class="op">/</span><span class="st"> </span><span class="dv">2</span></code></pre></div>
<pre><code>## [1] 21</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(x)</code></pre></div>
<pre><code>## [1] 3.73767</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">^</span><span class="dv">2</span></code></pre></div>
<pre><code>## [1] 1764</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(x)</code></pre></div>
<pre><code>## [1] 6.480741</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>You can re-assign any value to a variable at any time. Try assigning <strong>“Go Jacks!”</strong> to <strong>x</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> &quot;Go Jacks!&quot;</span></code></pre></div>
<p>You can print the value of a variable at any time just by typing its name in the console. Try printing the current value of x.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x</code></pre></div>
<pre><code>## [1] &quot;Go Jacks!&quot;</code></pre>
<p>Now try assigning the <strong>TRUE</strong> logical value to <strong>x</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="ot">TRUE</span></code></pre></div>
<p>You can store multiple values in a variable or object. That is called a <strong>vector</strong>, which is explained below. An object can also contain a table with rows and columns, like an Excel spreadsheet, as a <strong>matrix</strong>, or <strong>data frame</strong>.</p>
</div>
<div id="functions" class="section level3">
<h3><span class="header-section-number">3.1.4</span> Functions</h3>
<p>You call a function by typing its name, followed by one or more arguments to that function in parenthesis. Most of your R commands are functional calls. Let’s try using the sum function, to add up a few numbers. Enter:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Some arguments have names. For example, to repeat a value 3 times, you would call the <strong>rep</strong> function and provide its <strong>times</strong> argument:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="st">&quot;Yo ho!&quot;</span>, <span class="dt">times =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] &quot;Yo ho!&quot; &quot;Yo ho!&quot; &quot;Yo ho!&quot;</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-127" class="exercise"><strong>Exercise 3.2  </strong></span>Suppose a vector is definded as x &lt;- c(12, 56, 31, -5, 7). Calculate the mean of all elements in x, assign the mean to <em>y</em>. Squared each element in x and assign the result in a new vector <em>z</em>.
</div>


<div class="exercise">
<span id="exr:unnamed-chunk-128" class="exercise"><strong>Exercise 3.3  </strong></span>Try to find and run the two functions that sets and returns the current working directory.
</div>


<div class="exercise">
<span id="exr:unnamed-chunk-129" class="exercise"><strong>Exercise 3.4  </strong></span>Try to find and run the function that lists all the files in the current working folder.
</div>

<p>Many times, we want to re-use a chunk of code. The most efficient way is to wrap these code as a function, clearly define what the input and the output. Functions are fundamental building blocks of R. Most of the times when we run R commands, we are calling and executing functions. We can easily define our very own functions.</p>
<p>For example, we have the following arithmetic function:</p>
<p><span class="math display">\[f(x)=1.5 x^3+ x^2-2x+1\]</span></p>
<p>Obviously, we can use the following code to do the computing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">5</span>
<span class="fl">1.57345</span> <span class="op">*</span><span class="st"> </span>x <span class="op">^</span><span class="st"> </span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span>x <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] 212.6813</code></pre>
<p>This will work, but every time we have to re-write this code. So let’s try to define our own function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myf &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
       y =<span class="st"> </span><span class="fl">1.57345</span> <span class="op">*</span><span class="st"> </span>x <span class="op">^</span><span class="st"> </span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span>x <span class="op">^</span><span class="st"> </span><span class="dv">2</span> <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
       <span class="kw">return</span>(y)
}</code></pre></div>
<p>Note that “{” and “}” signify the beginning and end of a block of code. <strong>“function”</strong> tells R that a function is going to be defined. At the end, the <strong>“return”</strong> statement returns the desired value.</p>
<p>You can copy and paste the 4 lines of code to R and it defines a function called myf, which you can call by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">myf</span>(<span class="dv">5</span>)  <span class="co"># or myf(x = 5)</span></code></pre></div>
<pre><code>## [1] 212.6813</code></pre>
<p>As you can see you get the same results when x=5. But now you can use this in many ways.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="op">-</span><span class="st"> </span><span class="dv">10</span> <span class="op">:</span><span class="st"> </span><span class="dv">10</span>  <span class="co"># x now is a vector  with 21 numbers -10, -9, … 10</span>
<span class="kw">myf</span>(x) </code></pre></div>
<pre><code>##  [1] -1452.45000 -1047.04505  -724.60640  -475.69335  -290.86520
##  [6]  -160.68125   -75.70080   -26.48315    -3.58760     2.42655
## [11]     1.00000     1.57345    13.58760    46.48315   109.70080
## [16]   212.68125   364.86520   575.69335   854.60640  1211.04505
## [21]  1654.45000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x, <span class="kw">myf</span>(x))  <span class="co"># see plot on the right.</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p>Obviously functions can handle many different calculations beyond arithmetic functions. It can take in one or more inputs and return a list of complex data objects too.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-134" class="exercise"><strong>Exercise 3.5  </strong></span>Write an R function to implement this arithmetic function: f(x)= |x|+5x-6. Note |x| means the absolute value of x. Use this function to find f(4.534), and also produce a plot like the example.
</div>

<p>Let’s define a function to count even numbers in a vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#counts the number of even intergers in vec</span>
evencount &lt;-<span class="st"> </span><span class="cf">function</span>(vec) {
  k &lt;-<span class="st"> </span><span class="dv">0</span> <span class="co"># assign o to i      #assign 0 to a count varialbe k</span>
  <span class="cf">for</span> (i <span class="cf">in</span> vec) {            <span class="co">#set i to vec[1],vec[2],...</span>
    <span class="cf">if</span> (i <span class="op">%%</span><span class="st"> </span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) k &lt;-<span class="st"> </span>k <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="co"># test if i is an even or odd number. %% is the modulo operator</span>
  }
  <span class="kw">return</span>(k)                   <span class="co">#print the computed value of k</span>
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x=<span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">14</span>, <span class="dv">12</span>, <span class="dv">8</span>, <span class="dv">3</span>) <span class="co">#a vector</span>
<span class="kw">evencount</span>(x)           <span class="co">#Call the function evencount(). </span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>A vaiable is called local variable if it is only visible within a function. Such as <em>k</em> and <em>vec</em> are local variables to the function <strong>evencount()</strong>. They disappear after the function returns.</p>
<p>k</p>
<p>Error: object ‘vec’ not found</p>
<p>vec</p>
<p>Error: object ‘vec’ not found</p>
<p>A variable is called global variable if it is defined outside of functions.A global variable is also available within functions. Here is an example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myfun.globle &lt;-<span class="st"> </span><span class="cf">function</span> (x){
  y &lt;-<span class="st"> </span><span class="dv">1</span>
  <span class="kw">return</span>(x <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>y)
}
<span class="kw">myfun.globle</span>(<span class="dv">8</span>)    <span class="co"># set x=8, and do the calculation: 8-2*y = 8-2*(1)=6</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Here y is a global variable.</p>
<p>The function <em>myfun.globle2()</em> defined below returns the same values as above. But both x and y within the the paratheses <em>(x, y=1)</em> following <em>function</em> are local variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">myfun.globle2 &lt;-<span class="st"> </span><span class="cf">function</span> (x, <span class="dt">y =</span> <span class="dv">1</span>){ <span class="co">#y is set as 1 within the function by default.</span>
  <span class="kw">return</span>(x <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>y)
 }
<span class="kw">myfun.globle2</span>(<span class="dv">8</span>)    <span class="co">#8-2*y = 8-2*(1)=6</span></code></pre></div>
<pre><code>## [1] 6</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-139" class="exercise"><strong>Exercise 3.6  </strong></span>Define a function counting the values that are less than 0 for two vectors x=rnorm(50) and y=rnorm(5000) respectively. Define another function to calcute the proportion that values are less than 0 for x and y respectively. Compare calculated proportions with theoretical proportion 0.5, what conclusions can you make?
</div>

</div>
<div id="looking-for-help-and-example-code" class="section level3">
<h3><span class="header-section-number">3.1.5</span> Looking for Help and Example Code</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">? sum </code></pre></div>
<p>A web page will pope up. This is the official help information for this function. At the bottom of the page is some example code. The quickest way to learn an R function is to run the example codes and see the input and output. You can easily copy, paste, and twist the example code to do your analysis.</p>
<p><strong>example()</strong> brings up examples of usage for the given function. Try displaying examples for the min function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">example</span>(min)</code></pre></div>
<pre><code>## 
## min&gt; require(stats); require(graphics)
## 
## min&gt;  min(5:1, pi) #-&gt; one number
## [1] 1
## 
## min&gt; pmin(5:1, pi) #-&gt;  5  numbers
## [1] 3.141593 3.141593 3.000000 2.000000 1.000000
## 
## min&gt; x &lt;- sort(rnorm(100));  cH &lt;- 1.35
## 
## min&gt; pmin(cH, quantile(x)) # no names
## [1] -2.91210180 -0.65309447 -0.04353514  0.43252312  1.35000000
## 
## min&gt; pmin(quantile(x), cH) # has names
##          0%         25%         50%         75%        100% 
## -2.91210180 -0.65309447 -0.04353514  0.43252312  1.35000000 
## 
## min&gt; plot(x, pmin(cH, pmax(-cH, x)), type = &quot;b&quot;, main =  &quot;Huber&#39;s function&quot;)</code></pre>
<pre><code>## 
## min&gt; cut01 &lt;- function(x) pmax(pmin(x, 1), 0)
## 
## min&gt; curve(      x^2 - 1/4, -1.4, 1.5, col = 2)</code></pre>
<pre><code>## 
## min&gt; curve(cut01(x^2 - 1/4), col = &quot;blue&quot;, add = TRUE, n = 500)
## 
## min&gt; ## pmax(), pmin() preserve attributes of *first* argument
## min&gt; D &lt;- diag(x = (3:1)/4) ; n0 &lt;- numeric()
## 
## min&gt; stopifnot(identical(D,  cut01(D) ),
## min+           identical(n0, cut01(n0)),
## min+           identical(n0, cut01(NULL)),
## min+           identical(n0, pmax(3:1, n0, 2)),
## min+           identical(n0, pmax(n0, 4)))</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">min</span>(<span class="dv">5</span><span class="op">:</span><span class="dv">1</span>, pi)  <span class="co"># -&gt; one number</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Example commands and plots will show up automatically by typing Return in RStudio. In R, you need to click on the plots.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">example</span>(boxplot)  <span class="co"># bring example of boxplot</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<p>I found a lot of help information about R through Google. Google tolerate typos, grammar errors, and different notations. Also, most (99 %) of your questions have been asked and answered on various forums. Many R gurus answered a ton of questions on web sites like** <a href="stackoverflow.com" class="uri">stackoverflow.com</a>**, with example codes! I also use Google as a reference.</p>
<p>It is important to add comments to your code. Everything after the “#” will be ignored by R when running. We often recycle and repurpose our codes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">max</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>)  <span class="co"># return the maximum value of a vector</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
</div>
<div id="data-structures-1" class="section level2">
<h2><span class="header-section-number">3.2</span> Data structures</h2>
<div id="vectors" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Vectors</h3>
<p>A vector is an object that holds a sequence of values of the same type. A vector’s values can be numbers, strings, logical values, or any other type, as long as they’re all the same type. They can come from a column of a data frame. if we have a vector x:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
x</code></pre></div>
<pre><code>## [1]  5  2 22 11  5</code></pre>
<p>Here <strong>c</strong> stands for <em>concatenate</em>, do not use it as variable name. It is as special as you!</p>
<p>Vectors can not hold values with different modes (types). Try mixing modes and see what happens:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="dv">1</span>, <span class="ot">TRUE</span>, <span class="st">&quot;three&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;1&quot;     &quot;TRUE&quot;  &quot;three&quot;</code></pre>
<p>All the values were converted to a single mode (characters) so that the vector can hold them all. To hold diverse types of values, you will need a <strong>list</strong>, which is explained later in this chapter.</p>
<p>If you need a vector with a sequence of numbers you can create it with <strong>start:end</strong> notation. This is often used in loops and operations on the indices of vectors etc. Let’s make a vector with values from 5 through 9:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">5</span><span class="op">:</span><span class="dv">9</span></code></pre></div>
<pre><code>## [1] 5 6 7 8 9</code></pre>
<p>A more versatile way to make sequences is to call the <strong>seq</strong> function. Let’s do the same thing with <strong>seq</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">5</span>, <span class="dt">to =</span> <span class="dv">9</span>)</code></pre></div>
<pre><code>## [1] 5 6 7 8 9</code></pre>
<p>seq also allows you to use increments other than 1. Try it with steps of 0.5:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">5</span>, <span class="dt">to =</span> <span class="dv">9</span>, <span class="dt">by =</span> .<span class="dv">5</span>)</code></pre></div>
<pre><code>## [1] 5.0 5.5 6.0 6.5 7.0 7.5 8.0 8.5 9.0</code></pre>
<p>Create a sequence from 5 to 9 with length 15:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">5</span>, <span class="dt">to =</span> <span class="dv">9</span>, <span class="dt">length =</span> <span class="dv">15</span>)</code></pre></div>
<pre><code>##  [1] 5.000000 5.285714 5.571429 5.857143 6.142857 6.428571 6.714286
##  [8] 7.000000 7.285714 7.571429 7.857143 8.142857 8.428571 8.714286
## [15] 9.000000</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-152" class="exercise"><strong>Exercise 3.7  </strong></span>Compute 1+2+3… +1000 with one line of R code. Hint: examine the example code for sum( ) function in the R help document.
</div>

<div id="commands-about-vector" class="section level4">
<h4><span class="header-section-number">3.2.1.1</span> Commands about vector</h4>
<p>Next we will try those commands about vector. First let’s find out what is the 4th element of our vector x &lt;- c(5, 2, 22, 11, 5), or the elements from 2 to 4.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">4</span>]</code></pre></div>
<pre><code>## [1] 11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]</code></pre></div>
<pre><code>## [1]  2 22 11</code></pre>
<p>If you define the vector as y,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]</code></pre></div>
<p>No result is returned but you “captured” the result in a new vector, which holds 3 numbers. You can type y and hit enter to see the results. Or do some computing with it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]; y</code></pre></div>
<pre><code>## [1]  2 22 11</code></pre>
<p>This does exactly the same in one line. Semicolon separates multiple commands.</p>
<p>Now if we want to know the number of elements in the vector</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(x)</code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>It’s also easy to know about the maximum, minimum, sum, mean and median individually or together. We can get standard deviation too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">max</span>(x)</code></pre></div>
<pre><code>## [1] 22</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">min</span>(x)</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(x)</code></pre></div>
<pre><code>## [1] 45</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(x)</code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">median</span>(x)</code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(x)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       2       5       5       9      11      22</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(x)</code></pre></div>
<pre><code>## [1] 7.968689</code></pre>
<p>rank() function ranks the elements. Ties are shown as the average of these ranks. While sort() will sort from the smallest to the biggest, decreasing = T will make it sort form the biggest to the smallest.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rank</span>(x)</code></pre></div>
<pre><code>## [1] 2.5 1.0 5.0 4.0 2.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sort</span>(x)</code></pre></div>
<pre><code>## [1]  2  5  5 11 22</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sort</span>(x, <span class="dt">decreasing =</span> T)</code></pre></div>
<pre><code>## [1] 22 11  5  5  2</code></pre>
<p>diff() lag and iterate the differences of vector x.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">diff</span>(x)</code></pre></div>
<pre><code>## [1]  -3  20 -11  -6</code></pre>
<p>rev() will reverse the position of the elements in the vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rev</span>(x)</code></pre></div>
<pre><code>## [1]  5 11 22  2  5</code></pre>
<p>Operations are performed element by element. Same for log, sqrt, x^2, etc. They return vectors too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(x)</code></pre></div>
<pre><code>## [1] 1.6094379 0.6931472 3.0910425 2.3978953 1.6094379</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(x)</code></pre></div>
<pre><code>## [1] 2.236068 1.414214 4.690416 3.316625 2.236068</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">^</span><span class="dv">2</span></code></pre></div>
<pre><code>## [1]  25   4 484 121  25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">*</span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] 11  5 45 23 11</code></pre>
<p>If we don’t want the second element and save it as y:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="op">-</span><span class="dv">2</span>]
y</code></pre></div>
<pre><code>## [1]  5 22 11  5</code></pre>
<p>Add an element 100 to the vector x between the second and the third element:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)     
x &lt;-<span class="st"> </span><span class="kw">c</span>(x[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>], <span class="dv">100</span>, x[<span class="dv">3</span><span class="op">:</span><span class="dv">5</span>] )  <span class="co">#add an element 100 to x between elements 8 and 9</span>
x                          <span class="co">#The value 100 is added to the previous vector x </span></code></pre></div>
<pre><code>## [1]   5   2 100  22  11   5</code></pre>
<p>Length of the new created x is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(x)</code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>To add a new element to the end, we can use the two commands below, they generate same result.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>) 
<span class="kw">c</span>(x, <span class="dv">7</span>)</code></pre></div>
<pre><code>## [1]  5  2 22 11  5  7</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">append</span>(x, <span class="dv">7</span>)</code></pre></div>
<pre><code>## [1]  5  2 22 11  5  7</code></pre>
<p>Creat an empty vector y:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>()
y</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(y)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Sometimes we are interested in unique elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>) 
<span class="kw">unique</span>(x)</code></pre></div>
<pre><code>## [1]  5  2 22 11</code></pre>
<p>And the frequencies of the unique elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">table</span>(x)</code></pre></div>
<pre><code>## x
##  2  5 11 22 
##  1  2  1  1</code></pre>
<p>If we are interested in the index of the maximum or minimum:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">which.max</span>(x)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">which.min</span>(x)</code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Or we need to look for the location of a special value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">which</span>(x <span class="op">==</span><span class="st"> </span><span class="dv">11</span>)</code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Or more complicated, we want to find the locations where <span class="math inline">\(x^2&gt;100\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
x<span class="op">^</span><span class="dv">2</span></code></pre></div>
<pre><code>## [1]  25   4 484 121  25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">which</span> (x<span class="op">^</span><span class="dv">2</span> <span class="op">&gt;</span><span class="st"> </span><span class="dv">100</span>)</code></pre></div>
<pre><code>## [1] 3 4</code></pre>
<p>We can randomly select some elements from the vector. Run the following code more than once, do you always get the same results? The answer is “No”. Because the 3 elements are randomly selected.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">sample</span>(x, <span class="dv">3</span>)</code></pre></div>
<pre><code>## [1]  5  5 11</code></pre>
<p>Elements in the vector can have names. Type “x” in the command window to see the difference.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">names</span>(x) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;David&quot;</span>, <span class="st">&quot;Breck&quot;</span>, <span class="st">&quot;Zach&quot;</span>, <span class="st">&quot;Amy&quot;</span>, <span class="st">&quot;John&quot;</span>)
x</code></pre></div>
<pre><code>## David Breck  Zach   Amy  John 
##     5     2    22    11     5</code></pre>
<p>Now we can refer to the elements by their names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="st">&quot;Amy&quot;</span>]</code></pre></div>
<pre><code>## Amy 
##  11</code></pre>
<p>The <em>any()</em> and <em>all()</em> functions produce logical values. They return if any of all of their arguments are TRUE.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">any</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="dv">10</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">any</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">all</span>(x <span class="op">&lt;</span><span class="st"> </span><span class="dv">10</span>)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
<span class="kw">any</span>(x <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">&gt;</span><span class="dv">10</span></code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE FALSE</code></pre>
<p>If we want to get a subset from a vector, there are multiple methods can be used.Here are some examples:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">NA</span>, <span class="dv">2</span>, <span class="op">-</span><span class="dv">4</span>, <span class="ot">NA</span>, <span class="dv">9</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">5</span>)
x</code></pre></div>
<pre><code>## [1] NA  2 -4 NA  9 -1  5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[x <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>]
y</code></pre></div>
<pre><code>## [1] NA -4 NA -1</code></pre>
<p>There are annoying NAs in the subset y. We can remove the NAs by applying <em>na.rm()</em> function to y. Or we can use the <em>subset()</em> function to get a “clean” data without NAs.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">subset</span>(x, x <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] -4 -1</code></pre>
<p>The <em>ifelse()</em> function allows us do conditional element selection. The usage is <em>ifelse(test, yes, no)</em>. The yes and no depends on the test is true of false. Here are two examples.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="op">-</span><span class="dv">3</span>, <span class="dv">4</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">5</span>, <span class="dv">6</span>)
y &lt;-<span class="st"> </span><span class="kw">ifelse</span>(x <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="st">&#39;Positive&#39;</span>, <span class="st">&#39;Negative&#39;</span>)
y</code></pre></div>
<pre><code>## [1] &quot;Positive&quot; &quot;Negative&quot; &quot;Positive&quot; &quot;Negative&quot; &quot;Negative&quot; &quot;Positive&quot;</code></pre>
<p>In this example, the element in y is either ‘positive’ or ‘negative’. It depends on x greater than 0 or less than 0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="op">-</span><span class="dv">6</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">2</span>)
y &lt;-<span class="st"> </span><span class="kw">ifelse</span> (x <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>, <span class="kw">abs</span>(x), <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">1</span>) 
y</code></pre></div>
<pre><code>## [1] 7 9 6 3 2</code></pre>
<p>In this example, if an element in x is less than 0, then take the absolute value of the element. Otherwise multiply the element by 2 then add 1.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-187" class="exercise"><strong>Exercise 3.8  </strong></span>Using sample selction function randomly select 10 integers from 1 to 100. Create a vector y which satisfies the following conditions: if an selcted integer is an even number, then y returns ‘even’, otherwise y returns ‘odd’.
</div>

<p>If we have two vectors and try to compare them with each other:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">22</span>, <span class="dv">11</span>, <span class="dv">5</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">11</span>, <span class="dv">8</span>)
z &lt;-<span class="st"> </span><span class="kw">match</span>(y, x)
z</code></pre></div>
<pre><code>## [1]  1  4 NA</code></pre>
<p>match() returns the locations in 2nd vector. NA means missing, not found. To check if NA is in a vector, we use the function is.na( ). Note that the result is a vector holding logical values. Do we have missing value in our vector?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.na</span>(x)</code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE FALSE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.na</span>(z)</code></pre></div>
<pre><code>## [1] FALSE FALSE  TRUE</code></pre>
<p>Sometimes, when working with sample data, a given value isn’t available. But it’s not a good idea to just throw those values out. R has a value that explicitly indicates a sample was not available: <strong>NA</strong>. Many functions that work with vectors treat this value specially. For our z vector, try to get the sum of its values, and see what the result is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(z)</code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>The sum is considered “not available” by default because one of the vector’s values was <strong>NA</strong>. This is the responsible thing to do; R won’t just blithely add up the numbers without warning you about the incomplete data. We can explicitly tell <strong>sum</strong> (and many other functions) to remove <strong>NA</strong> values before they do their calculations, however.</p>
<p>Bring up documentation for the <strong>sum</strong> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">? sum</code></pre></div>
<p>sum package:base</p>
<p>R Documentation …</p>
<p>As you see in the documentation, <strong>sum</strong> can take an optional named argument, <strong>na.rm</strong>. It’s set to <strong>FALSE</strong> by default, but if you set it to <strong>TRUE</strong>, all <strong>NA</strong> arguments will be removed from the vector before the calculation is performed.</p>
<p>Try calling <strong>sum</strong> again, with <strong>na.rm</strong> parameter set to <strong>TRUE</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(z, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] 5</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-193" class="exercise"><strong>Exercise 3.9  </strong></span>Now compute the average of values in z. Ignore the missing values.
</div>

<p>Let’s using examples to show the differences between NULL and NA.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># build up a vector of numbers greater than 10 in vector vec.x</span>
vec.x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">40</span>, <span class="dv">3</span>, <span class="dv">11</span>, <span class="dv">0</span>, <span class="dv">9</span>)
z1 &lt;-<span class="st"> </span><span class="ot">NULL</span>
<span class="cf">for</span> (i <span class="cf">in</span> vec.x) {
  <span class="cf">if</span> (i <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>) z1 &lt;-<span class="st"> </span><span class="kw">c</span>(z1, i)
}
z1</code></pre></div>
<pre><code>## [1] 40 11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(z1)</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># build up a vector of numbers greater than 10 in vector vec.x</span>
vec.x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">40</span>, <span class="dv">3</span>, <span class="dv">11</span>, <span class="dv">0</span>, <span class="dv">9</span>)
z2 &lt;-<span class="st"> </span><span class="ot">NA</span>
<span class="cf">for</span> (i <span class="cf">in</span> vec.x) {
  <span class="cf">if</span> (i <span class="op">&gt;</span><span class="st"> </span><span class="dv">10</span>) z2 &lt;-<span class="st"> </span><span class="kw">c</span>(z2, i)
}
z2</code></pre></div>
<pre><code>## [1] NA 40 11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(z2)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Comparing the length of z1 and z2, we know the NULL is counted as nonexistent, but the NA is counted as a missing value.</p>
<p>Let’s do some opertations related to vectors. Firsly, we start from the operation between a vector and a scalar.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Operation between x and a scalar</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="dv">1</span>
x<span class="op">+</span>y</code></pre></div>
<pre><code>## [1]  2  5  9 10 11</code></pre>
<p>As you can see, 1 is added to each element in x. The operation is equivalent to:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)
x<span class="op">+</span>y</code></pre></div>
<pre><code>## [1]  2  5  9 10 11</code></pre>
<p>The operation between vectors with same length is element-wise. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Operation between two vectors with same length</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">15</span>)
x<span class="op">+</span>y</code></pre></div>
<pre><code>## [1]  2  6  8 12 25</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">*</span>y</code></pre></div>
<pre><code>## [1]   1   8   0  27 150</code></pre>
<p>If vectors have different length, then R will automatically <em>recycles</em> the shorter one, untill it has the same length as the longer one. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)
x<span class="op">+</span>y</code></pre></div>
<pre><code>## Warning in x + y: longer object length is not a multiple of shorter object
## length</code></pre>
<pre><code>## [1]  2  6  9 11 11</code></pre>
<p>The y was <em>recyled</em>, in fact the real operation is showed below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>)
x<span class="op">+</span>y</code></pre></div>
<pre><code>## [1]  2  6  9 11 11</code></pre>
</div>
<div id="scatter-plots-of-two-vectors" class="section level4">
<h4><span class="header-section-number">3.2.1.2</span> Scatter Plots of two vectors</h4>
<p>The <strong>plot</strong> function takes two vectors, one for X values and one for Y values, and draws a graph of them. Let’s draw a graph showing the relationship of numbers and their sines.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">20</span>, <span class="fl">0.1</span>)
y &lt;-<span class="st"> </span><span class="kw">sqrt</span>(x)</code></pre></div>
<p>Then simply call plot with your two vectors:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x, y)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-205-1.png" width="672" /></p>
<p>Great job! Notice on the graph that values from the first argument (x) are used for the horizontal axis, and values from the second (y) for the vertical.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-206" class="exercise"><strong>Exercise 3.10  </strong></span>Create a vector with 21 integers from -10 to 10, and store it in the x variable. Then create a scatterplot of x^2 against x.
</div>

</div>
<div id="fish-example-of-vector" class="section level4">
<h4><span class="header-section-number">3.2.1.3</span> Fish example of vector</h4>
<p>Once upon a time, Tom, Jerry, and Mickey went fishing and they caught 7, 3, and 9 fishes, respectively. This information can be stored in a vector, like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(<span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">9</span>)</code></pre></div>
<pre><code>## [1] 7 3 9</code></pre>
<p>The <strong>c()</strong> function creates a new vector by combining a set of values. If we want to continue to use the vector, we hold it in an object and give it a name:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">9</span>)
fishes</code></pre></div>
<pre><code>## [1] 7 3 9</code></pre>
<p><strong>fishes</strong> is a vector with 3 data elements. There are many functions that operate on vectors. You can plot the vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(fishes)  <span class="co"># see figure 6.1A</span></code></pre></div>
<p>You can compute the total:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(fishes)</code></pre></div>
<pre><code>## [1] 19</code></pre>
<p>We can access the individual elements by indices:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes[<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 9</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-212" class="exercise"><strong>Exercise 3.11  </strong></span>Does Mickey caught more fishes than Tom and Jerry combined? Write R code to verify this statement using the <strong>fishes</strong> vector and return a TRUE or FALSE value.
</div>

<p>Jerry protested that the ¼ inch long fish he caught and released per fishing rules was not counted properly. We can change the values in the 2nd element directly by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes[<span class="dv">2</span>] &lt;-<span class="st"> </span>fishes[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span><span class="dv">1</span> </code></pre></div>
<p>On the left side, we take the current value of the 2nd element, which is 3, and add an 1 to it. The result (4) is assigned back to the 2nd element itself. As a result, the 2nd element is increased by 1. This is not an math equation, but a value assignment operation. More rigorously, we should write this as fishes[2] <strong>&lt;-</strong> fishes[2] + 1</p>
<p>We can also directly overwrite the values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="dv">4</span>
fishes</code></pre></div>
<pre><code>## [1] 7 4 9</code></pre>
<p>They started a camp fire, and each ate 1 fish for dinner. Now the fishes left:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes2 &lt;-<span class="st"> </span>fishes <span class="op">-</span><span class="st"> </span><span class="dv">1</span>
fishes2</code></pre></div>
<pre><code>## [1] 6 3 8</code></pre>
<p>Most arithmetic operations work just as well on vectors as they do on single values. R subtracts 1 from each individual element. If you add a scalar (a single value) to a vector, the scalar will be added to each value in the vector, returning a new vector with the results.</p>
<p>While they are sleeping in their camping site, a fox stole 3 fishes from Jerry’s bucket, and 4 fishes from Mickey’s bucket. How many left?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stolen &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">4</span>)  <span class="co"># a new vector</span>
fishes2 <span class="op">-</span><span class="st"> </span>stolen</code></pre></div>
<pre><code>## [1] 6 0 4</code></pre>
<p>If you add or subtract two vectors of the same length, R will take the corresponding values from each vector and add or subtract them. The 0 is necessary to keep the vector length the same.</p>
<p>Proud of himself, Mickey wanted to make a 5ft x 5ft poster to show he is the best fisherman. Knowing that <strong>a picture worthes a thousand words</strong>, he learned R and started plotting. He absolutely needs his names on the plots. The data elements in a vector can have names or labels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(fishes) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Tom&quot;</span>, <span class="st">&quot;Jerry&quot;</span>, <span class="st">&quot;Mickey&quot;</span>)</code></pre></div>
<p>The right side is a vector, holding 3 character values. These values are assigned as the names of the 3 elements in the fishes vector. names is a built-in function. Our vector looks like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes</code></pre></div>
<pre><code>##    Tom  Jerry Mickey 
##      7      4      9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(fishes)   <span class="co"># see figure 6.1B</span></code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:6-1"></span>
<img src="images/img0601_fish.png" alt="Simple Bar plot" width="80%" />
<p class="caption">
Figure 3.1: Simple Bar plot
</p>
</div>
<p>Assigning names for a vector also enables us to use labels to access each element. Try getting the value for Jerry:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fishes[<span class="st">&quot;Jerry&quot;</span>]</code></pre></div>
<pre><code>## Jerry 
##     4</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-220" class="exercise"><strong>Exercise 3.12  </strong></span>Now see if you can set the value for <strong>Tom</strong> to something other than 5 using the name rather than the index.
</div>

<p>Tom proposes that their goal for next fishing trip is to double their catches.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>fishes</code></pre></div>
<pre><code>##    Tom  Jerry Mickey 
##     14      8     18</code></pre>
<p>Hopelessly optimistic, Jerry proposed that next time each should “square” their catches, so that together they may feed the entire school.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(fishes <span class="op">^</span><span class="st"> </span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 146</code></pre>
<p>Note that two operations are nested. You can obviously do it in two steps.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-223" class="exercise"><strong>Exercise 3.13  </strong></span>Create a vector representing the prices of groceries, bread $2.5, milk $3.1, jam $5.3, beer $9.1. And create a bar plot to represent this information.
</div>

</div>
</div>
<div id="matrix-operations" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Matrix operations</h3>
<p><strong>Matrix</strong> is a two dimensional data structure in R programming. Technically, a matrix is also a vector, but with two additional attributes: the number of rows and the number of columns. A matrix has rows and columns, but it can only contain one type of values, i.e. numbers, characters, or logical values.</p>
<p>We can creat a matrix by using <em>rbind</em> or <em>cbind</em> function. <em>rbind</em> combine all row Here are two examples:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>), <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">15</span>)) <span class="co"># combine vectors by row</span>
m</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    3    4    5
## [2,]   10   13   15</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>), <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">13</span>, <span class="dv">15</span>), <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)) <span class="co"># combine vectors by column</span>
n</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    3   10    3
## [2,]    4   13    2
## [3,]    5   15    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">s &lt;-<span class="st"> </span><span class="kw">rbind</span>(m,n)      <span class="co">#combine two matrices m and n by row</span>
s</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    3    4    5
## [2,]   10   13   15
## [3,]    3   10    3
## [4,]    4   13    2
## [5,]    5   15    1</code></pre>
<p>To use <em>rbind()</em> combining matrices by row, the matrices must have same number of columns. Similar to <em>cbind()</em>, the matrices must have same number of rows.</p>
<p>We can also create a matrix by using the <em>matrix()</em> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">12</span>), <span class="dt">nrow =</span> <span class="dv">4</span>, <span class="dt">ncol =</span> <span class="dv">3</span>)
x</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    5    9
## [2,]    2    6   10
## [3,]    3    7   11
## [4,]    4    8   12</code></pre>
<p>The argument <em>seq()</em> create a sequence from 1 to 12, <em>nrom()</em> define the number of rows in the matrix, <em>ncol()</em> define the number of columns in the matrix. We don’t have to give both <em>nrom()</em> and <em>ncol()</em> since if one is provided, the other is inferred from length of the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">12</span>), <span class="dt">nrow =</span> <span class="dv">4</span>)
y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    5    9
## [2,]    2    6   10
## [3,]    3    7   11
## [4,]    4    8   12</code></pre>
<p>As we can see that, the matrix is filled in column-wise by default. If you want to fill a matrix by row-wise, add the <em>byrow = TRUE</em> to the argument:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">seq</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">12</span>), <span class="dt">nrow =</span> <span class="dv">4</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)    <span class="co"># fill matrix row-wise</span>
z</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    2    3
## [2,]    4    5    6
## [3,]    7    8    9
## [4,]   10   11   12</code></pre>
<p>The following code will create an empty matrix y:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">w &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">nrow =</span> <span class="dv">4</span>, <span class="dt">ncol =</span> <span class="dv">3</span>)
w</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   NA   NA   NA
## [2,]   NA   NA   NA
## [3,]   NA   NA   NA
## [4,]   NA   NA   NA</code></pre>
<p>We can assign values to the matrix. For example, let’s assign the value 3 to the position at first row and first column and value 100 to position of the second row and third column:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">w[<span class="dv">1</span>,<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">3</span>
w[<span class="dv">2</span>,<span class="dv">3</span>] &lt;-<span class="st"> </span><span class="dv">100</span>
w</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    3   NA   NA
## [2,]   NA   NA  100
## [3,]   NA   NA   NA
## [4,]   NA   NA   NA</code></pre>
<p>We can also create a matrix from a vector by setting its dimension using function <em>dim()</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">21</span>, <span class="dv">15</span>, <span class="dv">76</span>)
x</code></pre></div>
<pre><code>## [1]  1  5  6  9  8 10 21 15 76</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(x) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">3</span>)
x</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    9   21
## [2,]    5    8   15
## [3,]    6   10   76</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;matrix&quot;</code></pre>
<p>We can convert a non-matrix data set to a matrix using <em>as.matrix()</em> function. Take the data <em>iris</em> as an example.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">subset.iris &lt;-<span class="st"> </span>iris[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]
<span class="kw">class</span>(subset.iris)</code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>The data structure of <em>subset.iris</em> is a data frame. The function <em>as.matrix</em> wii transfer a data frame to a matix.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(subset.iris)
<span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;matrix&quot;</code></pre>
<p>Various matrix operation can be applied in R. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
x</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">^</span><span class="dv">2</span>                         <span class="co">#Squared each element in x</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    9   25
## [2,]    4   16   36</code></pre>
<p>You can transform the matrix if you want, for the convenience of view and analysis.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">t</span>(x)                <span class="co"># transpose of x</span>
y</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4
## [3,]    5    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x <span class="op">%*%</span><span class="st"> </span>y                  <span class="co"># Matrix Multiplication</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   35   44
## [2,]   44   56</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#x - y                   # Matrix subtraction</span></code></pre></div>
<p>Error in x - y : non-conformable arrays</p>
<p>The error reminders us that the matrices for subtraction must have same dimensions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)    
y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1    1
## [2,]    1    1    1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x <span class="op">-</span><span class="st"> </span>y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    0    2    4
## [2,]    1    3    5</code></pre>
<p>We can produce a new matrix by each element is doubled and added 5</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">5</span>
z</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    7   11   15
## [2,]    9   13   17</code></pre>
<p>We can also get a logical matrix using logical code like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">12</span>, <span class="dv">34</span>, <span class="dv">51</span>, <span class="dv">27</span>, <span class="dv">26</span>, <span class="dv">10</span>), <span class="dt">ncol =</span> <span class="dv">2</span>)
x <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span></code></pre></div>
<pre><code>##       [,1]  [,2]
## [1,] FALSE  TRUE
## [2,]  TRUE  TRUE
## [3,]  TRUE FALSE</code></pre>
<p>We can extract all <em>TRUE</em> results from x by using <em>x[x&gt;20]</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[x <span class="op">&gt;</span><span class="st"> </span><span class="dv">20</span>]</code></pre></div>
<pre><code>## [1] 34 51 27 26</code></pre>
<p>Similar we can define a vector with logical values, then apply it to x to get all TRUE values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">log.vau &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)
x[log.vau]</code></pre></div>
<pre><code>## [1] 34 51 27 26</code></pre>
<p>Remember matrix is a vector, and filled by column-wise. Therefore the vector with logical values applies to x by column-wise order.</p>
<p>Since matrix is a vector with two dimension, all operations for vectors also apply to matrix. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">1</span>, ]                         <span class="co"># Get the first row of x</span></code></pre></div>
<pre><code>## [1] 12 27</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])   <span class="co">#Take out the first 4 columns of iris and convert it to matrix.  </span>
c &lt;-<span class="st"> </span>a[<span class="dv">5</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]             <span class="co"># Extract a subset</span>
c</code></pre></div>
<pre><code>##      Sepal.Width Petal.Length Petal.Width
## [1,]         3.6          1.4         0.2
## [2,]         3.9          1.7         0.4
## [3,]         3.4          1.4         0.3
## [4,]         3.4          1.5         0.2
## [5,]         2.9          1.4         0.2
## [6,]         3.1          1.5         0.1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), <span class="dt">nrow =</span> <span class="dv">2</span>)
c[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, ] &lt;-<span class="st"> </span>x                 <span class="co"># Replace the first two rows of c with x</span>
c</code></pre></div>
<pre><code>##      Sepal.Width Petal.Length Petal.Width
## [1,]         1.0          3.0         5.0
## [2,]         2.0          4.0         6.0
## [3,]         3.4          1.4         0.3
## [4,]         3.4          1.5         0.2
## [5,]         2.9          1.4         0.2
## [6,]         3.1          1.5         0.1</code></pre>
<p>Now if we want to know the mean and sum of these rows and columns, try <em>rowMeans()</em>, <em>colMeans()</em>, <em>rowSums()</em>, <em>colSums()</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(iris[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])
<span class="kw">rowMeans</span>(x)</code></pre></div>
<pre><code>##     1     2     3     4     5     6     7     8     9    10 
## 2.550 2.375 2.350 2.350 2.550 2.850 2.425 2.525 2.225 2.400</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colMeans</span>(x)</code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##         4.86         3.31         1.45         0.22</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rowSums</span>(x)</code></pre></div>
<pre><code>##    1    2    3    4    5    6    7    8    9   10 
## 10.2  9.5  9.4  9.4 10.2 11.4  9.7 10.1  8.9  9.6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colSums</span>(x)</code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##         48.6         33.1         14.5          2.2</code></pre>
<p>Here we are computing the standard deviation by columns, using <em>apply()</em> function.The second argument “1” or “2” in <em>apply()</em> reprents the function applies to rows or columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(x, <span class="dv">2</span>, sd) <span class="co"># Calculate the standard deviation of each column in x </span></code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##   0.29135698   0.30713732   0.10801234   0.07888106</code></pre>
<p>Or median by rows, using 1 for rows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">apply</span>(x, <span class="dv">1</span>, median)  <span class="co"># Calculate the median of each row in x </span></code></pre></div>
<pre><code>##    1    2    3    4    5    6    7    8    9   10 
## 2.45 2.20 2.25 2.30 2.50 2.80 2.40 2.45 2.15 2.30</code></pre>
<p>Heatmap is my favorite type of graph for visualizing a large matrix data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">heatmap</span>(x, <span class="dt">scale =</span> <span class="st">&quot;column&quot;</span>, <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">5</span>))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-258-1.png" width="672" /></p>

<div class="exercise">
<span id="exr:unnamed-chunk-259" class="exercise"><strong>Exercise 3.14  </strong></span>Let <em>subset.iris &lt;- as.matrix(iris[1:10, 1:4])</em>, Using apply function to calculate the mean of <em>subset.iris</em> by column.
</div>

<p><strong>Example:</strong> Define a function to find the positions of minimal value in each column of <em>subset.iris &lt;- as.matrix(iris[1:10, 1:4])</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">find.min.posi &lt;-<span class="st"> </span><span class="cf">function</span>(x){
  y &lt;-<span class="st"> </span><span class="cf">function</span>(xcol){
    <span class="kw">return</span>(<span class="kw">which.min</span>(xcol))
  }
  <span class="kw">return</span>(<span class="kw">apply</span>(x, <span class="dv">2</span>, y))
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">subset.iris &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(iris[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])
subset.iris</code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1           5.1         3.5          1.4         0.2
## 2           4.9         3.0          1.4         0.2
## 3           4.7         3.2          1.3         0.2
## 4           4.6         3.1          1.5         0.2
## 5           5.0         3.6          1.4         0.2
## 6           5.4         3.9          1.7         0.4
## 7           4.6         3.4          1.4         0.3
## 8           5.0         3.4          1.5         0.2
## 9           4.4         2.9          1.4         0.2
## 10          4.9         3.1          1.5         0.1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">find.min.posi</span>(subset.iris)</code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##            9            9            3           10</code></pre>
<p>As you can see that the minimal value for Sepal.Length is 4.4 which locates at the 9th row. Similar to other variable. The minimal value locates at the 9th, 3rd and 10th row for Sepal.Width, Petal.Lenth and Petal.Width respectively.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-263" class="exercise"><strong>Exercise 3.15  </strong></span>Let <em>subset.iris.2 &lt;- as.matrix(iris[, 1:4])</em>, fill blanks in the <em>find.max</em> function defined below to find the maximal value in each column of <em>subset.iris.2</em>.
</div>

<p>find.max &lt;- function(x){<br />
y &lt;- function(xcol){<br />
return(_________)<br />
}<br />
return(_______(x, ____, y))<br />
}</p>
<p>________(subset.iris.2)</p>
<p>To make a matrix more easily readable, we can use functions <em>colnames()</em> and <em>rownames</em> to assign names to the columns and rows of the matrix. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>), <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>))
y</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colnames</span>(y) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;First.Col&#39;</span>, <span class="st">&#39;Second.Col&#39;</span>, <span class="st">&#39;Third.Col&#39;</span>)
<span class="kw">row.names</span>(y) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;odd.number&#39;</span>, <span class="st">&#39;even.number&#39;</span>)
y</code></pre></div>
<pre><code>##             First.Col Second.Col Third.Col
## odd.number          1          3         5
## even.number         2          4         6</code></pre>
<p>Another interesting application of matrix is the manipulation of images.You may have heard pixel matrix which represents “picure elements”. They are small little dots making up images. Each image is a matrix with thousands or even millions of pixels. Each pixel can only be one color at a time. If we have a grayscale imge, the brightness of color for each pixel is determined by the value assigned to it. In other words, the pixel value is a single number that represents the brightness of the pixel. For example, if the color value 0.2941 is assigned to a pixel which locates 3rd row and 4th column, then the image at 3rd row and 4th column is pretty dark. The range of the colors from black to white correspond to the scale varies from 0% to 100%.</p>
<p>Most time, we need to blur images or add mosaic to a picture for various purposes. Let’s use one example to demonstrate how to add mosaic to a grayscale image.</p>
<p><strong>Example: Add mosaic to Einstein image</strong></p>
<p>Firstly, let’s read an grayscale image of Einstein into R and view the image.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(pixmap)</code></pre></div>
<pre><code>## Warning: package &#39;pixmap&#39; was built under R version 3.5.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EINSTEIN &lt;-<span class="st"> </span><span class="kw">read.pnm</span>(<span class="st">&quot;EINSTEIN.pgm&quot;</span>, <span class="dt">cellres =</span> <span class="dv">1</span>)
<span class="kw">plot</span>(EINSTEIN)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-266-1.png" width="672" /></p>
<p>Then let us look at structure of this image:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(EINSTEIN)</code></pre></div>
<pre><code>## Formal class &#39;pixmapGrey&#39; [package &quot;pixmap&quot;] with 6 slots
##   ..@ grey    : num [1:512, 1:512] 0.596 0.541 0.522 0.529 0.561 ...
##   ..@ channels: chr &quot;grey&quot;
##   ..@ size    : int [1:2] 512 512
##   ..@ cellres : num [1:2] 1 1
##   ..@ bbox    : num [1:4] 0 0 512 512
##   ..@ bbcent  : logi FALSE</code></pre>
<p>Here we get a new class which is S4 type. We don’t go into depth for this time. One fact we need to pay attendtion is that we must use “@” instead of “$” sign to designate the components.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(EINSTEIN<span class="op">@</span><span class="st"> </span>grey)</code></pre></div>
<pre><code>## [1] &quot;matrix&quot;</code></pre>
<p>The class of <em>EINSTEIN@ grey</em> is matrix. The output <em>..@ grey : num [1:512, 1:512]</em> shows that the dimension of matrix is 512*512. The values “0.596 0.541 0.522 0.529 0.561 …” reprent the brightness values in the matrix. For example, the value of the pixel at 3rd row and 4th column is 0.2941176 as showed below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EINSTEIN<span class="op">@</span><span class="st"> </span>grey[<span class="dv">3</span>,<span class="dv">4</span>]</code></pre></div>
<pre><code>## [1] 0.2941176</code></pre>
<p>If we change the value 0.2941176 to 0 by <em>EINSTEIN@ grey[3,4] &lt;- 0</em>, then that pixel will become pure black. If we assign a random number between 0 to 1 to the value, then the color in the pixel will be randomly assigned based on the random number. Using this idea, we define a masoic function which will be used to blur the image.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mosaic.plot &lt;-<span class="st"> </span><span class="cf">function</span>(image, yrange, xrange){
  length.y &lt;-<span class="st"> </span><span class="kw">length</span>(yrange)
  length.x &lt;-<span class="st"> </span><span class="kw">length</span>(xrange)
  image2 &lt;-<span class="st"> </span>image
  whitenoise &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dt">nrow =</span> length.y, <span class="dt">ncol =</span> length.x, <span class="kw">runif</span>(length.y <span class="op">*</span><span class="st"> </span>length.x))
  image2<span class="op">@</span>grey[yrange, xrange] &lt;-<span class="st"> </span>whitenoise
  <span class="kw">return</span>(image2)
}</code></pre></div>
<p>The argument <em>image</em> is the original image, <em>yrange</em> is the range of rows that you want to blur, <em>xrange</em> is the range of columns that you want to blur. The <em>xrange</em> and <em>yrange</em> construct the mosaic region. Since we don’t want to change the origial image,therefore we copy the original image to image2 by assigning <em>image</em> to <em>image2</em>. The <em>whitenoise</em> creates a matrix filled with random numbers following uniform distribution. The dimensions of <em>whitenoise</em> is determined by the mosaic region. Replace the values in the original image that you want to blur <em><a href="mailto:image2@grey">image2@grey</a>[yrange,xrange]</em> by the <em>whitenoise</em> matrix.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EINSTEIN.mosaic &lt;-<span class="st"> </span><span class="kw">mosaic.plot</span>(EINSTEIN, <span class="dv">175</span><span class="op">:</span><span class="dv">249</span>, <span class="dv">118</span><span class="op">:</span><span class="dv">295</span>)
<span class="kw">plot</span>(EINSTEIN.mosaic)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-271-1.png" width="672" /></p>
<p>Here, we take <em>yrange=175:249</em> and <em>xrange=118:295</em> to select a sub-matrix from 175th row to 249th row, and 118th column to 295th column. This sub-matrix store the color values of Einstein’ eyes region. The sub-matix is replaced by whitenoise matrix. Therefore the image near eyes region are replaced by random colors.</p>
<p>The function <em>locator()</em> allows us to find the relevant rows and columns. Type <strong>locator()</strong> in the <em>Console</em> window, then R will wait for you to click a point within an image, then click <em>esc</em> on your keyboard to exit the function. Then the function will return the coordinates of that point in the <em>Console</em> window. If you click more points once, then the function will return all coordinates of these points sorted by your clicking order. You must be careful about the y-coordinate. The row numbers in <em>pixmap</em> objects increase from the top of the image to the bottom, therefore you need to opposite the y-coordinate by subtracting them from the number of rows in the original image. For example, the y-coordinates that I obtained from <em>locator()</em> function are 337 and 263. After subtracting them from 512, I got 175 and 249. They are the yrange used in the mosaic function.</p>

<div class="exercise">
<p><span id="exr:unnamed-chunk-272" class="exercise"><strong>Exercise 3.16  </strong></span>Using the <em>mosaic.plot()</em> function to blur the image of mona_lisa.pgm by adding mosaic to her eyes region. Your output should look like the graph below.</p>
</div>

<img src="book_files/figure-html/unnamed-chunk-273-1.png" width="672" /> 
<div class="exercise">
<p><span id="exr:unnamed-chunk-274" class="exercise"><strong>Exercise 3.17  </strong></span>Fill in blanks of the following function so that the eyes region of Mona Lisa is covered by pure color, not mosaic.</p>
<p>mosaic.plot.2 &lt;- function(picture, yrange, xrange, degree){<br />
length.y &lt;- _______(yrange)<br />
length.x &lt;- length(______)<br />
pic2 &lt;- picture<br />
pic2@____[_______,_______] &lt;- degree<br />
return(pic2)<br />
}</p>
Setting the degree=0, 0.5 and 1 respectively, plot the images of Mona Lisa that eyes region are covered by pure colors.
</div>

</div>
<div id="lists" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Lists</h3>
<p>All elements in vectors must be same type. The list can combine objectes of different types. Let’s start from creating a list:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dv">5</span>, <span class="st">&quot;John Doe&quot;</span>, <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">7</span>), mean) <span class="co"># a list with 4 components</span>
y</code></pre></div>
<pre><code>## [[1]]
## [1] 5
## 
## [[2]]
## [1] &quot;John Doe&quot;
## 
## [[3]]
## [1] 100   7
## 
## [[4]]
## function (x, ...) 
## UseMethod(&quot;mean&quot;)
## &lt;bytecode: 0x000000001ac32918&gt;
## &lt;environment: namespace:base&gt;</code></pre>
<p>There are 4 components in the list y. We can associate each components with a <em>tag</em>. We add tags “height”, “name”, “BP” and “fun” to the y.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">height =</span> <span class="dv">5</span>, <span class="dt">name =</span> <span class="st">&quot;John Doe&quot;</span>, <span class="dt">BP =</span> <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">77</span>), <span class="dt">fun =</span> mean)  
y</code></pre></div>
<pre><code>## $height
## [1] 5
## 
## $name
## [1] &quot;John Doe&quot;
## 
## $BP
## [1] 100  77
## 
## $fun
## function (x, ...) 
## UseMethod(&quot;mean&quot;)
## &lt;bytecode: 0x000000001ac32918&gt;
## &lt;environment: namespace:base&gt;</code></pre>
<p>Here is another example for creating a list:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x1 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">9</span>), <span class="dt">ncol =</span> <span class="dv">3</span>) <span class="co"># create a matrix</span>
x2 &lt;-<span class="st"> </span><span class="dv">8</span> <span class="op">:</span><span class="st"> </span><span class="dv">1</span>
x3 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">2.4</span>, <span class="fl">5.1</span>, <span class="fl">9.0</span>, <span class="fl">4.4</span>)
x4 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;u&#39;</span>, <span class="st">&#39;v&#39;</span>, <span class="st">&#39;w&#39;</span>)
z &lt;-<span class="st"> </span><span class="kw">list</span>(x1, x2, x3, x4)
z</code></pre></div>
<pre><code>## [[1]]
##      [,1] [,2] [,3]
## [1,]    4    5   10
## [2,]    2    6    9
## 
## [[2]]
## [1] 8 7 6 5 4 3 2 1
## 
## [[3]]
## [1] 2.4 5.1 9.0 4.4
## 
## [[4]]
## [1] &quot;u&quot; &quot;v&quot; &quot;w&quot;</code></pre>
<p>We can build a list by creating an empty list and assigning values to it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v &lt;-<span class="st"> </span><span class="kw">list</span>()         <span class="co">#Create an empty list</span>
v[[<span class="dv">1</span>]] &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">10</span>, <span class="dv">9</span>), <span class="dt">ncol =</span> <span class="dv">3</span>)  <span class="co"># Assign a matrix to v[[1]]</span>
v[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="dv">8</span> <span class="op">:</span><span class="st"> </span><span class="dv">1</span>    <span class="co">#Assign a vector to v[[2]]</span>
v[[<span class="dv">3</span>]] &lt;-<span class="st"> </span>x3       <span class="co">#Assign x3 to v[[3]] where x3 is defined as above</span>
v[[<span class="dv">4</span>]] &lt;-<span class="st"> </span>x4       <span class="co">#Assign x4 to v[[4]] where x4 is defined as above</span>
v</code></pre></div>
<pre><code>## [[1]]
##      [,1] [,2] [,3]
## [1,]    4    5   10
## [2,]    2    6    9
## 
## [[2]]
## [1] 8 7 6 5 4 3 2 1
## 
## [[3]]
## [1] 2.4 5.1 9.0 4.4
## 
## [[4]]
## [1] &quot;u&quot; &quot;v&quot; &quot;w&quot;</code></pre>
<p>We used different methods creating list z and v. The list v and z are identical because that we assigned same components for v as that of in z.</p>
<p>There are several different ways to access the elements in a list. For example, to access the third component in y:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">height =</span> <span class="dv">5</span>, <span class="dt">name =</span> <span class="st">&quot;John Doe&quot;</span>, <span class="dt">BP =</span> <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">77</span>), <span class="dt">fun =</span> mean)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[[<span class="dv">3</span>]]        <span class="co">#Specifing the number in a double square braket</span></code></pre></div>
<pre><code>## [1] 100  77</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y<span class="op">$</span>BP          <span class="co">#Using $ sign</span></code></pre></div>
<pre><code>## [1] 100  77</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[[<span class="st">&quot;BP&quot;</span>]]     <span class="co">#Using the tag</span></code></pre></div>
<pre><code>## [1] 100  77</code></pre>
<p>Note: we used <strong>double square braket</strong> ‘[[]]’ to access the element in a list, which is different from using single square braket ‘[]’ in a vector. If we use sigle square braket in a list, we will get a sublist. For example, y[3] returns a list, y[[3]] returns a numerical vector. Functions <em>class()</em> and <em>is.list</em> can be used to check the types.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[<span class="dv">3</span>]</code></pre></div>
<pre><code>## $BP
## [1] 100  77</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(y[<span class="dv">3</span>])</code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.list</span>(y[<span class="dv">3</span>])</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[[<span class="dv">3</span>]]</code></pre></div>
<pre><code>## [1] 100  77</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(y[[<span class="dv">3</span>]])               <span class="co">#Get the class of y[[3]] </span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.list</span>(y[[<span class="dv">3</span>]])           <span class="co">#Check if y[[3]] is a list or not</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>The forth component of y is <em>fun = mean</em>. There are no quotation marks around <em>mean</em>. The <em>class(y[[4]])</em> returns a function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(y[[<span class="dv">4</span>]])</code></pre></div>
<pre><code>## [1] &quot;function&quot;</code></pre>
<p>This implies that y[[4]] is same as the <em>mean()</em> function. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[[<span class="dv">4</span>]](<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>))          <span class="co">#Get the mean of 1, 2, 3, 4, 5</span></code></pre></div>
<pre><code>## [1] 3</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-287" class="exercise"><strong>Exercise 3.18  </strong></span>Access the second component in list1 by three ways as we introduced above. What is the type of list1[“Hobby”] and list1[[“Hobby”]] respectively?
</div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">  list1 &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">Name =</span> <span class="st">&quot;Tom&quot;</span>, <span class="dt">Hobby =</span> <span class="st">&quot;Fishing&quot;</span>, <span class="dt">Num.fish =</span> <span class="kw">c</span>(<span class="dv">16</span>, <span class="dv">27</span>, <span class="dv">5</span>))</code></pre></div>
<p>Here are some examples for list operation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">height =</span> <span class="dv">5</span>, <span class="dt">name =</span> <span class="st">&quot;John Doe&quot;</span>, <span class="dt">BP =</span> <span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">77</span>), <span class="dt">fun =</span> mean)
y[[<span class="dv">2</span>]] &lt;-<span class="st"> &quot;Mike&quot;</span>    <span class="co">#Change the 2nd component from &quot;John Doe&quot; to &quot;Mike&quot;</span>
y[[<span class="dv">4</span>]] &lt;-<span class="st"> </span><span class="ot">NULL</span>      <span class="co">#Delete the 4th component by setting it to NULL</span>
y</code></pre></div>
<pre><code>## $height
## [1] 5
## 
## $name
## [1] &quot;Mike&quot;
## 
## $BP
## [1] 100  77</code></pre>
<p>The output shows that the name has been changed to Mike and the mean function is deleted. So far, the length of y is 3:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(y)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>We can add the forth components to y using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y<span class="op">$</span>class &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;math&quot;</span>, <span class="st">&quot;art&quot;</span>) <span class="co">#Add a class component</span>
y</code></pre></div>
<pre><code>## $height
## [1] 5
## 
## $name
## [1] &quot;Mike&quot;
## 
## $BP
## [1] 100  77
## 
## $class
## [1] &quot;math&quot; &quot;art&quot;</code></pre>
<p>If we have a vector of tags and a vector of corresponding values, we can associate the names and values into a list by creating an empty list and then fill it via assignment statements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sales &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">100</span>, <span class="dv">105</span>, <span class="dv">98</span>, <span class="dv">112</span>)
seasons &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Spring&quot;</span>, <span class="st">&quot;Summer&quot;</span>, <span class="st">&quot;Fall&quot;</span>, <span class="st">&quot;Winter&quot;</span>)
sale.tag &lt;-<span class="st"> </span><span class="kw">list</span>()               <span class="co">#Create an empty list</span>
sale.tag[seasons] &lt;-<span class="st"> </span>sales
sale.tag</code></pre></div>
<pre><code>## $Spring
## [1] 100
## 
## $Summer
## [1] 105
## 
## $Fall
## [1] 98
## 
## $Winter
## [1] 112</code></pre>
<p>Equivalently, we can associate the names and values by creating an empty list and then assign each component corresponding value or vector. For example.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sale.tag &lt;-<span class="st"> </span><span class="kw">list</span>()               <span class="co">#Create an empty list</span>
sale.tag[[<span class="st">&quot;Spring&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">100</span>
sale.tag[[<span class="st">&quot;Summer&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">105</span>
sale.tag[[<span class="st">&quot;Fall&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">98</span>
sale.tag[[<span class="st">&quot;Winter&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">112</span>
sale.tag</code></pre></div>
<pre><code>## $Spring
## [1] 100
## 
## $Summer
## [1] 105
## 
## $Fall
## [1] 98
## 
## $Winter
## [1] 112</code></pre>

<div class="exercise">
<p><span id="exr:unnamed-chunk-294" class="exercise"><strong>Exercise 3.19  </strong></span>Based on the data set of sale.tag, choose all correct answers from the following options A - F.<br />
A: sale.tag[[1]]<br />
B: sale.tag[[Spring]]<br />
C: sale.tag[[“Spring”]]<br />
D: sale.tag[“Spring”]<br />
E: sale.tag[1]<br />
F: sale.tag[Spring]</p>
1, Which options return a vector. Answer:___________<br />
2, Which options return a list. Answer:___________<br />
3, Which options returns an error. Answer:___________
</div>

<p>Suppose we want to calculate the mean of sales in the dataset sale.tag. Because basic statistical functions work on vectors but not on lists. The mean() does not work: &gt; mean(sale.tag)<br />
[1] NA<br />
Warning message:<br />
In mean.default(sale.tag) :<br />
argument is not numeric or logical: returning NA</p>
<p>To calculate the mean, we need to use function <em>unlist()</em> to flatten the list into a vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(<span class="kw">unlist</span>(sale.tag))</code></pre></div>
<pre><code>## [1] 103.75</code></pre>
<p>Similar to <em>apply()</em> funciton works on vectors, <em>lapply()</em> (for list apply) works on each component of lists. Here is an example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>), <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>))
mean.x &lt;-<span class="st"> </span><span class="kw">lapply</span>(x, mean)
mean.x</code></pre></div>
<pre><code>## [[1]]
## [1] 20
## 
## [[2]]
## [1] 6</code></pre>
<p>The <em>mean.x</em> returns a list consisting of 20 and 6 which are means of components of x respectively.</p>
<p>When the list returned by <em>lapply()</em> could be simplified to a vector or matrix, we can use function <em>sapply()</em> (for <em>simplified [l]apply</em>). Let’s redo the previous example by <em>sapply()</em> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean.x.<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">sapply</span>(x, mean)
mean.x.<span class="dv">2</span></code></pre></div>
<pre><code>## [1] 20  6</code></pre>
<p>We can double check the outputs by <em>class()</em> or <em>is.vector()</em> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(mean.x)               </code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(mean.x.<span class="dv">2</span>)             </code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is.vector</span>(mean.x.<span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Here is another example for <em>sapply()</em> function. Suppose we have NULL elements in a list.null. To remove the NULL element, apply <em>is.null</em> function to every element of the list.null. If the logical value is TRUE, i.e. the element is a NULL, then delete the element by setting NULL to it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">list.null &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&#39;art&#39;</span>, <span class="ot">NULL</span>, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>))
list.null</code></pre></div>
<pre><code>## [[1]]
## [1] &quot;art&quot;
## 
## [[2]]
## NULL
## 
## [[3]]
## [1] 2 4 6 8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">list.null[<span class="kw">sapply</span>(list.null, is.null)] &lt;-<span class="st"> </span><span class="ot">NULL</span>
list.null</code></pre></div>
<pre><code>## [[1]]
## [1] &quot;art&quot;
## 
## [[2]]
## [1] 2 4 6 8</code></pre>
<p>For a small size data set, if we can locate the position of NULL element, we can easily remove the NULL element by setting NULL to that element. For example, we already know the second element of list.null is NULL, to remove this NULL element, we set a NULL to the second element:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">list.null &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&#39;art&#39;</span>, <span class="ot">NULL</span>, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>))
list.null[[<span class="dv">2</span>]] &lt;-<span class="st"> </span><span class="ot">NULL</span>
list.null</code></pre></div>
<pre><code>## [[1]]
## [1] &quot;art&quot;
## 
## [[2]]
## [1] 2 4 6 8</code></pre>
<p>But for large size of data set, we turn to the <em>sapply()</em> function to remove NULL elements.</p>
<p><strong>Example</strong>: Suppose we have a list of customers who visited our store in the last 10 days. Some customers visited the store more than once. We want to find out on which days and the total number of days that each customer visited. The customer names are recorded by the order of the day they came:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">customer &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Brandon&quot;</span>, <span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Daniel&quot;</span>, <span class="st">&quot;Grace&quot;</span>, <span class="st">&quot;Mary&quot;</span>, 
                 <span class="st">&quot;Mary&quot;</span>, <span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Tom&quot;</span>, <span class="st">&quot;Grace&quot;</span>)</code></pre></div>
<p>Firsly, we define a function which returns all locations of same elements in a list.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">loc.names &lt;-<span class="st"> </span><span class="cf">function</span>(f){
y &lt;-<span class="st"> </span><span class="kw">unlist</span>(f)                     <span class="co"># Flatten a list x into a vector y</span>
x &lt;-<span class="st"> </span><span class="kw">list</span>()                        <span class="co"># Create an empty list</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(y)){        
  c.name &lt;-<span class="st"> </span>y[i]                   <span class="co"># Assign the ith element to c.name. </span>
  x[[c.name]] &lt;-<span class="st"> </span><span class="kw">c</span>(x[[c.name]],i)  <span class="co"># assign values to x[[c.name]]. c.name is the name of x.</span>
}
<span class="kw">return</span>(x)
}</code></pre></div>
<p>the <em>f</em> will be replaced by your own list. In this example, <em>f</em> will be replaced by the list of customer when we apply the funtion.<br />
x &lt;- list () # create an empty list.<br />
In the <em>for</em> loop, i starts from 1 to the length of y. In our example, the length of y is the length of list of customers: 10.<br />
<em>c.name &lt;- y[i]</em> # Assign the ith element in y to a new variable <em>c.name</em>. For example, if i=1, y[1] is the “Alex”, then <em>c.name = “Alex”</em>.</p>
<p><em>x[[c.name]] &lt;- c(x[[c.name]], i)</em> For i=1, we have <em>c.name &lt;- “Alex”</em>, then <em>x[[c.name]] = x[[“Alex”]] = NULL</em> since x starting from an empty list. Therefore c(x[[“Alex”]], i) = c(NULL, i) = i = 1. The value 1 will be assigned to x[[“Alex”]] by the code: <em>x[[“Alex”]] &lt;- c(x[[“Alex”]], i) = 1</em>. Now x is not an empty list, it is a list with 1 component:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">list</span>()
x[[<span class="st">&quot;Alex&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">1</span>
x</code></pre></div>
<pre><code>## $Alex
## [1] 1</code></pre>
<p>For i=2, y[2] &lt;- “Brandon”, then similar to the case of i=1, we have <em>x[[“Brandon”]] &lt;- 1</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[[<span class="st">&quot;Brandon&quot;</span>]] &lt;-<span class="st"> </span><span class="dv">1</span>
x</code></pre></div>
<pre><code>## $Alex
## [1] 1
## 
## $Brandon
## [1] 1</code></pre>
<p>For i=3, <em>y[3] &lt;- “Alex”</em>. We have met “Alex” once, which returned <em>x[[“Alex”]] &lt;- 1</em>. Now we meet “Alex” again which means we are going to update <em>x[[“Alex”]]</em> by <em>x[[“Alex”]] &lt;- c(x[[“Alex”]], i) = c(1, i) = c(1, 3)</em>. The updated x is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[[<span class="st">&quot;Alex&quot;</span>]] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)
x</code></pre></div>
<pre><code>## $Alex
## [1] 1 3
## 
## $Brandon
## [1] 1</code></pre>
<p>The process will stop till i = length (y) = 10. The <em>loc.names()</em> funciton will return all locations of all names which are already stored in x.</p>
<p>Let’s find all days of cumsters who visited to our store.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">customer &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Brandon&quot;</span>, <span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Daniel&quot;</span>, <span class="st">&quot;Grace&quot;</span>, <span class="st">&quot;Mary&quot;</span>, 
                 <span class="st">&quot;Mary&quot;</span>, <span class="st">&quot;Alex&quot;</span>, <span class="st">&quot;Tom&quot;</span>, <span class="st">&quot;Grace&quot;</span>)
v1 &lt;-<span class="st"> </span><span class="kw">loc.names</span>(customer)
v1</code></pre></div>
<pre><code>## $Alex
## [1] 1 3 8
## 
## $Brandon
## [1] 2
## 
## $Daniel
## [1] 4
## 
## $Grace
## [1]  5 10
## 
## $Mary
## [1] 6 7
## 
## $Tom
## [1] 9</code></pre>
<p>The output tells us that Alex visited our store at the first, third and eighth days, Brandon came at the second day, etc.</p>
<p>Then we use <em>sapply()</em> function to calculate the repeat times of each element.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">v2 &lt;-<span class="st"> </span><span class="kw">sapply</span>(v1,length)     <span class="co"># Calculate the length of each component in v1</span>
v2</code></pre></div>
<pre><code>##    Alex Brandon  Daniel   Grace    Mary     Tom 
##       3       1       1       2       2       1</code></pre>
<p>You can sort the v2 by the number of days that they presented by function <em>sort()</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sort</span>(v2, <span class="dt">decreasing =</span> T)</code></pre></div>
<pre><code>##    Alex   Grace    Mary Brandon  Daniel     Tom 
##       3       2       2       1       1       1</code></pre>

<div class="exercise">
<p><span id="exr:unnamed-chunk-309" class="exercise"><strong>Exercise 3.20  </strong></span>Fill blanks in the function <em>my.fun()</em> so that for a given list, the function returns all locations of each element and sort the frequency of the elements in an increasing order. Then apply <em>my.fun()</em> to a set of gender:<br />
F F M M M M I I F I F M I F M I I M I I F<br />
Where F, M and I represent Female, Male and Infant respectively.</p>
my.fun &lt;- function(f){ y &lt;- unlist(f)<br />
x &lt;- ___________<br />
for (i in 1:____){<br />
g1 &lt;- y[i]<br />
x[[______]] &lt;- c(x[[____]],i)<br />
} freq &lt;- _________(x, length)<br />
z &lt;- sort(________, decreasing = ____)<br />
lst &lt;- list(x, z)<br />
___________(lst)<br />
}<br />
gender &lt;- list( “F”, ________________________________, “F”)<br />
__________(gender) #
</div>

<p>Many R functions, such as <em>t.test()</em>, returns results as a <strong>list</strong>, which contain a series of components, such as a p value, a vector of residuals or coefficients, and even a matrix of data. A list is the natural way to represent this sort of thing as one big object that could be parsed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">r1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)  <span class="co"># Create 100 random numbers following Normal Distribution</span>
r2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)
t.result &lt;-<span class="st"> </span><span class="kw">t.test</span>(r1, r2) <span class="co"># Run the t test. Test if the mean of r1 and r2 are same.</span>
<span class="kw">is.list</span>(t.result) <span class="co"># Check if the t.result is a list</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">t.result  <span class="co"># A list holds all components of t-test</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  r1 and r2
## t = -0.18167, df = 195.8, p-value = 0.856
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2883629  0.2397186
## sample estimates:
##  mean of x  mean of y 
## -0.1473170 -0.1229948</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(t.result) <span class="co"># Returns all tags of the t test result</span></code></pre></div>
<pre><code>## [1] &quot;statistic&quot;   &quot;parameter&quot;   &quot;p.value&quot;     &quot;conf.int&quot;    &quot;estimate&quot;   
## [6] &quot;null.value&quot;  &quot;alternative&quot; &quot;method&quot;      &quot;data.name&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">t.result<span class="op">$</span>p.value  <span class="co"># Retrieves  p-value for the test</span></code></pre></div>
<pre><code>## [1] 0.8560332</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">t.result<span class="op">$</span>estimate  <span class="co"># Returns mean of r1 and r2</span></code></pre></div>
<pre><code>##  mean of x  mean of y 
## -0.1473170 -0.1229948</code></pre>
<p>The help page of t.test contains information about what types of values are returned and their names. Run the ?t.test to access the help page.</p>
<p>Let’s run a simulation using a loop. What we want to do is to generate two sets of 100 random numbers from the standard normal distribution with zero mean and unit standard deviation, and perform t-test and get the p value. By repeating this process 500 times, we want to see the distribution of p values and count how many times we get significant result with p &lt; 0.05.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pvalues &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">500</span>)  <span class="co"># define a vector containing 500 numbers, all equal to 1.</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">500</span>) {  <span class="co"># Loop: The values of i takes values from 1,2,3, …, 500</span>
     result =<span class="st"> </span><span class="kw">t.test</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>), <span class="kw">rnorm</span>(<span class="dv">100</span>))    
     pvalues[i] =<span class="st"> </span>result<span class="op">$</span>p.value  <span class="co"># p values are stored in the i-th element in the vector</span>
}  
<span class="kw">hist</span>(pvalues)  <span class="co"># Histogram of p-values</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-311-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(pvalues)   </code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## 0.003955 0.252846 0.503080 0.497877 0.740991 0.998539</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(pvalues <span class="op">&lt;</span><span class="st"> </span><span class="fl">0.05</span>)  <span class="co"># Number of p-value&#39;s which are less than 0.05. </span></code></pre></div>
<pre><code>## [1] 25</code></pre>
</div>
<div id="data-frames" class="section level3">
<h3><span class="header-section-number">3.2.4</span> Data Frames</h3>
<p>Similar to a matrix, a data frame is a two-dimensional array-like structure. But it differs from the matrix in that the mode of each column could be different. In fact, a data frame is a special case of a two-dimensional list. The data set <em>iris</em> that we analyzied before is a data frame.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(iris)</code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(iris)</code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>There are some properties of a data frame.Firstly, the mode for each column in a data frame can be of numeric, factor or character. Such as the class of Sepal.Length is numeric, and the class of Species is factor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(iris<span class="op">$</span>Sepal.Length)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(iris<span class="op">$</span>Species)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>Secondly, the column names must be non-empty. Usually, the columns represent various variables in a statistical problem. There are 5 column names or variables in the <em>iris</em> data set, they are Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, and Species respectively.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colnames</span>(iris)</code></pre></div>
<pre><code>## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot; 
## [5] &quot;Species&quot;</code></pre>
<p>Thirdly, each column should contain same number of data items. In other words, each variable contains same observations. Fourthly, the row names are unique. If they are not pre-named, the indices “1”, “2”, “3”, <span class="math inline">\(\cdots\)</span>, “n” will be assigned to each row, where “n” is the length of a row or the number of observations. For example, there are 150 observations for each variable in the <em>iris</em> data, the rows names are shown below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rownames</span>(iris)</code></pre></div>
<pre><code>##   [1] &quot;1&quot;   &quot;2&quot;   &quot;3&quot;   &quot;4&quot;   &quot;5&quot;   &quot;6&quot;   &quot;7&quot;   &quot;8&quot;   &quot;9&quot;   &quot;10&quot;  &quot;11&quot; 
##  [12] &quot;12&quot;  &quot;13&quot;  &quot;14&quot;  &quot;15&quot;  &quot;16&quot;  &quot;17&quot;  &quot;18&quot;  &quot;19&quot;  &quot;20&quot;  &quot;21&quot;  &quot;22&quot; 
##  [23] &quot;23&quot;  &quot;24&quot;  &quot;25&quot;  &quot;26&quot;  &quot;27&quot;  &quot;28&quot;  &quot;29&quot;  &quot;30&quot;  &quot;31&quot;  &quot;32&quot;  &quot;33&quot; 
##  [34] &quot;34&quot;  &quot;35&quot;  &quot;36&quot;  &quot;37&quot;  &quot;38&quot;  &quot;39&quot;  &quot;40&quot;  &quot;41&quot;  &quot;42&quot;  &quot;43&quot;  &quot;44&quot; 
##  [45] &quot;45&quot;  &quot;46&quot;  &quot;47&quot;  &quot;48&quot;  &quot;49&quot;  &quot;50&quot;  &quot;51&quot;  &quot;52&quot;  &quot;53&quot;  &quot;54&quot;  &quot;55&quot; 
##  [56] &quot;56&quot;  &quot;57&quot;  &quot;58&quot;  &quot;59&quot;  &quot;60&quot;  &quot;61&quot;  &quot;62&quot;  &quot;63&quot;  &quot;64&quot;  &quot;65&quot;  &quot;66&quot; 
##  [67] &quot;67&quot;  &quot;68&quot;  &quot;69&quot;  &quot;70&quot;  &quot;71&quot;  &quot;72&quot;  &quot;73&quot;  &quot;74&quot;  &quot;75&quot;  &quot;76&quot;  &quot;77&quot; 
##  [78] &quot;78&quot;  &quot;79&quot;  &quot;80&quot;  &quot;81&quot;  &quot;82&quot;  &quot;83&quot;  &quot;84&quot;  &quot;85&quot;  &quot;86&quot;  &quot;87&quot;  &quot;88&quot; 
##  [89] &quot;89&quot;  &quot;90&quot;  &quot;91&quot;  &quot;92&quot;  &quot;93&quot;  &quot;94&quot;  &quot;95&quot;  &quot;96&quot;  &quot;97&quot;  &quot;98&quot;  &quot;99&quot; 
## [100] &quot;100&quot; &quot;101&quot; &quot;102&quot; &quot;103&quot; &quot;104&quot; &quot;105&quot; &quot;106&quot; &quot;107&quot; &quot;108&quot; &quot;109&quot; &quot;110&quot;
## [111] &quot;111&quot; &quot;112&quot; &quot;113&quot; &quot;114&quot; &quot;115&quot; &quot;116&quot; &quot;117&quot; &quot;118&quot; &quot;119&quot; &quot;120&quot; &quot;121&quot;
## [122] &quot;122&quot; &quot;123&quot; &quot;124&quot; &quot;125&quot; &quot;126&quot; &quot;127&quot; &quot;128&quot; &quot;129&quot; &quot;130&quot; &quot;131&quot; &quot;132&quot;
## [133] &quot;133&quot; &quot;134&quot; &quot;135&quot; &quot;136&quot; &quot;137&quot; &quot;138&quot; &quot;139&quot; &quot;140&quot; &quot;141&quot; &quot;142&quot; &quot;143&quot;
## [144] &quot;144&quot; &quot;145&quot; &quot;146&quot; &quot;147&quot; &quot;148&quot; &quot;149&quot; &quot;150&quot;</code></pre>
<p>We can creat a data frame by using function <em>data.frame()</em> to combine vectors. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">41</span>, <span class="dv">32</span>, <span class="dv">13</span>, <span class="dv">89</span>)
z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;TRUE&quot;</span>, <span class="st">&quot;FALSE&quot;</span>, <span class="st">&quot;FALSE&quot;</span>, <span class="st">&quot;TRUE&quot;</span>)
df1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,y,z)
df1</code></pre></div>
<pre><code>##   x  y     z
## 1 A 41  TRUE
## 2 B 32 FALSE
## 3 C 13 FALSE
## 4 D 89  TRUE</code></pre>
<p>As you can see in the output, the <em><fctr></em> underneath the x means that the class of x has been changed from a character to a factor. So does the z. We can check the change by the <em>class()</em> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x)</code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(df1<span class="op">$</span>x)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>To keep the class of x unchanged after becoming a component of a data frame, we need an argument <em>stringsAsFactors = FALSE</em> in the <em>data.frame()</em> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(df1<span class="op">$</span>x)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,y,z,<span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
df2</code></pre></div>
<pre><code>##   x  y     z
## 1 A 41  TRUE
## 2 B 32 FALSE
## 3 C 13 FALSE
## 4 D 89  TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(df2<span class="op">$</span>x)</code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
``` 
<div class="exercise">
<p><span id="exr:unnamed-chunk-319" class="exercise"><strong>Exercise 3.21  </strong></span>What is the class of the R built-in data set <em>mtcars</em>? Show the function that you used to check the class.</p>
</div>

<p>Once data is read in as <strong>data frame</strong>, these are commands you can use to analyze it.</p>
<p>Read in data frame x:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>iris</code></pre></div>
<p>Using summary() we can get descriptive statistics of each column.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(x)</code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>head() and tail() functions show the fist and last few rows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(x)</code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(x)</code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica</code></pre>
<p>If we want to know both number of rows and number of columns of the data frame:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(x)</code></pre></div>
<pre><code>## [1] 150   5</code></pre>
<p>We can just get number of rows or number of columns separately:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nrow</span>(x)</code></pre></div>
<pre><code>## [1] 150</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ncol</span>(x)</code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>str() is a very useful function, which shows data types for all columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(x)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Like matrix, we can select one element in a data frame. Let’s select the element in the second row and third column:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">2</span>, <span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 1.4</code></pre>
<p>Also we can subtract a subset data frame from x. For example, let’s select the columns 2 to 4 and rows 1 to 10:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">4</span>]</code></pre></div>
<pre><code>##    Sepal.Width Petal.Length Petal.Width
## 1          3.5          1.4         0.2
## 2          3.0          1.4         0.2
## 3          3.2          1.3         0.2
## 4          3.1          1.5         0.2
## 5          3.6          1.4         0.2
## 6          3.9          1.7         0.4
## 7          3.4          1.4         0.3
## 8          3.4          1.5         0.2
## 9          2.9          1.4         0.2
## 10         3.1          1.5         0.1</code></pre>
<p>We can view the first column:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[, <span class="dv">1</span>]</code></pre></div>
<pre><code>##   [1] 5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4
##  [18] 5.1 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.0 5.0 5.2 5.2 4.7 4.8 5.4 5.2 5.5
##  [35] 4.9 5.0 5.5 4.9 4.4 5.1 5.0 4.5 4.4 5.0 5.1 4.8 5.1 4.6 5.3 5.0 7.0
##  [52] 6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 5.0 5.9 6.0 6.1 5.6 6.7 5.6 5.8
##  [69] 6.2 5.6 5.9 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.0 5.7 5.5 5.5 5.8 6.0 5.4
##  [86] 6.0 6.7 6.3 5.6 5.5 5.5 6.1 5.8 5.0 5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8
## [103] 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7
## [120] 6.0 6.9 5.6 7.7 6.3 6.7 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7
## [137] 6.3 6.4 6.0 6.9 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9</code></pre>
<p>Using the data frame name x followed column name has the same effect.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x<span class="op">$</span>Sepal.Length</code></pre></div>
<pre><code>##   [1] 5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4
##  [18] 5.1 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.0 5.0 5.2 5.2 4.7 4.8 5.4 5.2 5.5
##  [35] 4.9 5.0 5.5 4.9 4.4 5.1 5.0 4.5 4.4 5.0 5.1 4.8 5.1 4.6 5.3 5.0 7.0
##  [52] 6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 5.0 5.9 6.0 6.1 5.6 6.7 5.6 5.8
##  [69] 6.2 5.6 5.9 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.0 5.7 5.5 5.5 5.8 6.0 5.4
##  [86] 6.0 6.7 6.3 5.6 5.5 5.5 6.1 5.8 5.0 5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8
## [103] 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7
## [120] 6.0 6.9 5.6 7.7 6.3 6.7 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7
## [137] 6.3 6.4 6.0 6.9 6.7 6.9 5.8 6.8 6.7 6.7 6.3 6.5 6.2 5.9</code></pre>
<p>The argument <em>drop=FALSE</em> will keep a one-column vector to a data frame. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x[, <span class="dv">1</span>])</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(x[,<span class="dv">1</span>, <span class="dt">drop =</span> <span class="ot">FALSE</span>])</code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>If we need to know the average Sepal Length, we use mean() function. By the way, expressions can be nested.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(x<span class="op">$</span>Sepal.Length)</code></pre></div>
<pre><code>## [1] 5.843333</code></pre>
<p>It’s very common to select a subset of data by certain column. The “==”, “&gt;”, and “&lt;” are logical operations and the “=” is an equality sign for assigning value. Let’s select a subset which contains only the species of setosa:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">subset</span>(x, Species <span class="op">==</span><span class="st"> &quot;setosa&quot;</span>)
<span class="kw">head</span>(y)</code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Similar we can obtain a subset that the lengh of sepal are greater than 7.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">subset</span>(x, Sepal.Length <span class="op">&gt;</span><span class="st"> </span><span class="dv">7</span>)</code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 103          7.1         3.0          5.9         2.1 virginica
## 106          7.6         3.0          6.6         2.1 virginica
## 108          7.3         2.9          6.3         1.8 virginica
## 110          7.2         3.6          6.1         2.5 virginica
## 118          7.7         3.8          6.7         2.2 virginica
## 119          7.7         2.6          6.9         2.3 virginica
## 123          7.7         2.8          6.7         2.0 virginica
## 126          7.2         3.2          6.0         1.8 virginica
## 130          7.2         3.0          5.8         1.6 virginica
## 131          7.4         2.8          6.1         1.9 virginica
## 132          7.9         3.8          6.4         2.0 virginica
## 136          7.7         3.0          6.1         2.3 virginica</code></pre>
<p>If there are more than one conditions are applied to the data, we use <em>&amp;</em> to connect the conditions. For example, we want to select a subset which contains only the species of virginica, and the length of sepal is greater than 7, meanwhile remove the length of petal from the data:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x.3conds &lt;-<span class="st"> </span>x[x<span class="op">$</span>Sepal.Length<span class="op">&gt;</span><span class="dv">7</span> <span class="op">&amp;</span><span class="st"> </span>x<span class="op">$</span>Species <span class="op">==</span><span class="st"> &quot;virginica&quot;</span>, <span class="op">-</span><span class="dv">3</span>]       <span class="co"># -3 means removing the 3rd column from x.</span></code></pre></div>

<div class="exercise">
<span id="exr:unnamed-chunk-335" class="exercise"><strong>Exercise 3.22  </strong></span>Select a subset which satisfies that the <em>cyl</em> is 6 and <em>mpg</em> greater than 21.2, meanwhile the subset doesn’t include the variable <em>carb</em>.
</div>

<p>We can add new column named “id” to the data frame, which goes from 1 to 150. Function <em>head()</em> is used to view the first 6 rows of the new data set.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x.id &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="dt">id =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">150</span>), x)
<span class="kw">head</span>(x.id)</code></pre></div>
<pre><code>##   id Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1  1          5.1         3.5          1.4         0.2  setosa
## 2  2          4.9         3.0          1.4         0.2  setosa
## 3  3          4.7         3.2          1.3         0.2  setosa
## 4  4          4.6         3.1          1.5         0.2  setosa
## 5  5          5.0         3.6          1.4         0.2  setosa
## 6  6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Adding another column of random numbers y to x.id.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">150</span>)
x2 &lt;-<span class="st"> </span><span class="kw">cbind</span>(y, x.id)
<span class="kw">head</span>(x2)</code></pre></div>
<pre><code>##             y id Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1  1.41662970  1          5.1         3.5          1.4         0.2  setosa
## 2 -0.64557873  2          4.9         3.0          1.4         0.2  setosa
## 3 -1.28899366  3          4.7         3.2          1.3         0.2  setosa
## 4 -0.04950646  4          4.6         3.1          1.5         0.2  setosa
## 5 -0.68218059  5          5.0         3.6          1.4         0.2  setosa
## 6  1.62609534  6          5.4         3.9          1.7         0.4  setosa</code></pre>
<p>Similar as cbind(), rbind() is for adding another exist row or rows with same length of columns. Now we use tail() to examine the result.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">newRow &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="st">&quot;setosa&quot;</span>, <span class="dv">151</span>)
x3 &lt;-<span class="st"> </span><span class="kw">rbind</span>(x, newRow)
<span class="kw">tail</span>(x3)</code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 146          6.7           3          5.2         2.3 virginica
## 147          6.3         2.5            5         1.9 virginica
## 148          6.5           3          5.2           2 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9           3          5.1         1.8 virginica
## 151            1           1            1           1    setosa</code></pre>
<p>We can sort the data frame by certain column. For example we need to sort first column in ascending, or to sort second column in descending order.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="kw">order</span>(x[, <span class="dv">1</span>]), ]
<span class="kw">head</span>(y)</code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 14          4.3         3.0          1.1         0.1  setosa
## 9           4.4         2.9          1.4         0.2  setosa
## 39          4.4         3.0          1.3         0.2  setosa
## 43          4.4         3.2          1.3         0.2  setosa
## 42          4.5         2.3          1.3         0.3  setosa
## 4           4.6         3.1          1.5         0.2  setosa</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span>x[<span class="kw">rev</span>(<span class="kw">order</span>(x[, <span class="dv">2</span>])), ]
<span class="kw">head</span>(y)</code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 16          5.7         4.4          1.5         0.4  setosa
## 34          5.5         4.2          1.4         0.2  setosa
## 33          5.2         4.1          1.5         0.1  setosa
## 15          5.8         4.0          1.2         0.2  setosa
## 17          5.4         3.9          1.3         0.4  setosa
## 6           5.4         3.9          1.7         0.4  setosa</code></pre>
<p>We can view sepal length by species using boxplot.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(Sepal.Length <span class="op">~</span><span class="st"> </span>Species, x)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-340-1.png" width="672" /></p>
<p>We can obtain summary statistics by category. Let’s calculate the mean of the variables by species:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(. <span class="op">~</span><span class="st"> </span>Species, x, mean)</code></pre></div>
<pre><code>##      Species Sepal.Length Sepal.Width Petal.Length Petal.Width
## 1     setosa        5.006       3.428        1.462       0.246
## 2 versicolor        5.936       2.770        4.260       1.326
## 3  virginica        6.588       2.974        5.552       2.026</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-342" class="exercise"><strong>Exercise 3.23  </strong></span>Use <em>aggregate()</em> function to calculate the median of the variables: <em>mpg</em>, <em>disp</em>, <em>hp</em>, and <em>wt</em> across the number of cylinders <em>cyl</em> in the <em>mtcars</em> data set.
</div>

<p>It is easier to conduct statistical analysis after organizing data as data frame. Analysis of variance, or ANOVA tests whether sepal length has significant difference cross species in data frame iris.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw">aov</span>(Sepal.Length <span class="op">~</span><span class="st"> </span>Species, iris)
<span class="kw">summary</span>(m)</code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  63.21  31.606   119.3 &lt;2e-16 ***
## Residuals   147  38.96   0.265                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The p-value is close to 0, therefore we reject the null hypothesis and conclude that the length of sepal among three species are not same.</p>
<p>We can use the <em>sapply()</em> function to do the ANOVA test for all of the 4 numeric variables acorss the species.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">aov.fun &lt;-<span class="st"> </span><span class="cf">function</span>(temx){
  m1 &lt;-<span class="st"> </span><span class="kw">aov</span>(temx <span class="op">~</span><span class="st"> </span>iris<span class="op">$</span>Species)
  <span class="kw">summary</span>(m1)
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nvar &lt;-<span class="st"> </span>iris[<span class="op">-</span><span class="dv">5</span>]  <span class="co"># Remove the variable Species which lies at the 5th column in the data set.</span>
da &lt;-<span class="st"> </span><span class="kw">sapply</span>(nvar, aov.fun)   <span class="co"># Apply the aov.fun() function to each of the variable in the data set nvar. </span>
da</code></pre></div>
<pre><code>## $Sepal.Length
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## iris$Species   2 63.212  31.606  119.26 &lt; 2.2e-16 ***
## Residuals    147 38.956   0.265                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## $Sepal.Width
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## iris$Species   2 11.345  5.6725   49.16 &lt; 2.2e-16 ***
## Residuals    147 16.962  0.1154                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## $Petal.Length
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## iris$Species   2 437.10 218.551  1180.2 &lt; 2.2e-16 ***
## Residuals    147  27.22   0.185                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## $Petal.Width
##               Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## iris$Species   2 80.413  40.207  960.01 &lt; 2.2e-16 ***
## Residuals    147  6.157   0.042                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Regression analysis use linear model(lm) to analyze the relationship of these columns. Here we use sepal length as a function of sepal width and petal length plus error.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m &lt;-<span class="st"> </span><span class="kw">lm</span>(Sepal.Length <span class="op">~</span><span class="st"> </span>Sepal.Width <span class="op">+</span><span class="st"> </span>Petal.Length, x)
<span class="kw">summary</span>(m)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sepal.Length ~ Sepal.Width + Petal.Length, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.96159 -0.23489  0.00077  0.21453  0.78557 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.24914    0.24797    9.07 7.04e-16 ***
## Sepal.Width   0.59552    0.06933    8.59 1.16e-14 ***
## Petal.Length  0.47192    0.01712   27.57  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3333 on 147 degrees of freedom
## Multiple R-squared:  0.8402, Adjusted R-squared:  0.838 
## F-statistic: 386.4 on 2 and 147 DF,  p-value: &lt; 2.2e-16</code></pre>

<div class="exercise">
<p><span id="exr:unnamed-chunk-347" class="exercise"><strong>Exercise 3.24  </strong></span>Test if the variables <em>mpg</em>, <em>disp</em>, <em>hp</em>, <em>wt</em> and <em>qsec</em> have significant difference across the three cyl in the R build data set <em>mtcars</em>. Fill the blanks and interpret your conclusion based on the p-values.</p>
<p>aov.fun.car &lt;- function(temx){<br />
m2 &lt;- ________(________ ~ _________$______)<br />
summary(________)<br />
}</p>
<p>sub.car &lt;- mtcars[, ___________]<br />
aov.car &lt;- ___________(_________, __________)<br />
____________</p>
</div>

<p>We can merge two data frames by the function <em>merge()</em>. Here are some examples:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfmg1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">V1 =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>), <span class="dt">V2 =</span> <span class="kw">c</span>(<span class="dv">90</span>, <span class="dv">80</span>, <span class="dv">70</span>, <span class="dv">60</span>), <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
dfmg1</code></pre></div>
<pre><code>##   V1 V2
## 1  A 90
## 2  B 80
## 3  C 70
## 4  D 60</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfmg2 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">V1 =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;C&quot;</span>), <span class="dt">W2 =</span> <span class="kw">c</span>(<span class="dv">95</span>, <span class="dv">85</span>), <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
dfmg2</code></pre></div>
<pre><code>##   V1 W2
## 1  A 95
## 2  C 85</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">merge</span>(dfmg1, dfmg2)</code></pre></div>
<pre><code>##   V1 V2 W2
## 1  A 90 95
## 2  C 70 85</code></pre>
<p>Here the two data frames dfmg1 and dfmg2 have the same variable V1. After merging the two data frames, the rows with common elements “A” and “C” in both V1’s are selected. If two columns contains similar information, but they have different names in different data frames, then we can use <em>by.x</em> and <em>by.y</em> arguments to merge them. Let <em>by.x=</em> and <em>by.y=</em> specify the variable names in the first and second data frame respectively. See the example below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfmg3 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">W1 =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;F&quot;</span>, <span class="st">&quot;C&quot;</span>), <span class="dt">W2 =</span> <span class="kw">c</span>(<span class="dv">95</span>, <span class="dv">85</span>, <span class="dv">65</span>), <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>)
dfmg3</code></pre></div>
<pre><code>##   W1 W2
## 1  A 95
## 2  F 85
## 3  C 65</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">merge</span>(dfmg1, dfmg3, <span class="dt">by.x=</span><span class="st">&quot;V1&quot;</span>, <span class="dt">by.y=</span><span class="st">&quot;W1&quot;</span>)</code></pre></div>
<pre><code>##   V1 V2 W2
## 1  A 90 95
## 2  C 70 65</code></pre>
<p>We use data.frame() function to define a new data frame with 100 rows and two columns, <em>ids</em> and <em>rand</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">100</span>, <span class="dt">rand =</span> <span class="kw">rnorm</span>(<span class="dv">100</span>))
<span class="kw">head</span>(y)</code></pre></div>
<pre><code>##   id         rand
## 1  1  0.571273477
## 2  2  0.008071262
## 3  3 -1.097127387
## 4  4 -0.006290796
## 5  5  1.757672470
## 6  6  1.368428462</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(y)</code></pre></div>
<pre><code>##      id       rand
## 95   95  0.2653948
## 96   96 -0.8319552
## 97   97 -1.0563742
## 98   98  1.8917802
## 99   99 -0.7772326
## 100 100 -0.4279420</code></pre>
<p>Now we merge two data frames x and y by a common column named <strong>id</strong>. Note the new data frame z has only 100 rows. We can also merge data frame by row names too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>iris
x<span class="op">$</span>id =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">150</span>)
z &lt;-<span class="st"> </span><span class="kw">merge</span>(x, y, <span class="dt">by =</span> <span class="st">&quot;id&quot;</span>)
<span class="kw">head</span>(z)</code></pre></div>
<pre><code>##   id Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1  1          5.1         3.5          1.4         0.2  setosa
## 2  2          4.9         3.0          1.4         0.2  setosa
## 3  3          4.7         3.2          1.3         0.2  setosa
## 4  4          4.6         3.1          1.5         0.2  setosa
## 5  5          5.0         3.6          1.4         0.2  setosa
## 6  6          5.4         3.9          1.7         0.4  setosa
##           rand
## 1  0.571273477
## 2  0.008071262
## 3 -1.097127387
## 4 -0.006290796
## 5  1.757672470
## 6  1.368428462</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(z)</code></pre></div>
<pre><code>##      id Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
## 95   95          5.6         2.7          4.2         1.3 versicolor
## 96   96          5.7         3.0          4.2         1.2 versicolor
## 97   97          5.7         2.9          4.2         1.3 versicolor
## 98   98          6.2         2.9          4.3         1.3 versicolor
## 99   99          5.1         2.5          3.0         1.1 versicolor
## 100 100          5.7         2.8          4.1         1.3 versicolor
##           rand
## 95   0.2653948
## 96  -0.8319552
## 97  -1.0563742
## 98   1.8917802
## 99  -0.7772326
## 100 -0.4279420</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(z)</code></pre></div>
<pre><code>##        id          Sepal.Length    Sepal.Width     Petal.Length  
##  Min.   :  1.00   Min.   :4.300   Min.   :2.000   Min.   :1.000  
##  1st Qu.: 25.75   1st Qu.:5.000   1st Qu.:2.800   1st Qu.:1.500  
##  Median : 50.50   Median :5.400   Median :3.050   Median :2.450  
##  Mean   : 50.50   Mean   :5.471   Mean   :3.099   Mean   :2.861  
##  3rd Qu.: 75.25   3rd Qu.:5.900   3rd Qu.:3.400   3rd Qu.:4.325  
##  Max.   :100.00   Max.   :7.000   Max.   :4.400   Max.   :5.100  
##   Petal.Width          Species        rand        
##  Min.   :0.100   setosa    :50   Min.   :-2.1448  
##  1st Qu.:0.200   versicolor:50   1st Qu.:-0.7697  
##  Median :0.800   virginica : 0   Median :-0.2380  
##  Mean   :0.786                   Mean   :-0.1446  
##  3rd Qu.:1.300                   3rd Qu.: 0.3518  
##  Max.   :1.800                   Max.   : 2.0108</code></pre>
</div>
<div id="strings-and-string-vectors" class="section level3">
<h3><span class="header-section-number">3.2.5</span> Strings and string vectors</h3>
<p>We encounter text data sometimes. Plus, we also have row and column names. We can easily manipulate these string objects.</p>
<p>Define a <strong>string</strong> x: “R is cool”</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> &quot;R is cool&quot;</span></code></pre></div>
<p>If we want to know the number of character of the string:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nchar</span>(x)</code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>We can concatenate strings. By default a space is added.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(x, <span class="st">&quot;!!&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;R is cool !!&quot;</code></pre>
<p>If we want to extract sub-string from position of 6 and 9:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">substr</span>(x, <span class="dv">6</span>, <span class="dv">9</span>)</code></pre></div>
<pre><code>## [1] &quot;cool&quot;</code></pre>
<p>Split string into a list which is separated by space:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">strsplit</span>(x, <span class="st">&quot; &quot;</span>)</code></pre></div>
<pre><code>## [[1]]
## [1] &quot;R&quot;    &quot;is&quot;   &quot;cool&quot;</code></pre>
<p>Find pattern “R” and replace with “Tim”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gsub</span>(<span class="st">&quot;R&quot;</span>, <span class="st">&quot;Tim&quot;</span>, x)</code></pre></div>
<pre><code>## [1] &quot;Tim is cool&quot;</code></pre>
<p>Or remove space followed by anything:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">gsub</span>(<span class="st">&quot; .*&quot;</span>, <span class="st">&quot;&quot;</span>, x)</code></pre></div>
<pre><code>## [1] &quot;R&quot;</code></pre>
<p>We can search for pattern like “is” in the string.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">grepl</span>(<span class="st">&quot;is&quot;</span>, x)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>We can also convert the whole string into low case or upper case by “tolower” or “toupper” function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tolower</span>(x)</code></pre></div>
<pre><code>## [1] &quot;r is cool&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">toupper</span>(x)</code></pre></div>
<pre><code>## [1] &quot;R IS COOL&quot;</code></pre>
<p>A <strong>string vector</strong> can hold many strings. This can be a column of names or IDs in a table. First let’s define a character vector <strong>x &lt;- c(“ab”, “cde”, “d”, “ab”)</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;ab&quot;</span>, <span class="st">&quot;cde&quot;</span>, <span class="st">&quot;d&quot;</span>, <span class="st">&quot;ab&quot;</span>) </code></pre></div>
<p>We can use all commands about vector for our string vector, such as 2nd element in vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] &quot;cde&quot;</code></pre>
<p>Number of strings in the vector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(x)</code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>Unique elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unique</span>(x)</code></pre></div>
<pre><code>## [1] &quot;ab&quot;  &quot;cde&quot; &quot;d&quot;</code></pre>
<p>Now we are interested in the duplicated element in the string vector. Is there any duplicated element in the vector?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">duplicated</span>(x)</code></pre></div>
<pre><code>## [1] FALSE FALSE FALSE  TRUE</code></pre>
<p>The last element is duplicated. F denotes FALSE, and T for TRUE. If we want to know the number of characters in each of the element:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nchar</span>(x)</code></pre></div>
<pre><code>## [1] 2 3 1 2</code></pre>
<p>We can also unite two vectors x and y if we define another vector y first:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;ab&quot;</span>, <span class="st">&quot;e&quot;</span>)
<span class="kw">union</span>(x, y)</code></pre></div>
<pre><code>## [1] &quot;ab&quot;  &quot;cde&quot; &quot;d&quot;   &quot;e&quot;</code></pre>
<p>Is there intercept among these two sets of strings?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">intersect</span>(x, y)</code></pre></div>
<pre><code>## [1] &quot;ab&quot;</code></pre>
<p>We can add something like “Q” to each element:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(x, <span class="st">&quot;Q&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;ab Q&quot;  &quot;cde Q&quot; &quot;d Q&quot;   &quot;ab Q&quot;</code></pre>
<p>To get rid of the space between these element and “Q”, try paste0:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste0</span>(x, <span class="st">&quot;Q&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;abQ&quot;  &quot;cdeQ&quot; &quot;dQ&quot;   &quot;abQ&quot;</code></pre>
<p>If we want to collapse multiple strings into one, which is joined by space:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(x, <span class="dt">collapse =</span> <span class="st">&quot; &quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;ab cde d ab&quot;</code></pre>
<p>Using these functions, we can achieve many things. For example if we have a piece of DNA sequence:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DNA &lt;-<span class="st"> &quot;taaCCATTGtaaGAACATGGTTGTCcaaaCAAGATGCTAGT&quot;</span></code></pre></div>
<p>Note that I am using the assignment operator “&lt;-”, instead of “=”, which also works most of the times but it could be ambiguous. First we need to convert everything to upper case.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DNA &lt;-<span class="st"> </span><span class="kw">toupper</span>(DNA)</code></pre></div>
<p>Next, we want to cut this DNA into smaller pieces by looking for a certain pattern “ATG”. This type of thing happens in nature, as some enzymes cut DNA according to certain pattern.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">segs &lt;-<span class="st"> </span><span class="kw">strsplit</span>(DNA, <span class="st">&quot;ATG&quot;</span>)</code></pre></div>
<p>The result is contained in an object segs, which is a list. We needed the unlist( ) function to convert list to a string vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">segs &lt;-<span class="st"> </span><span class="kw">unlist</span>(segs)   
segs  <span class="co"># a vector of strings</span></code></pre></div>
<pre><code>## [1] &quot;TAACCATTGTAAGAAC&quot; &quot;GTTGTCCAAACAAG&quot;   &quot;CTAGT&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">segs[<span class="dv">1</span>]  <span class="co"># first segment</span></code></pre></div>
<pre><code>## [1] &quot;TAACCATTGTAAGAAC&quot;</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-376" class="exercise"><strong>Exercise 3.25  </strong></span>In the iris flower dataset iris, define a new column called FullName which contains the full species name by adding “Iris“ in front of species name. In other words, “setosa” should become “Iris setosa”, “virginica” would be “Iris virginica”, and “versicolor” needs to be “Iris versicolor”.
</div>

</div>
</div>
<div id="for-more-in-depth-exercises" class="section level2">
<h2><span class="header-section-number">3.3</span> For more in-depth exercises</h2>
<p>Go to: <a href="http://tryr.codeschool.com/" class="uri">http://tryr.codeschool.com/</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-importing.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
