<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Learning R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Learning R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learning R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  

<meta name="author" content="Xijin Ge">


<meta name="date" content="2019-02-07">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="exploring-of-state-data-set.html">
<link rel="next" href="exploring-of-employee-salary-data-set.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.39.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Index</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R program-Analyzing iris flower dataset</a><ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#data-frames-have-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.1</b> Data frames have rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.2</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#students-t-test"><i class="fa fa-check"></i><b>1.3</b> Student’s t-test</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#test-for-normal-distribution"><i class="fa fa-check"></i><b>1.4</b> Test for normal distribution</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-a-column-of-categorical-values"><i class="fa fa-check"></i><b>1.5</b> Analyzing a column of categorical values</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-the-relationship-between-two-columns-of-numbers"><i class="fa fa-check"></i><b>1.6</b> Analyzing the relationship between two columns of numbers</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#visualizing-and-testing-the-differences-in-groups"><i class="fa fa-check"></i><b>1.7</b> Visualizing and testing the differences in groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#testing-the-difference-among-multiple-groups-analysis-of-variance-anova"><i class="fa fa-check"></i><b>1.8</b> Testing the difference among multiple groups (Analysis of Variance: ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><i class="fa fa-check"></i><b>2</b> Visualizing data set-Analyzing cars and iris flower data sets</a><ul>
<li class="chapter" data-level="2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-mtcars-dataset"><i class="fa fa-check"></i><b>2.2</b> Visualizing mtcars dataset</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot"><i class="fa fa-check"></i><b>2.2.1</b> scatter plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#barplot-with-error-bars"><i class="fa fa-check"></i><b>2.2.2</b> Barplot with error bars</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-correlation-between-categorical-variables"><i class="fa fa-check"></i><b>2.2.3</b> Visualizing correlation between categorical variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#detecting-correlations-among-variables"><i class="fa fa-check"></i><b>2.2.4</b> Detecting correlations among variables</a></li>
<li class="chapter" data-level="2.2.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#hierarchical-clustering"><i class="fa fa-check"></i><b>2.2.5</b> Hierarchical clustering</a></li>
<li class="chapter" data-level="2.2.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#representing-data-using-faces.-serious-scientific-research-only"><i class="fa fa-check"></i><b>2.2.6</b> Representing data using faces. Serious scientific research only!</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-iris-data-set"><i class="fa fa-check"></i><b>2.3</b> Visualizing iris data set</a><ul>
<li class="chapter" data-level="2.3.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#a-matrix-only-contains-numbers"><i class="fa fa-check"></i><b>2.3.1</b> A Matrix only contains numbers</a></li>
<li class="chapter" data-level="2.3.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.3.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#heatmap"><i class="fa fa-check"></i><b>2.3.3</b> Heatmap</a></li>
<li class="chapter" data-level="2.3.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#star-plot"><i class="fa fa-check"></i><b>2.3.4</b> Star plot</a></li>
<li class="chapter" data-level="2.3.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#segment-diagrams"><i class="fa fa-check"></i><b>2.3.5</b> Segment diagrams</a></li>
<li class="chapter" data-level="2.3.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#parallel-coordinate-plot"><i class="fa fa-check"></i><b>2.3.6</b> Parallel coordinate plot</a></li>
<li class="chapter" data-level="2.3.7" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#box-plot"><i class="fa fa-check"></i><b>2.3.7</b> Box plot</a></li>
<li class="chapter" data-level="2.3.8" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#bar-plot-with-error-bar"><i class="fa fa-check"></i><b>2.3.8</b> Bar plot with error bar</a></li>
<li class="chapter" data-level="2.3.9" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#combining-plots"><i class="fa fa-check"></i><b>2.3.9</b> Combining plots</a></li>
<li class="chapter" data-level="2.3.10" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#plot-using-principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.3.10</b> Plot using principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.3.11" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#attempt-at-ggplot2"><i class="fa fa-check"></i><b>2.3.11</b> Attempt at ggplot2</a></li>
<li class="chapter" data-level="2.3.12" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#classification-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.3.12</b> Classification: Predicting the odds of binary outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a><ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Looking for Help and Example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrix-operations"><i class="fa fa-check"></i><b>3.2.2</b> Matrix operations</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.3</b> Lists</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#operations-on-data-frames"><i class="fa fa-check"></i><b>3.2.5</b> Operations on data frames</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#for-more-in-depth-exercises"><i class="fa fa-check"></i><b>3.3</b> For more in-depth exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-importing.html"><a href="data-importing.html"><i class="fa fa-check"></i><b>4</b> Data importing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-importing.html"><a href="data-importing.html#enter-data-manually"><i class="fa fa-check"></i><b>4.1</b> Enter data manually</a></li>
<li class="chapter" data-level="4.2" data-path="data-importing.html"><a href="data-importing.html#reading-data-from-file-using-import-dataset-in-rstudio"><i class="fa fa-check"></i><b>4.2</b> Reading data from file using Import dataset in Rstudio</a></li>
<li class="chapter" data-level="4.3" data-path="data-importing.html"><a href="data-importing.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.3</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.4" data-path="data-importing.html"><a href="data-importing.html#reading-file-using-read.table-read.csv-etc."><i class="fa fa-check"></i><b>4.4</b> Reading file using read.table, read.csv, etc.</a></li>
<li class="chapter" data-level="4.5" data-path="data-importing.html"><a href="data-importing.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.5</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.6" data-path="data-importing.html"><a href="data-importing.html#recommended-workflow-for-every-project"><i class="fa fa-check"></i><b>4.6</b> Recommended workflow for EVERY project</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> Analyzing heart attack data set I</a><ul>
<li class="chapter" data-level="5.1" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="5.2" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="5.3" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="5.4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="5.5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html"><i class="fa fa-check"></i><b>6</b> Analyzing heart attack data set II</a><ul>
<li class="chapter" data-level="6.1" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>6.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="vectors-1.html"><a href="vectors-1.html"><i class="fa fa-check"></i><b>7</b> Vectors</a></li>
<li class="chapter" data-level="8" data-path="matrics-and-arrays.html"><a href="matrics-and-arrays.html"><i class="fa fa-check"></i><b>8</b> Matrics and arrays</a></li>
<li class="chapter" data-level="9" data-path="lists-1.html"><a href="lists-1.html"><i class="fa fa-check"></i><b>9</b> Lists</a></li>
<li class="chapter" data-level="10" data-path="data-frames.html"><a href="data-frames.html"><i class="fa fa-check"></i><b>10</b> Data frames</a></li>
<li class="chapter" data-level="11" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>11</b> Strings</a></li>
<li class="chapter" data-level="12" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>12</b> Advanced topics</a><ul>
<li class="chapter" data-level="12.1" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>12.1</b> Tidyverse</a></li>
<li class="chapter" data-level="12.2" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps-and-interactive-plots"><i class="fa fa-check"></i><b>12.2</b> Shiny Apps and interactive plots</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html"><i class="fa fa-check"></i><b>13</b> Exploring of state data set</a><ul>
<li class="chapter" data-level="13.1" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#reading-in-and-manipulating-data"><i class="fa fa-check"></i><b>13.1</b> Reading in and manipulating data</a></li>
<li class="chapter" data-level="13.2" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#basic-information-about-data"><i class="fa fa-check"></i><b>13.2</b> Basic information about data</a></li>
<li class="chapter" data-level="13.3" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>13.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="13.4" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#peeking-the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>13.4</b> Peeking the whole picture of the data set</a></li>
<li class="chapter" data-level="13.5" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#linear-model-anylysis"><i class="fa fa-check"></i><b>13.5</b> Linear Model Anylysis</a></li>
<li class="chapter" data-level="13.6" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#conclusion"><i class="fa fa-check"></i><b>13.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html"><i class="fa fa-check"></i><b>14</b> Exploring of game sale dataset</a><ul>
<li class="chapter" data-level="14.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#reading-in-data-and-manage-data"><i class="fa fa-check"></i><b>14.1</b> Reading in data and manage data</a></li>
<li class="chapter" data-level="14.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#visualizing-of-categorical-variables"><i class="fa fa-check"></i><b>14.2</b> Visualizing of categorical variables</a></li>
<li class="chapter" data-level="14.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>14.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="14.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>14.4</b> Analysis of Score and Count</a><ul>
<li class="chapter" data-level="14.4.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#distribution-of-two-scores"><i class="fa fa-check"></i><b>14.4.1</b> Distribution of two scores</a></li>
<li class="chapter" data-level="14.4.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-top-sale-game"><i class="fa fa-check"></i><b>14.4.2</b> Score &amp; Top sale game</a></li>
<li class="chapter" data-level="14.4.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-rating"><i class="fa fa-check"></i><b>14.4.3</b> Score &amp; Rating</a></li>
<li class="chapter" data-level="14.4.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-genre"><i class="fa fa-check"></i><b>14.4.4</b> 7) Score &amp; Genre</a></li>
<li class="chapter" data-level="14.4.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-global-sales"><i class="fa fa-check"></i><b>14.4.5</b> 8) Score &amp; Global sales</a></li>
<li class="chapter" data-level="14.4.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-top-sale-developer"><i class="fa fa-check"></i><b>14.4.6</b> 9) Score &amp; Top Sale Developer</a></li>
<li class="chapter" data-level="14.4.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#score-publisher"><i class="fa fa-check"></i><b>14.4.7</b> 10) Score &amp; Publisher</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>14.5</b> Analysis of Sales</a><ul>
<li class="chapter" data-level="14.5.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-year.release"><i class="fa fa-check"></i><b>14.5.1</b> 1) By Year.Release</a></li>
<li class="chapter" data-level="14.5.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-region"><i class="fa fa-check"></i><b>14.5.2</b> 2) By Region</a></li>
<li class="chapter" data-level="14.5.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-genre"><i class="fa fa-check"></i><b>14.5.3</b> 3) By Genre</a></li>
<li class="chapter" data-level="14.5.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating"><i class="fa fa-check"></i><b>14.5.4</b> 4) By Rating</a></li>
<li class="chapter" data-level="14.5.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating-genre"><i class="fa fa-check"></i><b>14.5.5</b> 5) By Rating &amp; Genre</a></li>
<li class="chapter" data-level="14.5.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-platform"><i class="fa fa-check"></i><b>14.5.6</b> 6) By Platform</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-for-numeric-matrix-heatmap-and-pca"><i class="fa fa-check"></i><b>14.6</b> Analysis for numeric matrix: Heatmap and PCA</a></li>
<li class="chapter" data-level="14.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>14.7</b> Models for Global Sales</a></li>
<li class="chapter" data-level="14.8" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>14.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html"><i class="fa fa-check"></i><b>15</b> Exploring of employee salary data set</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learning R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exploring-of-game-sale-dataset" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> Exploring of game sale dataset</h1>
<p>This is a video game sales data including game sales of North America, Euroupean, Japan and other area, together they make the global sale. The data also give the information about the critic score, user score and the number of critics or users who gave these two scores. This data is downloaded from <a href="https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings#Video_Games_Sales_as_at_22_Dec_2016.csv" class="uri">https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings#Video_Games_Sales_as_at_22_Dec_2016.csv</a>.</p>
<p>The detail about the data is listed as follow:</p>
<p>Name: Name of the game</p>
<p>Platform: Console on which the game is running</p>
<p>Year_of_Release: Year of the game released</p>
<p>Genre: Game’s category</p>
<p>Publisher: Publisher</p>
<p>NA_Sales: Game sales in North America (in millions of units)</p>
<p>EU_Sales: Game sales in the European Union (in millions of units)</p>
<p>JP_Sales: Game sales in Japan (in millions of units)</p>
<p>Other_Sales: Game sales in the rest of the world, i.e. Africa, Asia excluding Japan, Australia, Europe excluding the E.U. and South America (in millions of units)</p>
<p>Global_Sales: Total sales in the world (in millions of units)</p>
<p>Critic_Score: Aggregate score compiled by Meta critic staff</p>
<p>Critic_Count: The number of critics used in coming up with the Critic_score</p>
<p>User_Score: Score by Metacritic’s subscribers</p>
<p>User_Count: Number of users who gave the user_score</p>
<p>Developer: Party responsible for creating the game</p>
<p>Rating: The ESRB ratings: E for “Everyone”; E10+ for “Everyone 10+”; T for “Teen”; M for “Mature”; AO for “Adults Only”; RP for “Rating Pending”.</p>
<p>After downloading the data, We replace N/A with NA first in excel and save it as csv file and read in. We remove these observations with empty string of Rating and 6825 observations was left in our data.</p>
<div id="reading-in-data-and-manage-data" class="section level2">
<h2><span class="header-section-number">14.1</span> Reading in data and manage data</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tem &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;datasets/video-game-sales-at-22-Dec-2016.csv&quot;</span>)
<span class="co">#tem &lt;- read.csv(&quot;datasets/video-game-sales.csv&quot;)</span>
game &lt;-<span class="st"> </span><span class="kw">na.omit</span>(tem)  <span class="co">#remove NA</span>

<span class="kw">library</span>(dplyr)
game &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Rating <span class="op">!=</span><span class="st"> &quot;&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">droplevels</span>()  <span class="co">#remove empty rating observations</span>

<span class="co">#by multiplying 1000000 we get the actual sale, </span>
<span class="co">#adding 1 makes all sales positive which make log possible for all sales later</span>
game<span class="op">$</span>Year_of_Release &lt;-<span class="st"> </span><span class="kw">as.factor</span>(<span class="kw">as.character</span>(game<span class="op">$</span>Year_of_Release))
game<span class="op">$</span>NA_Sales &lt;-<span class="st"> </span>game<span class="op">$</span>NA_Sales <span class="op">*</span><span class="st"> </span><span class="dv">1000000</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
game<span class="op">$</span>EU_Sales &lt;-<span class="st"> </span>game<span class="op">$</span>EU_Sales <span class="op">*</span><span class="st"> </span><span class="dv">1000000</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
game<span class="op">$</span>JP_Sales &lt;-<span class="st"> </span>game<span class="op">$</span>JP_Sales <span class="op">*</span><span class="st"> </span><span class="dv">1000000</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
game<span class="op">$</span>Other_Sales &lt;-<span class="st"> </span>game<span class="op">$</span>Other_Sales <span class="op">*</span><span class="st"> </span><span class="dv">1000000</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
game<span class="op">$</span>Global_Sales &lt;-<span class="st"> </span>game<span class="op">$</span>Global_Sales <span class="op">*</span><span class="st"> </span><span class="dv">1000000</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>

<span class="co"># By divide by 10 to make Critic Score the same decimal as User Score</span>
game<span class="op">$</span>Critic_Score &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.character</span>(game<span class="op">$</span>Critic_Score)) <span class="op">/</span><span class="st"> </span><span class="dv">10</span>  
game<span class="op">$</span>User_Score &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.character</span>(game<span class="op">$</span>User_Score))
game<span class="op">$</span>Critic_Count &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(game<span class="op">$</span>Critic_Count)
game<span class="op">$</span>User_Count &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(game<span class="op">$</span>User_Count)
<span class="kw">colnames</span>(game) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Platform&quot;</span>, <span class="st">&quot;Year.Release&quot;</span>, <span class="st">&quot;Genre&quot;</span>, <span class="st">&quot;Publisher&quot;</span>, <span class="st">&quot;NA.Sales&quot;</span>, <span class="st">&quot;EU.Sales&quot;</span>, <span class="st">&quot;JP.Sales&quot;</span>, <span class="st">&quot;Other.Sales&quot;</span>, <span class="st">&quot;Global.Sales&quot;</span>, <span class="st">&quot;Critic.Score&quot;</span>, <span class="st">&quot;Critic.Count&quot;</span>, <span class="st">&quot;User.Score&quot;</span>, <span class="st">&quot;User.Count&quot;</span>, <span class="st">&quot;Developer&quot;</span>, <span class="st">&quot;Rating&quot;</span>)
<span class="kw">head</span>(game)</code></pre></div>
<pre><code>##                        Name Platform Year.Release    Genre Publisher
## 1                Wii Sports      Wii         2006   Sports  Nintendo
## 2            Mario Kart Wii      Wii         2008   Racing  Nintendo
## 3         Wii Sports Resort      Wii         2009   Sports  Nintendo
## 4     New Super Mario Bros.       DS         2006 Platform  Nintendo
## 5                  Wii Play      Wii         2006     Misc  Nintendo
## 6 New Super Mario Bros. Wii      Wii         2009 Platform  Nintendo
##   NA.Sales EU.Sales JP.Sales Other.Sales Global.Sales Critic.Score
## 1 41360001 28960001  3770001     8450001     82530001          7.6
## 2 15680001 12760001  3790001     3290001     35520001          8.2
## 3 15610001 10930001  3280001     2950001     32770001          8.0
## 4 11280001  9140001  6500001     2880001     29800001          8.9
## 5 13960001  9180001  2930001     2840001     28920001          5.8
## 6 14440001  6940001  4700001     2240001     28320001          8.7
##   Critic.Count User.Score User.Count Developer Rating
## 1           51        8.0        322  Nintendo      E
## 2           73        8.3        709  Nintendo      E
## 3           73        8.0        192  Nintendo      E
## 4           65        8.5        431  Nintendo      E
## 5           41        6.6        129  Nintendo      E
## 6           80        8.4        594  Nintendo      E</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(game)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    6825 obs. of  16 variables:
##  $ Name        : Factor w/ 4377 levels &quot; Tales of Xillia 2&quot;,..: 4203 2055 4205 2530 4201 2533 2054 4195 1820 4196 ...
##  $ Platform    : Factor w/ 17 levels &quot;3DS&quot;,&quot;DC&quot;,&quot;DS&quot;,..: 13 13 13 3 13 13 3 13 15 13 ...
##  $ Year.Release: Factor w/ 25 levels &quot;1985&quot;,&quot;1988&quot;,..: 15 17 18 15 15 18 14 16 19 18 ...
##  $ Genre       : Factor w/ 12 levels &quot;Action&quot;,&quot;Adventure&quot;,..: 11 7 11 5 4 5 7 11 4 11 ...
##  $ Publisher   : Factor w/ 262 levels &quot;10TACLE Studios&quot;,..: 164 164 164 164 164 164 164 164 147 164 ...
##  $ NA.Sales    : num  41360001 15680001 15610001 11280001 13960001 ...
##  $ EU.Sales    : num  28960001 12760001 10930001 9140001 9180001 ...
##  $ JP.Sales    : num  3770001 3790001 3280001 6500001 2930001 ...
##  $ Other.Sales : num  8450001 3290001 2950001 2880001 2840001 ...
##  $ Global.Sales: num  82530001 35520001 32770001 29800001 28920001 ...
##  $ Critic.Score: num  7.6 8.2 8 8.9 5.8 8.7 9.1 8 6.1 8 ...
##  $ Critic.Count: num  51 73 73 65 41 80 64 63 45 33 ...
##  $ User.Score  : num  8 8.3 8 8.5 6.6 8.4 8.6 7.7 6.3 7.4 ...
##  $ User.Count  : num  322 709 192 431 129 594 464 146 106 52 ...
##  $ Developer   : Factor w/ 1289 levels &quot;10tacle Studios, Fusionsphere Systems&quot;,..: 779 779 779 779 779 779 779 779 468 779 ...
##  $ Rating      : Factor w/ 7 levels &quot;AO&quot;,&quot;E&quot;,&quot;E10+&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int  2 5 6 10 11 13 19 21 22 23 ...
##   ..- attr(*, &quot;names&quot;)= chr  &quot;2&quot; &quot;5&quot; &quot;6&quot; &quot;10&quot; ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(game)</code></pre></div>
<pre><code>##                                         Name         Platform   
##  LEGO Star Wars II: The Original Trilogy  :   8   PS2    :1140  
##  Madden NFL 07                            :   8   X360   : 858  
##  Need for Speed: Most Wanted              :   8   PS3    : 769  
##  Harry Potter and the Order of the Phoenix:   7   PC     : 651  
##  Madden NFL 08                            :   7   XB     : 565  
##  Need for Speed Carbon                    :   7   Wii    : 479  
##  (Other)                                  :6780   (Other):2363  
##   Year.Release           Genre                            Publisher   
##  2008   : 592   Action      :1630   Electronic Arts            : 944  
##  2007   : 590   Sports      : 943   Ubisoft                    : 496  
##  2005   : 562   Shooter     : 864   Activision                 : 492  
##  2009   : 550   Role-Playing: 712   Sony Computer Entertainment: 316  
##  2006   : 528   Racing      : 581   THQ                        : 307  
##  2003   : 498   Platform    : 403   Nintendo                   : 291  
##  (Other):3505   (Other)     :1692   (Other)                    :3979  
##     NA.Sales           EU.Sales           JP.Sales      
##  Min.   :       1   Min.   :       1   Min.   :      1  
##  1st Qu.:   60001   1st Qu.:   20001   1st Qu.:      1  
##  Median :  150001   Median :   60001   Median :      1  
##  Mean   :  394485   Mean   :  236090   Mean   :  64159  
##  3rd Qu.:  390001   3rd Qu.:  210001   3rd Qu.:  10001  
##  Max.   :41360001   Max.   :28960001   Max.   :6500001  
##                                                         
##   Other.Sales        Global.Sales       Critic.Score    Critic.Count   
##  Min.   :       1   Min.   :   10001   Min.   :1.300   Min.   :  3.00  
##  1st Qu.:   10001   1st Qu.:  110001   1st Qu.:6.200   1st Qu.: 14.00  
##  Median :   20001   Median :  290001   Median :7.200   Median : 25.00  
##  Mean   :   82678   Mean   :  777591   Mean   :7.027   Mean   : 28.93  
##  3rd Qu.:   70001   3rd Qu.:  750001   3rd Qu.:8.000   3rd Qu.: 39.00  
##  Max.   :10570001   Max.   :82530001   Max.   :9.800   Max.   :113.00  
##                                                                        
##    User.Score      User.Count                 Developer     Rating    
##  Min.   :0.500   Min.   :    4.0   EA Canada       : 149   AO  :   1  
##  1st Qu.:6.500   1st Qu.:   11.0   EA Sports       : 142   E   :2082  
##  Median :7.500   Median :   27.0   Capcom          : 126   E10+: 930  
##  Mean   :7.186   Mean   :  174.7   Ubisoft         : 103   K-A :   1  
##  3rd Qu.:8.200   3rd Qu.:   89.0   Konami          :  95   M   :1433  
##  Max.   :9.600   Max.   :10665.0   Ubisoft Montreal:  87   RP  :   1  
##                                    (Other)         :6123   T   :2377</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Name &lt;- game$Name </span>
<span class="co">#Platform &lt;- game$Platform </span>
Year.Release &lt;-<span class="st"> </span>game<span class="op">$</span>Year.Release 
<span class="co">#Genre &lt;- game$Genre       </span>
<span class="co">#Publisher &lt;- game$Publisher  </span>
<span class="co">#NA.Sales &lt;- game$NA.Sales   </span>
<span class="co">#EU.Sales &lt;- game$EU.Sales  </span>
<span class="co">#JP.Sales &lt;- game$JP.Sales   </span>
<span class="co">#Other.Sales &lt;- game$Other.Sales  </span>
<span class="co">#Global.Sales &lt;- game$Global.Sales </span>
Critic.Score &lt;-<span class="st"> </span>game<span class="op">$</span>Critic.Score 
Critic.Count &lt;-<span class="st"> </span>game<span class="op">$</span>Critic.Count 
User.Score &lt;-<span class="st"> </span>game<span class="op">$</span>User.Score   
User.Count &lt;-<span class="st"> </span>game<span class="op">$</span>User.Count  
<span class="co">#Developer &lt;- game$Developer  </span>
<span class="co">#Rating &lt;- game$Rating </span></code></pre></div>
<p>Summary of these variables tell us that some of the games was published several times in the same name; PS2 is the most popular platform; Action is the most popular Genre; Electronic Arts has the most high frequency among the publishers; Rating T and E are the two most released ratings; For these sales, though the minimums, several quantiles and medians are small, but the maximums are high, which means there are special cases in sales; Maximum User count is extreme big.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="kw">colnames</span>(game)[<span class="kw">c</span>(<span class="dv">6</span><span class="op">:</span><span class="dv">14</span>)]  <span class="co"># pick up the numeric columns according to the names </span>
<span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">3</span>))  <span class="co"># layout in 3 rows and 3 columns</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(a)){
  sub &lt;-<span class="st"> </span><span class="kw">sample</span>(game[a[i]][, <span class="dv">1</span>], <span class="dv">5000</span>)
  <span class="kw">hist</span>(sub, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Hist. of&quot;</span>, a[i], <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>), <span class="dt">xlab =</span> a[i])
 }</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-438-1.png" width="768" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">NA.Sales.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>NA.Sales)   
EU.Sales.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>EU.Sales)  
JP.Sales.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>JP.Sales)   
Other.Sales.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>Other.Sales)  
Global.Sales.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>Global.Sales) 
Critic.Count.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>Critic.Count)
User.Count.Log &lt;-<span class="st"> </span><span class="kw">log</span>(game<span class="op">$</span>User.Count)</code></pre></div>
<p>We combine the log variables with the original variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game.log &lt;-<span class="st"> </span><span class="kw">cbind.data.frame</span>(NA.Sales.Log, EU.Sales.Log, JP.Sales.Log, Other.Sales.Log,
Global.Sales.Log, Critic.Count.Log, User.Count.Log)
game &lt;-<span class="st"> </span><span class="kw">cbind.data.frame</span>(game, game.log)  <span class="co"># the data we use for analysis</span>
<span class="kw">head</span>(game)</code></pre></div>
<pre><code>##                        Name Platform Year.Release    Genre Publisher
## 1                Wii Sports      Wii         2006   Sports  Nintendo
## 2            Mario Kart Wii      Wii         2008   Racing  Nintendo
## 3         Wii Sports Resort      Wii         2009   Sports  Nintendo
## 4     New Super Mario Bros.       DS         2006 Platform  Nintendo
## 5                  Wii Play      Wii         2006     Misc  Nintendo
## 6 New Super Mario Bros. Wii      Wii         2009 Platform  Nintendo
##   NA.Sales EU.Sales JP.Sales Other.Sales Global.Sales Critic.Score
## 1 41360001 28960001  3770001     8450001     82530001          7.6
## 2 15680001 12760001  3790001     3290001     35520001          8.2
## 3 15610001 10930001  3280001     2950001     32770001          8.0
## 4 11280001  9140001  6500001     2880001     29800001          8.9
## 5 13960001  9180001  2930001     2840001     28920001          5.8
## 6 14440001  6940001  4700001     2240001     28320001          8.7
##   Critic.Count User.Score User.Count Developer Rating NA.Sales.Log
## 1           51        8.0        322  Nintendo      E     17.53782
## 2           73        8.3        709  Nintendo      E     16.56790
## 3           73        8.0        192  Nintendo      E     16.56342
## 4           65        8.5        431  Nintendo      E     16.23854
## 5           41        6.6        129  Nintendo      E     16.45171
## 6           80        8.4        594  Nintendo      E     16.48551
##   EU.Sales.Log JP.Sales.Log Other.Sales.Log Global.Sales.Log
## 1     17.18143     15.14259        15.94968         18.22867
## 2     16.36183     15.14788        15.00640         17.38561
## 3     16.20702     15.00335        14.89732         17.30502
## 4     16.02817     15.68731        14.87330         17.21002
## 5     16.03254     14.89051        14.85931         17.18004
## 6     15.75281     15.36307        14.62199         17.15908
##   Critic.Count.Log User.Count.Log
## 1         3.931826       5.774552
## 2         4.290459       6.563856
## 3         4.290459       5.257495
## 4         4.174387       6.066108
## 5         3.713572       4.859812
## 6         4.382027       6.386879</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(game)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    6825 obs. of  23 variables:
##  $ Name            : Factor w/ 4377 levels &quot; Tales of Xillia 2&quot;,..: 4203 2055 4205 2530 4201 2533 2054 4195 1820 4196 ...
##  $ Platform        : Factor w/ 17 levels &quot;3DS&quot;,&quot;DC&quot;,&quot;DS&quot;,..: 13 13 13 3 13 13 3 13 15 13 ...
##  $ Year.Release    : Factor w/ 25 levels &quot;1985&quot;,&quot;1988&quot;,..: 15 17 18 15 15 18 14 16 19 18 ...
##  $ Genre           : Factor w/ 12 levels &quot;Action&quot;,&quot;Adventure&quot;,..: 11 7 11 5 4 5 7 11 4 11 ...
##  $ Publisher       : Factor w/ 262 levels &quot;10TACLE Studios&quot;,..: 164 164 164 164 164 164 164 164 147 164 ...
##  $ NA.Sales        : num  41360001 15680001 15610001 11280001 13960001 ...
##  $ EU.Sales        : num  28960001 12760001 10930001 9140001 9180001 ...
##  $ JP.Sales        : num  3770001 3790001 3280001 6500001 2930001 ...
##  $ Other.Sales     : num  8450001 3290001 2950001 2880001 2840001 ...
##  $ Global.Sales    : num  82530001 35520001 32770001 29800001 28920001 ...
##  $ Critic.Score    : num  7.6 8.2 8 8.9 5.8 8.7 9.1 8 6.1 8 ...
##  $ Critic.Count    : num  51 73 73 65 41 80 64 63 45 33 ...
##  $ User.Score      : num  8 8.3 8 8.5 6.6 8.4 8.6 7.7 6.3 7.4 ...
##  $ User.Count      : num  322 709 192 431 129 594 464 146 106 52 ...
##  $ Developer       : Factor w/ 1289 levels &quot;10tacle Studios, Fusionsphere Systems&quot;,..: 779 779 779 779 779 779 779 779 468 779 ...
##  $ Rating          : Factor w/ 7 levels &quot;AO&quot;,&quot;E&quot;,&quot;E10+&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ NA.Sales.Log    : num  17.5 16.6 16.6 16.2 16.5 ...
##  $ EU.Sales.Log    : num  17.2 16.4 16.2 16 16 ...
##  $ JP.Sales.Log    : num  15.1 15.1 15 15.7 14.9 ...
##  $ Other.Sales.Log : num  15.9 15 14.9 14.9 14.9 ...
##  $ Global.Sales.Log: num  18.2 17.4 17.3 17.2 17.2 ...
##  $ Critic.Count.Log: num  3.93 4.29 4.29 4.17 3.71 ...
##  $ User.Count.Log  : num  5.77 6.56 5.26 6.07 4.86 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">a &lt;-<span class="st"> </span><span class="kw">colnames</span>(game)[<span class="kw">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="op">:</span><span class="dv">23</span>)]  <span class="co"># pick up the numeric columns according to the names </span>
<span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">4</span>))  <span class="co"># layout in 5 rows and 4 columns</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(a)){
  sub &lt;-<span class="st"> </span><span class="kw">sample</span>(game[a[i]][, <span class="dv">1</span>], <span class="dv">5000</span>)
  submean &lt;-<span class="st"> </span><span class="kw">mean</span>(sub)
  <span class="kw">hist</span>(sub, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Hist. of&quot;</span>, a[i], <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>), <span class="dt">xlab =</span> a[i])
  <span class="kw">abline</span>(<span class="dt">v =</span> submean, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">lwd =</span> <span class="dv">1</span>)
  <span class="kw">qqnorm</span>(sub, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Q-Q Plot of&quot;</span>, a[i], <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>))
  <span class="kw">qqline</span>(sub) 
  <span class="cf">if</span> (i <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) {s.t &lt;-<span class="st"> </span><span class="kw">shapiro.test</span>(sub)
  } <span class="cf">else</span> {s.t &lt;-<span class="st"> </span><span class="kw">rbind</span>(s.t, <span class="kw">shapiro.test</span>(sub))
 }
}
s.t &lt;-<span class="st"> </span>s.t[, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]
<span class="kw">mode</span>(s.t) =<span class="st"> &quot;numeric&quot;</span>  <span class="co"># show shapiro.test result as numeric</span>
s.t &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">data.frame</span>(s.t), <span class="dv">3</span>)  <span class="co"># round to decimal 3</span>
s.t<span class="op">$</span>data.name &lt;-<span class="st"> </span>a
s.t</code></pre></div>
<pre><code>##     statistic p.value        data.name
## s.t     0.962       0     Critic.Score
## X       0.910       0       User.Score
## X.1     0.646       0     NA.Sales.Log
## X.2     0.714       0     EU.Sales.Log
## X.3     0.622       0     JP.Sales.Log
## X.4     0.711       0  Other.Sales.Log
## X.5     0.997       0 Global.Sales.Log
## X.6     0.978       0 Critic.Count.Log
## X.7     0.942       0   User.Count.Log</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-441-1.png" width="768" /></p>
<p>Though the Shapiro test still deny the normality of these log values. We assume they are normal distributed data after log-transformation.</p>
<p>There are lots of interest points in this data set such as the distribution of global and regional sales and their relationship, the correlation of critic score and user score and their counts, whether these scores are the main effect for sales, or the other factors like genre, rating, platform, even publisher affect the sales more, and so on.</p>
</div>
<div id="visualizing-of-categorical-variables" class="section level2">
<h2><span class="header-section-number">14.2</span> Visualizing of categorical variables</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(wordcloud)
<span class="kw">library</span>(ngram)
<span class="kw">library</span>(tm)
<span class="kw">library</span>(RColorBrewer)
titles &lt;-<span class="st"> </span><span class="kw">concatenate</span>(game<span class="op">$</span>Name)
titles &lt;-<span class="st"> </span><span class="kw">tolower</span>(titles)
titles &lt;-<span class="st"> </span><span class="kw">removeNumbers</span>(titles)
titles &lt;-<span class="st"> </span><span class="kw">removePunctuation</span>(titles)
titles &lt;-<span class="st"> </span><span class="kw">stripWhitespace</span>(titles)
titles &lt;-<span class="st"> </span><span class="kw">removeWords</span>(titles, <span class="kw">c</span>(<span class="kw">stopwords</span>(<span class="st">&quot;en&quot;</span>), <span class="st">&quot;game&quot;</span>))
unigram &lt;-<span class="st"> </span><span class="kw">ngram</span>(titles, <span class="dt">n =</span> <span class="dv">1</span>)
freq &lt;-<span class="st"> </span><span class="kw">tbl_df</span>(<span class="kw">get.phrasetable</span>(unigram))
<span class="kw">wordcloud</span>(freq<span class="op">$</span>ngrams, freq<span class="op">$</span>freq, <span class="dt">random.order =</span> <span class="ot">FALSE</span>, <span class="dt">rot.per =</span> <span class="fl">0.35</span>,
          <span class="dt">color=</span><span class="kw">brewer.pal</span>(<span class="dv">8</span>, <span class="st">&quot;Dark2&quot;</span>), <span class="dt">max.words =</span> <span class="dv">500</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-442-1.png" width="672" /></p>
<p>The most common word in game name is world and ii, then star, wars and NBA. Soccer, NFL, dragon, Lego and warriors are the third popular team.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span><span class="kw">sort</span>(<span class="kw">table</span>(game<span class="op">$</span>Platform), <span class="dt">decreasing =</span> <span class="ot">TRUE</span>)
percentages &lt;-<span class="st"> </span><span class="dv">100</span> <span class="op">*</span><span class="st"> </span>counts <span class="op">/</span><span class="st"> </span><span class="kw">length</span>(game<span class="op">$</span>Platform)
<span class="kw">barplot</span>(percentages[<span class="dv">1</span><span class="op">:</span><span class="dv">18</span>], <span class="dt">las =</span> <span class="dv">3</span>, <span class="dt">ylab =</span> <span class="st">&quot;Percentage&quot;</span>, <span class="dt">col =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">axis.lty =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-443-1.png" width="672" /></p>
<p>These are the top 18 platforms according to the frequency. PSs occupies big portion.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#regroup platform as Platform.type </span>
pc &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;PC&quot;</span>)
xbox &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;X360&quot;</span>, <span class="st">&quot;XB&quot;</span>, <span class="st">&quot;XOne&quot;</span>)
nintendo &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Wii&quot;</span>, <span class="st">&quot;WiiU&quot;</span>, <span class="st">&quot;N64&quot;</span>, <span class="st">&quot;GC&quot;</span>, <span class="st">&quot;NES&quot;</span>, <span class="st">&quot;3DS&quot;</span>, <span class="st">&quot;DS&quot;</span>) 
playstation &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;PS&quot;</span>, <span class="st">&quot;PS2&quot;</span>, <span class="st">&quot;PS3&quot;</span>, <span class="st">&quot;PS4&quot;</span>, <span class="st">&quot;PSP&quot;</span>, <span class="st">&quot;PSV&quot;</span>)
game &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Platform.type =</span> <span class="kw">ifelse</span>(Platform <span class="op">%in%</span><span class="st"> </span>pc, <span class="st">&quot;pc&quot;</span>,
                           <span class="kw">ifelse</span>(Platform <span class="op">%in%</span><span class="st"> </span>xbox, <span class="st">&quot;xbox&quot;</span>,
                             <span class="kw">ifelse</span>(Platform <span class="op">%in%</span><span class="st"> </span>nintendo, <span class="st">&quot;nintendo&quot;</span>, 
                               <span class="kw">ifelse</span>(Platform <span class="op">%in%</span><span class="st"> </span>playstation, <span class="st">&quot;playstation&quot;</span>, <span class="st">&quot;others&quot;</span>))))) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> Platform.type)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-445-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">table</span>(game<span class="op">$</span>Genre))
dat<span class="op">$</span>fraction =<span class="st"> </span>dat<span class="op">$</span>Freq <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(dat<span class="op">$</span>Freq)
dat =<span class="st"> </span>dat[<span class="kw">order</span>(dat<span class="op">$</span>fraction), ]
dat<span class="op">$</span>ymax =<span class="st"> </span><span class="kw">cumsum</span>(dat<span class="op">$</span>fraction)
dat<span class="op">$</span>ymin =<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">head</span>(dat<span class="op">$</span>ymax, <span class="dt">n =</span> <span class="op">-</span><span class="dv">1</span>))
<span class="kw">names</span>(dat)[<span class="dv">1</span>] &lt;-<span class="st"> &quot;Genre&quot;</span>
<span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(dat, <span class="kw">aes</span>(<span class="dt">fill =</span> dat<span class="op">$</span>Genre, <span class="dt">ymax =</span> ymax, <span class="dt">ymin =</span> ymin, <span class="dt">xmax =</span> <span class="dv">4</span>, <span class="dt">xmin =</span> <span class="dv">3</span>)) <span class="op">+</span>
<span class="kw">geom_rect</span>(<span class="dt">colour =</span> <span class="st">&quot;grey30&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># background color</span>
<span class="kw">coord_polar</span>(<span class="dt">theta =</span> <span class="st">&quot;y&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># coordinate system to polar</span>
<span class="kw">xlim</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">4</span>)) <span class="op">+</span>
<span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Ring plot for Genre type&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;Genre&quot;</span>) <span class="op">+</span>
<span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-446-1.png" width="672" /></p>
<p>Action, Sports and Shooter are the first three biggest genre. Action occupies almost 25% genre. Three of them together contribute half of genre count.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#regroup Genre as Genre.type</span>
genre &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Platform&quot;</span>, <span class="st">&quot;Racing&quot;</span>, <span class="st">&quot;Simulation&quot;</span>, <span class="st">&quot;Sports&quot;</span>, <span class="st">&quot;Misc&quot;</span>)
<span class="co">#Combat &lt;- c(&quot;fighting&quot;, &quot;Shooter&quot;)</span>

game &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Genre.type =</span> <span class="kw">ifelse</span>(Genre <span class="op">%in%</span><span class="st"> </span>genre, <span class="kw">as.character</span>(Genre),
                        <span class="kw">ifelse</span>(Genre <span class="op">==</span><span class="st"> &quot;Fighting&quot;</span> <span class="op">|</span><span class="st"> </span>Genre <span class="op">==</span><span class="st"> &quot;Shooter&quot;</span>, <span class="st">&quot;Combat&quot;</span>,
                          <span class="kw">ifelse</span>(Genre <span class="op">==</span><span class="st"> &quot;Puzzle&quot;</span> <span class="op">|</span><span class="st"> </span>Genre <span class="op">==</span><span class="st"> &quot;Strategy&quot;</span>, <span class="st">&quot;Strategy&quot;</span>,
                                      <span class="st">&quot;Action/Adventure&quot;</span>))))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#regroup Rating as Rating.type </span>
rating &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;E&quot;</span>, <span class="st">&quot;T&quot;</span>, <span class="st">&quot;M&quot;</span>, <span class="st">&quot;E10+&quot;</span>)
game &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">Rating.type =</span> <span class="kw">ifelse</span>(Rating <span class="op">%in%</span><span class="st"> </span>rating, <span class="kw">as.character</span>(Rating), <span class="st">&quot;Others&quot;</span>)) </code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span><span class="kw">sort</span>(<span class="kw">table</span>(game<span class="op">$</span>Rating.type), <span class="dt">decreasing =</span> <span class="ot">TRUE</span>)
<span class="kw">names</span>(counts)[<span class="dv">1</span>] &lt;-<span class="st"> &quot;T - Teen&quot;</span>  <span class="co"># rename the names of counts for detail information</span>
<span class="kw">names</span>(counts)[<span class="dv">2</span>] &lt;-<span class="st"> &quot;E - Everyone&quot;</span>
<span class="kw">names</span>(counts)[<span class="dv">3</span>] &lt;-<span class="st"> &quot;M - Mature&quot;</span>
<span class="kw">names</span>(counts)[<span class="dv">4</span>] &lt;-<span class="st"> &quot;E10+ - Everyone 10+&quot;</span>
pct &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="kw">round</span>(counts<span class="op">/</span><span class="kw">sum</span>(counts) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>), <span class="st">&quot;%&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)
lbls &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="kw">names</span>(counts), <span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>, pct, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)  <span class="co"># labels with count number</span>
<span class="kw">pie</span>(counts, <span class="dt">labels =</span> lbls, <span class="dt">col =</span> <span class="kw">rainbow</span>(<span class="kw">length</span>(lbls)),
<span class="dt">main=</span><span class="st">&quot;Pie Chart of Ratings with sample sizes&quot;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-449-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">15</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<p>According to the order, the most popular ratings are T, E, M and E10+. There are altogether 6722 in 6825 games belong to these four ratings. Other ratings only occupy very little in the all games.</p>
</div>
<div id="correlation-among-numeric-variables" class="section level2">
<h2><span class="header-section-number">14.3</span> Correlation among numeric variables</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">st &lt;-<span class="st"> </span>game[, <span class="kw">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="op">:</span><span class="dv">23</span>)]  <span class="co"># take numeric variables as goal matrix</span>
st &lt;-<span class="st"> </span><span class="kw">na.omit</span>(st)
<span class="kw">library</span>(ellipse)  <span class="co"># install.packages(&quot;ellipses&quot;)</span>
<span class="kw">library</span>(corrplot)
corMatrix &lt;-<span class="st"> </span><span class="kw">cor</span>(<span class="kw">as.matrix</span>(st))  <span class="co"># correlation matrix</span>
col &lt;-<span class="st"> </span><span class="kw">colorRampPalette</span>(<span class="kw">c</span>(<span class="st">&quot;#7F0000&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;#FF7F00&quot;</span>, <span class="st">&quot;yellow&quot;</span>, <span class="st">&quot;#7FFF7F&quot;</span>,
                           <span class="st">&quot;cyan&quot;</span>, <span class="st">&quot;#007FFF&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;#00007F&quot;</span>))
<span class="kw">corrplot.mixed</span>(corMatrix, <span class="dt">order =</span> <span class="st">&quot;AOE&quot;</span>, <span class="dt">lower =</span> <span class="st">&quot;number&quot;</span>, <span class="dt">lower.col =</span> <span class="st">&quot;black&quot;</span>, 
               <span class="dt">number.cex =</span> .<span class="dv">8</span>, <span class="dt">upper =</span> <span class="st">&quot;ellipse&quot;</span>,  <span class="dt">upper.col =</span> <span class="kw">col</span>(<span class="dv">10</span>), 
               <span class="dt">diag =</span> <span class="st">&quot;u&quot;</span>, <span class="dt">tl.pos =</span> <span class="st">&quot;lt&quot;</span>, <span class="dt">tl.col =</span> <span class="st">&quot;black&quot;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-450-1.png" width="768" /></p>
<p>There are high r values of 0.75, 0.65, 0.52 and 0.42 between the log value of Global.Sales and regional sales, we will consider to use Global.Sales.Log as our target sales to analyze the relationship with other variables later. On the other hand, there are good positive correlation between regional sales too. User Score is positive correlated to Critic Score with r of 0.58. There is little correlation between User Count log value and User Score.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">hclust</span>(<span class="kw">as.dist</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">cor</span>(<span class="kw">as.matrix</span>(st)))))  <span class="co"># hierarchical clustering</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-451-1.png" width="672" /></p>
<p>All sales’ log value except JP.Sales.Log build one cluster, scores build second cluster, and log value of counts and JP.Sales build another one. In sales cluster, Other.Sales.Log is the closest to Global.Sales.Log, then NA.Sales.Log, and EU.Sales.Log is the next.</p>
</div>
<div id="analysis-of-score-and-count" class="section level2">
<h2><span class="header-section-number">14.4</span> Analysis of Score and Count</h2>
<div id="distribution-of-two-scores" class="section level3">
<h3><span class="header-section-number">14.4.1</span> Distribution of two scores</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">data =</span> game, <span class="kw">aes</span>(<span class="dt">x=</span>Critic.Score), <span class="dt">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">data =</span> game, <span class="kw">aes</span>(<span class="dt">x=</span>User.Score), <span class="dt">color =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;lightgreen&quot;</span>, <span class="dt">alpha=</span>.<span class="dv">5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Critic.Score-blue, User.Score-green&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;Density plot for critic and user score&quot;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-452-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> Year.Release, <span class="dt">y =</span> Critic.Score, <span class="dt">colour =</span> <span class="st">&quot;CriticScore&quot;</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> <span class="fl">1.0</span>) <span class="op">+</span><span class="st">  </span><span class="co"># scatter point of critic score</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> User.Score, <span class="dt">colour =</span> <span class="st">&quot;UserScore&quot;</span>)) <span class="op">+</span><span class="st">  </span><span class="co"># scatter point of user score</span>
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Critic.Score, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">fun.y =</span> mean,   <span class="co">#add average critic score line</span>
               <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">size =</span> <span class="fl">1.5</span>, <span class="dt">group =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y =</span> User.Score, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">fun.y =</span> mean,  <span class="co">#add average critic score line</span>
               <span class="dt">colour =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="dt">size =</span> <span class="fl">1.5</span>, <span class="dt">group =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Critic.Score, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">fun.y =</span> mean,  <span class="co">#add average critic score point</span>
               <span class="dt">colour =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">group =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y =</span> User.Score, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">fun.y =</span> mean,  <span class="co">#add average user score point</span>
               <span class="dt">colour =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">group =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>,
          <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
          <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>),  <span class="co">#background</span>
          <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),  <span class="co">#no panel grid</span>
          <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">   </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Score distribution of Each Year&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Year Release&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Scores&quot;</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-453-1.png" width="672" /></p>
<p>There is not so many evaluation about the game available before 1996. In the early years, averages of Critic.Score are higher than averages of User.Score. From 1998 Users gave higher score then critics on average, the situation kept until 2009. From 2010 till 2016, the trend of early years came back, average critic scores are higher than average user score again.</p>
<p>Between 1996 and 1999, both critics and users intended to give higher scores than the other years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggpmisc)  <span class="co">#package for function stat_poly_eq</span>
formula &lt;-<span class="st"> </span>y <span class="op">~</span><span class="st"> </span>x
<span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> User.Score, <span class="dt">y =</span> Critic.Score)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Platform), <span class="dt">alpha =</span> .<span class="dv">8</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>, <span class="dt">formula =</span> formula) <span class="op">+</span><span class="st">  </span><span class="co">#add regression line</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_poly_eq</span>(<span class="dt">formula =</span> formula,   <span class="co">#add regression equation and R square value</span>
               <span class="dt">eq.with.lhs =</span> <span class="st">&quot;italic(hat(y))~`=`~&quot;</span>,  <span class="co"># add ^ on y</span>
               <span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste</span>(..eq.label.., ..rr.label.., <span class="dt">sep =</span> <span class="st">&quot;*plain(</span><span class="ch">\&quot;</span><span class="st">,</span><span class="ch">\&quot;</span><span class="st">)~&quot;</span>)),
               <span class="dt">label.x.npc =</span> <span class="st">&quot;left&quot;</span>, <span class="dt">label.y.npc =</span> <span class="fl">0.92</span>,   <span class="co"># position of the equation label</span>
               <span class="dt">parse =</span> <span class="ot">TRUE</span>)   </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-454-1.png" width="672" /></p>
<p>There is good correlation between Critic.Score and User.Score. Some of the GBA games got highest User.Score, while highest Critic.Score came from X360 and PS series.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(game<span class="op">$</span>Critic.Score, game<span class="op">$</span>User.Score)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  game$Critic.Score and game$User.Score
## t = -6.5463, df = 13629, p-value = 6.108e-11
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2058518 -0.1109834
## sample estimates:
## mean of x mean of y 
##  7.027209  7.185626</code></pre>
<p>T-test with p value of much less than 0.05 let us accept the alternative hypothesis with 95% confidence that there is difference in the means of critic score and user score. The mean of critic score is 7.03, and mean of user score is 7.19.</p>
</div>
<div id="score-top-sale-game" class="section level3">
<h3><span class="header-section-number">14.4.2</span> Score &amp; Top sale game</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game<span class="op">$</span>Name &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="st">&quot;Brain Age: Train Your Brain in Minutes a Day&quot;</span>,  <span class="co">#shorten the game name</span>
                    <span class="st">&quot;Brain Age: Train Your Brain&quot;</span>, game<span class="op">$</span>Name)
p1 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Name, User.Score, Critic.Score, Global.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Name) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales), <span class="dt">Avg.User.Score =</span> <span class="kw">mean</span>(User.Score), 
            <span class="dt">Avg.Critic.Score =</span> <span class="kw">mean</span>(Critic.Score)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">20</span>)
<span class="kw">ggplot</span>(p1, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(Name, <span class="dt">levels =</span> Name))) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Total.Sales<span class="op">/</span><span class="dv">10000000</span>), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;green&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.User.Score, <span class="dt">group =</span> <span class="dv">1</span>, <span class="dt">colour =</span> <span class="st">&quot;Avg.User.Score&quot;</span>), <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>( <span class="kw">aes</span>(<span class="dt">y =</span> Avg.User.Score), <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;Yellow&quot;</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Critic.Score,  <span class="dt">group =</span> <span class="dv">1</span>, <span class="dt">colour =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>), <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Critic.Score), <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">size =</span> <span class="dv">8</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Top Global Sales Game with Score&quot;</span> ) <span class="op">+</span><span class="st">  </span><span class="co"># add title in the center of the plot</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-456-1.png" width="672" /></p>
<p>Among these 20 top sale games, top two games, Wii Sports and Grand Theft Auto V have much better sales than the other games. Both of them were scored above 7.5. Grand Theft Auto V even got the highest Critic score among all these top games. Though there are several other games like Grand Theft Auto IV, The Elder Scrolls V: Skyrim have really high scores too. This plot also indicates that for these top games, their global sales have no clear linear correlation with the average User.Score and Critic.Score. For most games, average critic score is higher than average user score. Call of Duty: Modern Warfare 3 and Call of Duty: Ghosts got really lower average user score comparing with other top sales game.</p>
</div>
<div id="score-rating" class="section level3">
<h3><span class="header-section-number">14.4.3</span> Score &amp; Rating</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(game<span class="op">$</span>Critic.Score <span class="op">~</span><span class="st"> </span>game<span class="op">$</span>Rating))</code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## game$Rating    6    102   17.02   8.913 1.03e-09 ***
## Residuals   6818  13023    1.91                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(game<span class="op">$</span>User.Score <span class="op">~</span><span class="st"> </span>game<span class="op">$</span>Rating))</code></pre></div>
<pre><code>##               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## game$Rating    6    122  20.333   9.883 6.99e-11 ***
## Residuals   6818  14027   2.057                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There is significant difference in at least two different ratings for both critic score and user score means.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">fill =</span> Rating)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>) 
p2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> User.Score, <span class="dt">fill =</span> Rating)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> <span class="fl">0.3</span>) 
<span class="kw">library</span>(gridExtra)
<span class="kw">grid.arrange</span>(p1, p2, <span class="dt">nrow =</span> <span class="dv">1</span>,<span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-458-1.png" width="1152" /></p>
<p>In total, Rating M got more higher Critic.Score than others, E10+ got more lower Critic.Score; For User.Score, as same as Critic.Score, E10+ is low. While the others are similar and higher.</p>
</div>
<div id="score-genre" class="section level3">
<h3><span class="header-section-number">14.4.4</span> 7) Score &amp; Genre</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(scales)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st"> </span><span class="kw">group_by</span>(Genre, Critic.Score) <span class="op">%&gt;%</span>
<span class="st"> </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales)) <span class="op">%&gt;%</span>
<span class="st"> </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Total.Sales, <span class="dt">group =</span> Genre, <span class="dt">fill =</span> Genre)) <span class="op">+</span>
<span class="st">   </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span>
<span class="st">   </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">percent_format</span>()) <span class="op">+</span>
<span class="st">   </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>), 
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;black&quot;</span>), 
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),  
        <span class="dt">panel.grid.minor=</span><span class="kw">element_blank</span>())</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-459-1.png" width="672" /></p>
<p>Some Racing and Adventure game got the lowest Critic.Score. On the other side, some action game got excellent evaluation from critics and have great Global.Sales. Sports, Shooter and Platform came next.</p>
</div>
<div id="score-global-sales" class="section level3">
<h3><span class="header-section-number">14.4.5</span> 8) Score &amp; Global sales</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Genre)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>()
p2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> User.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>()
<span class="kw">grid.arrange</span>(p1, p2, <span class="dt">nrow =</span> <span class="dv">1</span>,<span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-460-1.png" width="1152" /></p>
<p>Independent from Genre and Rating, the higher of Score, the better of Global.Sales.Log. Especially for Critic.Score bigger than 9, Global.Sales straight rising. Global.Sales rise slowly with User.Score.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game.bottom &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="kw">filter</span>(game, Critic.Score <span class="op">&lt;</span><span class="st"> </span><span class="fl">2.5</span>), <span class="kw">c</span>(Global.Sales.Log, Critic.Score))
game.low &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="kw">filter</span>(game, Critic.Score <span class="op">&gt;=</span><span class="st"> </span><span class="fl">2.5</span> <span class="op">&amp;</span><span class="st"> </span>Critic.Score <span class="op">&lt;</span><span class="st"> </span><span class="dv">5</span>), 
                   <span class="kw">c</span>(Global.Sales.Log, Critic.Score))
game.middle &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="kw">filter</span>(game, Critic.Score <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span> <span class="op">&amp;</span><span class="st"> </span>Critic.Score <span class="op">&lt;</span><span class="st"> </span><span class="fl">7.5</span>), 
                   <span class="kw">c</span>(Global.Sales.Log, Critic.Score))
game.high &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="kw">filter</span>(game, Critic.Score <span class="op">&gt;=</span><span class="st"> </span><span class="fl">7.5</span> <span class="op">&amp;</span><span class="st"> </span>Critic.Score <span class="op">&lt;</span><span class="st"> </span><span class="dv">9</span>), 
                   <span class="kw">c</span>(Global.Sales.Log, Critic.Score))
game.top &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="kw">filter</span>(game, Critic.Score <span class="op">&gt;=</span><span class="st"> </span><span class="dv">9</span>), <span class="kw">c</span>(Global.Sales.Log, Critic.Score))
formula &lt;-<span class="st"> </span>y <span class="op">~</span><span class="st"> </span>x
p1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game.bottom, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">   </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()
p2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game.low, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">   </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()
p3 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game.middle, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>()
<span class="kw">grid.arrange</span>(p1, p2, p3, <span class="dt">ncol =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;
## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-461-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">r1 &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">with</span>(game.high, <span class="kw">cor</span>(Critic.Score, Global.Sales.Log)), <span class="dt">digits =</span> <span class="dv">2</span>)
p4 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game.high, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_poly_eq</span>(<span class="dt">formula =</span> formula, <span class="co">#add regression equation and R square value</span>
    <span class="dt">eq.with.lhs =</span> <span class="st">&quot;italic(hat(y))~`=`~&quot;</span>, <span class="co"># add ^ on y</span>
    <span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste</span>(..eq.label.., ..rr.label.., <span class="dt">sep =</span> <span class="st">&quot;*plain(</span><span class="ch">\&quot;</span><span class="st">,</span><span class="ch">\&quot;</span><span class="st">)~&quot;</span>)),
    <span class="dt">label.x.npc =</span> <span class="st">&quot;left&quot;</span>, <span class="dt">label.y.npc =</span> <span class="fl">0.92</span>, <span class="co"># position of the equation label</span>
    <span class="dt">parse =</span> <span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">7.62</span>, <span class="dt">y =</span> <span class="fl">17.2</span>, <span class="dt">label =</span> <span class="kw">paste</span>(<span class="st">&quot;r =&quot;</span>, r1, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)) <span class="co"># add correlation rate r</span>
r2 &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">with</span>(game.top, <span class="kw">cor</span>(Critic.Score, Global.Sales.Log)), <span class="dt">digits =</span> <span class="dv">2</span>)
p5 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(game.top, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">stat_poly_eq</span>(<span class="dt">formula =</span> formula, <span class="co">#add regression equation and R square value</span>
    <span class="dt">eq.with.lhs =</span> <span class="st">&quot;italic(hat(y))~`=`~&quot;</span>, <span class="co"># add ^ on y</span>
    <span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste</span>(..eq.label.., ..rr.label.., <span class="dt">sep =</span> <span class="st">&quot;*plain(</span><span class="ch">\&quot;</span><span class="st">,</span><span class="ch">\&quot;</span><span class="st">)~&quot;</span>)),
    <span class="dt">label.x.npc =</span> <span class="st">&quot;right&quot;</span>, <span class="dt">label.y.npc =</span> <span class="fl">0.1</span>, <span class="co"># position of the equation label</span>
    <span class="dt">parse =</span> <span class="ot">TRUE</span>)<span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="fl">9.5</span>, <span class="dt">y =</span> <span class="fl">9.5</span>, <span class="dt">label =</span> <span class="kw">paste</span>(<span class="st">&quot;r =&quot;</span>, r2, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)) <span class="co"># add correlation rate r</span>
<span class="kw">grid.arrange</span>(p4, p5, <span class="dt">ncol =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-462-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#ggarrange(p4, p5, ncol = 2)</span></code></pre></div>
<p>If we seperate the citic score into 5 groups: bottom(&lt;2.5), low(between2.5 &amp; 5), middle(between 5 &amp; 7.5), high(between 7.5 &amp; 9) and top(&gt;=9), there is no linear relationship between Global.Sales.Log and Critic.Score in the first three groups. For “high” group, correlation r is 0.22 and the linear equation of critic score can only explain about 0.05 global sales log; While for “top” group, correlation r is higher as 0.35 and the linear equation of critic score can only explain more global sales log up to 0.13.</p>
</div>
<div id="score-top-sale-developer" class="section level3">
<h3><span class="header-section-number">14.4.6</span> 9) Score &amp; Top Sale Developer</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(reshape2)
p &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Developer, Critic.Score, User.Score, Global.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Developer) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Avg.Critic.Score =</span> <span class="kw">mean</span>(Critic.Score), <span class="dt">Avg.User.Score =</span> <span class="kw">mean</span>(User.Score), 
            <span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales<span class="op">/</span><span class="dv">4</span><span class="op">/</span><span class="dv">10</span><span class="op">^</span><span class="dv">7</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(Total.Sales <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>) 
<span class="co">#arrange according to sales, melt only developer and scores</span>
p1 &lt;-<span class="st"> </span>p[, <span class="op">-</span><span class="dv">4</span>]
p1 &lt;-<span class="st"> </span><span class="kw">melt</span>(p1, <span class="dt">value.name =</span> <span class="st">&quot;Scores&quot;</span>)</code></pre></div>
<pre><code>## Using Developer as id variables</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p2 &lt;-<span class="st"> </span>p[, <span class="dv">4</span>]
comp &lt;-<span class="st"> </span><span class="kw">cbind.data.frame</span>(p1, p2)
comp &lt;-<span class="st"> </span>comp[<span class="kw">rev</span>(<span class="kw">order</span>(comp<span class="op">$</span>Total.Sales)), ]
lv &lt;-<span class="st"> </span><span class="kw">unique</span>(comp[<span class="dv">1</span>])
<span class="kw">ggplot</span>(comp, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(Developer, <span class="dt">levels =</span> <span class="kw">as.factor</span>(lv[,<span class="dv">1</span>])))) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Scores, <span class="dt">fill =</span> variable), <span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">width =</span> .<span class="dv">5</span>, <span class="dt">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Top sale Developers and their Scores&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Top Developers&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Total.Sales, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">col =</span> <span class="st">&quot;navyblue&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-463-1.png" width="960" /></p>
<p>According to our analysis, Nintendo is the only one which has total sales over 400 millions, much more than the other developers. The other top developers included EA Sports, EA Canada, Rockstar North, Capcorm and so on. This is a little bitter different order from the top developers according to number of games. But EA Sports, EA Canada and Capcorm are included in the top five in both list. Naughty Dogs has the highest user score, while Rockstar North got highest critic score. Infinity Ward got pretty good critic score, but user gave it a lowest score. Best sale developer Nintendo have pretty good scores, but not the highest in both scores.</p>
</div>
<div id="score-publisher" class="section level3">
<h3><span class="header-section-number">14.4.7</span> 10) Score &amp; Publisher</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p1 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Publisher, Critic.Score, User.Score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Publisher) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Avg.Critic.Score =</span> <span class="kw">mean</span>(Critic.Score), <span class="dt">Avg.User.Score =</span> <span class="kw">mean</span>(User.Score)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>( <span class="op">!</span>Avg.Critic.Score <span class="op">==</span><span class="st">&#39;NA&#39;</span> <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span>Avg.User.Score <span class="op">==</span><span class="st">&#39;NA&#39;</span> <span class="op">&amp;</span><span class="st"> </span>Avg.Critic.Score <span class="op">&gt;</span><span class="st"> </span><span class="dv">8</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Avg.Critic.Score))
<span class="kw">ggplot</span>(p1, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">factor</span>(Publisher, <span class="dt">levels =</span> Publisher))) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.User.Score, <span class="dt">group =</span> <span class="dv">1</span>, <span class="dt">colour =</span> <span class="st">&quot;Avg.User.Score&quot;</span>), <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>( <span class="kw">aes</span>(<span class="dt">y =</span> Avg.User.Score), <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;yellow&quot;</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Critic.Score,  <span class="dt">group =</span> <span class="dv">1</span>, <span class="dt">colour =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>), <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Critic.Score), <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>, <span class="dt">size =</span> <span class="dv">8</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Top Publishers with Average Critic Score greater than 8&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Top Publisher&quot;</span> )</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-464-1.png" width="672" /></p>
<p>These are the top publisher who got highest average critic score. Valve, Valve Software and Blue Byte are the top three publisher who got the highest average critic score. For Activision Blizzard and Slightly Mad Studios, though they got relatively higher average critic score, but their average user score are not ideal. While for Kadokawa Shoten, Nihon Falcom Corporation and Sony Computer Entertainment Europe, they got even much higher average user score than average critic score.</p>
</div>
</div>
<div id="analysis-of-sales" class="section level2">
<h2><span class="header-section-number">14.5</span> Analysis of Sales</h2>
<div id="by-year.release" class="section level3">
<h3><span class="header-section-number">14.5.1</span> 1) By Year.Release</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">table</span>(game<span class="op">$</span>Year.Release))
p &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Year.Release, Global.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year.Release) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales))
q &lt;-<span class="st"> </span><span class="kw">cbind.data.frame</span>(p, counts[<span class="dv">2</span>])
<span class="kw">names</span>(q)[<span class="dv">3</span>] &lt;-<span class="st"> &quot;count&quot;</span>
q<span class="op">$</span>count &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(q<span class="op">$</span>count)

p1 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(q, <span class="kw">aes</span>(<span class="dt">x =</span> Year.Release, <span class="dt">y =</span> Total.Sales, <span class="dt">label =</span> q<span class="op">$</span>count)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;green&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">y =</span> q<span class="op">$</span>count <span class="op">*</span><span class="st"> </span><span class="dv">500000</span>, <span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">shape =</span> <span class="dv">21</span>, <span class="dt">fill =</span> <span class="st">&quot;Yellow&quot;</span> ) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">y =</span> (q<span class="op">$</span>count <span class="op">-</span><span class="st"> </span><span class="dv">30</span>) <span class="op">*</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">+</span><span class="st">  </span><span class="co"># position of the text: count of games each year</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;purple&quot;</span>),
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
        <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="st">&quot;Year.Release&quot;</span>, <span class="dt">labels =</span> <span class="kw">as.character</span>(Year.Release), <span class="dt">breaks =</span> Year.Release)
  <span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Global Sales Each Year&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Year Release&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Global Sales&quot;</span>)</code></pre></div>
<pre><code>## $title
## [1] &quot;Global Sales Each Year&quot;
## 
## $x
## [1] &quot;Year Release&quot;
## 
## $y
## [1] &quot;Global Sales&quot;
## 
## attr(,&quot;class&quot;)
## [1] &quot;labels&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">r &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">with</span>(q, <span class="kw">cor</span>(count, Total.Sales)), <span class="dt">digits =</span> <span class="dv">2</span>)
formula &lt;-<span class="st"> </span>y <span class="op">~</span><span class="st"> </span>x    
<span class="kw">library</span>(ggpmisc)
p2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(q, <span class="kw">aes</span>(<span class="dt">x =</span> count, <span class="dt">y =</span> Total.Sales)) <span class="op">+</span><span class="st"> </span>
<span class="st">   </span><span class="kw">geom_point</span>() <span class="op">+</span>
<span class="st">   </span><span class="kw">geom_smooth</span>() <span class="op">+</span>
<span class="st">   </span><span class="kw">stat_poly_eq</span>(<span class="dt">formula =</span> formula,   <span class="co">#add regression equation and R square value</span>
               <span class="dt">eq.with.lhs =</span> <span class="st">&quot;italic(hat(y))~`=`~&quot;</span>,  <span class="co"># add ^ on y</span>
               <span class="kw">aes</span>(<span class="dt">label =</span> <span class="kw">paste</span>(..eq.label.., ..rr.label.., <span class="dt">sep =</span> <span class="st">&quot;*plain(</span><span class="ch">\&quot;</span><span class="st">,</span><span class="ch">\&quot;</span><span class="st">)~&quot;</span>)),
               <span class="dt">label.x.npc =</span> <span class="st">&quot;left&quot;</span>, <span class="dt">label.y.npc =</span> <span class="fl">0.92</span>,   <span class="co"># position of the equation label</span>
               <span class="dt">parse =</span> <span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_text</span>(<span class="dt">x =</span> <span class="dv">25</span>, <span class="dt">y =</span> <span class="dv">410000000</span>, <span class="dt">label =</span> <span class="kw">paste</span>(<span class="st">&quot;r =&quot;</span>, r, <span class="dt">sep =</span> <span class="st">&quot; &quot;</span>)) <span class="co"># add correlation rate r</span>
<span class="kw">grid.arrange</span>(p1, p2, <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">nrow =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-465-1.png" width="768" /></p>
<p>We can notice from the histogram of total sales that there is very little sales before 1996. There is only one game was released for these years. For several years between 1996 and 2000 the sales increased slowly. The count of games too, from 7 to 30. After that there is a big climbing in total sales. Over 100 games were released each year after that. The top sales happened in 2008, and the most count games was released that year(592). After that total sales of the video games sloped down. And the count of games reduced too. There is a good correlation between total sales and the count of game sold with r=0.96. If we use the equation top left in the figure, we can explain 0.92 of the total sales.</p>
</div>
<div id="by-region" class="section level3">
<h3><span class="header-section-number">14.5.2</span> 2) By Region</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Year.Release, NA.Sales.Log, EU.Sales.Log, JP.Sales.Log, 
         Other.Sales.Log, Global.Sales.Log) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year.Release) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">NorthAmerica =</span> <span class="kw">sum</span>(NA.Sales.Log), <span class="dt">Europe =</span> <span class="kw">sum</span>(EU.Sales.Log), 
            <span class="dt">Japan =</span> <span class="kw">sum</span>(JP.Sales.Log), <span class="dt">Other =</span> <span class="kw">sum</span>(Other.Sales.Log), 
            <span class="dt">Global =</span> <span class="kw">sum</span>(Global.Sales.Log)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year.Release, <span class="dt">y =</span> NorthAmerica,  <span class="dt">colour=</span><span class="st">&quot;NorthAmerica&quot;</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st">  </span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="dt">group =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Europe, <span class="dt">colour =</span> <span class="st">&quot;Europe&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Europe, <span class="dt">colour =</span> <span class="st">&quot;Europe&quot;</span>, <span class="dt">group =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Japan, <span class="dt">colour =</span> <span class="st">&quot;Japan&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Japan, <span class="dt">colour =</span> <span class="st">&quot;Japan&quot;</span>, <span class="dt">group =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Other, <span class="dt">colour =</span> <span class="st">&quot;Other&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Other, <span class="dt">colour =</span> <span class="st">&quot;Other&quot;</span>, <span class="dt">group =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Global, <span class="dt">colour =</span> <span class="st">&quot;Global&quot;</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Global, <span class="dt">colour =</span> <span class="st">&quot;Global&quot;</span>, <span class="dt">group =</span> <span class="dv">1</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,
          <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
          <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill=</span><span class="st">&quot;pink&quot;</span>),
          <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
          <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_discrete</span>(<span class="st">&quot;Year.Release&quot;</span>, <span class="dt">labels =</span> <span class="kw">as.character</span>(Year.Release), 
                     <span class="dt">breaks =</span> Year.Release) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Regional Global Sales Log Distribution Each Year&quot;</span>, 
         <span class="dt">x =</span> <span class="st">&quot;Year Release&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Total Sales Log Value&quot;</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-466-1.png" width="768" /></p>
<p>The pattern of log value for these regional sales in those years are similar for Global, North America, Europe, and Others. Japan is much different from them. Same conclusion as cluster analysis.</p>
</div>
<div id="by-genre" class="section level3">
<h3><span class="header-section-number">14.5.3</span> 3) By Genre</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Year.Release, Global.Sales.Log, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year.Release, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales.Log =</span> <span class="kw">sum</span>(Global.Sales.Log)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year.Release, <span class="dt">y =</span> Total.Sales.Log, <span class="dt">group =</span> Genre, <span class="dt">fill =</span> Genre)) <span class="op">+</span>
<span class="st">         </span><span class="kw">geom_area</span>() <span class="op">+</span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
               <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>),
               <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
               <span class="dt">panel.grid.minor=</span><span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">         </span><span class="kw">scale_x_discrete</span>(<span class="st">&quot;Year.Release&quot;</span>, <span class="dt">labels =</span> <span class="kw">as.character</span>(Year.Release), 
                          <span class="dt">breaks =</span> Year.Release)<span class="op">+</span>
<span class="st">         </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year Wise Log Global Sales by Genre&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">         </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-467-1.png" width="672" /></p>
<p>In total the golden years are from 2007 to 2009 for most of these Genres. Action keeps on the top sale for all those years. Strategy is on the bottom sale list.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(scales )
 <span class="co"># reorder according to the length per Genre, to make the plots look beautiful and keep axis y stable </span>
game<span class="op">$</span>Genre. &lt;-<span class="st"> </span><span class="kw">with</span>(game, <span class="kw">reorder</span>(Genre, Genre, <span class="cf">function</span>(x) <span class="op">-</span><span class="kw">length</span>(x))) 
P0 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Genre., Global.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Genre.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">GlobalSales =</span> <span class="kw">sum</span>(Global.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(GlobalSales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p.GlobalSales =</span> GlobalSales<span class="op">/</span><span class="kw">sum</span>(GlobalSales) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span><span class="st">  </span><span class="co">#percentage in total Sales</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.GlobalSales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre., <span class="dt">y =</span> p.GlobalSales)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;purple&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()
P1 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Genre., NA.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Genre.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">NASales =</span> <span class="kw">sum</span>(NA.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(NASales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p.NASales =</span> NASales <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(NASales) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.NASales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre., <span class="dt">y =</span> p.NASales)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>())  
P2 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Genre.,EU.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Genre.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">EUSales =</span> <span class="kw">sum</span>(EU.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(EUSales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p.EUSales =</span> EUSales <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(EUSales) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.EUSales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre., <span class="dt">y =</span> p.EUSales)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>())
P3 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Genre., JP.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Genre.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">JPSales =</span> <span class="kw">sum</span>(JP.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(JPSales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p.JPSales =</span> JPSales <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(JPSales) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.JPSales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre., <span class="dt">y =</span> p.JPSales)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>())
P4 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Genre., Other.Sales) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Genre.) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">OtherSales =</span> <span class="kw">sum</span>(Other.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(OtherSales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">p.OtherSales =</span> OtherSales <span class="op">/</span><span class="st"> </span><span class="kw">sum</span>(OtherSales) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(p.OtherSales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre., <span class="dt">y =</span> p.OtherSales)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="st">&quot;green&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()<span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.title.y =</span> <span class="kw">element_blank</span>(), <span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>())
<span class="kw">library</span>(ggpubr)</code></pre></div>
<pre><code>## Loading required package: magrittr</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(magrittr)
<span class="kw">ggarrange</span>(P0, P1, P2, P3, P4, <span class="dt">ncol =</span> <span class="dv">5</span>, <span class="dt">nrow =</span> <span class="dv">1</span>, <span class="dt">widths =</span> <span class="kw">c</span>(<span class="fl">1.3</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-468-1.png" width="1152" /></p>
<p>Generally North America, Europe Sales and other sales follow the global Sales pattern. They all have Action, Sports and Shooter as top 3 genres, Puzzle, Adventure and Strategy as bottom 3 genres. Japan market is different from them. The Role-Playing gets the largest portion in Japan sales, while Shooter plays much less portion comparing with the other regions. Platform and Puzzle are popular in Japan than in other regions. As other regions, action and sports are still the most popular Genre in Japan.</p>
</div>
<div id="by-rating" class="section level3">
<h3><span class="header-section-number">14.5.4</span> 4) By Rating</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(Year.Release, Global.Sales, Rating) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Year.Release, Rating) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Year.Release, <span class="dt">y =</span> Total.Sales, <span class="dt">group =</span> Rating, <span class="dt">fill =</span> Rating)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_area</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;green&quot;</span>),
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(), <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="st">&quot;Year.Release&quot;</span>, <span class="dt">labels =</span> <span class="kw">as.character</span>(Year.Release), <span class="dt">breaks =</span> Year.Release) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Year Wise Global Sales by Rating&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_flip</span>()</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-469-1.png" width="672" /></p>
<p>Rating E and E10+ run the first two in global sales. Compare with E, E10+, M and T, the other rating sales were so little and even not show in our area figure. 2008 is a good year for all ratings. <img src="book_files/figure-html/unnamed-chunk-470-1.png" width="1152" /></p>
<p>The patterns for Rating are almost the same for different region sales and global sales. E is the biggest rating, then M and T, E10+ is the smallest in these four ratings. In Europe there is a little of bit of AO portion, while in Japan, some K-A games are released too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))
x &lt;-<span class="st"> </span>game[,<span class="dv">6</span><span class="op">:</span><span class="dv">10</span>]
<span class="kw">matplot</span>(<span class="kw">t</span>(x), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, <span class="dt">col =</span> <span class="kw">rainbow</span>(<span class="dv">9</span>)[game<span class="op">$</span>Rating])
<span class="kw">legend</span>(<span class="st">&quot;center&quot;</span>, <span class="kw">levels</span>(game<span class="op">$</span>Rating), <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">9</span>), <span class="dt">cex =</span> <span class="fl">0.8</span>, <span class="dt">pt.cex =</span> <span class="dv">1</span>)
<span class="kw">text</span>(<span class="kw">c</span>(<span class="fl">1.2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="fl">3.9</span>, <span class="fl">4.8</span>), <span class="dv">80000000</span>, <span class="kw">colnames</span>(x))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-471-1.png" width="1152" /></p>
<p>There is one E game which was mainly sold in North America and Europe which was really popular and produced a sale tale of over 80 millions’ global sale, while North America contributed half of the global sales. We can check the game data and know it’s Wii Sports released in 2006. We also noticed that M game is popular in North America(blue), which contributed a lot to global sales, E games(green) have good sale in Europe, while Japanese like T(red) And E(green) games. It’s balance in rating for “other” region.</p>
</div>
<div id="by-rating-genre" class="section level3">
<h3><span class="header-section-number">14.5.5</span> 5) By Rating &amp; Genre</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Rating, Global.Sales, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Rating, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre, <span class="dt">y =</span> Total.Sales, <span class="dt">fill =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;Identity&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>))</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-472-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggmosaic)
<span class="kw">ggplot</span>(game) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_mosaic</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">product</span>(Rating), <span class="dt">fill =</span> Platform.type), <span class="dt">na.rm=</span><span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Rating&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Platform Type&quot;</span>, <span class="dt">title=</span><span class="st">&quot;Mosaic Plot&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>())</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-473-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p1 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Rating, Global.Sales, Genre, User.Score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Rating, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales), <span class="dt">Avg.Score =</span> <span class="kw">mean</span>(User.Score)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">20</span>) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre, <span class="dt">y =</span> Total.Sales, <span class="dt">fill =</span> Rating)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;Identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;stack&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">8</span>, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">col=</span><span class="st">&quot;yellow&quot;</span>,<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">8</span>, <span class="dt">col=</span>Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">8</span>),<span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;black&quot;</span>),
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
        <span class="dt">panel.grid.minor =</span> <span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Global Sales&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;Rating&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Spectral&quot;</span>)
p2 &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(Rating, JP.Sales, Genre, User.Score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Rating, Genre) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(JP.Sales), <span class="dt">Avg.Score =</span> <span class="kw">mean</span>(User.Score)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">20</span>) <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Genre, <span class="dt">y =</span> Total.Sales, <span class="dt">fill =</span> Rating)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;Identity&quot;</span>,<span class="dt">position =</span> <span class="st">&quot;stack&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">7</span>, <span class="dt">group =</span> <span class="dv">1</span>), <span class="dt">col =</span> <span class="st">&quot;yellow&quot;</span>,<span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">y =</span> Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">7</span>, <span class="dt">col=</span>Avg.Score<span class="op">*</span><span class="dv">10</span><span class="op">^</span><span class="dv">7</span>),<span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;black&quot;</span>),
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
        <span class="dt">panel.grid.minor=</span><span class="kw">element_blank</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Genre&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;JP Sales&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;Rating&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Spectral&quot;</span>)
<span class="kw">grid.arrange</span>(p1, p2, <span class="dt">ncol =</span> <span class="dv">2</span>, <span class="dt">top =</span> <span class="st">&quot;Distribution of genre and rating for top sales&quot;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-474-1.png" width="960" /></p>
<p>For the top 20 sales of genre*rating combination, same as we discussed previously, Action, Shooter and Sports have biggest Global.Sales while Role-Playing and Action are sold better in Japan. Rating M contribute big portion in both Action and Shooter global sales, Rating E sports game are popular globally. In Japan, teenage play a lot of Role-Playing games, they also play part of action and fighting games. Almost half of Japan action games are rated as M and lots of other genre games are rated as E. In both sales plots, Role-Playing games got highest average user score.</p>
</div>
<div id="by-platform" class="section level3">
<h3><span class="header-section-number">14.5.6</span> 6) By Platform</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(viridis)</code></pre></div>
<pre><code>## Loading required package: viridisLite</code></pre>
<pre><code>## 
## Attaching package: &#39;viridis&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:scales&#39;:
## 
##     viridis_pal</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(scales)
p &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Platform.type, Year.Release) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">total =</span> <span class="kw">sum</span>(Global.Sales))
  p<span class="op">$</span>Year.Release. &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">as.character</span>(p<span class="op">$</span>Year.Release))
<span class="kw">ggplot</span>(p, <span class="kw">aes</span>(<span class="dt">x =</span> Year.Release., <span class="dt">fill =</span> Platform.type)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_density</span>(<span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of platform type and market share by released year&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Market Share&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_viridis</span>(<span class="dt">discrete =</span> <span class="ot">TRUE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">percent_format</span>()) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-475-1.png" width="672" /></p>
<p>Nintendo and xbox came after 1990. Before that pc and playstation occupied the game market, pc are the main platform at that time. After 1995, the portion of pc and playstation shrinked, while nintendo and xbox grew fast and took over more portion than playstation and pc in the market. Together with Nintendo and xbox, there were other game platform sprouting out in early 1990s, but they last for 20 years and dissapeared. From around 2010, the portions of these 4 platforms keep relatively evenly and stablly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Platform.type, Critic.Score) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Total.Sales =</span> <span class="kw">sum</span>(Global.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Total.Sales)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Total.Sales, <span class="dt">group =</span> Platform.type, <span class="dt">fill =</span> Platform.type)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">position =</span> <span class="st">&quot;fill&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.7</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">percent_format</span>()) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of platform type and market share by critical score&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Market Share&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">90</span>),
        <span class="dt">panel.background =</span> <span class="kw">element_rect</span>(<span class="dt">fill =</span> <span class="st">&quot;black&quot;</span>),
        <span class="dt">panel.grid.major =</span> <span class="kw">element_blank</span>(),
        <span class="dt">panel.grid.minor=</span><span class="kw">element_blank</span>())</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-476-1.png" width="672" /></p>
<p>*show year every 10 , sales 45 degree</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#library(ggiraph)</span>
<span class="kw">ggplot</span>(game, <span class="kw">aes</span>(Global.Sales, Year.Release)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Platform.type)) <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(<span class="op">~</span><span class="st"> </span>Rating) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Global Sales Vs. Year of Release by Rating&quot;</span>) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-477-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(game, <span class="kw">aes</span>(Global.Sales, Year.Release)) <span class="op">+</span><span class="st"> </span>
<span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> Platform.type)) <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(<span class="op">~</span><span class="st"> </span>Platform.type) <span class="op">+</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Global Sales Vs. Year of Release by Platform.type&quot;</span>) </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-477-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">game<span class="op">$</span>Platform.type &lt;-<span class="st"> </span><span class="kw">as.factor</span>(game<span class="op">$</span>Platform.type)
<span class="kw">ggplot</span>(game, <span class="kw">aes</span>(<span class="dt">x =</span> Platform.type, <span class="dt">y =</span> Global.Sales.Log, <span class="dt">fill =</span> Genre)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_boxplot</span>() </code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-478-1.png" width="1152" /></p>
<p>In total, PC have lower Global sales log comparing with other platform type, while palystation have more higher sale mediums for different genre. For Xbox, Shooter is the top sale genre, puzzle is not a popular; Misc genre contribute a lot for Nintendo, strategy is at the bottom of Nintendo sale log list. For nintendo and playstation, different genre keep balance in global sales log. Nintendo have several real high global sales for some games.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#compute 1-way ANOVA test forlog value of global sales by Platform Type</span>
model &lt;-<span class="st"> </span><span class="kw">aov</span>(Global.Sales.Log <span class="op">~</span><span class="st"> </span>Platform.type, <span class="dt">data =</span> game)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>##                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Platform.type    4   1283   320.8   181.2 &lt;2e-16 ***
## Residuals     6820  12077     1.8                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tukey &lt;-<span class="st"> </span><span class="kw">TukeyHSD</span>(model)
tukey</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Global.Sales.Log ~ Platform.type, data = game)
## 
## $Platform.type
##                             diff         lwr          upr     p adj
## others-nintendo      -0.24010322 -0.48731168  0.007105248 0.0617768
## pc-nintendo          -1.32914311 -1.49896515 -1.159321071 0.0000000
## playstation-nintendo  0.21083015  0.09556168  0.326098618 0.0000061
## xbox-nintendo         0.04846421 -0.08162001  0.178548439 0.8478736
## pc-others            -1.08903989 -1.35880736 -0.819272426 0.0000000
## playstation-others    0.45093337  0.21172262  0.690144113 0.0000028
## xbox-others           0.28856743  0.04187559  0.535259278 0.0123768
## playstation-pc        1.53997326  1.38201984  1.697926677 0.0000000
## xbox-pc               1.37760733  1.20853821  1.546676446 0.0000000
## xbox-playstation     -0.16236593 -0.27652224 -0.048209629 0.0009961</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">1</span>))
<span class="kw">plot</span>(tukey, <span class="dt">las =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-479-1.png" width="672" /></p>
<p>ANOVA test shows that there is at lease one of the platform type is significant different from the others. The plot of Turkey tests shows that there is significant difference between all other pairs of platform types but between xbox and nintendo, others and nintendo.</p>
</div>
</div>
<div id="analysis-for-numeric-matrix-heatmap-and-pca" class="section level2">
<h2><span class="header-section-number">14.6</span> Analysis for numeric matrix: Heatmap and PCA</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gplots)
<span class="co">#require(RColorBrewer)</span>
hclust2 &lt;-<span class="st"> </span><span class="cf">function</span>(x, ...)  <span class="co"># average linkage method</span>
  <span class="kw">hclust</span>(x, <span class="dt">method=</span><span class="st">&quot;average&quot;</span>, ...)
dist2 &lt;-<span class="st"> </span><span class="cf">function</span>(x, ...)  <span class="co">#distance method</span>
  <span class="kw">as.dist</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">cor</span>(<span class="kw">t</span>(x), <span class="dt">method=</span><span class="st">&quot;pearson&quot;</span>))

<span class="co"># Transform data, standardize</span>
st &lt;-<span class="st"> </span>game[, <span class="kw">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="op">:</span><span class="dv">23</span>)] 
st.matrix &lt;-<span class="st"> </span><span class="kw">as.matrix</span>(st)
s &lt;-<span class="st"> </span><span class="kw">apply</span>(st.matrix, <span class="dv">2</span>, <span class="cf">function</span>(y)(y <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(y)) <span class="op">/</span><span class="st"> </span><span class="kw">sd</span>(y))
a &lt;-<span class="st"> </span><span class="kw">heatmap.2</span>(s, 
        <span class="dt">distfun =</span> dist2,  <span class="co"># use 1-Pearson as distance</span>
        <span class="dt">hclustfun =</span> hclust2,  <span class="co"># use average linkage</span>
        <span class="dt">col =</span> <span class="kw">greenred</span>(<span class="dv">75</span>),   <span class="co">#color green red</span>
        <span class="dt">density.info =</span> <span class="st">&quot;none&quot;</span>, <span class="co"># turns off density plot inside color legend</span>
        <span class="dt">trace =</span> <span class="st">&quot;none&quot;</span>,  <span class="co"># turns off trace lines inside the heat map</span>
        <span class="dt">scale =</span> <span class="st">&quot;none&quot;</span>, 
        <span class="dt">RowSideColors =</span> <span class="kw">rainbow</span>(<span class="dv">5</span>)[<span class="kw">as.factor</span>(game<span class="op">$</span>Platform.type)],  
        <span class="dt">srtCol =</span> <span class="dv">45</span>,  <span class="co">#column labels at 45 degree</span>
        <span class="dt">margins =</span> <span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">6</span>), <span class="co"># bottom and right margins</span>
        <span class="dt">lhei =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">10</span>))
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="kw">levels</span>(<span class="kw">as.factor</span>(game<span class="op">$</span>Platform.type)), 
       <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">5</span>), <span class="dt">cex =</span> <span class="fl">0.8</span>)    <span class="co"># add legend </span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-480"></span>
<img src="book_files/figure-html/unnamed-chunk-480-1.png" alt="Heat map for whole game sales data set" width="576" />
<p class="caption">
Figure 14.1: Heat map for whole game sales data set
</p>
</div>
<p>The heat map clustered these columns into different groups, same as Cluster Dendrogram plot, all sales logs except JP.Sales.Log combined as one cluster, JP.Sales.Log together with tow count logs build another cluster, and two scores combined as another cluster; Also, we can find on the left side of the map, all observations are clustered into four middle clusters, then separated into two big clusters, each two middle clusters combined into one big clusters. PC and some playstation games gather together to build the second little cluster on the left bottom.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#rownames(st) = make.names(Name, unique=TRUE)</span>
pca =<span class="st"> </span><span class="kw">prcomp</span>(st, <span class="dt">scale =</span> T)  <span class="co">#scale = T to normalize the data</span>
<span class="kw">plot</span>(pca)  <span class="co"># plot the amount of variance each principal components captures.</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-481-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#str(pca)  # this shows the structure of the object, listing all parts.</span>
<span class="kw">summary</span>(pca)  <span class="co">#shows the importance of the components</span></code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2    PC3     PC4     PC5     PC6    PC7
## Standard deviation     1.8862 1.2623 1.0124 0.93400 0.80751 0.70404 0.6090
## Proportion of Variance 0.3953 0.1770 0.1139 0.09693 0.07245 0.05508 0.0412
## Cumulative Proportion  0.3953 0.5723 0.6862 0.78316 0.85561 0.91068 0.9519
##                            PC8     PC9
## Standard deviation     0.53487 0.38329
## Proportion of Variance 0.03179 0.01632
## Cumulative Proportion  0.98368 1.00000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">percentVar &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="dv">100</span> <span class="op">*</span><span class="st"> </span><span class="kw">summary</span>(pca)<span class="op">$</span>importance[<span class="dv">2</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>], <span class="dv">0</span>)  <span class="co"># compute % variances</span>
percentVar</code></pre></div>
<pre><code>## PC1 PC2 PC3 
##  40  18  11</code></pre>
<p>The first three components are 40%, 18% and 11%, together 69% of the variance. The first two components contribute 58% of the variance.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(pca<span class="op">$</span>x) <span class="co"># the new coordinate values for each observation</span></code></pre></div>
<pre><code>##            PC1        PC2       PC3        PC4       PC5        PC6
## [1,] -5.337840 -1.5425166 0.2148701 -0.9310124 0.9108405 -0.3403442
## [2,] -5.362199 -0.5974062 0.4825383 -0.8908894 0.5115049 -0.3116997
## [3,] -4.927962 -0.9618487 0.2311185 -0.9861267 0.5348391 -0.6280182
## [4,] -5.295960 -0.3242512 0.1013105 -0.9933864 0.6407655 -0.1718503
## [5,] -3.783444 -2.3065954 0.9632205 -1.1245323 1.0135062 -0.7365037
## [6,] -5.345388 -0.3008932 0.3339654 -0.9821817 0.3644934 -0.2868611
##             PC7         PC8       PC9
## [1,] 0.36945558  0.43170108 1.2721742
## [2,] 0.36577429  0.46022159 0.9140274
## [3,] 0.24775320 -0.05232101 0.9839195
## [4,] 0.45391170  0.06974085 0.7992214
## [5,] 0.09935275  0.40325747 1.0982611
## [6,] 0.44603528  0.20989323 0.8046071</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pcaData &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(pca<span class="op">$</span>x[, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]) <span class="co">#First and Second principal component value</span>
pcaData &lt;-<span class="st"> </span><span class="kw">cbind</span>(pcaData, game<span class="op">$</span>Platform.type)  <span class="co">#add platform type as third col. for cluster purpose</span>
<span class="kw">colnames</span>(pcaData) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;PC1&quot;</span>, <span class="st">&quot;PC2&quot;</span>, <span class="st">&quot;Platform&quot;</span>)
<span class="kw">ggplot</span>(pcaData, <span class="kw">aes</span>(PC1, PC2, <span class="dt">color =</span> Platform, <span class="dt">shape =</span> Platform)) <span class="op">+</span><span class="st">  </span>
<span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="fl">0.8</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="kw">paste0</span>(<span class="st">&quot;PC1: &quot;</span>, percentVar[<span class="dv">1</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="op">+</span><span class="st">  </span><span class="co"># x label</span>
<span class="st">  </span><span class="kw">ylab</span>(<span class="kw">paste0</span>(<span class="st">&quot;PC2: &quot;</span>, percentVar[<span class="dv">2</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="op">+</span><span class="st">  </span><span class="co"># y label</span>
<span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Principal component analysis (PCA)&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="co"># title</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">aspect.ratio =</span> <span class="dv">1</span>)  <span class="co"># width and height ratio</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-482-1.png" width="672" /></p>
<p>PC, xbox, playstation and nintendo occupy in their own positions in the PCA figure, which illustrate that they play different important role in components of the variance of PC1 and PC2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">123</span>)
<span class="co"># Compute and plot wss for k = 2 to k = 15 to find the best k for clusters</span>
<span class="co">#The elbow method looks at the percentage of variance explained as a function of the number of clusters :https://www.r-bloggers.com/finding-optimal-number-of-clusters/</span>
<span class="co">#iter.max=15 to ensure the algorithm converges and nstart=50 to ensure that at least 50 random sets are choosen  </span>
k.max &lt;-<span class="st"> </span><span class="dv">15</span>
scaled_data =<span class="st"> </span><span class="kw">as.matrix</span>(<span class="kw">scale</span>(st)) <span class="co"># Scale and center data, as matrix</span>
wss &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span>k.max, 
              <span class="cf">function</span>(k){<span class="kw">kmeans</span>(scaled_data, k, <span class="dt">nstart =</span> <span class="dv">50</span>, <span class="dt">iter.max =</span> <span class="dv">15</span> )<span class="op">$</span>tot.withinss})
<span class="kw">plot</span>(<span class="dv">1</span><span class="op">:</span>k.max, wss,
     <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>, <span class="dt">pch =</span> <span class="dv">19</span>, <span class="dt">frame =</span> <span class="ot">FALSE</span>, 
     <span class="dt">xlab =</span> <span class="st">&quot;Number of clusters K&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Total within-clusters sum of squares&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-483"></span>
<img src="book_files/figure-html/unnamed-chunk-483-1.png" alt="Kmeans figure using ggfortify" width="672" />
<p class="caption">
Figure 14.2: Kmeans figure using ggfortify
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#library(mclust)</span>
<span class="co">#d_clust &lt;- Mclust(as.matrix(scaled_data), G=1:15, </span>
                  <span class="co">#modelNames = mclust.options(&quot;emModelNames&quot;))</span>
<span class="co">#d_clust$BIC</span>
<span class="co">#plot(d_clust)</span>
<span class="co">#library(NbClust)</span>
<span class="co">#nb &lt;- NbClust(scaled_data, diss=NULL, distance = &quot;euclidean&quot;, </span>
             <span class="co"># min.nc=2, max.nc=5, method = &quot;kmeans&quot;, </span>
              <span class="co">#index = &quot;all&quot;, alphaBeale = 0.1)</span>

<span class="kw">library</span>(ggfortify)
<span class="kw">set.seed</span>(<span class="dv">1</span>)
<span class="kw">autoplot</span>(<span class="kw">kmeans</span>(st, <span class="dv">3</span>), <span class="dt">data =</span> st, <span class="dt">label =</span> <span class="ot">FALSE</span>, <span class="dt">label.size =</span> <span class="fl">0.1</span>)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-483"></span>
<img src="book_files/figure-html/unnamed-chunk-483-2.png" alt="Kmeans figure using ggfortify" width="672" />
<p class="caption">
Figure 14.2: Kmeans figure using ggfortify
</p>
</div>
<p>From the wss plot we find the best k for our data st is 2. Kmeans plot, as similar as PCA plot, explains PC1 44% and PC2 26%, altogether 66% of variance. It separate the games into two different color clusters. Each cluster is located in two different areas. This match the heat map that two middle clusters combined into one big cluster, and there are two big clusters in total. Together with PCA figure, we will find that top of the first cluster is contributed mainly by pc, and some playstation, and a little bit of nintendo; Bottom of the first cluster is contributed mainly by xbox and platstation, and some nintendo too. Top of second cluster is built by xbox and nintendo, there are some playstation and others platform too. Bottom of second cluster is related to nintendo, playstation and xbox evenly.</p>
<p>library(cluster) autoplot(fanny(pcaData, 3), frame = TRUE)</p>
</div>
<div id="models-for-global-sales" class="section level2">
<h2><span class="header-section-number">14.7</span> Models for Global Sales</h2>
<p>Because there are two many of levels in Publisher and Developer, and there are apparent correlation between them, we use only top ten levels of Publisher and classified the other publishers as “Others”; Because of the good correlation between Critic.Score and User.Score, we use only critic score; Same reason, we will not put “other.sale.log” in our model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#re-categorize publisher into 13 groups</span>
Publisher. &lt;-<span class="st"> </span><span class="kw">head</span>(<span class="kw">names</span>(<span class="kw">sort</span>(<span class="kw">table</span>(game<span class="op">$</span>Publisher), <span class="dt">decreasing =</span> <span class="ot">TRUE</span>)), <span class="dv">12</span>)
game &lt;-<span class="st"> </span>game <span class="op">%&gt;%</span>
<span class="kw">mutate</span>(<span class="dt">Publisher.type =</span> <span class="kw">ifelse</span>(Publisher <span class="op">%in%</span><span class="st"> </span>Publisher., <span class="kw">as.character</span>(Publisher), <span class="st">&quot;Others&quot;</span>)) 
game.log &lt;-<span class="st"> </span>game[, <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">16</span>, <span class="dv">21</span><span class="op">:</span><span class="dv">25</span>, <span class="dv">29</span>)]
game.log<span class="op">$</span>Genre.type &lt;-<span class="st"> </span><span class="kw">as.factor</span>(game.log<span class="op">$</span>Genre.type)
game.log<span class="op">$</span>Publisher.type &lt;-<span class="st"> </span><span class="kw">as.factor</span>(game.log<span class="op">$</span>Publisher.type)
<span class="kw">summary</span>(game.log)</code></pre></div>
<pre><code>##   Year.Release   Critic.Score     User.Score     Rating    
##  2008   : 592   Min.   :1.300   Min.   :0.500   AO  :   1  
##  2007   : 590   1st Qu.:6.200   1st Qu.:6.500   E   :2082  
##  2005   : 562   Median :7.200   Median :7.500   E10+: 930  
##  2009   : 550   Mean   :7.027   Mean   :7.186   K-A :   1  
##  2006   : 528   3rd Qu.:8.000   3rd Qu.:8.200   M   :1433  
##  2003   : 498   Max.   :9.800   Max.   :9.600   RP  :   1  
##  (Other):3505                                   T   :2377  
##  Global.Sales.Log Critic.Count.Log User.Count.Log      Platform.type 
##  Min.   : 9.21    Min.   :1.099    Min.   :1.386   nintendo   :1535  
##  1st Qu.:11.61    1st Qu.:2.639    1st Qu.:2.398   others     : 251  
##  Median :12.58    Median :3.219    Median :3.296   pc         : 651  
##  Mean   :12.58    Mean   :3.125    Mean   :3.588   playstation:2806  
##  3rd Qu.:13.53    3rd Qu.:3.664    3rd Qu.:4.489   xbox       :1582  
##  Max.   :18.23    Max.   :4.727    Max.   :9.275                     
##                                                                      
##             Genre.type                       Publisher.type
##  Action/Adventure:2590   Others                     :2566  
##  Combat          :1242   Electronic Arts            : 944  
##  Sports          : 943   Ubisoft                    : 496  
##  Racing          : 581   Activision                 : 492  
##  Platform        : 403   Sony Computer Entertainment: 316  
##  Strategy        : 385   THQ                        : 307  
##  (Other)         : 681   (Other)                    :1704</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(game.log)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    6825 obs. of  10 variables:
##  $ Year.Release    : Factor w/ 25 levels &quot;1985&quot;,&quot;1988&quot;,..: 15 17 18 15 15 18 14 16 19 18 ...
##  $ Critic.Score    : num  7.6 8.2 8 8.9 5.8 8.7 9.1 8 6.1 8 ...
##  $ User.Score      : num  8 8.3 8 8.5 6.6 8.4 8.6 7.7 6.3 7.4 ...
##  $ Rating          : Factor w/ 7 levels &quot;AO&quot;,&quot;E&quot;,&quot;E10+&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ Global.Sales.Log: num  18.2 17.4 17.3 17.2 17.2 ...
##  $ Critic.Count.Log: num  3.93 4.29 4.29 4.17 3.71 ...
##  $ User.Count.Log  : num  5.77 6.56 5.26 6.07 4.86 ...
##  $ Platform.type   : Factor w/ 5 levels &quot;nintendo&quot;,&quot;others&quot;,..: 1 1 1 1 1 1 1 1 5 1 ...
##  $ Genre.type      : Factor w/ 8 levels &quot;Action/Adventure&quot;,..: 7 5 7 4 3 4 5 7 3 7 ...
##  $ Publisher.type  : Factor w/ 13 levels &quot;Activision&quot;,&quot;Atari&quot;,..: 7 7 7 7 7 7 7 7 8 7 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Global.Sales.Log <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> game.log)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ ., data = game.log)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8649 -0.5731  0.0201  0.5895  4.2732 
## 
## Coefficients:
##                                            Estimate Std. Error t value
## (Intercept)                                10.71640    1.30807   8.193
## Year.Release1988                           -3.29954    1.30632  -2.526
## Year.Release1992                           -1.74762    1.30549  -1.339
## Year.Release1994                            3.13785    1.30664   2.401
## Year.Release1996                            1.84430    0.99838   1.847
## Year.Release1997                            1.25844    0.95925   1.312
## Year.Release1998                            0.84769    0.94314   0.899
## Year.Release1999                            0.71424    0.93989   0.760
## Year.Release2000                            0.80687    0.92881   0.869
## Year.Release2001                            0.79390    0.92604   0.857
## Year.Release2002                            0.59258    0.92533   0.640
## Year.Release2003                            0.36996    0.92518   0.400
## Year.Release2004                            0.53724    0.92528   0.581
## Year.Release2005                            0.19977    0.92506   0.216
## Year.Release2006                            0.11858    0.92505   0.128
## Year.Release2007                            0.36392    0.92495   0.393
## Year.Release2008                            0.51766    0.92501   0.560
## Year.Release2009                            0.42851    0.92499   0.463
## Year.Release2010                            0.57568    0.92523   0.622
## Year.Release2011                            0.37861    0.92527   0.409
## Year.Release2012                           -0.01031    0.92586  -0.011
## Year.Release2013                           -0.14424    0.92634  -0.156
## Year.Release2014                           -0.35679    0.92645  -0.385
## Year.Release2015                           -0.45103    0.92664  -0.487
## Year.Release2016                           -0.82241    0.92651  -0.888
## Critic.Score                                0.14093    0.01234  11.419
## User.Score                                 -0.05743    0.01055  -5.443
## RatingE                                    -0.56818    0.92470  -0.614
## RatingE10+                                 -0.62424    0.92462  -0.675
## RatingK-A                                  -1.44761    1.35963  -1.065
## RatingM                                    -1.05089    0.92406  -1.137
## RatingRP                                   -0.02935    1.30711  -0.022
## RatingT                                    -0.91178    0.92421  -0.987
## Critic.Count.Log                            0.09882    0.02240   4.412
## User.Count.Log                              0.57620    0.01299  44.344
## Platform.typeothers                        -0.17891    0.06643  -2.693
## Platform.typepc                            -2.43384    0.05246 -46.398
## Platform.typeplaystation                    0.12782    0.03398   3.761
## Platform.typexbox                          -0.13423    0.03764  -3.567
## Genre.typeCombat                            0.04058    0.03311   1.226
## Genre.typeMisc                              0.45990    0.05285   8.701
## Genre.typePlatform                         -0.06325    0.05311  -1.191
## Genre.typeRacing                            0.01118    0.04654   0.240
## Genre.typeSimulation                        0.52613    0.05929   8.874
## Genre.typeSports                            0.10473    0.04550   2.302
## Genre.typeStrategy                         -0.33057    0.05318  -6.216
## Publisher.typeAtari                        -0.50153    0.08214  -6.106
## Publisher.typeCapcom                       -0.72436    0.07885  -9.187
## Publisher.typeElectronic Arts              -0.11366    0.05342  -2.128
## Publisher.typeKonami Digital Entertainment -0.67449    0.07323  -9.211
## Publisher.typeNamco Bandai Games           -0.55156    0.07421  -7.432
## Publisher.typeNintendo                      0.07571    0.07541   1.004
## Publisher.typeOthers                       -0.63418    0.04633 -13.689
## Publisher.typeSega                         -0.51815    0.06973  -7.431
## Publisher.typeSony Computer Entertainment  -0.60272    0.06972  -8.644
## Publisher.typeTake-Two Interactive         -0.26543    0.07111  -3.733
## Publisher.typeTHQ                          -0.08086    0.06848  -1.181
## Publisher.typeUbisoft                      -0.36278    0.05929  -6.118
##                                            Pr(&gt;|t|)    
## (Intercept)                                3.03e-16 ***
## Year.Release1988                           0.011565 *  
## Year.Release1992                           0.180723    
## Year.Release1994                           0.016357 *  
## Year.Release1996                           0.064748 .  
## Year.Release1997                           0.189598    
## Year.Release1998                           0.368794    
## Year.Release1999                           0.447327    
## Year.Release2000                           0.385032    
## Year.Release2001                           0.391305    
## Year.Release2002                           0.521932    
## Year.Release2003                           0.689255    
## Year.Release2004                           0.561512    
## Year.Release2005                           0.829032    
## Year.Release2006                           0.898006    
## Year.Release2007                           0.694002    
## Year.Release2008                           0.575755    
## Year.Release2009                           0.643193    
## Year.Release2010                           0.533830    
## Year.Release2011                           0.682418    
## Year.Release2012                           0.991113    
## Year.Release2013                           0.876263    
## Year.Release2014                           0.700165    
## Year.Release2015                           0.626461    
## Year.Release2016                           0.374766    
## Critic.Score                                &lt; 2e-16 ***
## User.Score                                 5.43e-08 ***
## RatingE                                    0.538943    
## RatingE10+                                 0.499615    
## RatingK-A                                  0.287046    
## RatingM                                    0.255474    
## RatingRP                                   0.982088    
## RatingT                                    0.323896    
## Critic.Count.Log                           1.04e-05 ***
## User.Count.Log                              &lt; 2e-16 ***
## Platform.typeothers                        0.007092 ** 
## Platform.typepc                             &lt; 2e-16 ***
## Platform.typeplaystation                   0.000171 ***
## Platform.typexbox                          0.000364 ***
## Genre.typeCombat                           0.220393    
## Genre.typeMisc                              &lt; 2e-16 ***
## Genre.typePlatform                         0.233697    
## Genre.typeRacing                           0.810107    
## Genre.typeSimulation                        &lt; 2e-16 ***
## Genre.typeSports                           0.021378 *  
## Genre.typeStrategy                         5.42e-10 ***
## Publisher.typeAtari                        1.08e-09 ***
## Publisher.typeCapcom                        &lt; 2e-16 ***
## Publisher.typeElectronic Arts              0.033403 *  
## Publisher.typeKonami Digital Entertainment  &lt; 2e-16 ***
## Publisher.typeNamco Bandai Games           1.20e-13 ***
## Publisher.typeNintendo                     0.315459    
## Publisher.typeOthers                        &lt; 2e-16 ***
## Publisher.typeSega                         1.21e-13 ***
## Publisher.typeSony Computer Entertainment   &lt; 2e-16 ***
## Publisher.typeTake-Two Interactive         0.000191 ***
## Publisher.typeTHQ                          0.237709    
## Publisher.typeUbisoft                      9.99e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.921 on 6767 degrees of freedom
## Multiple R-squared:  0.5704, Adjusted R-squared:  0.5667 
## F-statistic: 157.6 on 57 and 6767 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">aov</span>(Global.Sales.Log <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> game.log)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>##                    Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Year.Release       24    521    21.7   25.59  &lt; 2e-16 ***
## Critic.Score        1   1747  1747.0 2059.58  &lt; 2e-16 ***
## User.Score          1     34    34.5   40.65 1.94e-10 ***
## Rating              6     86    14.3   16.82  &lt; 2e-16 ***
## Critic.Count.Log    1   1120  1119.8 1320.08  &lt; 2e-16 ***
## User.Count.Log      1    561   561.3  661.74  &lt; 2e-16 ***
## Platform.type       4   2914   728.6  858.93  &lt; 2e-16 ***
## Genre.type          7    237    33.8   39.88  &lt; 2e-16 ***
## Publisher.type     12    400    33.3   39.29  &lt; 2e-16 ***
## Residuals        6767   5740     0.8                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Global sales is mostly effected by factors of platform type, user count log, critic score, and Publisher type in glm analysis. ANOVA shows every factors are included in the contribution, critic score and it’s count log are the most important factors.</p>
<p>Critic score and User.Count.Log positively affect the global sales log. Platform types and publisher types either lift or pull down the global sales according to their types. This model will explain the global sales log with R-Square of 0.57.</p>
<p>Because of the curve smooth line at global sale ~ critic score plot in our previous analysis and its big contribution in linear model analysis, We try a polynomial fit (degree 4) of critic score only.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Global.Sales.Log <span class="op">~</span><span class="st"> </span>
<span class="st">           </span>Critic.Score <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Critic.Score<span class="op">^</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Critic.Score<span class="op">^</span><span class="dv">3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Critic.Score<span class="op">^</span><span class="dv">4</span>),  <span class="dt">data =</span> game.log)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ Critic.Score + I(Critic.Score^2) + 
##     I(Critic.Score^3) + I(Critic.Score^4), data = game.log)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.0029 -0.7972  0.0916  0.8801  5.6201 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       12.030638   1.468428   8.193 3.02e-16 ***
## Critic.Score      -0.840810   1.095444  -0.768   0.4428    
## I(Critic.Score^2)  0.385671   0.292104   1.320   0.1868    
## I(Critic.Score^3) -0.060971   0.033147  -1.839   0.0659 .  
## I(Critic.Score^4)  0.003434   0.001358   2.528   0.0115 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.281 on 6820 degrees of freedom
## Multiple R-squared:  0.1623, Adjusted R-squared:  0.1618 
## F-statistic: 330.4 on 4 and 6820 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The first two levels are not statistically significant, we try the third and fourth levels only.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(Global.Sales.Log <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(Critic.Score<span class="op">^</span><span class="dv">3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(Critic.Score<span class="op">^</span><span class="dv">4</span>),  <span class="dt">data =</span> game.log)
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ I(Critic.Score^3) + I(Critic.Score^4), 
##     data = game.log)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8634 -0.7892  0.0950  0.8837  5.5807 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        1.193e+01  7.115e-02 167.722  &lt; 2e-16 ***
## I(Critic.Score^3) -2.989e-03  7.972e-04  -3.749 0.000179 ***
## I(Critic.Score^4)  6.076e-04  8.224e-05   7.387 1.67e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.283 on 6822 degrees of freedom
## Multiple R-squared:  0.1597, Adjusted R-squared:  0.1595 
## F-statistic: 648.3 on 2 and 6822 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In total, the coefficients are statistically significant, the model of two levels of critic score itself will explain the data with R square 0.16.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testFunc &lt;-<span class="st"> </span><span class="cf">function</span>(x) {model<span class="op">$</span>coefficients[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>x<span class="op">*</span>x<span class="op">*</span>x<span class="op">*</span>model<span class="op">$</span>coefficients[<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span>x<span class="op">*</span>x<span class="op">*</span>x<span class="op">*</span>x<span class="op">*</span>model<span class="op">$</span>coefficients[<span class="dv">3</span>]}
<span class="kw">ggplot</span>(<span class="dt">data =</span> game.log, <span class="kw">aes</span>(<span class="dt">x =</span> Critic.Score, <span class="dt">y =</span> Global.Sales.Log)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> testFunc, <span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Meta Critic Score&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Global Sales Log&#39;</span>)</code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-488-1.png" width="672" /></p>
<p>Here is the scatter plot of Global.Sales.Log ~ Critic Score and the model line which predict the global sales log.</p>
</div>
<div id="conclusion-1" class="section level2">
<h2><span class="header-section-number">14.8</span> Conclusion</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exploring-of-state-data-set.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exploring-of-employee-salary-data-set.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
