<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Step into R programming:The iris flower dataset | Learn R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Step into R programming:The iris flower dataset | Learn R through examples" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Step into R programming:The iris flower dataset | Learn R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  

<meta name="author" content="Xijin Ge, Jianli Qi, and Rong Fan" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="visualizing-the-iris-flower-data-set.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R programming:The iris flower dataset</a>
<ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting started</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-proper-way-of-using-rstudio"><i class="fa fa-check"></i><b>1.2</b> The proper way of using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.3</b> Data frames contain rows and columns: the iris flower dataset</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.4</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable"><i class="fa fa-check"></i><b>1.5</b> Analyzing a categorical variable</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables"><i class="fa fa-check"></i><b>1.6</b> The relationship between two numerical variables</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups"><i class="fa fa-check"></i><b>1.7</b> Testing the differences between two groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-differences-among-multiple-groups-anova"><i class="fa fa-check"></i><b>1.8</b> Testing differences among multiple groups (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html"><i class="fa fa-check"></i><b>2</b> Visualizing the iris flower data set</a>
<ul>
<li class="chapter" data-level="2.1" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#star-and-segment-diagrams"><i class="fa fa-check"></i><b>2.3</b> Star and segment diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#the-ggplot2-package-is-intuitive-and-powerful"><i class="fa fa-check"></i><b>2.4</b> The ggplot2 package is intuitive and powerful</a></li>
<li class="chapter" data-level="2.5" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#other-types-of-plots-with-ggplot2"><i class="fa fa-check"></i><b>2.5</b> Other types of plots with ggplot2</a></li>
<li class="chapter" data-level="2.6" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#hierarchical-clustering-and-heat-map"><i class="fa fa-check"></i><b>2.6</b> Hierarchical clustering and heat map</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.7</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#logistic-regression-for-binary-outcomes-prediction"><i class="fa fa-check"></i><b>2.8</b> Logistic Regression for Binary Outcomes Prediction</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#seeking-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Seeking help and example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.2</b> Matrices</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.5</b> Lists</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html"><i class="fa fa-check"></i><b>4</b> Importing data and managing files</a>
<ul>
<li class="chapter" data-level="4.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#project-oriented-workflow"><i class="fa fa-check"></i><b>4.1</b> Project-oriented workflow</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-project-in-a-new-folder"><i class="fa fa-check"></i><b>4.1.1</b> Create a project in a new folder</a></li>
<li class="chapter" data-level="4.1.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-script-file-and-comment-please"><i class="fa fa-check"></i><b>4.1.2</b> Create a script file (and Comment, Please!)</a></li>
<li class="chapter" data-level="4.1.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#copy-data-files-to-the-new-directory"><i class="fa fa-check"></i><b>4.1.3</b> Copy data files to the new directory</a></li>
<li class="chapter" data-level="4.1.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#import-data-files"><i class="fa fa-check"></i><b>4.1.4</b> Import data files</a></li>
<li class="chapter" data-level="4.1.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#check-and-convert-data-types"><i class="fa fa-check"></i><b>4.1.5</b> Check and convert data types</a></li>
<li class="chapter" data-level="4.1.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#close-a-project-when-you-are-done"><i class="fa fa-check"></i><b>4.1.6</b> Close a project when you are done</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#read-files-directly-using-read.table"><i class="fa fa-check"></i><b>4.2</b> Read files directly using read.table</a></li>
<li class="chapter" data-level="4.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.3</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#enter-data-manually"><i class="fa fa-check"></i><b>4.4</b> Enter data manually</a></li>
<li class="chapter" data-level="4.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-transformation-using-the-dplyr"><i class="fa fa-check"></i><b>4.6</b> Data transformation using the dplyr</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> The heart attack data set (I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-individually"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column individually</a></li>
<li class="chapter" data-level="5.2" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns</a></li>
<li class="chapter" data-level="5.3" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables</a></li>
<li class="chapter" data-level="5.4" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables</a></li>
<li class="chapter" data-level="5.5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html"><i class="fa fa-check"></i><b>6</b> The heart attack dataset (II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#statistical-models-easy-to-run-tricky-to-interpret"><i class="fa fa-check"></i><b>6.5</b> Statistical models: Easy to Run, tricky to interpret!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>7.1</b> Introduction to R Markdown</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> Tidyverse</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package"><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
<li class="chapter" data-level="7.4.4" data-path="advanced-topics.html"><a href="advanced-topics.html#publish-your-app"><i class="fa fa-check"></i><b>7.4.4</b> Publish your app</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-topics.html"><a href="advanced-topics.html#define-your-own-function"><i class="fa fa-check"></i><b>7.5</b> Define your own function</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="state-dataset.html"><a href="state-dataset.html"><i class="fa fa-check"></i><b>8</b> State dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="state-dataset.html"><a href="state-dataset.html#data-import-and-manipulation"><i class="fa fa-check"></i><b>8.1</b> Data Import and Manipulation</a></li>
<li class="chapter" data-level="8.2" data-path="state-dataset.html"><a href="state-dataset.html#visualizing-data"><i class="fa fa-check"></i><b>8.2</b> Visualizing data</a></li>
<li class="chapter" data-level="8.3" data-path="state-dataset.html"><a href="state-dataset.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="state-dataset.html"><a href="state-dataset.html#the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> The whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="state-dataset.html"><a href="state-dataset.html#linear-model-analysis"><i class="fa fa-check"></i><b>8.5</b> Linear model analysis</a></li>
<li class="chapter" data-level="8.6" data-path="state-dataset.html"><a href="state-dataset.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html"><i class="fa fa-check"></i><b>9</b> The game sales dataset</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#reading-in-data-and-managing-the-dataset"><i class="fa fa-check"></i><b>9.1</b> Reading in data and managing the dataset</a></li>
<li class="chapter" data-level="9.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#effect-of-platform-type-on-principle-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type on principle components</a></li>
<li class="chapter" data-level="9.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html"><i class="fa fa-check"></i><b>10</b> The messy salary data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#data-preparation-and-cleaning"><i class="fa fa-check"></i><b>10.1</b> Data Preparation and Cleaning</a></li>
<li class="chapter" data-level="10.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#variable-analysis"><i class="fa fa-check"></i><b>10.2</b> Variable Analysis</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income-types"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income types</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#defining-gross-income-types"><i class="fa fa-check"></i><b>10.4.1</b> Defining Gross income types</a></li>
<li class="chapter" data-level="10.4.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#the-intersection-of-ethnic-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> The Intersection of Ethnic, Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learn R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="step-into-r-programmingthe-iris-flower-dataset" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Step into R programming:The iris flower dataset<a href="step-into-r-programmingthe-iris-flower-dataset.html#step-into-r-programmingthe-iris-flower-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Learning objectives:</p>
<ul>
<li>Utilize R via <a href="https://rstudio.cloud/">Rstudio Cloud</a> or through a local installation.</li>
<li>Familiarize yourself with the RStudio interface, including Console, Script, Environment, Plots panels.</li>
<li>Understand and manipulate data frames and vectors.</li>
<li>Master the basics workflow: importing data, checking data types, defining vectors from columns, and data through plotting.</li>
</ul>
<div id="getting-started" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Getting started<a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>1. Using RStudio Cloud:</strong></p>
<p>R and RStudio are accessible through a web browser via <a href="https://rstudio.cloud/">Rstudio
Cloud</a>. You can create a free account, or simply log in using your Google account. Begin by clicking the <strong>New Project</strong> button.</p>
<p><strong>2. Local Installation:</strong></p>
<p>Alternatively, you can install R on your laptop from <a href="https://cloud.r-project.org/">www.R-project.org</a>. Then install RStudio Desktop from
<a href="https://www.rstudio.com/products/rstudio/download/#download">www.RStudio.com</a>. If you’re using older versions of R or Rstudio, it’s wise to uninstall them, delete the folder containing R packages, and install the latest versions for an optimal experience.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:Rinterface"></span>
<img src="images/img0100_Rstudio.png" alt="Interface of RStudio." width="80%" />
<p class="caption">
Figure 1.1: Interface of RStudio.
</p>
</div>
<p>RStudio uses R in the background but provides a more user-friendly interface. R
commands can be typed directly into the “Console” window, as shown in Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:Rinterface">1.1</a>.</p>
<p>For a quick demonstration, try executing the following commands in the Console window.
Remember, R is case-sensitive: “Species” and “species” are two different variables.
If these commands seem like a breeze, perhaps this book is too basic for you.
Consider exploring more advanced books like <a href="https://r4ds.had.co.nz/">R for Data Science</a>.
Conversely, if typing these 248 characters feels like a multi-month project, consider a typing tutorial at <a href="www.RapidTyping.com">www.RapidTyping.com</a>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-1" tabindex="-1"></a><span class="fu">head</span>(iris)</span>
<span id="cb1-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-2" tabindex="-1"></a><span class="fu">str</span>(iris)</span>
<span id="cb1-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-3" tabindex="-1"></a><span class="fu">summary</span>(iris)</span>
<span id="cb1-4"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb1-5"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-5" tabindex="-1"></a><span class="fu">boxplot</span>(df)</span>
<span id="cb1-6"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-6" tabindex="-1"></a><span class="fu">pairs</span>(df)</span>
<span id="cb1-7"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-7" tabindex="-1"></a><span class="fu">stars</span>(df)</span>
<span id="cb1-8"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-8" tabindex="-1"></a></span>
<span id="cb1-9"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-9" tabindex="-1"></a>PL <span class="ot">&lt;-</span> df<span class="sc">$</span>Petal.Length</span>
<span id="cb1-10"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-10" tabindex="-1"></a><span class="fu">barplot</span>(PL)</span>
<span id="cb1-11"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-11" tabindex="-1"></a><span class="fu">hist</span>(PL)</span>
<span id="cb1-12"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-12" tabindex="-1"></a>SP <span class="ot">&lt;-</span> iris<span class="sc">$</span>Species</span>
<span id="cb1-13"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-13" tabindex="-1"></a><span class="fu">pie</span>(<span class="fu">table</span>(SP))</span>
<span id="cb1-14"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-14" tabindex="-1"></a><span class="fu">boxplot</span>(PL <span class="sc">~</span> SP)</span>
<span id="cb1-15"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-15" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(PL <span class="sc">~</span> SP))</span>
<span id="cb1-16"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-16" tabindex="-1"></a></span>
<span id="cb1-17"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-17" tabindex="-1"></a>PW <span class="ot">&lt;-</span> df<span class="sc">$</span>Petal.Width</span>
<span id="cb1-18"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-18" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, <span class="at">col =</span> SP)</span>
<span id="cb1-19"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb1-19" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(PW <span class="sc">~</span> PL))</span></code></pre></div>
<div class="float">
<img src="https://github.com/gexijin/learnR/raw/master/images/demo.gif" alt="Animated GIF for screen shot." />
<div class="figcaption">Animated GIF for screen shot.</div>
</div>
</div>
<div id="the-proper-way-of-using-rstudio" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> The proper way of using RStudio<a href="step-into-r-programmingthe-iris-flower-dataset.html#the-proper-way-of-using-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p><strong>Create a project</strong>: In RStudio, a project serves as a convenient means to organize your work. For each new research project, we put all related files (source code, data, results) into a designated folder. On RStudio.cloud, this is a must for starting an R session.
Click the <strong>Untitled Project</strong> on the top of the window to rename it as something meaningful, such as “Workshop”. For local R users, navigate to <strong>File</strong> in the main menu, select <strong>New Project</strong>, then follow the instructions to choose or create a new folder.</p></li>
<li><p><strong>Create a script file</strong>: Begin by going to <strong>File &gt; New File &gt; R Script</strong>, or by clicking on the green plus icon. Instead of directly typing commands into the console window, we will use the <strong>R Script</strong> window. This allows us to save our work. To execute one line of code, simply click anywhere on the line and then click the <strong>Run</strong> button. You can also execute a block of code by highlighting it and clicking Run. For practice, type these two lines into the Script window, save the script as ‘Workshop_script.R’. Then click each line and <strong>Run</strong> from the icon. After that, highlight both lines and click <strong>Run</strong>.</p></li>
</ol>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb2-1" tabindex="-1"></a><span class="fu">head</span>(iris)</span>
<span id="cb2-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb2-2" tabindex="-1"></a><span class="fu">plot</span>(iris)</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li><strong>Copy file into project folder</strong>: To integrate the dataset into your project, download it from
<a href="https://raw.githubusercontent.com/gexijin/learnR/master/datasets/iris.csv">GitHub</a> and save it as ‘iris.csv’.</li>
</ol>
</div>
<div id="data-frames-contain-rows-and-columns-the-iris-flower-dataset" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Data frames contain rows and columns: the iris flower dataset<a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In 1936, Edgar Anderson collected data on [<em>iris</em> flowers] to quantify the geographic variations
(<a href="https://en.wikipedia.org/wiki/iris_flower_data_set" class="uri">https://en.wikipedia.org/wiki/iris_flower_data_set</a>).
The dataset includes 50 samples from each of the three
sub-species ( <em>iris setosa</em>, <em>iris virginica,</em> and <em>iris versicolor</em>), with measurements in centimeters (cm) for lengths and widths of sepals and petals. This is one of many built-in datasets in R. You can also <strong>download</strong> the dataset from
<a href="https://raw.githubusercontent.com/gexijin/learnR/master/datasets/iris.csv">GitHub</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="images/img0101_iris.png" alt="iris flower. Photo from Wikipedia." width="50%" />
<p class="caption">
Figure 1.2: iris flower. Photo from Wikipedia.
</p>
</div>
<p>If you are using <a href="https://rstudio.cloud/">Rstudio Cloud</a> through a web browser,
remember that it operates on cloud-based servers. This means you cannot directly access
local files, and must first upload them using the <strong>Upload</strong> button in the <strong>Files</strong>
tab of the lower right panel.</p>
<p>To <strong>import</strong> the dataset into R, go to <strong>Import Dataset</strong> in the <strong>File</strong> menu, then
select <strong>“From Text(base)…”</strong>. The default settings should suffice; just click
<strong>Import</strong> in the pop-up window. Thankfully, importing data in R isn’t a lengthy process like in some other software(says SAS). If you have trouble with importing, skip this step as this dataset is already included in R.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="images/img0102_dataframe.png" alt="Example of a data frame." width="80%" />
<p class="caption">
Figure 1.3: Example of a data frame.
</p>
</div>
<p>Let’s open the dataset in Excel for a quick review. Think about what distinguishes the three species. Imagine you find an iris flower with sepals of 6.5cm long by 3.0cm wide, and petals of 6.2cm long by 2.2cm wide. Which species do you think it belongs to? <strong>Think</strong> (!) for a few minutes while eyeballing the data in Excel. Write down your guess about the species. Getting familiar with this dataset is crucial for this chapter and those that follow.</p>
<p>To answer these questions, let’s visualize and analyze the data with R. <strong>Type the commands, omit those marked by “#”</strong>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb3-1" tabindex="-1"></a><span class="fu">View</span>(iris) <span class="co"># View as a spreadsheet</span></span></code></pre></div>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb4-1" tabindex="-1"></a><span class="fu">head</span>(iris) <span class="co"># Display the first few rows</span></span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb6-1" tabindex="-1"></a><span class="fu">class</span>(iris) <span class="co"># Reveal the data type</span></span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb8-1" tabindex="-1"></a><span class="fu">str</span>(iris) <span class="co"># Expose the structure</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>The imported data is stored in a <strong>data frame</strong> named <em>iris</em>, which contains
information for 150 observations (flowers) across 5 variables. The first 4 variables/columns,
<em>Sepal.Length</em>, <em>Sepal.Width</em>, <em>Petal.Length</em>, and <em>Petal.Width</em>, are <strong>numeric</strong>.
The 5<sup>th</sup> variable/column, <em>Species</em>, consists of <strong>character</strong> strings indicating the sub-species of each sample. It’s important to note that numeric and character data are treated differently in R. Sometimes we need to overwrite data types guessed by R, which can be done during the data importing process. If you are using the built-in iris data, the variable/column <em>Species</em> is a <strong>factor</strong> with three levels.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb10-1" tabindex="-1"></a><span class="fu">summary</span>(iris) <span class="co"># Provide summary statistics</span></span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>The <em>summary</em> function offers insights into the distribution of each variables, highlighting that there are 50 observations for each of the three subspecies.</p>
<p>Individual values in a <strong>data frame</strong> can be accessed using row and column indices.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb12-1" tabindex="-1"></a>iris[<span class="dv">3</span>, <span class="dv">4</span>] <span class="co"># Value at row 3 and column 4</span></span>
<span id="cb12-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb12-2" tabindex="-1"></a>iris[<span class="dv">3</span>, ] <span class="co"># All values in row 3</span></span>
<span id="cb12-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb12-3" tabindex="-1"></a>iris[, <span class="dv">4</span>] <span class="co"># All values in column 4</span></span>
<span id="cb12-4"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb12-4" tabindex="-1"></a>iris[<span class="dv">3</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>] <span class="co"># Values in row 3 for columns 1 to 4</span></span></code></pre></div>
<p><strong>To do the exercises, you need to start with a blank Word document. Copy-and-paste the R code and corresponding outputs into the document, then save it as both a Word and a PDF file. Submit these files to the Dropbox.</strong></p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-9}</p>
</blockquote>
<blockquote>

</blockquote>
<p>Type <strong>data()</strong> in the R Console window. The pop-up window - “R data sets” - contains all built-in data sets in package <strong>datasets</strong>. Choose a data set whose structure is data frame, then answer the following questions:</p>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Display the first few rows of the data set. <strong>NOT</strong> the entire set.<br />
</li>
<li>Show the dimensions of the data set.<br />
</li>
<li>Extract a subset containing values from rows 2 to 5 and columns 1 to 4. Choose another data set if yours has fewer rows or columns.
:::</li>
</ol>
</blockquote>
<p>Feel free to replace the <strong>iris</strong> data set with any of the built-in data sets as long as it’s a <strong>data frame</strong>. Make sure to check the type of the data set using <strong>class()</strong> or <strong>str()</strong> function. Note that you will need to change the variable names and row/column ranges accordingly.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb13-1" tabindex="-1"></a><span class="fu">colnames</span>(iris) <span class="co"># Display column names</span></span></code></pre></div>
<pre><code>## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot;  &quot;Species&quot;</code></pre>
<p>Memorize these column names; they are essential for our analysis. We can retrieve an entire column by using the data frame name followed by the column name. For example, sepal length information is under the column <strong>Sepal.Length</strong>. Be mindful that R is case-sensitive; a term like “iris$petal.length” will not be recognized.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb15-1" tabindex="-1"></a>iris<span class="sc">$</span>Petal.Length <span class="co"># Display 150 petal lengths</span></span></code></pre></div>
<p>To minimize typing, let’s store the data in a new <strong>vector</strong> named PL.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb16-1" tabindex="-1"></a>PL <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Length <span class="co"># Store Petal.Length values in a new vector</span></span></code></pre></div>
<p>Someone might complain that nothing happens after typing in this command. Actually, you have already created a new <strong>vector</strong> called PL in the memory. You can find it in the <strong>Environment</strong> tab in the top right panel. Programming mainly involves creating and modifying data objects in memory.
<img src="images/environment.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Like withdrawing money saved in a bank, these data can be retrieved and used.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb17-1" tabindex="-1"></a>PL  <span class="co"># Output the 150 numbers stored in PL</span></span></code></pre></div>
<pre><code>##   [1] 1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
##  [19] 1.7 1.5 1.7 1.5 1.0 1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
##  [37] 1.3 1.4 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.0
##  [55] 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.0 4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.0
##  [73] 4.9 4.7 4.3 4.4 4.8 5.0 4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.0
##  [91] 4.4 4.6 4.0 3.3 4.2 4.2 4.2 4.3 3.0 4.1 6.0 5.1 5.9 5.6 5.8 6.6 4.5 6.3
## [109] 5.8 6.1 5.1 5.3 5.5 5.0 5.1 5.3 5.5 6.7 6.9 5.0 5.7 4.9 6.7 4.9 5.7 6.0
## [127] 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
## [145] 5.7 5.2 5.0 5.2 5.4 5.1</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb19-1" tabindex="-1"></a><span class="fu">mean</span>(PL)  <span class="co"># Calculate the mean. Pretty straightforward!</span></span></code></pre></div>
<pre><code>## [1] 3.758</code></pre>
<blockquote>
<p>::: {.exercise #unnamed-chunk-15}</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Calculate the mean of the sepal length in the data set <strong>iris</strong>.<br />
</li>
<li>Find the mean of speed in the built-in data set <strong>cars</strong>.
:::</li>
</ol>
</blockquote>
<p>The best way to discover and learn R functions is through a Google search. The R community is incredibly supportive. Websites like <a href="https://stackoverflow.com/">StackOverflow.com</a> are treasure troves for code examples and answers to even the most basic questions.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-16}</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Look up “R square root function” on Google, then compute the value of <span class="math inline">\(\sqrt{56.7}\)</span>.<br />
</li>
<li>Find the maximum value of the variable <em>mpg</em> in the data set <strong>mtcars</strong>.
:::</li>
</ol>
</blockquote>
</div>
<div id="analyzing-one-set-of-numbers" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Analyzing one set of numbers<a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A <strong>vector</strong> in R holds a series of numbers or characters, and R’s diverse <strong>functions</strong> make it simple to perform calculations (like addition, subtraction, multiplication, etc.) on these elements, either individually or collectively.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb21-1" tabindex="-1"></a><span class="fu">summary</span>(PL)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.600   4.350   3.758   5.100   6.900</code></pre>
<p>The <strong>summary</strong> function provides a detailed overview of the petal length distribution:</p>
<ul>
<li><p>The minimum is 1.000, while the maximum reaches 6.900.</p></li>
<li><p>The average petal length stands at 3.758.</p></li>
<li><p>The mid-point, or median, at 4.350, indicates that half the values are smaller than this. Ever wonder why the median and mean differ? Imagine if there’s a typo and a petal length is erroneously entered as 340cm instead of 3.40cm. That would skew things quite a bit!</p></li>
<li><p>The 3rd quartile, or 75<sup>th</sup> percentile, is 5.100, meaning 75% of the petals are shorter than this. Conversely, a student ranked 5th in a class of 25 would be in the 80th percentile. The minimum is the 0<sup>th</sup> percentile and the maximum is the 100<sup>th</sup> percentile.</p></li>
<li><p>The 1st quartile, or 25<sup>th</sup> percentile, is at 1.600, indicating that Only 25% of the flowers have
petals shorter than this.</p></li>
</ul>
<p>These summary statistics are visually represented in a boxplot (Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:1-3">1.4</a>A). Boxplots are particularly useful when comparing multiple data sets.</p>

<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb23-1" tabindex="-1"></a><span class="fu">boxplot</span>(PL) <span class="co"># Boxplot of Petal Length.</span></span>
<span id="cb23-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb23-2" tabindex="-1"></a><span class="fu">boxplot</span>(iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]) <span class="co"># Boxplots of four columns of iris.</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:1-3"></span>
<img src="book_files/figure-html/1-3-1.png" alt="Boxplot of petal length (A) and of all 4 columns (B)." width="50%" /><img src="book_files/figure-html/1-3-2.png" alt="Boxplot of petal length (A) and of all 4 columns (B)." width="50%" />
<p class="caption">
Figure 1.4: Boxplot of petal length (A) and of all 4 columns (B).
</p>
</div>
<p>In RStudio, you can copy a plot to the clipboard using the <strong>Export</strong> button on
top of the plot area. Or you can click <strong>zoom</strong>, right-click on the pop-up plot,
and select <strong>“Copy Image”</strong>. Then you can paste the plot into Word.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-18}</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Check the data structure of the built-in data set <strong>mtcars</strong>.<br />
</li>
<li>Create a boxplot of Mile Per Gallon (<em>mpg</em>) in <strong>mtcars</strong>.
:::</li>
</ol>
</blockquote>
<p>To quantify the variance, we compute the <strong>standard deviation</strong> σ as follows:
<span class="math display">\[\begin{align}
σ=\sqrt{\frac{1}{N-1}[(x_{1}-\bar x)^2+(x_{2}-\bar x)^2+...+(x_{N}-\bar x)^2]}    
\end{align}\]</span>
where N is the sample size and <span class="math inline">\(\bar{x}\)</span> is the mean:
<span class="math display">\[\begin{align}
\bar x=\frac{1}{N}(x_{1}+x_{2}+\cdots+x_{N})

\end{align}\]</span>
A small standard deviation implies that the measurements cluster closely around the mean.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb24-1" tabindex="-1"></a><span class="fu">sd</span>(PL) <span class="co"># Standard deviation of Petal Length</span></span></code></pre></div>
<pre><code>## [1] 1.765298</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb26-1" tabindex="-1"></a>SW <span class="ot">&lt;-</span> iris<span class="sc">$</span>Sepal.Width</span>
<span id="cb26-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb26-2" tabindex="-1"></a><span class="fu">sd</span>(SW) <span class="co"># Standard deviation of Sepal Width</span></span></code></pre></div>
<pre><code>## [1] 0.4358663</code></pre>
<p>The results suggest that these flowers have similar sepal width but exhibit significant variation in
petal length, as indicated by the boxplot above. This variation might be an adaptation survival in different habitats.</p>
<p>With R, it is straightforward to generate graphs.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb28-1" tabindex="-1"></a><span class="fu">barplot</span>(PL) <span class="co"># Bar plot of Petal Length</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-20"></span>
<img src="book_files/figure-html/unnamed-chunk-20-1.png" alt="Barplot of petal length." width="80%" />
<p class="caption">
Figure 1.5: Barplot of petal length.
</p>
</div>
<p>This bar plot suggests that the first 50 flowers (iris setosa) have much shorter
petals than the other two species, and the last 50 flowers (iris virginica) have
slightly longer petals than iris versicolor.</p>

<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb29-1" tabindex="-1"></a><span class="fu">plot</span>(PL) <span class="co"># Scatter plot</span></span>
<span id="cb29-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb29-2" tabindex="-1"></a><span class="fu">hist</span>(PL) <span class="co"># Histogram</span></span>
<span id="cb29-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb29-3" tabindex="-1"></a><span class="fu">lag.plot</span>(PL) <span class="co"># Lag plot</span></span>
<span id="cb29-4"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb29-4" tabindex="-1"></a><span class="fu">qqnorm</span>(PL) <span class="co"># Q-Q plot for normal distribution</span></span>
<span id="cb29-5"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb29-5" tabindex="-1"></a><span class="fu">qqline</span>(PL) <span class="co">#Add the regression line</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:1-4"></span>
<img src="book_files/figure-html/1-4-1.png" alt="Scatter plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-2.png" alt="Scatter plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-3.png" alt="Scatter plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-4.png" alt="Scatter plot, histogram, lag plot and normal Q-Q plot." width="50%" />
<p class="caption">
Figure 1.6: Scatter plot, histogram, lag plot and normal Q-Q plot.
</p>
</div>
<p>In the scatter plot, three distinct groups are apparent, with one group having much smaller petal lengths.</p>
<p>Histogram shows the distribution of data by plotting the frequency of data in bins.
Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:1-4">1.6</a> reveals that there are more flowers with Petal Length between 1 cm and 1.5 cm. It also indicates that the data does not show a bell-curved distribution.</p>
<p>The lag plot is a scatter plot against the same set of number with an offset of
1. Any structure in a lag plot indicates non-randomness in the order in which
the data is presented. We can clearly see three clusters, indicating that
values are centered around three levels sequentially.</p>
<p>Q-Q (quantile-quantile) plots are used to check if data follows a normal distribution, a pre-requisite for many statistical methods. Quantiles of the data are compared against those in a normal distribution. If the data points on a Q-Q plot form a straight line, the data likely adheres to a normal distribution. See Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:1-5">1.7</a> for an example.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-21}</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Run x = rnorm(500) to generate 500 random numbers following the Standard Normal distribution.<br />
</li>
<li>Generate scatter plot, histogram, lag plot, and Q-Q plot of these numbers. Your plots should resemble those in Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:1-5">1.7</a>.<br />
:::</li>
</ol>
</blockquote>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:1-5"></span>
<img src="book_files/figure-html/1-5-1.png" alt="Plots for randomly generated numbers following a normal distribution." width="50%" /><img src="book_files/figure-html/1-5-2.png" alt="Plots for randomly generated numbers following a normal distribution." width="50%" /><img src="book_files/figure-html/1-5-3.png" alt="Plots for randomly generated numbers following a normal distribution." width="50%" /><img src="book_files/figure-html/1-5-4.png" alt="Plots for randomly generated numbers following a normal distribution." width="50%" />
<p class="caption">
Figure 1.7: Plots for randomly generated numbers following a normal distribution.
</p>
</div>
<blockquote>
<p>::: {.exercise #unnamed-chunk-22}</p>
</blockquote>
<blockquote>
<p>Create scatter plot, histogram, lag plot, and Q-Q plot for the Septal Length in the iris dataset.
:::</p>
</blockquote>
<p>A one-sample t-test is ideal for testing the mean of a normally distributed data.
Suppose the pental length of the species <em>setosa</em>, the first 50 observations of <em>PL</em>,
follows a normal distribution. We aim to test if its mean is different from 1.5 cm at the significance level of <span class="math inline">\(\alpha = 0.05\)</span>.
Here is the code to perform this test:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb30-1" tabindex="-1"></a><span class="fu">t.test</span>(PL[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>], <span class="at">mu =</span> <span class="fl">1.5</span>) <span class="co"># Two-sided t-test for the mean petal length of setosa</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  PL[1:50]
## t = -1.5472, df = 49, p-value = 0.1282
## alternative hypothesis: true mean is not equal to 1.5
## 95 percent confidence interval:
##  1.412645 1.511355
## sample estimates:
## mean of x 
##     1.462</code></pre>
<p>In this case, our null hypothesis is that the mean petal length of <em>setosa</em> is 1.5 cm.
Since p-value 0.1282 is greater than the significance level 0.05,
there is no strong evidence to reject the null hypothesis.
This function also provides the 95% confidence interval for the mean.
Based on our sample of the 50 observations, we are 95% confident that the actual mean petal length of setosa (if we were to measure all setosa in the world) lies between 1.412645 cm and 1.511355 cm.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-24}</p>
</blockquote>
<blockquote>
<p>Compute the 95% confidence interval for the sepal length of setosa.
:::</p>
</blockquote>
<p>Hypothesis testing can also determine whether a set of numbers is derived from normal distribution.
It’s crucial to clearly state the null hypothesis when interpreting results. Here the null hypothesis is that the data comes from a normal distribution.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb32-1" tabindex="-1"></a><span class="co"># Normality test </span></span>
<span id="cb32-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb32-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(PL)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  PL
## W = 0.87627, p-value = 7.412e-10</code></pre>
<p>Given the test statistic of 0.87627, the chance that the petal length is normally distributed is only 7.412×10<sup>-10</sup>. In other words, it is highly unlikely that the petal length follows a normal distribution. We reject the normal distribution hypothesis, corroborating our earlier plots.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb34-1" tabindex="-1"></a><span class="co"># Normality test of the first 50 observations of PL</span></span>
<span id="cb34-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb34-2" tabindex="-1"></a><span class="fu">shapiro.test</span>(PL[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>])</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  PL[1:50]
## W = 0.95498, p-value = 0.05481</code></pre>
<p>With a p-value of 0.05481, slightly above the threshold of <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. This indicates that we don’t have sufficient evidence to refute the claim that the petal length of setosa follows a normal distribution.</p>
<p>In statistics, combining graphical insights with statistical models leads to well-rounded conclusions.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-27}</p>
</blockquote>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Conduct Shapiro’s test on sepal width. Does it follow a normal distribution given the significant level <span class="math inline">\(\alpha = 0.05\)</span>?<br />
</li>
<li>Generate histogram and Q-Q plot for sepal width. Do these plots show a normal distribution?<br />
:::</li>
</ol>
</blockquote>
</div>
<div id="analyzing-a-categorical-variable" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Analyzing a categorical variable<a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the iris dataset, the species information in the last column is what we call a <strong>categorical variable</strong>.
Bar and Pie charts are excellent for displaying proportions. In this case, they display equal representation of the three species, with 50 observations each.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb36-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(iris<span class="sc">$</span>Species) <span class="co"># Tabulate the frequencies</span></span>
<span id="cb36-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb36-2" tabindex="-1"></a>counts</span></code></pre></div>
<pre><code>## 
##     setosa versicolor  virginica 
##         50         50         50</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb38-1" tabindex="-1"></a><span class="fu">pie</span>(counts) <span class="co"># Create a pie chart</span></span>
<span id="cb38-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb38-2" tabindex="-1"></a><span class="fu">barplot</span>(counts) <span class="co"># Generate a bar plot</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="book_files/figure-html/unnamed-chunk-28-1.png" alt="Frequencies of categorical values visualized by Pie chart (A) and bar chart (B)." width="50%" /><img src="book_files/figure-html/unnamed-chunk-28-2.png" alt="Frequencies of categorical values visualized by Pie chart (A) and bar chart (B)." width="50%" />
<p class="caption">
Figure 1.8: Frequencies of categorical values visualized by Pie chart (A) and bar chart (B).
</p>
</div>
</div>
<div id="the-relationship-between-two-numerical-variables" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> The relationship between two numerical variables<a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Scatter plot is very effective in visualizing the correlation between two numerical variables.</p>

<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb39-1" tabindex="-1"></a>PW <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Width <span class="co"># Shortcut for petal width</span></span>
<span id="cb39-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb39-2" tabindex="-1"></a><span class="fu">plot</span>(PW, PL) <span class="co"># Scatter plot of petal width vs petal length</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:2-1"></span>
<img src="book_files/figure-html/2-1-1.png" alt="Scatter plot of petal width and petal length." width="80%" />
<p class="caption">
Figure 1.9: Scatter plot of petal width and petal length.
</p>
</div>
<p>Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:2-1">1.9</a> shows that there is a positive correlation between petal
length and width. This implies that flowers with longer petals are also
wider, suggesting a proportional increase in both dimensions.</p>
<p>Another unusual feature is that there seem to be two distinct clusters. Do the
points in the small cluster represent one particular species of iris? To explore
this, we can color-code the species in the plot. The resultant Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:2-2">1.10</a> clearly demonstrates that one particular species, <em>setosa</em> forms the smaller cluster in
the low left corner. The other two species, while not as distinctly separated, also exhibit a notable differences. This insight is crucial for understanding the dataset.</p>

<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb40-1" tabindex="-1"></a>SP <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(iris<span class="sc">$</span>Species)</span>
<span id="cb40-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb40-2" tabindex="-1"></a><span class="fu">plot</span>(PW, PL, <span class="at">col =</span> SP) <span class="co"># Colors based on Species</span></span>
<span id="cb40-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb40-3" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="fu">levels</span>(SP), <span class="at">fill =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="co"># Add legends on top left.</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:2-2"></span>
<img src="book_files/figure-html/2-2-1.png" alt="Scatter plot showing the correlation of petal width and petal length." width="80%" />
<p class="caption">
Figure 1.10: Scatter plot showing the correlation of petal width and petal length.
</p>
</div>
<p>To enable species-based color coding, we defined a new variable SP by converting the last column into a <strong>factor</strong>. The function <strong>str(SP)</strong> shows that the SP is a factor with 3 levels, internally coded as 1, 2, and 3, which we use for color coding. This method of base plotting in R has been simplified by
modern systems such as ggplot2, which we will discuss later. So it’s not necessary to remember any of these steps.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb41-1" tabindex="-1"></a><span class="fu">str</span>(SP) <span class="co"># Display the structure of Species.</span></span></code></pre></div>
<pre><code>##  Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>The variation in petal length might be an adaptation to different environments. For instance, <em>setosa</em>, with the smallest petals, is typically found in Arctic
regions. <em>versicolor</em> is often found in the Eastern United States and
Eastern Canada. While <em>virginica</em> is common along the coastal plain from Florida
to Georgia in the Southeastern United States–<em>Wikipedia</em>.” It appears that the iris
flowers in warmer places are much larger than those in colder ones. R makes graph creation easy, but interpreting these graphs in context still requires thoughtful analysis.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-30}</p>
</blockquote>
<blockquote>
<p>Explore the <strong>mtcars</strong> dataset available at: <a href="https://stat.ethz.ch/R-manual/R-patched/RHOME/library/datasets/html/mtcars.html">https://stat.ethz.ch/R-manual/R-patched/RHOME/library/datasets/html/mtcars.html</a>. Create a scatter plot to analyze the correlation between Miles/(US) gallon and Displacement (cu.in.). Since the type of cyl is numeric, you will need to use function newcyl -&gt; as.factor(cyl) to convert it into factor. Replace all ‘mtcars$cyl’ with ‘newcyl’.</p>
<ol style="list-style-type: lower-alpha">
<li>Color-code the scatter plot by the Number of cylinders;</li>
<li>Include a legend to the top right corner.
:::</li>
</ol>
</blockquote>
<p>We can quantitatively measure the strength of a correlation using metrics like Pearson’s correlation coefficient, which ranges from -1 to 1. A value of zero signifies no linear correlation.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb43-1" tabindex="-1"></a><span class="fu">cor</span>(PW, PL)</span></code></pre></div>
<pre><code>## [1] 0.9628654</code></pre>
<p>This outcome indicates a strong, positive correlation between petal width and petal length. To visually represent this on a plot, we can add a text annotation:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb45-1" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">1.5</span>, <span class="fl">1.5</span>, <span class="fu">paste</span>(<span class="st">&quot;R=0.96&quot;</span>))</span></code></pre></div>
<p>A correlation test can further assess the statistical significance of the correlation:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb46-1" tabindex="-1"></a><span class="fu">cor.test</span>(PW, PL)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  PW and PL
## t = 43.387, df = 148, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9490525 0.9729853
## sample estimates:
##       cor 
## 0.9628654</code></pre>
<p>This test allows us to reject the null hypothesis that the true correlation is zero (no correlation), which indicates that the correlation is statistically significant. It’s worth noting that Pearson’s coefficient can be influenced by outliers, and alternatives like Spearman’s coefficient may be used for more robust analysis. For more information, consult the help documentation:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb48-1" tabindex="-1"></a>?cor <span class="co"># Display help information for the cor() function</span></span></code></pre></div>
<p>Regression analysis can further reveal the relationship between petal length and width using an equation. We consider a linear model:</p>
<p><span class="math inline">\(Petal.Length = \alpha × Petal.Width + c + \epsilon\)</span>,</p>
<p>where <span class="math inline">\(\alpha\)</span> is the slope parameter, <span class="math inline">\(c\)</span> is a constant, and <span class="math inline">\(\epsilon\)</span> represents random error. This model can be established using a least squared-error method:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb49-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(PL <span class="sc">~</span> PW) <span class="co"># Linear Model (lm)</span></span>
<span id="cb49-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb49-2" tabindex="-1"></a><span class="fu">summary</span>(model) <span class="co"># Display model details</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = PL ~ PW)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.33542 -0.30347 -0.02955  0.25776  1.39453 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.08356    0.07297   14.85   &lt;2e-16 ***
## PW           2.22994    0.05140   43.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4782 on 148 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9266 
## F-statistic:  1882 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the regression model, the tilde(~) links a response variable on the left with one or more independent variables on the right side. We are defining a statistical model where PL is modeled as a function of PW.
Our analysis estimates <span class="math inline">\(\alpha=2.22944\)</span> and <span class="math inline">\(c=1.08356\)</span>, with both parameters significantly
different from zero (p-values&lt;2×10<sup>-16</sup>) in both cases. Consequently, we can reliably predict the petal length with the equation:</p>
<p><span class="math inline">\(Petal.Length = 2.22944 × Petal.Width + 1.08356\)</span>.</p>
<p>Formulas like this are also used in plots. This model can be visualized on a scatter plot as a regression line:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb51-1" tabindex="-1"></a><span class="fu">abline</span>(model) <span class="co"># Add the regression line to plot</span></span></code></pre></div>
<p>To analyze the model’s accuracy and assumptions, diagnostic plots are useful:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb52-1" tabindex="-1"></a><span class="fu">plot</span>(model) <span class="co"># Diagnostic plots for regression</span></span></code></pre></div>
<p>Regression analysis is a powerful tool for examining the significance of relationships between variables.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-38}</p>
</blockquote>
<blockquote>
<p>Investigate the relationship between sepal length and sepal width using scatter plots,
correlation coefficients, test of correlation, and linear regression.
Again interpret all your results in clear and straightforward English.
:::</p>
</blockquote>
</div>
<div id="testing-the-differences-between-two-groups" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Testing the differences between two groups<a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In research, we often encounter questions like “Are boys taller than girls of the same age?” To address such queries, we analyze a random <strong>sample</strong> from a <strong>population</strong> to determine if observed differences between two groups reflect actual population differences or are merely due to random sampling errors.</p>

<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb53-1" tabindex="-1"></a>Species <span class="ot">&lt;-</span> iris<span class="sc">$</span>Species</span>
<span id="cb53-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb53-2" tabindex="-1"></a><span class="co"># Compare distributions of petal length for the three species via boxplot</span></span>
<span id="cb53-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb53-3" tabindex="-1"></a><span class="fu">boxplot</span>(PL <span class="sc">~</span> Species)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-39"></span>
<img src="book_files/figure-html/unnamed-chunk-39-1.png" alt="Boxplot of petal length, grouped by species." width="80%" />
<p class="caption">
Figure 1.11: Boxplot of petal length, grouped by species.
</p>
</div>
<p>Here, R automatically splits the dataset into three groups based on species and creates a boxplot for each. The boxplot clearly shows that <em>Setosa</em> has much shorter petals. But are the differences between <em>versicolor</em> and <em>virginica</em> statistically significant? Despite our limited sample size of 50 flowers per species, we seek to draw broader conclusions. We could measure all the iris flowers across the world or <strong>use statistical inference</strong>. Let’s extract corresponding data.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb54-1" tabindex="-1"></a>PL1 <span class="ot">&lt;-</span> PL[<span class="dv">51</span><span class="sc">:</span><span class="dv">100</span>] <span class="co"># Petal Length of versicolor</span></span>
<span id="cb54-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb54-2" tabindex="-1"></a>PL1 </span>
<span id="cb54-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb54-3" tabindex="-1"></a>PL2 <span class="ot">&lt;-</span> PL[<span class="dv">101</span><span class="sc">:</span><span class="dv">150</span>] <span class="co"># Petal length of virginica</span></span>
<span id="cb54-4"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb54-4" tabindex="-1"></a>PL2 </span></code></pre></div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb55-1" tabindex="-1"></a><span class="fu">boxplot</span>(PL1, PL2) <span class="co"># Boxplot of the two groups</span></span>
<span id="cb55-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb55-2" tabindex="-1"></a><span class="fu">t.test</span>(PL1, PL2) <span class="co"># Two-sample t-test</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  PL1 and PL2
## t = -12.604, df = 95.57, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.49549 -1.08851
## sample estimates:
## mean of x mean of y 
##     4.260     5.552</code></pre>
<p>In this two sample t-test, our null hypothesis states that the mean petal length for <em>versicolor</em> is the same as for <em>virginica</em>. The small p-value of 2.2x10<sup>-16</sup> indicates that it is extremely unlikely to observe the difference of 1.292cm through random sampling. Hence, we reject this hypothesis and conclude that the means for the two species are significantly different. If we measure all <em>versicolor</em> and <em>virginica</em> flowers in the world and compute their average petal lengths, it is very likely that the two averages are different. Conversely, a p-value larger than a chosen significance level, let’s say <span class="math inline">\(\alpha = 0.05\)</span>, would imply insufficient evidence to reject the hypothesis of equal means.</p>
<p>Interestingly, we do not need separate data objects for a t-test. It can be performed directly within the dataframe, with R separateing data points by columns.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb57-1" tabindex="-1"></a><span class="co"># Extract observations of species versicolor which are lined at rows from 51 to 150</span></span>
<span id="cb57-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb57-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> iris[<span class="dv">51</span><span class="sc">:</span><span class="dv">150</span>, ]</span>
<span id="cb57-3"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb57-3" tabindex="-1"></a><span class="fu">t.test</span>(Petal.Length <span class="sc">~</span> Species, <span class="at">data =</span> df) <span class="co"># t-test within the data frame</span></span>
<span id="cb57-4"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb57-4" tabindex="-1"></a><span class="fu">boxplot</span>(Petal.Length <span class="sc">~</span> Species, <span class="at">data =</span> <span class="fu">droplevels</span>(df)) <span class="co"># Boxplot with adjusted species levels</span></span></code></pre></div>
<blockquote>
<p>::: {.exercise #unnamed-chunk-43}</p>
</blockquote>
<blockquote>
<p>Use boxplot and t-test to investigate whether there are significant differences in
sepal width between <em>versicolor</em> and <em>virginica</em>. Interpret your results.
:::</p>
</blockquote>
</div>
<div id="testing-differences-among-multiple-groups-anova" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Testing differences among multiple groups (ANOVA)<a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-differences-among-multiple-groups-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As indicated in Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:2-5">1.12</a>, sepal width variation across species is small. We aim to determine if the mean sepal widths for the 3 species are equal. This is a perfect task for Analysis of Variance (ANOVA).</p>

<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb58-1" tabindex="-1"></a>SW <span class="ot">&lt;-</span> iris<span class="sc">$</span>Sepal.Width</span>
<span id="cb58-2"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb58-2" tabindex="-1"></a><span class="fu">boxplot</span>(SW <span class="sc">~</span> SP)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:2-5"></span>
<img src="book_files/figure-html/2-5-1.png" alt="Boxplot of sepal width across 3 species." width="672" />
<p class="caption">
Figure 1.12: Boxplot of sepal width across 3 species.
</p>
</div>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="step-into-r-programmingthe-iris-flower-dataset.html#cb59-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(SW <span class="sc">~</span> SP))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## SP            2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>With the p-value significantly below 0.05, we reject the null hypothesis, concluding that not all the 3 species share the same mean sepal width. The boxplot in Figure <a href="step-into-r-programmingthe-iris-flower-dataset.html#fig:2-5">1.12</a> suggests that <em>setosa</em> has wider sepals, though ANOVA only confirms that at least two species differ in mean sepal width, this is how the hypothesis was set up.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-44}</p>
</blockquote>
<blockquote>
<p>Explore if the mean spetal widths are the same across the 3 species using boxplot and ANOVA.
:::</p>
</blockquote>
<p>Hopefully, this chapter has given you a taste of what it’s like to use R for data visualization and analysis. It’s an interactive and graphical process. If I’ve made this seem overly complex, I apologize; that’s not my intention as an instructor. Many individuals can learn R independently by working on a small dataset of personal interest. The key is to Google everything and keep trying.</p>
<div class="float">
<img src="https://github.com/gexijin/learnR/raw/master/images/tenor_typing_cat.gif" alt="From Tenor.com" />
<div class="figcaption">From Tenor.com</div>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualizing-the-iris-flower-data-set.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
