<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Learning R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Learning R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Learning R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions welcome." />
  

<meta name="author" content="Xijin Ge">


<meta name="date" content="2019-02-19">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.8.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.39.2/plotly-latest.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Index</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R program-Analyzing iris flower dataset</a><ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#data-frames-have-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.1</b> Data frames have rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.2</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#students-t-test"><i class="fa fa-check"></i><b>1.3</b> Student’s t-test</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#test-for-normal-distribution"><i class="fa fa-check"></i><b>1.4</b> Test for normal distribution</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-a-column-of-categorical-values"><i class="fa fa-check"></i><b>1.5</b> Analyzing a column of categorical values</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#analyzing-the-relationship-between-two-columns-of-numbers"><i class="fa fa-check"></i><b>1.6</b> Analyzing the relationship between two columns of numbers</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#visualizing-and-testing-the-differences-in-groups"><i class="fa fa-check"></i><b>1.7</b> Visualizing and testing the differences in groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-program-analyzing-iris-flower-dataset.html"><a href="step-into-r-program-analyzing-iris-flower-dataset.html#testing-the-difference-among-multiple-groups-analysis-of-variance-anova"><i class="fa fa-check"></i><b>1.8</b> Testing the difference among multiple groups (Analysis of Variance: ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><i class="fa fa-check"></i><b>2</b> Visualizing data set-Analyzing cars and iris flower data sets</a><ul>
<li class="chapter" data-level="2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-mtcars-dataset"><i class="fa fa-check"></i><b>2.2</b> Visualizing mtcars dataset</a><ul>
<li class="chapter" data-level="2.2.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot"><i class="fa fa-check"></i><b>2.2.1</b> scatter plot</a></li>
<li class="chapter" data-level="2.2.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#barplot-with-error-bars"><i class="fa fa-check"></i><b>2.2.2</b> Barplot with error bars</a></li>
<li class="chapter" data-level="2.2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-correlation-between-categorical-variables"><i class="fa fa-check"></i><b>2.2.3</b> Visualizing correlation between categorical variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#detecting-correlations-among-variables"><i class="fa fa-check"></i><b>2.2.4</b> Detecting correlations among variables</a></li>
<li class="chapter" data-level="2.2.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#hierarchical-clustering"><i class="fa fa-check"></i><b>2.2.5</b> Hierarchical clustering</a></li>
<li class="chapter" data-level="2.2.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#representing-data-using-faces.-serious-scientific-research-only"><i class="fa fa-check"></i><b>2.2.6</b> Representing data using faces. Serious scientific research only!</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#visualizing-iris-data-set"><i class="fa fa-check"></i><b>2.3</b> Visualizing iris data set</a><ul>
<li class="chapter" data-level="2.3.1" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#a-matrix-only-contains-numbers"><i class="fa fa-check"></i><b>2.3.1</b> A Matrix only contains numbers</a></li>
<li class="chapter" data-level="2.3.2" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.3.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3.3" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#heatmap"><i class="fa fa-check"></i><b>2.3.3</b> Heatmap</a></li>
<li class="chapter" data-level="2.3.4" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#star-plot"><i class="fa fa-check"></i><b>2.3.4</b> Star plot</a></li>
<li class="chapter" data-level="2.3.5" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#segment-diagrams"><i class="fa fa-check"></i><b>2.3.5</b> Segment diagrams</a></li>
<li class="chapter" data-level="2.3.6" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#parallel-coordinate-plot"><i class="fa fa-check"></i><b>2.3.6</b> Parallel coordinate plot</a></li>
<li class="chapter" data-level="2.3.7" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#box-plot"><i class="fa fa-check"></i><b>2.3.7</b> Box plot</a></li>
<li class="chapter" data-level="2.3.8" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#bar-plot-with-error-bar"><i class="fa fa-check"></i><b>2.3.8</b> Bar plot with error bar</a></li>
<li class="chapter" data-level="2.3.9" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#combining-plots"><i class="fa fa-check"></i><b>2.3.9</b> Combining plots</a></li>
<li class="chapter" data-level="2.3.10" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#plot-using-principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.3.10</b> Plot using principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.3.11" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#attempt-at-ggplot2"><i class="fa fa-check"></i><b>2.3.11</b> Attempt at ggplot2</a></li>
<li class="chapter" data-level="2.3.12" data-path="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html"><a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html#classification-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.3.12</b> Classification: Predicting the odds of binary outcomes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a><ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Looking for Help and Example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrix-operations"><i class="fa fa-check"></i><b>3.2.2</b> Matrix operations</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.3</b> Lists</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#operations-on-data-frames"><i class="fa fa-check"></i><b>3.2.4</b> Operations on data frames</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.5</b> Strings and string vectors</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#for-more-in-depth-exercises"><i class="fa fa-check"></i><b>3.3</b> For more in-depth exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-importing.html"><a href="data-importing.html"><i class="fa fa-check"></i><b>4</b> Data importing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-importing.html"><a href="data-importing.html#enter-data-manually"><i class="fa fa-check"></i><b>4.1</b> Enter data manually</a></li>
<li class="chapter" data-level="4.2" data-path="data-importing.html"><a href="data-importing.html#reading-data-from-file-using-import-dataset-in-rstudio"><i class="fa fa-check"></i><b>4.2</b> Reading data from file using Import dataset in Rstudio</a></li>
<li class="chapter" data-level="4.3" data-path="data-importing.html"><a href="data-importing.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.3</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.4" data-path="data-importing.html"><a href="data-importing.html#reading-file-using-read.table-read.csv-etc."><i class="fa fa-check"></i><b>4.4</b> Reading file using read.table, read.csv, etc.</a></li>
<li class="chapter" data-level="4.5" data-path="data-importing.html"><a href="data-importing.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.5</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.6" data-path="data-importing.html"><a href="data-importing.html#recommended-workflow-for-every-project"><i class="fa fa-check"></i><b>4.6</b> Recommended workflow for EVERY project</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> Analyzing heart attack data set I</a><ul>
<li class="chapter" data-level="5.1" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="5.2" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="5.3" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="5.4" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="5.5" data-path="analyzing-heart-attack-data-set-i.html"><a href="analyzing-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html"><i class="fa fa-check"></i><b>6</b> Analyzing heart attack data set II</a><ul>
<li class="chapter" data-level="6.1" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="analyzing-heart-attack-data-set-ii.html"><a href="analyzing-heart-attack-data-set-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>6.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a><ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.1</b> Tidyverse</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.2</b> Shiny Apps</a><ul>
<li class="chapter" data-level="7.2.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package-by-typing-this-in-the-console."><i class="fa fa-check"></i><b>7.2.1</b> Install the Shiny package by typing this in the console.</a></li>
<li class="chapter" data-level="7.2.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.2.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.2.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.2.3</b> Let’s play!</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html"><i class="fa fa-check"></i><b>8</b> Exploring of state data set</a><ul>
<li class="chapter" data-level="8.1" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#reading-in-and-manipulating-data"><i class="fa fa-check"></i><b>8.1</b> Reading in and manipulating data</a></li>
<li class="chapter" data-level="8.2" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#basic-information-about-data"><i class="fa fa-check"></i><b>8.2</b> Basic information about data</a></li>
<li class="chapter" data-level="8.3" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#peeking-the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> Peeking the whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#linear-model-anylysis"><i class="fa fa-check"></i><b>8.5</b> Linear Model Anylysis</a></li>
<li class="chapter" data-level="8.6" data-path="exploring-of-state-data-set.html"><a href="exploring-of-state-data-set.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html"><i class="fa fa-check"></i><b>9</b> Exploring of game sale dataset</a><ul>
<li class="chapter" data-level="9.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#reading-in-data-and-manage-data"><i class="fa fa-check"></i><b>9.1</b> Reading in data and manage data</a></li>
<li class="chapter" data-level="9.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#visualizing-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualizing of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of Score and Count</a></li>
<li class="chapter" data-level="9.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of Sales</a><ul>
<li class="chapter" data-level="9.5.1" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#effect-of-platform-type-to-priciple-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type to priciple components</a></li>
<li class="chapter" data-level="9.7" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for Global Sales</a></li>
<li class="chapter" data-level="9.8" data-path="exploring-of-game-sale-dataset.html"><a href="exploring-of-game-sale-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="exploring-of-employee-salary-data-set.html"><a href="exploring-of-employee-salary-data-set.html"><i class="fa fa-check"></i><b>10</b> Exploring of employee salary data set</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learning R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="step-into-r-program-analyzing-iris-flower-dataset" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Step into R program-Analyzing iris flower dataset</h1>
<p><strong>Getting started</strong></p>
<ol style="list-style-type: decimal">
<li>Install R from <a href="www.R-project.org" class="uri">www.R-project.org</a>. Choose the cloud server or any U.S. mirror site.</li>
<li>Install RStudio Desktop from <a href="www.RStudio.com" class="uri">www.RStudio.com</a>. Rstudio uses the R software you just installed in the background, but provides a more user-friendly interface. We will use Rstudio. R commands can be typed directly into the “Console” window. Or you can enter them in the “R Script” window and click the “Run” button.</li>
</ol>
<p><img src="images/img0100_Rstudio.png" width="80%" /></p>
<p>Just try all of these commands and guess what’s going on. If it takes a few months to type these 188 characters, try <a href="www.RapidTyping.com" class="uri">www.RapidTyping.com</a>.<br />
<img src="images/img0100_magic.png" width="80%" /></p>
<div id="data-frames-have-rows-and-columns-the-iris-flower-dataset" class="section level2">
<h2><span class="header-section-number">1.1</span> Data frames have rows and columns: the Iris flower dataset</h2>
<p>In 1936, Edgar Anderson collected data to quantify the geographic variation of <em>Iris</em> flowers. The data set consists of 50 samples from each of three sub-species ( <em>Iris setosa</em>, <em>Iris virginica</em> and <em>Iris versicolor</em>). Four features were measured from each sample: the lengths and the widths of sepals and petals, in centimeters (cm). This data is included in R software. Go to the Wikipedia page for this data set (yes, it is famous!). Have a quick look at the data there, think about what distinguishes the three species? If we have a flower with sepals of 6.5cm long and 3.0cm wide, petals of 6.2cm long, and 2.2cm wide, which species does it most likely belong to? <strong>Think</strong> (!) for a few minutes while eyeballing the data at Wikipedia.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-3"></span>
<img src="images/img0101_iris.png" alt="Iris flower. Photo from Wikipedia." width="50%" />
<p class="caption">
Figure 1.1: Iris flower. Photo from Wikipedia.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-4"></span>
<img src="images/img0102_dataframe.png" alt="Example of a data frame. " width="80%" />
<p class="caption">
Figure 1.2: Example of a data frame.
</p>
</div>
<p>To answer these questions, let’s visualize and analyze the data with R. Type these commands without the comments after “#”.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">iris        <span class="co">#This will print the whole dataset, which is included with R </span>
<span class="kw">dim</span>(iris)   <span class="co"># show the dimension of the data frame: 150 rows and 5 columns.</span>
<span class="kw">head</span>(iris)  <span class="co"># show the first few rows; useful for bigger datasets. </span></code></pre></div>
<p>So the first 4 columns contain numeric values. The last one is species information as <strong>character</strong> values. This is an important distinction, as we cannot add or subtract character values. This object is a <strong>data frame</strong>, with both numeric and character columns. A <strong>matrix</strong> only contains one type of values, often just numbers.</p>
<p>To have a look at the data in a spreadsheet, we can use the fix( ) function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#fix(iris)  # examine data frame in a spreadsheet. </span></code></pre></div>
<p>Click on column names to double-check data types (numeric vs. character). Sometimes we need to overwrite data types guessed by R. For example, sometimes we use 1 for male and 0 for female. These are essentially categories; Values like 1.6 make no sense. In this case we need to enforce this column as characters. <strong>Note this window needs to be closed before proceeding to the next</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(iris)  <span class="co"># this Rstudio function also shows data. Note R is case sensitive. </span></code></pre></div>
<p>Individual values in a data frame can be accessed using row and column indices.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">iris[<span class="dv">3</span>, <span class="dv">4</span>]    <span class="co"># shows the value in 3rd row, 4th column.  It is 0.2.</span>
iris[<span class="dv">3</span>, ]     <span class="co"># shows all of row 3</span>
iris[, <span class="dv">4</span>]     <span class="co"># shows all of column 4</span>
iris[<span class="dv">3</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>]  <span class="co"># shows row 3, columns 1 to 4. </span></code></pre></div>

<div class="exercise">
<span id="exr:unnamed-chunk-9" class="exercise"><strong>Exercise 1.1  </strong></span>Display data in rows 1 to 10 from columns 2 to 5. Start a new Word document. Copy and paste your R code and the results to the document and save it as PDF.
</div>

<p><img src="images/img0100_tips.png" width="45%" style="display: block; margin: auto;" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">colnames</span>(iris)  <span class="co"># Column names. </span></code></pre></div>
<pre><code>## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot; 
## [5] &quot;Species&quot;</code></pre>
<p>Remember these column names, as we are going to use them in our analysis now. Note that sepal length information is contained in the column named <strong>Sepal.Length</strong>. Since R is case sensitive, we have to type these column names exactly as above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(iris)  <span class="co"># attach dataset to R working memory, so that columns can be accessible by name.</span>
Petal.Length  <span class="co"># after attaching, we can just use column names to represent a column of numbers as a vector </span></code></pre></div>
<p>R is case-sensitive. “petal.length” will not be recognized.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(Petal.Length)   <span class="co"># mean( ) is a function that operates on Petal.Length, a vector of 150 umbers</span></code></pre></div>
<pre><code>## [1] 3.758</code></pre>

<div class="exercise">
<span id="exr:unnamed-chunk-14" class="exercise"><strong>Exercise 1.2  </strong></span>Compute average sepal length. Hint: replace <strong>Petal.Length</strong> with <strong>Sepal.Length</strong>.
</div>

<p>The best way to learn about other R functions is Google search.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-15" class="exercise"><strong>Exercise 1.3  </strong></span>Google “R square root function” to find the R function, and compute the value of <span class="math inline">\(\sqrt(123.456)\)</span>.
</div>

</div>
<div id="analyzing-one-set-of-numbers" class="section level2">
<h2><span class="header-section-number">1.2</span> Analyzing one set of numbers</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>Petal.Length   <span class="co"># I am just lazy and don’t want to type “Petal.Length”, repeatedly.</span>
<span class="kw">summary</span>(x)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.600   4.350   3.758   5.100   6.900</code></pre>
<ul>
<li>The minimum petal length is 1.0, and the maximum is 6.9.<br />
</li>
<li><strong>Average</strong> petal length is 3.758.</li>
<li>The mid-point or median is 5.35, as about half of the numbers is smaller than 5.35. Why the median is different from the mean? What happens if there is a typo and one number is entered 340cm instead of 3.40cm?<br />
</li>
<li>The 3rd quartile, or 75<sup>th</sup> percentile is 5.1, as 75% of the flowers has petals shorter than 5.1. The 95<sup>th</sup> percentile for the weight of 2-year-old boy is 37 pounds. If a 2-year-old boy weighs 37 pounds, he is heavier than 95% of his peers. If a student’s GPA ranks 5<sup>th</sup> in a class of 25, he/she is at 80<sup>th</sup> percentile.</li>
<li>The 1st quartile, or 25<sup>th</sup> percentile is 1.6. Only 25% of the flowers has petals shorter than 1.6. These summary statistics are graphically represented as a boxplot in the Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-3">1.3</a>A. Boxplots are more useful when multiple sets of numbers are compared.</li>
</ul>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(x)   <span class="co"># Figure 1.3A. It graphically represents the spread of the data. </span>
<span class="kw">boxplot</span>(iris[, <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>])  <span class="co"># boxplot of several columns at the same time Figure 1.3B.</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:1-3"></span>
<img src="book_files/figure-html/1-3-1.png" alt="Boxplot of petal length (A) and of all 4 columns (B)." width="50%" /><img src="book_files/figure-html/1-3-2.png" alt="Boxplot of petal length (A) and of all 4 columns (B)." width="50%" />
<p class="caption">
Figure 1.3: Boxplot of petal length (A) and of all 4 columns (B).
</p>
</div>
<p>In Rstudio, you can copy a plot to clipboard using the <strong>Export</strong> button on top of the plot area. Or you can click <strong>zoom</strong>, right click on the popup plot and select <strong>“Copy Image”</strong>. Then you can paste the plot into Word. If you are using R software, instead of Rstudio, you can right click on the plots and copy as meta-file.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-17" class="exercise"><strong>Exercise 1.4  </strong></span>What can we tell from this boxplot (Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-3">1.3</a>B)? Summarize your observations in PLAIN English. Note the differences in median and the spread (tall boxes). What is the most variable characteristics?
</div>

To quantify the variance, we can compute the <strong>standard deviation</strong> σ:
<span class="math display">\[\begin{align}
σ=\sqrt{\frac{1}{N}[(x_{1}-u)^2+(x_{2}-u)^2+...+(x_{N}-u)^2]}    
\end{align}\]</span>
where
<span class="math display">\[\begin{align}
u=\frac{1}{N}(x_{1}+x_{2}+...x_{N})
\end{align}\]</span>
<p>If all the measurements are close to the mean (µ), then standard deviation should be small.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(x)  <span class="co"># sd( ) is a function for standard deviation</span></code></pre></div>
<pre><code>## [1] 1.765298</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(Sepal.Width) </code></pre></div>
<pre><code>## [1] 0.4358663</code></pre>
<p>As we can see, these flowers have similar sepal width. They differ widely in petal length. This is consistent with the boxplot above. Perhaps changes in petal length lead to better survival in different habitats.</p>
<p>With R it is very easy to generate graphs.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(x)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-19"></span>
<img src="book_files/figure-html/unnamed-chunk-19-1.png" alt="Barplot of petal length" width="80%" />
<p class="caption">
Figure 1.4: Barplot of petal length
</p>
</div>
<p>As we can see, the first 50 flowers (Iris setosa) have much shorter petals than the other two species. The last 50 flowers (Iris verginica) have slightly longer petals than the middle (iris versicolor).</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x)  <span class="co"># Run sequence plot</span>
<span class="kw">hist</span>(x)  <span class="co"># histogram</span>
<span class="kw">lag.plot</span>(x)
<span class="kw">qqnorm</span>(x)  <span class="co"># Q-Q plot for normal distribution</span>
<span class="kw">qqline</span>(x) </code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:1-4"></span>
<img src="book_files/figure-html/1-4-1.png" alt="Sequence plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-2.png" alt="Sequence plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-3.png" alt="Sequence plot, histogram, lag plot and normal Q-Q plot." width="50%" /><img src="book_files/figure-html/1-4-4.png" alt="Sequence plot, histogram, lag plot and normal Q-Q plot." width="50%" />
<p class="caption">
Figure 1.5: Sequence plot, histogram, lag plot and normal Q-Q plot.
</p>
</div>
<p>Histogram shows the distribution of data. The histogram top right of Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-4">1.5</a> shows that there are more flowers with Petal Length between 1 and 1.5. It also shows that the data does not show a bell-curved distribution.</p>
<p>Lag plot is a scatter plot against the same set of number with an offset of 1. Any structure in lag plot indicate non-randomness in the order in which the data is presented.</p>
<p>Q-Q plot can help check if data follows a Gaussian distribution, which is widely observed in many situations. Also referred to as normal distribution, it is the pre-requisite for many statistical methods. See Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-5">1.6</a> for an example of normal distribution. Quantiles of the data is compared against those in a normal distribution. If the normal Q-Q plot is close to the reference line produced by qqline( ), then the data has a normal distribution.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-20" class="exercise"><strong>Exercise 1.5  </strong></span>Generate 500 random numbers from the standard normal distribution and generate sequence plots, histogram, lag plot, and Q-Q plot. You should get plots like those in Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-5">1.6</a>. Hint: Run x = rnorm(500) to generate these numbers, and then re-run the last 5 lines of code on this page. They are also shown on Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:1-4">1.5</a>.
</div>

(ref:1-5) Plots for random generated numbers following a normal distribution. This is for reference.
<div class="figure" style="text-align: center"><span id="fig:1-5"></span>
<img src="book_files/figure-html/1-5-1.png" alt="(ref:1-5)" width="50%" /><img src="book_files/figure-html/1-5-2.png" alt="(ref:1-5)" width="50%" /><img src="book_files/figure-html/1-5-3.png" alt="(ref:1-5)" width="50%" /><img src="book_files/figure-html/1-5-4.png" alt="(ref:1-5)" width="50%" />
<p class="caption">
Figure 1.6: (ref:1-5)
</p>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-21" class="exercise"><strong>Exercise 1.6  </strong></span>Investigate Septal Length distribution using these techniques and summarize your observations in PLAIN English. Hint: assign x with the values in the sepal length column (x = Sepal.Length), and re-run all the code in this section.
</div>

</div>
<div id="students-t-test" class="section level2">
<h2><span class="header-section-number">1.3</span> Student’s t-test</h2>
<p>In hypothesis testing, we evaluate how likely the observed data can be generated if a certain hypothesis is true. If this probability (p value) is very small (&lt; 0.05, typically), we reject that hypothesis. Are the petal lengths of iris setosa significantly different from these of iris versicolor?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>Petal.Length[<span class="dv">1</span><span class="op">:</span><span class="dv">50</span>]  <span class="co"># the first 50 values of Sepal.Length are for iris setosa</span>
y &lt;-<span class="st"> </span>Petal.Length[<span class="dv">51</span><span class="op">:</span><span class="dv">100</span>]  <span class="co"># the next 50 values of Sepal.Length are for iris versicolor</span>
<span class="kw">t.test</span>(x, y)  <span class="co"># t.test( ) is an R function for student’s t-test</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -39.493, df = 62.14, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.939618 -2.656382
## sample estimates:
## mean of x mean of y 
##     1.462     4.260</code></pre>
<p>The null hypothesis is that the true mean is the same. Since p value is really small, we reject this hypothesis. Iris versicolor has longer sepals than iris setosa.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-23" class="exercise"><strong>Exercise 1.7  </strong></span>Are iris setosa and iris versicolor significantly different in sepal width? Hint: Replace Petal.Length with something else and re-run above code.
</div>

<p>We can also do t-test on one set of numbers. This is a one-sample t-test of mean:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Sepal.Length, <span class="dt">mu =</span> <span class="fl">5.8</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  Sepal.Length
## t = 0.64092, df = 149, p-value = 0.5226
## alternative hypothesis: true mean is not equal to 5.8
## 95 percent confidence interval:
##  5.709732 5.976934
## sample estimates:
## mean of x 
##  5.843333</code></pre>
<p>In this case, our hypothesis is that the true average of sepal length for all iris flowers is 5.8. Since p value is quite big, we accept this hypothesis. This function also tells us the 95% confidence interval on the mean. Based on our sample of 150 iris flowers, we are 95% confident that the true mean is between 5.71 and 5.98.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-25" class="exercise"><strong>Exercise 1.8  </strong></span>Compute 95% confidence interval of petal length.
</div>

</div>
<div id="test-for-normal-distribution" class="section level2">
<h2><span class="header-section-number">1.4</span> Test for normal distribution</h2>
<p>We can perform hypothesis testing on whether a set of numbers derived from normal distribution. The null hypothesis is that the data is from a normal distribution.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">shapiro.test</span>(Petal.Length)</code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  Petal.Length
## W = 0.87627, p-value = 7.412e-10</code></pre>
<p>If petal length is normally distributed, there is only 7.412×10<sup>-10</sup> chance of getting a test statistic of 0.87627, which is observed in our sample of 150 flowers. In other words, it is highly unlikely that petal length follows a normal distribution. We reject the normal distribution hypothesis.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-27" class="exercise"><strong>Exercise 1.9  </strong></span>Is sepal width normally distributed? Run Shapiro’s test and also generate histogram and normal Q-Q plot.
</div>

</div>
<div id="analyzing-a-column-of-categorical-values" class="section level2">
<h2><span class="header-section-number">1.5</span> Analyzing a column of categorical values</h2>
<p>In the iris dataset, the last column contains the species information. These are “string” values or categorical values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span><span class="kw">table</span>(Species)  <span class="co"># tabulate the frequencies</span>
counts</code></pre></div>
<pre><code>## Species
##     setosa versicolor  virginica 
##         50         50         50</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pie</span>(counts)  <span class="co"># See Figure 1.7A</span>
<span class="kw">barplot</span>(counts)  <span class="co"># See Figure 1.7B</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-28"></span>
<img src="book_files/figure-html/unnamed-chunk-28-1.png" alt="Frequencies of categorical values visualized by Pie chart (A) and bar chart (B)." width="50%" /><img src="book_files/figure-html/unnamed-chunk-28-2.png" alt="Frequencies of categorical values visualized by Pie chart (A) and bar chart (B)." width="50%" />
<p class="caption">
Figure 1.7: Frequencies of categorical values visualized by Pie chart (A) and bar chart (B).
</p>
</div>
<p>Pie charts are very effective in showing proportions.</p>
<p>We can see that the three species are each represented with 50 observations.</p>
</div>
<div id="analyzing-the-relationship-between-two-columns-of-numbers" class="section level2">
<h2><span class="header-section-number">1.6</span> Analyzing the relationship between two columns of numbers</h2>
<p>Scatter plot is very effective in visualizing correlation between two columns of numbers.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(iris)      <span class="co"># attach the data set</span>
x &lt;-<span class="st"> </span>Petal.Width  <span class="co"># just lazy</span>
y &lt;-<span class="st"> </span>Petal.Length 
<span class="kw">plot</span>(x, y)        <span class="co"># scatterplot,  refined version in Figure 1.9</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-1"></span>
<img src="book_files/figure-html/2-1-1.png" alt="Scatter plot of petal width and petal length." width="80%" />
<p class="caption">
Figure 1.8: Scatter plot of petal width and petal length.
</p>
</div>
<p>Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-1">1.8</a> shows that there is a positive correlation between petal length and petal width. In other words, flowers with longer petals are often wider. So the petals are getting bigger substantially, when both dimensions increase.<br />
Another unusual feature is that there seems to be two clusters of points. Do the points in the small cluster represent one particular species of Iris? We need to further investigate this. The following will produce a plot with the species information color-coded. The resultant Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-2">1.9</a> clearly shows that indeed one particular species, <em>I. setosa</em> constitutes the smaller cluster in the low left. The other two species also show difference in this plot, even though they are not easily separated. This is a very important insight into this dataset.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(x, y, <span class="dt">col =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>)[Species])  <span class="co"># change colors based on another column (Species). </span>
<span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="kw">levels</span>(Species), <span class="dt">fill =</span> <span class="kw">rainbow</span>(<span class="dv">3</span>))  <span class="co"># add legends on topleft.</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-2"></span>
<img src="book_files/figure-html/2-2-1.png" alt="Scatter plot shows the correlation of petal width and petal length." width="80%" />
<p class="caption">
Figure 1.9: Scatter plot shows the correlation of petal width and petal length.
</p>
</div>
<p>The rainbow( ) function generates 3 colors and Species information is used to choose colors. Note that Species column is a factor, which is a good way to encode columns with multiple levels. Internally, it is coded as 1, 2, 3.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(iris)  <span class="co"># show the structure of data object</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>Perhaps due to adaption to environment, change in petal length lead to better survival. With the smallest petals, <em>Iris Setosa</em> is found in Arctic regions. <em>Iris versicolor</em> is often found in the Eastern United States and Eastern Canada. <em>Iris virginica</em> “is common along the coastal plain from Florida to Georgia in the Southeastern United States [Wikipedia].” It appears the iris flowers in warmer places are much larger than those in colder ones. With R, it is very easy to generate lots of graphics. But we still have to do the thinking. It requires to put the plots in context.</p>
<p>We can quantitatively characterize the strength of the correlation using several types of correlation coefficients, such as Pearson’s correlation coefficient, r. It ranges from -1 to 1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor</span>(x, y) </code></pre></div>
<pre><code>## [1] 0.9628654</code></pre>
<p>This means the petal width and petal length are strongly and positively correlated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cor.test</span>(x, y)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 43.387, df = 148, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9490525 0.9729853
## sample estimates:
##       cor 
## 0.9628654</code></pre>
<p>Through hypothesis testing of the correlation, we reject the null hypothesis that the true correlation is zero. That means the correlation is statistically significant. Note that Pearson’s correlation coefficient is not robust against outliers and other methods such as Spearman’s exists. See help info:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?cor  <span class="co"># show help info on cor ( )</span></code></pre></div>
<p>We can also determine the equation that links petal length and petal width. This is so called regression analysis. We assume Petal.Length = <em>a</em> × Petal.Width + <em>c</em> + <em>e</em>, where <em>a</em> is the slope parameter, <em>c</em> is a constant, and <em>e</em> is some random error. This linear model can be determined by a method that minimizes the least squared-error:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)  <span class="co"># Linear Model (lm): petal length as a function of petal width</span>
<span class="kw">summary</span>(model)      <span class="co"># shows the details</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.33542 -0.30347 -0.02955  0.25776  1.39453 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.08356    0.07297   14.85   &lt;2e-16 ***
## x            2.22994    0.05140   43.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4782 on 148 degrees of freedom
## Multiple R-squared:  0.9271, Adjusted R-squared:  0.9266 
## F-statistic:  1882 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As we can see, we estimated that <em>a</em>=2.22944 and <em>c</em>=1.08356. Both parameters are significantly different from zero as the p values are &lt;2×10<sup>-16</sup> in both cases. In other words, we can reliably predict Petal.Length = 2.22944 × Petal.Width + 1.08356. This model can be put on the scatter plot as a line.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(model)
<span class="kw">abline</span>(model)  <span class="co"># add regression line to existing scatter plot. Finishes Figure 1.8.</span></code></pre></div>
<p>Sometimes, we use this type of regression analysis to investigate whether variables are associated.</p>

<div class="exercise">
<span id="exr:unnamed-chunk-35" class="exercise"><strong>Exercise 1.10  </strong></span>Investigate the relationship between sepal length and sepal width using scatter plots, correlation coefficients, test of correlation, and linear regression. Again interpret all your results in PLAIN and proper English.
</div>

</div>
<div id="visualizing-and-testing-the-differences-in-groups" class="section level2">
<h2><span class="header-section-number">1.7</span> Visualizing and testing the differences in groups</h2>
<p>Are boys taller than girls of the same age? Such situations are common. We have measurements of two groups of objects and want to know if the observed differences are real or due to random sampling error.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">attach</span>(iris)  <span class="co"># attach iris data</span>
<span class="kw">boxplot</span>(Petal.Length <span class="op">~</span><span class="st"> </span>Species)  <span class="co"># Generate boxplot: Petal length by species, see Figure 1.11</span></code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:2-4"></span>
<img src="images/img0204_LengthSpecies.png" alt="Boxplot of petal length, grouped by species."  />
<p class="caption">
Figure 1.10: Boxplot of petal length, grouped by species.
</p>
</div>
<p>From the boxplot, it is obvious that <em>I. Setosa</em> has much shorter petals. But are there significant differences between <em>I. versicolor</em> and <em>I. virginica</em>? We only had a small sample of 50 flowers for each species. But we want to draw some conclusion about the two species in general. We could measure all the iris flowers across the world; Or we could use statistics to make inference. First we need to extract these data</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>Petal.Length[<span class="dv">51</span><span class="op">:</span><span class="dv">100</span>]  <span class="co"># extract Petal Length of iris versicolor, from No.51 to No.100</span>
x  <span class="co"># x contain 50 measurements</span>
y &lt;-<span class="st"> </span>Petal.Length[<span class="dv">101</span><span class="op">:</span><span class="dv">150</span>]  <span class="co"># extract Petal length of iris virginica,  from No. 101 to No. 150</span>
y  <span class="co"># y contain 50 measurements</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(x, y)  <span class="co"># a boxplot of the two groups of values</span>
<span class="kw">t.test</span>(x, y)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -12.604, df = 95.57, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.49549 -1.08851
## sample estimates:
## mean of x mean of y 
##     4.260     5.552</code></pre>
<p>In this student’s t-test, our null hypothesis is that the mean petal length is the same for <em>I. versicolor</em> and <em>I. virginica</em>. A small p value of 2.2x10<sup>-16</sup> indicates under this hypothesis, it is extremely unlikely to observe the difference of 1.292cm through random sampling. Hence we reject that hypothesis and conclude that the true mean is different. If we measure all <em>I. versicolor</em> and <em>I. virginica</em> flowers in the world and compute their true average petal lengths, it is very likely that the two averages will differ. On the other hand, if p value is larger than a threshold, typically 0.05, we will accept the null hypothesis and conclude that real average petal length is the same.</p>
<p>We actually do not need to separate two set of numbers into two data objects in order to do t-test or compare them side-by-side on one plot. We can do it right within the data frame. R can separate data points by another column.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x2 &lt;-<span class="st"> </span>iris[<span class="dv">51</span><span class="op">:</span><span class="dv">150</span>, ]  <span class="co"># Extract rows 51 to 150</span>
<span class="kw">t.test</span>(Petal.Length <span class="op">~</span><span class="st"> </span>Species, <span class="dt">data =</span> x2)  <span class="co"># t-test of Petal.Length column, divided by the Species column in x2. </span>
<span class="kw">boxplot</span>(Petal.Length <span class="op">~</span><span class="st"> </span>Species, <span class="dt">data =</span> <span class="kw">droplevels</span>(x2))  <span class="co"># droplevels( ) removes empty levels in Species</span></code></pre></div>

<div class="exercise">
<span id="exr:unnamed-chunk-40" class="exercise"><strong>Exercise 1.11  </strong></span>Use boxplot and t-test to investigate whether sepal width is different between <em>I. versicolor</em> and <em>I. virginica</em>. Interpret your results.
</div>

</div>
<div id="testing-the-difference-among-multiple-groups-analysis-of-variance-anova" class="section level2">
<h2><span class="header-section-number">1.8</span> Testing the difference among multiple groups (Analysis of Variance: ANOVA)</h2>
<p>As indicated by Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-4">1.10</a>, sepal width has small variation, even across 3 species. We want to know if the mean sepal width is the same across 3 species. This is done through Analysis of Variance (ANOVA).</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">boxplot</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species)  <span class="co"># Figure 1.12</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-5"></span>
<img src="book_files/figure-html/2-5-1.png" alt="Boxplot of sepal width across 3 species." width="672" />
<p class="caption">
Figure 1.11: Boxplot of sepal width across 3 species.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(Sepal.Width <span class="op">~</span><span class="st"> </span>Species))</code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species       2  11.35   5.672   49.16 &lt;2e-16 ***
## Residuals   147  16.96   0.115                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Since p value is much smaller than 0.05, we reject the null hypothesis. The mean sepal width is not the same for 3 species. This is the only thing we can conclude from this. The boxplot in Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-5">1.11</a> seems to indicate that <em>I. Setosa</em> has wider sepals. Now we demonstrate how to use the lattice package for visualizing data using multiple panels. This package is not included in the base version of R. They need to be downloaded and installed. One of main advantages of R is that it is open, and users can contribute their code as packages. If you are using <strong>Rstudio</strong>, you can choose <strong>Tools-&gt;Install packages</strong> from the main menu, and then enter the name of the package. If you are using R software, you can install additional packages, by clicking <strong>Packages</strong> in the main menu, and select a mirror site. These mirror sites all work the same, but some may be faster. Lately I just use cloud mirror. After choosing a mirror and clicking “OK”, you can scroll down the long list to find your package. Alternatively, you can type this command to install packages.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#install.packages (&quot;ggplot2&quot;)  # choose the cloud mirror site when asked</span></code></pre></div>
<p>Packages only need to be installed once. But every time you need to use a package, you need to load it from your hard drive.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)  <span class="co"># load the ggplot2 package</span></code></pre></div>
<p>Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-6">1.12</a>A shows the sepal width distribution for each of the 3 species. The 3 histograms are aligned in panels: layout of 1 column and 3 rows.</p>
<p>Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-6">1.12</a>A shows an interesting feature in how sepal width is distributed. While for I. setosa it is skewed to the right. For the other two species it is skewed to the left.</p>
<p>We can also have density plots side-by-side (Figure <a href="step-into-r-program-analyzing-iris-flower-dataset.html#fig:2-6">1.12</a>B):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(iris, <span class="kw">aes</span>(<span class="dt">x =</span> Sepal.Width, <span class="dt">group =</span> Species, 
                 <span class="dt">y =</span> <span class="kw">c</span>(..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">1</span>]<span class="op">/</span><span class="kw">sum</span>(..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">1</span>]),
                       ..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">2</span>]<span class="op">/</span><span class="kw">sum</span>(..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">2</span>]),
                       ..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">3</span>]<span class="op">/</span><span class="kw">sum</span>(..count..[..group.. <span class="op">==</span><span class="st"> </span><span class="dv">3</span>])) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> .<span class="dv">2</span>, <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">fill =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">facet_grid</span>(Species <span class="op">~</span><span class="st"> </span>.) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Percent of Total&quot;</span>)
<span class="kw">ggplot</span>(iris, <span class="kw">aes</span>(<span class="dt">x =</span> Petal.Length, <span class="dt">fill =</span> Species)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="dt">alpha =</span> .<span class="dv">3</span>)</code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:2-6"></span>
<img src="images/img0206n_HistDensity.png" alt="Visualizing data using the ggplot2 package."  />
<p class="caption">
Figure 1.12: Visualizing data using the ggplot2 package.
</p>
</div>

<div class="exercise">
<span id="exr:unnamed-chunk-44" class="exercise"><strong>Exercise 1.12  </strong></span>Use boxplot, multiple panel histograms and density plots to investigate whether petal width is the same among three subspecies.
</div>


</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualizing-data-set-analyzing-cars-and-iris-flower-data-sets.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
