<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 The game sales dataset | Learn R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 The game sales dataset | Learn R through examples" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 The game sales dataset | Learn R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  

<meta name="author" content="Xijin Ge, Jianli Qi, and Rong Fan" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="state-dataset.html"/>
<link rel="next" href="the-messy-salary-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R programming:The iris flower dataset</a>
<ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting started</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-proper-way-of-using-rstudio"><i class="fa fa-check"></i><b>1.2</b> The proper way of using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.3</b> Data frames contain rows and columns: the iris flower dataset</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.4</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable"><i class="fa fa-check"></i><b>1.5</b> Analyzing a categorical variable</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables"><i class="fa fa-check"></i><b>1.6</b> The relationship between two numerical variables</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups"><i class="fa fa-check"></i><b>1.7</b> Testing the differences between two groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-differences-among-multiple-groups-anova"><i class="fa fa-check"></i><b>1.8</b> Testing differences among multiple groups (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html"><i class="fa fa-check"></i><b>2</b> Visualizing the iris flower data set</a>
<ul>
<li class="chapter" data-level="2.1" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#star-and-segment-diagrams"><i class="fa fa-check"></i><b>2.3</b> Star and segment diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#the-ggplot2-package-is-intuitive-and-powerful"><i class="fa fa-check"></i><b>2.4</b> The ggplot2 package is intuitive and powerful</a></li>
<li class="chapter" data-level="2.5" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#other-types-of-plots-with-ggplot2"><i class="fa fa-check"></i><b>2.5</b> Other types of plots with ggplot2</a></li>
<li class="chapter" data-level="2.6" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#hierarchical-clustering-and-heat-map"><i class="fa fa-check"></i><b>2.6</b> Hierarchical clustering and heat map</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.7</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#logistic-regression-for-binary-outcomes-prediction"><i class="fa fa-check"></i><b>2.8</b> Logistic Regression for Binary Outcomes Prediction</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#seeking-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Seeking help and example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.2</b> Matrices</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.5</b> Lists</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html"><i class="fa fa-check"></i><b>4</b> Importing data and managing files</a>
<ul>
<li class="chapter" data-level="4.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#project-oriented-workflow"><i class="fa fa-check"></i><b>4.1</b> Project-oriented workflow</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-project-in-a-new-folder"><i class="fa fa-check"></i><b>4.1.1</b> Create a project in a new folder</a></li>
<li class="chapter" data-level="4.1.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-script-file-and-comment-please"><i class="fa fa-check"></i><b>4.1.2</b> Create a script file (and Comment, Please!)</a></li>
<li class="chapter" data-level="4.1.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#copy-data-files-to-the-new-directory"><i class="fa fa-check"></i><b>4.1.3</b> Copy data files to the new directory</a></li>
<li class="chapter" data-level="4.1.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#import-data-files"><i class="fa fa-check"></i><b>4.1.4</b> Import data files</a></li>
<li class="chapter" data-level="4.1.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#check-and-convert-data-types"><i class="fa fa-check"></i><b>4.1.5</b> Check and convert data types</a></li>
<li class="chapter" data-level="4.1.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#close-a-project-when-you-are-done"><i class="fa fa-check"></i><b>4.1.6</b> Close a project when you are done</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#read-files-directly-using-read.table"><i class="fa fa-check"></i><b>4.2</b> Read files directly using read.table</a></li>
<li class="chapter" data-level="4.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.3</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#enter-data-manually"><i class="fa fa-check"></i><b>4.4</b> Enter data manually</a></li>
<li class="chapter" data-level="4.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-transformation-using-the-dplyr"><i class="fa fa-check"></i><b>4.6</b> Data transformation using the dplyr</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> The heart attack data set (I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-individually"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column individually</a></li>
<li class="chapter" data-level="5.2" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns</a></li>
<li class="chapter" data-level="5.3" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables</a></li>
<li class="chapter" data-level="5.4" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables</a></li>
<li class="chapter" data-level="5.5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html"><i class="fa fa-check"></i><b>6</b> The heart attack dataset (II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#statistical-models-easy-to-run-tricky-to-interpret"><i class="fa fa-check"></i><b>6.5</b> Statistical models: Easy to Run, tricky to interpret!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>7.1</b> Introduction to R Markdown</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> Tidyverse</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package"><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
<li class="chapter" data-level="7.4.4" data-path="advanced-topics.html"><a href="advanced-topics.html#publish-your-app"><i class="fa fa-check"></i><b>7.4.4</b> Publish your app</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-topics.html"><a href="advanced-topics.html#define-your-own-function"><i class="fa fa-check"></i><b>7.5</b> Define your own function</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="state-dataset.html"><a href="state-dataset.html"><i class="fa fa-check"></i><b>8</b> State dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="state-dataset.html"><a href="state-dataset.html#data-import-and-manipulation"><i class="fa fa-check"></i><b>8.1</b> Data Import and Manipulation</a></li>
<li class="chapter" data-level="8.2" data-path="state-dataset.html"><a href="state-dataset.html#visualizing-data"><i class="fa fa-check"></i><b>8.2</b> Visualizing data</a></li>
<li class="chapter" data-level="8.3" data-path="state-dataset.html"><a href="state-dataset.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="state-dataset.html"><a href="state-dataset.html#the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> The whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="state-dataset.html"><a href="state-dataset.html#linear-model-analysis"><i class="fa fa-check"></i><b>8.5</b> Linear model analysis</a></li>
<li class="chapter" data-level="8.6" data-path="state-dataset.html"><a href="state-dataset.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html"><i class="fa fa-check"></i><b>9</b> The game sales dataset</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#reading-in-data-and-managing-the-dataset"><i class="fa fa-check"></i><b>9.1</b> Reading in data and managing the dataset</a></li>
<li class="chapter" data-level="9.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#effect-of-platform-type-on-principle-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type on principle components</a></li>
<li class="chapter" data-level="9.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html"><i class="fa fa-check"></i><b>10</b> The messy salary data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#data-preparation-and-cleaning"><i class="fa fa-check"></i><b>10.1</b> Data Preparation and Cleaning</a></li>
<li class="chapter" data-level="10.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#variable-analysis"><i class="fa fa-check"></i><b>10.2</b> Variable Analysis</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income-types"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income types</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#defining-gross-income-types"><i class="fa fa-check"></i><b>10.4.1</b> Defining Gross income types</a></li>
<li class="chapter" data-level="10.4.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#the-intersection-of-ethnic-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> The Intersection of Ethnic, Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learn R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-game-sales-dataset" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> The game sales dataset<a href="the-game-sales-dataset.html#the-game-sales-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Welcome to the fascinating spectacle of video game sales data, which was heroically downloaded from Kaggle:
<a href="https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings#Video_Games_Sales_as_at_22_Dec_2016.csv">https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings#Video_Games_Sales_as_at_22_Dec_2016.csv</a>. We will witness the performance of the sales across North America, Europe, Japan, and other regions, which all add up to the global sales. Our dataset is also enchanted with the critic scores, user scores, and the number of brave souls who dared to contribute to these scores.</p>
<p>Here’s a brief overview of the dataset’s contents:</p>
<p>Name: Name of the game.</p>
<p>Platform: Console on which the game is running.</p>
<p>Year_of_Release: Year of the game released.</p>
<p>Genre: The category of the game.</p>
<p>Publisher: The game’s champion and distributor.</p>
<p>NA_Sales: Game sales in North America (in millions of units).</p>
<p>EU_Sales: Game sales in the European Union (in millions of units).</p>
<p>JP_Sales: Game sales in Japan (in millions of units).</p>
<p>Other_Sales: Game sales in the rest of the world, i.e. Africa, Asia excluding Japan, Australia, Europe excluding the E.U. and South America (in millions of units).</p>
<p>Global_Sales: Total sales in the world (in millions of units).</p>
<p>Critic_Score: Aggregate score compiled by Meta critic staff.</p>
<p>Critic_Count: The number of critics who’ve lent their voices to the Critic Score.</p>
<p>User_Score: Score by Metacritic’s subscribers.</p>
<p>User_Count: The number of users who weighed in with their opinions.</p>
<p>Developer: Party responsible for creating the game.</p>
<p>Rating: The ESRB ratings:
E for “Everyone”; E10+ for “Everyone 10+”; T for “Teen”; M for “Mature”; AO for “Adults Only”; RP for “Rating Pending”; and the nostalgic K-A for “kids to adults”.</p>
<p>After downloading the data, we transmuted N/A into NA first using Excel and saved it as a .csv file, then read it into R. We banished observations with empty strings of Rating, leaving us with 6825 observations in our “game” dataset. We observed a curious phenomenon: an abundance of sales values dared to be zero. We then transformed the sales into basic units and plus 1 to prepare for the logarithmic transformation (a wizard’s trick to normalize distributions). We also scaled the Critic Scores down by a factor of 10 to harmonize with the User Scores’ scale.</p>
<div id="reading-in-data-and-managing-the-dataset" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Reading in data and managing the dataset<a href="the-game-sales-dataset.html#reading-in-data-and-managing-the-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb818"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb818-1"><a href="the-game-sales-dataset.html#cb818-1" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb818-2"><a href="the-game-sales-dataset.html#cb818-2" tabindex="-1"></a>tem <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;datasets/video-game-sales-at-22-Dec-2016.csv&quot;</span>)</span>
<span id="cb818-3"><a href="the-game-sales-dataset.html#cb818-3" tabindex="-1"></a>tem <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(tem)  <span class="co"># Remove NA</span></span>
<span id="cb818-4"><a href="the-game-sales-dataset.html#cb818-4" tabindex="-1"></a></span>
<span id="cb818-5"><a href="the-game-sales-dataset.html#cb818-5" tabindex="-1"></a><span class="co"># Keep games with ratings and remove redundant levels</span></span>
<span id="cb818-6"><a href="the-game-sales-dataset.html#cb818-6" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb818-7"><a href="the-game-sales-dataset.html#cb818-7" tabindex="-1"></a>game <span class="ot">&lt;-</span> tem <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Rating <span class="sc">!=</span> <span class="st">&quot;&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">droplevels</span>() </span>
<span id="cb818-8"><a href="the-game-sales-dataset.html#cb818-8" tabindex="-1"></a></span>
<span id="cb818-9"><a href="the-game-sales-dataset.html#cb818-9" tabindex="-1"></a><span class="co"># Convert sales to actual figures by multiplying 1000000 </span></span>
<span id="cb818-10"><a href="the-game-sales-dataset.html#cb818-10" tabindex="-1"></a><span class="co"># Plus one to avoid the curse of negative log (sneaky!)</span></span>
<span id="cb818-11"><a href="the-game-sales-dataset.html#cb818-11" tabindex="-1"></a>game<span class="sc">$</span>Year_of_Release <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">as.character</span>(game<span class="sc">$</span>Year_of_Release))</span>
<span id="cb818-12"><a href="the-game-sales-dataset.html#cb818-12" tabindex="-1"></a>game<span class="sc">$</span>NA_Sales <span class="ot">&lt;-</span> game<span class="sc">$</span>NA_Sales <span class="sc">*</span> <span class="dv">1000000</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb818-13"><a href="the-game-sales-dataset.html#cb818-13" tabindex="-1"></a>game<span class="sc">$</span>EU_Sales <span class="ot">&lt;-</span> game<span class="sc">$</span>EU_Sales <span class="sc">*</span> <span class="dv">1000000</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb818-14"><a href="the-game-sales-dataset.html#cb818-14" tabindex="-1"></a>game<span class="sc">$</span>JP_Sales <span class="ot">&lt;-</span> game<span class="sc">$</span>JP_Sales <span class="sc">*</span> <span class="dv">1000000</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb818-15"><a href="the-game-sales-dataset.html#cb818-15" tabindex="-1"></a>game<span class="sc">$</span>Other_Sales <span class="ot">&lt;-</span> game<span class="sc">$</span>Other_Sales <span class="sc">*</span> <span class="dv">1000000</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb818-16"><a href="the-game-sales-dataset.html#cb818-16" tabindex="-1"></a>game<span class="sc">$</span>Global_Sales <span class="ot">&lt;-</span> game<span class="sc">$</span>Global_Sales <span class="sc">*</span> <span class="dv">1000000</span> <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb818-17"><a href="the-game-sales-dataset.html#cb818-17" tabindex="-1"></a></span>
<span id="cb818-18"><a href="the-game-sales-dataset.html#cb818-18" tabindex="-1"></a><span class="co"># Harmonizing Critic Scores to match the User Score scale by dividing by 10</span></span>
<span id="cb818-19"><a href="the-game-sales-dataset.html#cb818-19" tabindex="-1"></a>game<span class="sc">$</span>Critic_Score <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(game<span class="sc">$</span>Critic_Score)) <span class="sc">/</span> <span class="dv">10</span>  </span>
<span id="cb818-20"><a href="the-game-sales-dataset.html#cb818-20" tabindex="-1"></a>game<span class="sc">$</span>User_Score <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(game<span class="sc">$</span>User_Score))</span>
<span id="cb818-21"><a href="the-game-sales-dataset.html#cb818-21" tabindex="-1"></a>game<span class="sc">$</span>Critic_Count <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(game<span class="sc">$</span>Critic_Count)</span>
<span id="cb818-22"><a href="the-game-sales-dataset.html#cb818-22" tabindex="-1"></a>game<span class="sc">$</span>User_Count <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(game<span class="sc">$</span>User_Count)</span>
<span id="cb818-23"><a href="the-game-sales-dataset.html#cb818-23" tabindex="-1"></a></span>
<span id="cb818-24"><a href="the-game-sales-dataset.html#cb818-24" tabindex="-1"></a><span class="co"># Set category variables as factor variables </span></span>
<span id="cb818-25"><a href="the-game-sales-dataset.html#cb818-25" tabindex="-1"></a>game<span class="sc">$</span>Name <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Name)</span>
<span id="cb818-26"><a href="the-game-sales-dataset.html#cb818-26" tabindex="-1"></a>game<span class="sc">$</span>Platform <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Platform)</span>
<span id="cb818-27"><a href="the-game-sales-dataset.html#cb818-27" tabindex="-1"></a>game<span class="sc">$</span>Genre <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Genre)</span>
<span id="cb818-28"><a href="the-game-sales-dataset.html#cb818-28" tabindex="-1"></a>game<span class="sc">$</span>Publisher <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Publisher)</span>
<span id="cb818-29"><a href="the-game-sales-dataset.html#cb818-29" tabindex="-1"></a>game<span class="sc">$</span>Developer <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Developer)</span>
<span id="cb818-30"><a href="the-game-sales-dataset.html#cb818-30" tabindex="-1"></a>game<span class="sc">$</span>Rating <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Rating)</span>
<span id="cb818-31"><a href="the-game-sales-dataset.html#cb818-31" tabindex="-1"></a></span>
<span id="cb818-32"><a href="the-game-sales-dataset.html#cb818-32" tabindex="-1"></a><span class="co"># Format column names for clarity</span></span>
<span id="cb818-33"><a href="the-game-sales-dataset.html#cb818-33" tabindex="-1"></a><span class="fu">colnames</span>(game) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Name&quot;</span>, <span class="st">&quot;Platform&quot;</span>, <span class="st">&quot;Year.Release&quot;</span>, <span class="st">&quot;Genre&quot;</span>, <span class="st">&quot;Publisher&quot;</span>, <span class="st">&quot;NA.Sales&quot;</span>, <span class="st">&quot;EU.Sales&quot;</span>, <span class="st">&quot;JP.Sales&quot;</span>, <span class="st">&quot;Other.Sales&quot;</span>, <span class="st">&quot;Global.Sales&quot;</span>, <span class="st">&quot;Critic.Score&quot;</span>, <span class="st">&quot;Critic.Count&quot;</span>, <span class="st">&quot;User.Score&quot;</span>, <span class="st">&quot;User.Count&quot;</span>, <span class="st">&quot;Developer&quot;</span>, <span class="st">&quot;Rating&quot;</span>)</span>
<span id="cb818-34"><a href="the-game-sales-dataset.html#cb818-34" tabindex="-1"></a></span>
<span id="cb818-35"><a href="the-game-sales-dataset.html#cb818-35" tabindex="-1"></a><span class="co"># Display the structure and a summary of the dataset</span></span>
<span id="cb818-36"><a href="the-game-sales-dataset.html#cb818-36" tabindex="-1"></a><span class="fu">str</span>(game)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    6825 obs. of  16 variables:
##  $ Name        : Factor w/ 4377 levels &quot; Tales of Xillia 2&quot;,..: 4203 2055 4205 2530 4201 2533 2054 4195 1820 4196 ...
##  $ Platform    : Factor w/ 17 levels &quot;3DS&quot;,&quot;DC&quot;,&quot;DS&quot;,..: 13 13 13 3 13 13 3 13 15 13 ...
##  $ Year.Release: Factor w/ 25 levels &quot;1985&quot;,&quot;1988&quot;,..: 15 17 18 15 15 18 14 16 19 18 ...
##  $ Genre       : Factor w/ 12 levels &quot;Action&quot;,&quot;Adventure&quot;,..: 11 7 11 5 4 5 7 11 4 11 ...
##  $ Publisher   : Factor w/ 262 levels &quot;10TACLE Studios&quot;,..: 164 164 164 164 164 164 164 164 147 164 ...
##  $ NA.Sales    : num  41360001 15680001 15610001 11280001 13960001 ...
##  $ EU.Sales    : num  28960001 12760001 10930001 9140001 9180001 ...
##  $ JP.Sales    : num  3770001 3790001 3280001 6500001 2930001 ...
##  $ Other.Sales : num  8450001 3290001 2950001 2880001 2840001 ...
##  $ Global.Sales: num  82530001 35520001 32770001 29800001 28920001 ...
##  $ Critic.Score: num  7.6 8.2 8 8.9 5.8 8.7 9.1 8 6.1 8 ...
##  $ Critic.Count: num  51 73 73 65 41 80 64 63 45 33 ...
##  $ User.Score  : num  8 8.3 8 8.5 6.6 8.4 8.6 7.7 6.3 7.4 ...
##  $ User.Count  : num  322 709 192 431 129 594 464 146 106 52 ...
##  $ Developer   : Factor w/ 1289 levels &quot;10tacle Studios, Fusionsphere Systems&quot;,..: 779 779 779 779 779 779 779 779 468 779 ...
##  $ Rating      : Factor w/ 7 levels &quot;AO&quot;,&quot;E&quot;,&quot;E10+&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int [1:9826] 2 5 6 10 11 13 19 21 22 23 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:9826] &quot;2&quot; &quot;5&quot; &quot;6&quot; &quot;10&quot; ...</code></pre>
<div class="sourceCode" id="cb820"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb820-1"><a href="the-game-sales-dataset.html#cb820-1" tabindex="-1"></a><span class="fu">summary</span>(game)</span></code></pre></div>
<pre><code>##                                         Name         Platform     Year.Release 
##  LEGO Star Wars II: The Original Trilogy  :   8   PS2    :1140   2008   : 592  
##  Madden NFL 07                            :   8   X360   : 858   2007   : 590  
##  Need for Speed: Most Wanted              :   8   PS3    : 769   2005   : 562  
##  Harry Potter and the Order of the Phoenix:   7   PC     : 651   2009   : 550  
##  Madden NFL 08                            :   7   XB     : 565   2006   : 528  
##  Need for Speed Carbon                    :   7   Wii    : 479   2003   : 498  
##  (Other)                                  :6780   (Other):2363   (Other):3505  
##           Genre                            Publisher       NA.Sales       
##  Action      :1630   Electronic Arts            : 944   Min.   :       1  
##  Sports      : 943   Ubisoft                    : 496   1st Qu.:   60001  
##  Shooter     : 864   Activision                 : 492   Median :  150001  
##  Role-Playing: 712   Sony Computer Entertainment: 316   Mean   :  394485  
##  Racing      : 581   THQ                        : 307   3rd Qu.:  390001  
##  Platform    : 403   Nintendo                   : 291   Max.   :41360001  
##  (Other)     :1692   (Other)                    :3979                     
##     EU.Sales           JP.Sales        Other.Sales        Global.Sales     
##  Min.   :       1   Min.   :      1   Min.   :       1   Min.   :   10001  
##  1st Qu.:   20001   1st Qu.:      1   1st Qu.:   10001   1st Qu.:  110001  
##  Median :   60001   Median :      1   Median :   20001   Median :  290001  
##  Mean   :  236090   Mean   :  64159   Mean   :   82678   Mean   :  777591  
##  3rd Qu.:  210001   3rd Qu.:  10001   3rd Qu.:   70001   3rd Qu.:  750001  
##  Max.   :28960001   Max.   :6500001   Max.   :10570001   Max.   :82530001  
##                                                                            
##   Critic.Score    Critic.Count      User.Score      User.Count     
##  Min.   :1.300   Min.   :  3.00   Min.   :0.500   Min.   :    4.0  
##  1st Qu.:6.200   1st Qu.: 14.00   1st Qu.:6.500   1st Qu.:   11.0  
##  Median :7.200   Median : 25.00   Median :7.500   Median :   27.0  
##  Mean   :7.027   Mean   : 28.93   Mean   :7.186   Mean   :  174.7  
##  3rd Qu.:8.000   3rd Qu.: 39.00   3rd Qu.:8.200   3rd Qu.:   89.0  
##  Max.   :9.800   Max.   :113.00   Max.   :9.600   Max.   :10665.0  
##                                                                    
##             Developer     Rating    
##  EA Canada       : 149   AO  :   1  
##  EA Sports       : 142   E   :2082  
##  Capcom          : 126   E10+: 930  
##  Ubisoft         : 103   K-A :   1  
##  Konami          :  95   M   :1433  
##  Ubisoft Montreal:  87   RP  :   1  
##  (Other)         :6123   T   :2377</code></pre>
<p>The summary reveals the existence of games published under the same banner (or name) but across various platforms; PlayStation 2(PS2) is the Goliath among platform; Action claims the throne as the genre of choice; Electronic Arts boasts the highest frequency among publishers; Rating T and E lead the rating pack; The sales data display small minimums, quantiles, and medians but boast heroic maximums, indicating the presence of superstar games; Exceedingly big maximum User Count hints at a cult-like following for certain titles.</p>
<p>Our pre-analysis shows that these variables are shy away from normality, notably the sales and score counts. To remedy this, we shall wield the power of logarithms!</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb822-1"><a href="the-game-sales-dataset.html#cb822-1" tabindex="-1"></a>NA.Sales.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>NA.Sales)   </span>
<span id="cb822-2"><a href="the-game-sales-dataset.html#cb822-2" tabindex="-1"></a>EU.Sales.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>EU.Sales)  </span>
<span id="cb822-3"><a href="the-game-sales-dataset.html#cb822-3" tabindex="-1"></a>JP.Sales.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>JP.Sales)   </span>
<span id="cb822-4"><a href="the-game-sales-dataset.html#cb822-4" tabindex="-1"></a>Other.Sales.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>Other.Sales)  </span>
<span id="cb822-5"><a href="the-game-sales-dataset.html#cb822-5" tabindex="-1"></a>Global.Sales.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>Global.Sales) </span>
<span id="cb822-6"><a href="the-game-sales-dataset.html#cb822-6" tabindex="-1"></a>Critic.Count.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>Critic.Count)</span>
<span id="cb822-7"><a href="the-game-sales-dataset.html#cb822-7" tabindex="-1"></a>User.Count.Log <span class="ot">&lt;-</span> <span class="fu">log</span>(game<span class="sc">$</span>User.Count)</span></code></pre></div>
<p>Now let’s bind the log-transformed variables with their original counterparts.</p>
<div class="sourceCode" id="cb823"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb823-1"><a href="the-game-sales-dataset.html#cb823-1" tabindex="-1"></a>game.log <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(NA.Sales.Log, EU.Sales.Log, JP.Sales.Log, Other.Sales.Log,</span>
<span id="cb823-2"><a href="the-game-sales-dataset.html#cb823-2" tabindex="-1"></a>Global.Sales.Log, Critic.Count.Log, User.Count.Log)</span>
<span id="cb823-3"><a href="the-game-sales-dataset.html#cb823-3" tabindex="-1"></a>game <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(game, game.log)  <span class="co"># The data we use for analysis</span></span></code></pre></div>
<p>Time to conjure histograms and QQ plots for our transformed dataset.</p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb824-1"><a href="the-game-sales-dataset.html#cb824-1" tabindex="-1"></a><span class="co"># Select numeric columns for visualization</span></span>
<span id="cb824-2"><a href="the-game-sales-dataset.html#cb824-2" tabindex="-1"></a>name <span class="ot">&lt;-</span> <span class="fu">colnames</span>(game)[<span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="sc">:</span><span class="dv">23</span>)] </span>
<span id="cb824-3"><a href="the-game-sales-dataset.html#cb824-3" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>))  <span class="co"># Layout in 5 rows and 4 columns</span></span>
<span id="cb824-4"><a href="the-game-sales-dataset.html#cb824-4" tabindex="-1"></a></span>
<span id="cb824-5"><a href="the-game-sales-dataset.html#cb824-5" tabindex="-1"></a><span class="co"># Loop through each numeric variable and create a histogram and a Q-Q plot</span></span>
<span id="cb824-6"><a href="the-game-sales-dataset.html#cb824-6" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(name)){</span>
<span id="cb824-7"><a href="the-game-sales-dataset.html#cb824-7" tabindex="-1"></a>  sub <span class="ot">&lt;-</span> <span class="fu">sample</span>(game[name[i]][, <span class="dv">1</span>], <span class="dv">5000</span>)</span>
<span id="cb824-8"><a href="the-game-sales-dataset.html#cb824-8" tabindex="-1"></a>  submean <span class="ot">&lt;-</span> <span class="fu">mean</span>(sub)</span>
<span id="cb824-9"><a href="the-game-sales-dataset.html#cb824-9" tabindex="-1"></a>  <span class="fu">hist</span>(sub, <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">&quot;Hist. of&quot;</span>, name[i], <span class="at">sep =</span> <span class="st">&quot; &quot;</span>), <span class="at">xlab =</span> name[i])</span>
<span id="cb824-10"><a href="the-game-sales-dataset.html#cb824-10" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">v =</span> submean, <span class="at">col =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb824-11"><a href="the-game-sales-dataset.html#cb824-11" tabindex="-1"></a>  <span class="fu">qqnorm</span>(sub, <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">&quot;Q-Q Plot of&quot;</span>, name[i], <span class="at">sep =</span> <span class="st">&quot; &quot;</span>))</span>
<span id="cb824-12"><a href="the-game-sales-dataset.html#cb824-12" tabindex="-1"></a>  <span class="fu">qqline</span>(sub) </span>
<span id="cb824-13"><a href="the-game-sales-dataset.html#cb824-13" tabindex="-1"></a>  <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">1</span>) {s.t <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(sub)</span>
<span id="cb824-14"><a href="the-game-sales-dataset.html#cb824-14" tabindex="-1"></a>  } <span class="cf">else</span> {s.t <span class="ot">&lt;-</span> <span class="fu">rbind</span>(s.t, <span class="fu">shapiro.test</span>(sub))</span>
<span id="cb824-15"><a href="the-game-sales-dataset.html#cb824-15" tabindex="-1"></a> }</span>
<span id="cb824-16"><a href="the-game-sales-dataset.html#cb824-16" tabindex="-1"></a>}</span>
<span id="cb824-17"><a href="the-game-sales-dataset.html#cb824-17" tabindex="-1"></a><span class="co"># Extract the essence of the Shapiro-Wilk test results</span></span>
<span id="cb824-18"><a href="the-game-sales-dataset.html#cb824-18" tabindex="-1"></a>s.t <span class="ot">&lt;-</span> s.t[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]  <span class="co"># Take first two columns of shapiro.test result</span></span>
<span id="cb824-19"><a href="the-game-sales-dataset.html#cb824-19" tabindex="-1"></a>s.t <span class="ot">&lt;-</span> <span class="fu">cbind</span>(name, s.t) <span class="co"># Add variable name for the result</span></span>
<span id="cb824-20"><a href="the-game-sales-dataset.html#cb824-20" tabindex="-1"></a>s.t</span></code></pre></div>
<pre><code>##     name               statistic p.value     
## s.t &quot;Critic.Score&quot;     0.9639289 1.340987e-33
##     &quot;User.Score&quot;       0.9142633 1.176085e-46
##     &quot;NA.Sales.Log&quot;     0.6501188 1.278253e-72
##     &quot;EU.Sales.Log&quot;     0.7139223 1.531191e-68
##     &quot;JP.Sales.Log&quot;     0.6194571 2.339768e-74
##     &quot;Other.Sales.Log&quot;  0.7094548 7.506174e-69
##     &quot;Global.Sales.Log&quot; 0.9970272 2.198802e-08
##     &quot;Critic.Count.Log&quot; 0.9772805 1.537995e-27
##     &quot;User.Count.Log&quot;   0.9411244 1.029132e-40</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-459-1.png" width="768" />
The histograms and QQ plots of these original sales are not abnormally distributed, but the log-transformed sales data now resemble much clearer and close to normal distributions, especially the log value of global sales. Even though the Shapiro test, with a p-value less than 0.05, seems to dispel the illusion of normality, it’s nearly a portrait of normality. Perhaps the absentee values are the reason for the abnormality of the raw sales data. Our analytic crystal ball will gaze more intently upon the log of global sales.</p>
<p>The histograms and QQ plots also suggest that the two scores and log-transformed counts are doing a tantalizing tango with normal distribution. Despite the Shapiro-Wilk test’s naysaying, we’ll proceed under the assumption that they are normally distributed for our analysis.</p>
<p>In this realm of data, there lie intriguing enigmas: the distribution dance of global versus regional sales; the web of relationships between them; the mystical connection between critic and user scores along with their respective counts; and whether these scores and counts cast the most potent spells on sales, or if other arcane elements such as genre, rating, platform, and publisher have a part to play in this grand sales ritual.</p>
<p>Now let’s wave our wands for some visual magic!</p>
</div>
<div id="visualization-of-categorical-variables" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Visualization of categorical variables<a href="the-game-sales-dataset.html#visualization-of-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To simplify platform analysis, we regroup platform into a new variable called Platform.type.</p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="the-game-sales-dataset.html#cb826-1" tabindex="-1"></a><span class="co"># Regroup platform into Platform.type categories</span></span>
<span id="cb826-2"><a href="the-game-sales-dataset.html#cb826-2" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;PC&quot;</span>)</span>
<span id="cb826-3"><a href="the-game-sales-dataset.html#cb826-3" tabindex="-1"></a>xbox <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;X360&quot;</span>, <span class="st">&quot;XB&quot;</span>, <span class="st">&quot;XOne&quot;</span>)</span>
<span id="cb826-4"><a href="the-game-sales-dataset.html#cb826-4" tabindex="-1"></a>nintendo <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Wii&quot;</span>, <span class="st">&quot;WiiU&quot;</span>, <span class="st">&quot;N64&quot;</span>, <span class="st">&quot;GC&quot;</span>, <span class="st">&quot;NES&quot;</span>, <span class="st">&quot;3DS&quot;</span>, <span class="st">&quot;DS&quot;</span>) </span>
<span id="cb826-5"><a href="the-game-sales-dataset.html#cb826-5" tabindex="-1"></a>playstation <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;PS&quot;</span>, <span class="st">&quot;PS2&quot;</span>, <span class="st">&quot;PS3&quot;</span>, <span class="st">&quot;PS4&quot;</span>, <span class="st">&quot;PSP&quot;</span>, <span class="st">&quot;PSV&quot;</span>)</span>
<span id="cb826-6"><a href="the-game-sales-dataset.html#cb826-6" tabindex="-1"></a>game <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span></span>
<span id="cb826-7"><a href="the-game-sales-dataset.html#cb826-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Platform.type =</span> <span class="fu">ifelse</span>(Platform <span class="sc">%in%</span> pc, <span class="st">&quot;PC&quot;</span>,</span>
<span id="cb826-8"><a href="the-game-sales-dataset.html#cb826-8" tabindex="-1"></a>                           <span class="fu">ifelse</span>(Platform <span class="sc">%in%</span> xbox, <span class="st">&quot;Xbox&quot;</span>,</span>
<span id="cb826-9"><a href="the-game-sales-dataset.html#cb826-9" tabindex="-1"></a>                             <span class="fu">ifelse</span>(Platform <span class="sc">%in%</span> nintendo, <span class="st">&quot;Nintendo&quot;</span>, </span>
<span id="cb826-10"><a href="the-game-sales-dataset.html#cb826-10" tabindex="-1"></a>                               <span class="fu">ifelse</span>(Platform <span class="sc">%in%</span> playstation, <span class="st">&quot;Playstation&quot;</span>, <span class="st">&quot;Others&quot;</span>))))) </span></code></pre></div>

<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="the-game-sales-dataset.html#cb827-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb827-2"><a href="the-game-sales-dataset.html#cb827-2" tabindex="-1"></a><span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> Platform.type)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-PlatformType1"></span>
<img src="book_files/figure-html/game-PlatformType1-1.png" alt="Bar plot of platform type." width="672" />
<p class="caption">
Figure 9.1: Bar plot of platform type.
</p>
</div>
<p>The bar plot regales us with a tale of platform dominance: Playstation leads the charge, followed by Xbox and Nintendo, with the “Others” trailing behind.</p>
<p>The realm of genres is a diverse landscape, but let’s see who really rules the land.</p>
<div class="sourceCode" id="cb828"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb828-1"><a href="the-game-sales-dataset.html#cb828-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(game<span class="sc">$</span>Genre))</span>
<span id="cb828-2"><a href="the-game-sales-dataset.html#cb828-2" tabindex="-1"></a>dat<span class="sc">$</span>fraction <span class="ot">&lt;-</span> dat<span class="sc">$</span>Freq <span class="sc">/</span> <span class="fu">sum</span>(dat<span class="sc">$</span>Freq)</span>
<span id="cb828-3"><a href="the-game-sales-dataset.html#cb828-3" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[<span class="fu">order</span>(dat<span class="sc">$</span>fraction), ]</span>
<span id="cb828-4"><a href="the-game-sales-dataset.html#cb828-4" tabindex="-1"></a>dat<span class="sc">$</span>ymax <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(dat<span class="sc">$</span>fraction)</span>
<span id="cb828-5"><a href="the-game-sales-dataset.html#cb828-5" tabindex="-1"></a>dat<span class="sc">$</span>ymin <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">head</span>(dat<span class="sc">$</span>ymax, <span class="at">n =</span> <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb828-6"><a href="the-game-sales-dataset.html#cb828-6" tabindex="-1"></a><span class="fu">names</span>(dat)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Genre&quot;</span></span>
<span id="cb828-7"><a href="the-game-sales-dataset.html#cb828-7" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb828-8"><a href="the-game-sales-dataset.html#cb828-8" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">fill =</span> Genre, <span class="at">ymax =</span> ymax, <span class="at">ymin =</span> ymin, <span class="at">xmax =</span> <span class="dv">4</span>, <span class="at">xmin =</span> <span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb828-9"><a href="the-game-sales-dataset.html#cb828-9" tabindex="-1"></a>  <span class="fu">geom_rect</span>(<span class="at">colour =</span> <span class="st">&quot;grey30&quot;</span>) <span class="sc">+</span>  <span class="co"># Background color</span></span>
<span id="cb828-10"><a href="the-game-sales-dataset.html#cb828-10" tabindex="-1"></a>  <span class="fu">coord_polar</span>(<span class="at">theta =</span> <span class="st">&quot;y&quot;</span>) <span class="sc">+</span>  <span class="co"># Coordinate system to polar</span></span>
<span id="cb828-11"><a href="the-game-sales-dataset.html#cb828-11" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>)) <span class="sc">+</span>  </span>
<span id="cb828-12"><a href="the-game-sales-dataset.html#cb828-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Ring plot for Genre&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;Genre&quot;</span>) <span class="sc">+</span></span>
<span id="cb828-13"><a href="the-game-sales-dataset.html#cb828-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-461-1.png" width="672" /></p>
<p>The Genre ring plot crowns Action, Sports, and Shooter as the mightiest triumvirate, with Action occupies nearly a quarter of genre kingdom. Combined, these three genres account for more than half the realm. Puzzle, Adventure, and Stratege have relatively less count.</p>
<p>Now let’s consolidate the rare ratings AO, RP, and K-A under “Others” due to their sparse data points.</p>
<div class="sourceCode" id="cb829"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb829-1"><a href="the-game-sales-dataset.html#cb829-1" tabindex="-1"></a><span class="co"># Consolidate Ratings into Rating.type </span></span>
<span id="cb829-2"><a href="the-game-sales-dataset.html#cb829-2" tabindex="-1"></a>rating <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;E&quot;</span>, <span class="st">&quot;T&quot;</span>, <span class="st">&quot;M&quot;</span>, <span class="st">&quot;E10+&quot;</span>)</span>
<span id="cb829-3"><a href="the-game-sales-dataset.html#cb829-3" tabindex="-1"></a>game <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span> </span>
<span id="cb829-4"><a href="the-game-sales-dataset.html#cb829-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Rating.type =</span> <span class="fu">ifelse</span>(Rating <span class="sc">%in%</span> rating, <span class="fu">as.character</span>(Rating), <span class="st">&quot;Others&quot;</span>)) </span></code></pre></div>
<p>Let’s slice up the ratings pie chart of gamers’ preferred flavors.</p>
<div class="sourceCode" id="cb830"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb830-1"><a href="the-game-sales-dataset.html#cb830-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">table</span>(game<span class="sc">$</span>Rating.type), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb830-2"><a href="the-game-sales-dataset.html#cb830-2" tabindex="-1"></a><span class="co"># Rename the names of counts for detail information</span></span>
<span id="cb830-3"><a href="the-game-sales-dataset.html#cb830-3" tabindex="-1"></a><span class="fu">names</span>(counts) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;T - Teen&quot;</span>, <span class="st">&quot;E - Everyone&quot;</span>, <span class="st">&quot;M - Mature&quot;</span>, <span class="st">&quot;E10+ - Everyone 10+&quot;</span>, <span class="st">&quot;Others&quot;</span>)</span>
<span id="cb830-4"><a href="the-game-sales-dataset.html#cb830-4" tabindex="-1"></a>pct <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">round</span>(counts<span class="sc">/</span><span class="fu">sum</span>(counts) <span class="sc">*</span> <span class="dv">100</span>), <span class="st">&quot;%&quot;</span>, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)</span>
<span id="cb830-5"><a href="the-game-sales-dataset.html#cb830-5" tabindex="-1"></a>lbls <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">names</span>(counts), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>, pct, <span class="at">sep =</span> <span class="st">&quot; &quot;</span>)  <span class="co"># Rating information and percentage</span></span>
<span id="cb830-6"><a href="the-game-sales-dataset.html#cb830-6" tabindex="-1"></a><span class="fu">pie</span>(counts, <span class="at">labels =</span> lbls, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="fu">length</span>(lbls)),</span>
<span id="cb830-7"><a href="the-game-sales-dataset.html#cb830-7" tabindex="-1"></a>  <span class="at">main=</span><span class="st">&quot;Pie Chart of Ratings with sample sizes&quot;</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-463-1.png" width="672" /></p>
<p>The pie chart reveals that the popular ratings are T, E, M, and E10+, according to the order. While “Others” claims but a sliver of the pie.</p>

<div class="sourceCode" id="cb831"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb831-1"><a href="the-game-sales-dataset.html#cb831-1" tabindex="-1"></a><span class="fu">library</span>(ggmosaic)</span>
<span id="cb831-2"><a href="the-game-sales-dataset.html#cb831-2" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb831-3"><a href="the-game-sales-dataset.html#cb831-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game) <span class="sc">+</span></span>
<span id="cb831-4"><a href="the-game-sales-dataset.html#cb831-4" tabindex="-1"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(Rating.type), <span class="at">fill =</span> Platform.type), <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb831-5"><a href="the-game-sales-dataset.html#cb831-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Rating Type&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Platform Type&quot;</span>, <span class="at">title=</span><span class="st">&quot;Mosaic Plot&quot;</span>) <span class="sc">+</span></span>
<span id="cb831-6"><a href="the-game-sales-dataset.html#cb831-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())</span>
<span id="cb831-7"><a href="the-game-sales-dataset.html#cb831-7" tabindex="-1"></a><span class="fu">ggplotly</span>(p)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-mosaic"></span>
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-3f0b59ea7f18d56ccdd0" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-3f0b59ea7f18d56ccdd0">{"x":{"data":[{"x":[0,0,0.29285274725274729,0.29285274725274729,0],"y":[0,0.30306490953803827,0.30306490953803827,0,0],"text":"Nintendo<br>E<br>Frequency: 656","key":["Nintendo","E"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(248,118,109,0.8)","hoveron":"fills","name":"Nintendo","legendgroup":"Nintendo","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.3028527472527473,0.3028527472527473,0.43366593406593407,0.43366593406593407,0.3028527472527473],"y":[0,0.38991589693997475,0.38991589693997475,0,0],"text":"Nintendo<br>E10+<br>Frequency: 377","key":["Nintendo","E10+"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(248,118,109,0.8)","hoveron":"fills","name":"Nintendo","legendgroup":"Nintendo","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.44366593406593408,0.44366593406593408,0.64523076923076927,0.64523076923076927,0.44366593406593408],"y":[0,0.065779781332977863,0.065779781332977863,0,0],"text":"Nintendo<br>M<br>Frequency: 98","key":["Nintendo","M"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(248,118,109,0.8)","hoveron":"fills","name":"Nintendo","legendgroup":"Nintendo","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.65523076923076928,0.65523076923076928,0.65565274725274736,0.65565274725274736,0.65523076923076928],"y":[0,0,0,0,0],"text":"Nintendo<br>Others<br>Frequency: 0","key":["Nintendo","Others"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(248,118,109,0.8)","hoveron":"fills","name":"Nintendo","legendgroup":"Nintendo","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.66565274725274726,0.66565274725274726,1,1,0.66565274725274726],"y":[0,0.16348003557332402,0.16348003557332402,0,0],"text":"Nintendo<br>T<br>Frequency: 404","key":["Nintendo","T"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(248,118,109,0.8)","hoveron":"fills","name":"Nintendo","legendgroup":"Nintendo","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0,0,0.29285274725274729,0.29285274725274729,0],"y":[0.31259953543049418,0.39206167634595546,0.39206167634595546,0.31259953543049418,0.31259953543049418],"text":"Others<br>E<br>Frequency: 172","key":["Others","E"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(163,165,0,0.8)","hoveron":"fills","name":"Others","legendgroup":"Others","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.3028527472527473,0.3028527472527473,0.43366593406593407,0.43366593406593407,0.3028527472527473],"y":[0.39945052283243065,0.41806719695688571,0.41806719695688571,0.39945052283243065,0.39945052283243065],"text":"Others<br>E10+<br>Frequency: 18","key":["Others","E10+"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(163,165,0,0.8)","hoveron":"fills","name":"Others","legendgroup":"Others","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.44366593406593408,0.44366593406593408,0.64523076923076927,0.64523076923076927,0.44366593406593408],"y":[0.075314407225433783,0.080012963034932202,0.080012963034932202,0.075314407225433783,0.075314407225433783],"text":"Others<br>M<br>Frequency: 7","key":["Others","M"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(163,165,0,0.8)","hoveron":"fills","name":"Others","legendgroup":"Others","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.65523076923076928,0.65523076923076928,0.65565274725274736,0.65565274725274736,0.65523076923076928],"y":[0.0095346258924559248,0.0095346258924559248,0.0095346258924559248,0.0095346258924559248,0.0095346258924559248],"text":"Others<br>Others<br>Frequency: 0","key":["Others","Others"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(163,165,0,0.8)","hoveron":"fills","name":"Others","legendgroup":"Others","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.66565274725274726,0.66565274725274726,1,1,0.66565274725274726],"y":[0.17301466146577996,0.19486595334934306,0.19486595334934306,0.17301466146577996,0.17301466146577996],"text":"Others<br>T<br>Frequency: 54","key":["Others","T"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(163,165,0,0.8)","hoveron":"fills","name":"Others","legendgroup":"Others","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0,0,0.29285274725274729,0.29285274725274729,0],"y":[0.40159630223841136,0.4473332321839385,0.4473332321839385,0.40159630223841136,0.40159630223841136],"text":"PC<br>E<br>Frequency: 99","key":["PC","E"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,191,125,0.8)","hoveron":"fills","name":"PC","legendgroup":"PC","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.3028527472527473,0.3028527472527473,0.43366593406593407,0.43366593406593407,0.3028527472527473],"y":[0.42760182284934162,0.49276018228493423,0.49276018228493423,0.42760182284934162,0.42760182284934162],"text":"PC<br>E10+<br>Frequency: 63","key":["PC","E10+"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,191,125,0.8)","hoveron":"fills","name":"PC","legendgroup":"PC","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.44366593406593408,0.44366593406593408,0.64523076923076927,0.64523076923076927,0.44366593406593408],"y":[0.089547588927388122,0.25198337548433347,0.25198337548433347,0.089547588927388122,0.089547588927388122],"text":"PC<br>M<br>Frequency: 242","key":["PC","M"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,191,125,0.8)","hoveron":"fills","name":"PC","legendgroup":"PC","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.65523076923076928,0.65523076923076928,0.65565274725274736,0.65565274725274736,0.65523076923076928],"y":[0.01906925178491185,0.33968975059497064,0.33968975059497064,0.01906925178491185,0.01906925178491185],"text":"PC<br>Others<br>Frequency: 1","key":["PC","Others"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,191,125,0.8)","hoveron":"fills","name":"PC","legendgroup":"PC","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.66565274725274726,0.66565274725274726,1,1,0.66565274725274726],"y":[0.204400579241799,0.30394535337803097,0.30394535337803097,0.204400579241799,0.204400579241799],"text":"PC<br>T<br>Frequency: 246","key":["PC","T"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,191,125,0.8)","hoveron":"fills","name":"PC","legendgroup":"PC","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0,0,0.29285274725274729,0.29285274725274729,0],"y":[0.45686785807639441,0.81075157866501835,0.81075157866501835,0.45686785807639441,0.45686785807639441],"text":"Playstation<br>E<br>Frequency: 766","key":["Playstation","E"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,176,246,0.8)","hoveron":"fills","name":"Playstation","legendgroup":"Playstation","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.3028527472527473,0.3028527472527473,0.43366593406593407,0.43366593406593407,0.3028527472527473],"y":[0.50229480817739014,0.81257271025164057,0.81257271025164057,0.50229480817739014,0.50229480817739014],"text":"Playstation<br>E10+<br>Frequency: 300","key":["Playstation","E10+"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,176,246,0.8)","hoveron":"fills","name":"Playstation","legendgroup":"Playstation","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.44366593406593408,0.44366593406593408,0.64523076923076927,0.64523076923076927,0.44366593406593408],"y":[0.26151800137678943,0.67364846809565071,0.67364846809565071,0.26151800137678943,0.26151800137678943],"text":"Playstation<br>M<br>Frequency: 614","key":["Playstation","M"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,176,246,0.8)","hoveron":"fills","name":"Playstation","legendgroup":"Playstation","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.65523076923076928,0.65523076923076928,0.65565274725274736,0.65565274725274736,0.65523076923076928],"y":[0.34922437648742655,0.66984487529748526,0.66984487529748526,0.34922437648742655,0.34922437648742655],"text":"Playstation<br>Others<br>Frequency: 1","key":["Playstation","Others"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,176,246,0.8)","hoveron":"fills","name":"Playstation","legendgroup":"Playstation","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.66565274725274726,0.66565274725274726,1,1,0.66565274725274726],"y":[0.31347997927048687,0.76871522684471838,0.76871522684471838,0.31347997927048687,0.31347997927048687],"text":"Playstation<br>T<br>Frequency: 1125","key":["Playstation","T"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(0,176,246,0.8)","hoveron":"fills","name":"Playstation","legendgroup":"Playstation","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0,0,0.29285274725274729,0.29285274725274729,0],"y":[0.82028620455747425,1,1,0.82028620455747425,0.82028620455747425],"text":"Xbox<br>E<br>Frequency: 389","key":["Xbox","E"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(231,107,243,0.8)","hoveron":"fills","name":"Xbox","legendgroup":"Xbox","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.3028527472527473,0.3028527472527473,0.43366593406593407,0.43366593406593407,0.3028527472527473],"y":[0.82210733614409648,1,1,0.82210733614409648,0.82210733614409648],"text":"Xbox<br>E10+<br>Frequency: 172","key":["Xbox","E10+"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(231,107,243,0.8)","hoveron":"fills","name":"Xbox","legendgroup":"Xbox","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.44366593406593408,0.44366593406593408,0.64523076923076927,0.64523076923076927,0.44366593406593408],"y":[0.68318309398810662,1,1,0.68318309398810662,0.68318309398810662],"text":"Xbox<br>M<br>Frequency: 472","key":["Xbox","M"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(231,107,243,0.8)","hoveron":"fills","name":"Xbox","legendgroup":"Xbox","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.65523076923076928,0.65523076923076928,0.65565274725274736,0.65565274725274736,0.65523076923076928],"y":[0.67937950118994128,1,1,0.67937950118994128,0.67937950118994128],"text":"Xbox<br>Others<br>Frequency: 1","key":["Xbox","Others"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(231,107,243,0.8)","hoveron":"fills","name":"Xbox","legendgroup":"Xbox","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null},{"x":[0.66565274725274726,0.66565274725274726,1,1,0.66565274725274726],"y":[0.7782498527371744,1,1,0.7782498527371744,0.7782498527371744],"text":"Xbox<br>T<br>Frequency: 548","key":["Xbox","T"],"type":"scatter","mode":"lines","line":{"width":0.37795275590551186,"color":"transparent","dash":"solid"},"fill":"toself","fillcolor":"rgba(231,107,243,0.8)","hoveron":"fills","name":"Xbox","legendgroup":"Xbox","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","_isSimpleKey":true,"_isNestedKey":false,"frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":25.570776255707766},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"Mosaic Plot","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.050000000000000003,1.05],"tickmode":"array","ticktext":["E","E10+","M","Others","T"],"tickvals":[0.14642637362637367,0.36825934065934068,0.54444835164835181,0.65544175824175832,0.83282637362637368],"categoryorder":"array","categoryarray":["E","E10+","M","Others","T"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"Rating Type","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-0.050000000000000003,1.05],"tickmode":"array","ticktext":["Nintendo","Others","PC","Playstation","Xbox"],"tickvals":[0.15153245476901916,0.35233060588822485,0.42446476721117493,0.63380971837070632,0.91014310227873707],"categoryorder":"array","categoryarray":["Nintendo","Others","PC","Playstation","Xbox"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":false,"tickfont":{"color":null,"family":null,"size":0},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"Platform Type","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"Platform.type","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5084307c7713":{"x":{},"fill":{},"y":{},"x__fill__Platform.type":{},"x__Rating.type":{},"type":"scatter"}},"cur_data":"5084307c7713","visdat":{"5084307c7713":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p class="caption">
Figure 9.2: Mosaic plot between platform type and rating type.
</p>
</div>
<p>Same as we noticed previously, the mosaic plot reiterates that ‘Others’ is barely visible due to its minuscule size. For all platform and rating combinations, Playstation dominates the platform ratings for all other three different rating types except for Everyone 10 plus. Nintendo captures the heart of the “Everyone 10+” category. It’s the second most popular platform for rating Everyone. Xbox holds steady as the runner-up in Mature and Teenage categories, and holds the third favorite platform for rating Everyone and Everyone 10 plus. In the category of ‘Others’, games rated ‘Everyone’ are the chosen ones.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-464}</p>
</blockquote>
<blockquote>
<p>Download the game sales dataset and clean the data as previously outlined at the beginning of this chapter. Then, produce a mosaic plot between genre and rating. Briefly interpret your mystical creation.
:::</p>
</blockquote>
</div>
<div id="correlation-among-numeric-variables" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Correlation among numeric variables<a href="the-game-sales-dataset.html#correlation-among-numeric-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="sourceCode" id="cb832"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb832-1"><a href="the-game-sales-dataset.html#cb832-1" tabindex="-1"></a>st <span class="ot">&lt;-</span> game[, <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="sc">:</span><span class="dv">23</span>)] <span class="co"># Select the numeric variables of interest</span></span>
<span id="cb832-2"><a href="the-game-sales-dataset.html#cb832-2" tabindex="-1"></a>st <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(st)</span>
<span id="cb832-3"><a href="the-game-sales-dataset.html#cb832-3" tabindex="-1"></a><span class="fu">library</span>(ellipse)  </span>
<span id="cb832-4"><a href="the-game-sales-dataset.html#cb832-4" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb832-5"><a href="the-game-sales-dataset.html#cb832-5" tabindex="-1"></a>corMatrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="fu">as.matrix</span>(st))  <span class="co"># Correlation matrix</span></span>
<span id="cb832-6"><a href="the-game-sales-dataset.html#cb832-6" tabindex="-1"></a>col <span class="ot">&lt;-</span> <span class="fu">colorRampPalette</span>(<span class="fu">c</span>(<span class="st">&quot;#7F0000&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;#FF7F00&quot;</span>, <span class="st">&quot;yellow&quot;</span>, <span class="st">&quot;#7FFF7F&quot;</span>,</span>
<span id="cb832-7"><a href="the-game-sales-dataset.html#cb832-7" tabindex="-1"></a>                           <span class="st">&quot;cyan&quot;</span>, <span class="st">&quot;#007FFF&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;#00007F&quot;</span>))</span>
<span id="cb832-8"><a href="the-game-sales-dataset.html#cb832-8" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(corMatrix, <span class="at">order =</span> <span class="st">&quot;AOE&quot;</span>, <span class="at">lower =</span> <span class="st">&quot;number&quot;</span>, <span class="at">lower.col =</span> <span class="st">&quot;black&quot;</span>, </span>
<span id="cb832-9"><a href="the-game-sales-dataset.html#cb832-9" tabindex="-1"></a>               <span class="at">number.cex =</span> .<span class="dv">8</span>, <span class="at">upper =</span> <span class="st">&quot;ellipse&quot;</span>,  <span class="at">upper.col =</span> <span class="fu">col</span>(<span class="dv">10</span>), </span>
<span id="cb832-10"><a href="the-game-sales-dataset.html#cb832-10" tabindex="-1"></a>               <span class="at">diag =</span> <span class="st">&quot;u&quot;</span>, <span class="at">tl.pos =</span> <span class="st">&quot;lt&quot;</span>, <span class="at">tl.col =</span> <span class="st">&quot;black&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-corrplot"></span>
<img src="book_files/figure-html/game-corrplot-1.png" alt="Corrplot among numeric variables." width="768" />
<p class="caption">
Figure 9.3: Corrplot among numeric variables.
</p>
</div>
<p>With high r-values of 0.75, 0.65, 0.52, and 0.42 between the log-transformed values of Global.Sales and regional sales, We’ll earmark Global.Sales.Log as our target for later romance with other variables. Also, regional sales are positively flirting with one another. User Score is sweet to Critic Score with an r of 0.58. The correlation between User Count log and User Score stays relatively low.</p>

<div class="sourceCode" id="cb833"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb833-1"><a href="the-game-sales-dataset.html#cb833-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">hclust</span>(<span class="fu">as.dist</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">cor</span>(<span class="fu">as.matrix</span>(st)))))  <span class="co"># Hierarchical clustering</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-dendrogram"></span>
<img src="book_files/figure-html/game-dendrogram-1.png" alt="Exercise dendrogram for numeric variables." width="672" />
<p class="caption">
Figure 9.4: Exercise dendrogram for numeric variables.
</p>
</div>
<p>In this dendrogram, all log values of sales except JP.Sales.Log build one cluster like best friends; Scores, log values of counts, along with JP.Sales form their own clique. In the first cluster, Other.Sales.Log is whispering closest to Global.Sales.Log, followed by NA.Sales.Log, with EU.Sales.Log joining the fray.</p>
</div>
<div id="analysis-of-score-and-count" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Analysis of score and count<a href="the-game-sales-dataset.html#analysis-of-score-and-count" class="anchor-section" aria-label="Anchor link to header"></a></h2>

<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb834-1"><a href="the-game-sales-dataset.html#cb834-1" tabindex="-1"></a><span class="fu">library</span>(ggpmisc)  <span class="co"># Package for function stat_poly_eq(), adding equations to plots</span></span>
<span id="cb834-2"><a href="the-game-sales-dataset.html#cb834-2" tabindex="-1"></a>formula <span class="ot">&lt;-</span> y <span class="sc">~</span> x</span>
<span id="cb834-3"><a href="the-game-sales-dataset.html#cb834-3" tabindex="-1"></a></span>
<span id="cb834-4"><a href="the-game-sales-dataset.html#cb834-4" tabindex="-1"></a><span class="co"># A scatter plot that reveals the hidden dance between User Score and Critic Score</span></span>
<span id="cb834-5"><a href="the-game-sales-dataset.html#cb834-5" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> User.Score, <span class="at">y =</span> Critic.Score)) <span class="sc">+</span> </span>
<span id="cb834-6"><a href="the-game-sales-dataset.html#cb834-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Platform), <span class="at">alpha =</span> .<span class="dv">8</span>) <span class="sc">+</span> </span>
<span id="cb834-7"><a href="the-game-sales-dataset.html#cb834-7" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">formula =</span> formula) <span class="sc">+</span>  <span class="co"># Add regression line</span></span>
<span id="cb834-8"><a href="the-game-sales-dataset.html#cb834-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb834-9"><a href="the-game-sales-dataset.html#cb834-9" tabindex="-1"></a>  <span class="fu">stat_poly_eq</span>(<span class="at">formula =</span> formula,   <span class="co"># Add regression equation and R square value</span></span>
<span id="cb834-10"><a href="the-game-sales-dataset.html#cb834-10" tabindex="-1"></a>               <span class="at">eq.with.lhs =</span> <span class="st">&quot;italic(hat(y))~`=`~&quot;</span>,  <span class="co"># Add ^ on y</span></span>
<span id="cb834-11"><a href="the-game-sales-dataset.html#cb834-11" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste</span>(..eq.label.., ..rr.label.., <span class="at">sep =</span> <span class="st">&quot;*plain(</span><span class="sc">\&quot;</span><span class="st">,</span><span class="sc">\&quot;</span><span class="st">)~&quot;</span>)),</span>
<span id="cb834-12"><a href="the-game-sales-dataset.html#cb834-12" tabindex="-1"></a>               <span class="at">label.x.npc =</span> <span class="st">&quot;left&quot;</span>, <span class="at">label.y.npc =</span> <span class="fl">0.9</span>,   <span class="co"># Position of the equation label</span></span>
<span id="cb834-13"><a href="the-game-sales-dataset.html#cb834-13" tabindex="-1"></a>               <span class="at">parse =</span> <span class="cn">TRUE</span>)  <span class="co"># Output.type as &quot;expression&quot; </span></span>
<span id="cb834-14"><a href="the-game-sales-dataset.html#cb834-14" tabindex="-1"></a></span>
<span id="cb834-15"><a href="the-game-sales-dataset.html#cb834-15" tabindex="-1"></a><span class="co"># Density plot - where scores show off their curves</span></span>
<span id="cb834-16"><a href="the-game-sales-dataset.html#cb834-16" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb834-17"><a href="the-game-sales-dataset.html#cb834-17" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> game, <span class="fu">aes</span>(<span class="at">x =</span> Critic.Score), <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb834-18"><a href="the-game-sales-dataset.html#cb834-18" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">data =</span> game, <span class="fu">aes</span>(<span class="at">x =</span> User.Score), <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;lightgreen&quot;</span>,                                       <span class="at">alpha=</span>.<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb834-19"><a href="the-game-sales-dataset.html#cb834-19" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Critic.Score-blue, User.Score-green&quot;</span>) </span>
<span id="cb834-20"><a href="the-game-sales-dataset.html#cb834-20" tabindex="-1"></a></span>
<span id="cb834-21"><a href="the-game-sales-dataset.html#cb834-21" tabindex="-1"></a><span class="co"># Combine the plots for a double feature</span></span>
<span id="cb834-22"><a href="the-game-sales-dataset.html#cb834-22" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb834-23"><a href="the-game-sales-dataset.html#cb834-23" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-score"></span>
<img src="book_files/figure-html/game-score-1.png" alt="Scatter and density plot for critic score and user score." width="960" />
<p class="caption">
Figure 9.5: Scatter and density plot for critic score and user score.
</p>
</div>
<p>A positive correlation waltzes between Critic.Score and User.Score. It seems the critics are a tough crowd, scoring on average lower than users.</p>
<div class="sourceCode" id="cb835"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb835-1"><a href="the-game-sales-dataset.html#cb835-1" tabindex="-1"></a><span class="fu">t.test</span>(game<span class="sc">$</span>Critic.Score, game<span class="sc">$</span>User.Score)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  game$Critic.Score and game$User.Score
## t = -6.5463, df = 13629, p-value = 6.108e-11
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2058518 -0.1109834
## sample estimates:
## mean of x mean of y 
##  7.027209  7.185626</code></pre>
<p>T-test with a p-value of much less than 0.05 suggests to accept the alternative hypothesis with 95% confidence: the difference between critic and user scores is not by mere chance. The mean critic score prances at 7.03, while the mean user score frolics slightly higher at 7.19.</p>

<div class="sourceCode" id="cb837"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb837-1"><a href="the-game-sales-dataset.html#cb837-1" tabindex="-1"></a><span class="fu">library</span>(hexbin) <span class="co"># For hexagonal wizardry</span></span>
<span id="cb837-2"><a href="the-game-sales-dataset.html#cb837-2" tabindex="-1"></a></span>
<span id="cb837-3"><a href="the-game-sales-dataset.html#cb837-3" tabindex="-1"></a><span class="co"># Binhex plot for Critic Count Log</span></span>
<span id="cb837-4"><a href="the-game-sales-dataset.html#cb837-4" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> Critic.Count.Log, <span class="at">y =</span> Critic.Score)) <span class="sc">+</span></span>
<span id="cb837-5"><a href="the-game-sales-dataset.html#cb837-5" tabindex="-1"></a>  <span class="fu">stat_binhex</span>() <span class="sc">+</span> <span class="co"># Bin 2d plane into hexagons</span></span>
<span id="cb837-6"><a href="the-game-sales-dataset.html#cb837-6" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">colours =</span> <span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb837-7"><a href="the-game-sales-dataset.html#cb837-7" tabindex="-1"></a>                       <span class="at">name =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="co"># Adding a custom continuous color palette</span></span>
<span id="cb837-8"><a href="the-game-sales-dataset.html#cb837-8" tabindex="-1"></a></span>
<span id="cb837-9"><a href="the-game-sales-dataset.html#cb837-9" tabindex="-1"></a><span class="co"># Binhex plot for User Count Log</span></span>
<span id="cb837-10"><a href="the-game-sales-dataset.html#cb837-10" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> User.Count.Log, <span class="at">y =</span> User.Score)) <span class="sc">+</span></span>
<span id="cb837-11"><a href="the-game-sales-dataset.html#cb837-11" tabindex="-1"></a>  <span class="fu">stat_binhex</span>() <span class="sc">+</span></span>
<span id="cb837-12"><a href="the-game-sales-dataset.html#cb837-12" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">colours =</span> <span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>), </span>
<span id="cb837-13"><a href="the-game-sales-dataset.html#cb837-13" tabindex="-1"></a>                       <span class="at">name =</span> <span class="st">&quot;Frequency&quot;</span>) <span class="co"># Color legend</span></span>
<span id="cb837-14"><a href="the-game-sales-dataset.html#cb837-14" tabindex="-1"></a></span>
<span id="cb837-15"><a href="the-game-sales-dataset.html#cb837-15" tabindex="-1"></a><span class="co"># Show both hexes side by side</span></span>
<span id="cb837-16"><a href="the-game-sales-dataset.html#cb837-16" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-count1"></span>
<img src="book_files/figure-html/game-count1-1.png" alt="Binhex plot for critic count and user count." width="672" />
<p class="caption">
Figure 9.6: Binhex plot for critic count and user count.
</p>
</div>
<p>Critic.Score and Critic.Count.Log share a decent correlation, with an r-value of 0.41 noted earlier, though Critic.Count.Log doesn’t have an overall impact on Critic.Score. On the other canvas, User.Score appears to maintain its independence from User.Count.Log.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-466}</p>
</blockquote>
<blockquote>
<p>Use ggplot2 package to conjure up a scatter plot with a smooth line between Global_Sales and NA_Sales. In plain, mortal language, explain what you find in the plot.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-467}</p>
</blockquote>
<blockquote>
<p>Employ a density plot to illustrate the relationship among Global_Sales, NA_Sales, EU_Sales, JP_Sales, and Other_Sales. Interpret your plot.
:::</p>
</blockquote>
</div>
<div id="analysis-of-sales" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Analysis of sales<a href="the-game-sales-dataset.html#analysis-of-sales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With an eclectic collection of plots and analysis, we delve into the intricacies of sales through the prisms of year of release, region, rating, genre, and more.</p>
<div id="by-year.release" class="section level3 hasAnchor" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> By Year.Release<a href="the-game-sales-dataset.html#by-year.release" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb838"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb838-1"><a href="the-game-sales-dataset.html#cb838-1" tabindex="-1"></a><span class="co"># Prepare the data</span></span>
<span id="cb838-2"><a href="the-game-sales-dataset.html#cb838-2" tabindex="-1"></a>Year.Release <span class="ot">&lt;-</span> game<span class="sc">$</span>Year.Release </span>
<span id="cb838-3"><a href="the-game-sales-dataset.html#cb838-3" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(Year.Release))</span>
<span id="cb838-4"><a href="the-game-sales-dataset.html#cb838-4" tabindex="-1"></a>p <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span></span>
<span id="cb838-5"><a href="the-game-sales-dataset.html#cb838-5" tabindex="-1"></a>  <span class="fu">select</span>(Year.Release, Global.Sales) <span class="sc">%&gt;%</span></span>
<span id="cb838-6"><a href="the-game-sales-dataset.html#cb838-6" tabindex="-1"></a>  <span class="fu">group_by</span>(Year.Release) <span class="sc">%&gt;%</span></span>
<span id="cb838-7"><a href="the-game-sales-dataset.html#cb838-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total.Sales =</span> <span class="fu">sum</span>(Global.Sales))</span>
<span id="cb838-8"><a href="the-game-sales-dataset.html#cb838-8" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(p, counts[<span class="dv">2</span>])  <span class="co"># Add counts to data frame</span></span>
<span id="cb838-9"><a href="the-game-sales-dataset.html#cb838-9" tabindex="-1"></a><span class="fu">names</span>(q)[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="st">&quot;count&quot;</span></span>
<span id="cb838-10"><a href="the-game-sales-dataset.html#cb838-10" tabindex="-1"></a>q<span class="sc">$</span>count <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(q<span class="sc">$</span>count)</span>
<span id="cb838-11"><a href="the-game-sales-dataset.html#cb838-11" tabindex="-1"></a></span>
<span id="cb838-12"><a href="the-game-sales-dataset.html#cb838-12" tabindex="-1"></a><span class="co"># Plot the data</span></span>
<span id="cb838-13"><a href="the-game-sales-dataset.html#cb838-13" tabindex="-1"></a><span class="fu">ggplot</span>(q, <span class="fu">aes</span>(<span class="at">x =</span> Year.Release, <span class="at">y =</span> Total.Sales, <span class="at">label =</span> q<span class="sc">$</span>count)) <span class="sc">+</span></span>
<span id="cb838-14"><a href="the-game-sales-dataset.html#cb838-14" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb838-15"><a href="the-game-sales-dataset.html#cb838-15" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">y =</span> q<span class="sc">$</span>count <span class="sc">*</span> <span class="dv">500000</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">&quot;Yellow&quot;</span> ) <span class="sc">+</span></span>
<span id="cb838-16"><a href="the-game-sales-dataset.html#cb838-16" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">y =</span> (q<span class="sc">$</span>count <span class="sc">+</span> <span class="dv">50</span>) <span class="sc">*</span> <span class="dv">500000</span>) <span class="sc">+</span>  <span class="co"># Position of the text: count of games each year</span></span>
<span id="cb838-17"><a href="the-game-sales-dataset.html#cb838-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>),</span>
<span id="cb838-18"><a href="the-game-sales-dataset.html#cb838-18" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;purple&quot;</span>),</span>
<span id="cb838-19"><a href="the-game-sales-dataset.html#cb838-19" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb838-20"><a href="the-game-sales-dataset.html#cb838-20" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb838-21"><a href="the-game-sales-dataset.html#cb838-21" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="st">&quot;Year of Release&quot;</span>, <span class="at">labels =</span> <span class="fu">as.character</span>(Year.Release), <span class="at">breaks =</span> Year.Release) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesYear1"></span>
<img src="book_files/figure-html/game-SalesYear1-1.png" alt="Total global sales and games released by year." width="768" />
<p class="caption">
Figure 9.7: Total global sales and games released by year.
</p>
</div>
<p>The histogram of total sales illustrates that before 1996, game sales were akin to a lonely desert, only one game was released for each year. Between 1996 and 2000, like a slow-blooming flower, sales and game releases gradually climbed. After that, we witnessed a gold rush in sales and game releases, peaking in 2008. Following this golden year, both total sales and count of games went downhill.</p>
</div>
<div id="by-region" class="section level3 hasAnchor" number="9.5.2">
<h3><span class="header-section-number">9.5.2</span> By Region<a href="the-game-sales-dataset.html#by-region" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb839"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb839-1"><a href="the-game-sales-dataset.html#cb839-1" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb839-2"><a href="the-game-sales-dataset.html#cb839-2" tabindex="-1"></a>game <span class="sc">%&gt;%</span></span>
<span id="cb839-3"><a href="the-game-sales-dataset.html#cb839-3" tabindex="-1"></a>  <span class="fu">select</span>(Year.Release, NA.Sales.Log, EU.Sales.Log, JP.Sales.Log, </span>
<span id="cb839-4"><a href="the-game-sales-dataset.html#cb839-4" tabindex="-1"></a>         Other.Sales.Log, Global.Sales.Log) <span class="sc">%&gt;%</span></span>
<span id="cb839-5"><a href="the-game-sales-dataset.html#cb839-5" tabindex="-1"></a>  <span class="fu">melt</span>(<span class="at">id.vars =</span> <span class="st">&quot;Year.Release&quot;</span>) <span class="sc">%&gt;%</span>   <span class="co"># Stacks other columns into &quot;Year.Release&quot;</span></span>
<span id="cb839-6"><a href="the-game-sales-dataset.html#cb839-6" tabindex="-1"></a>  <span class="fu">group_by</span>(Year.Release, variable) <span class="sc">%&gt;%</span> </span>
<span id="cb839-7"><a href="the-game-sales-dataset.html#cb839-7" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total.sales =</span> <span class="fu">sum</span>(value)) <span class="sc">%&gt;%</span></span>
<span id="cb839-8"><a href="the-game-sales-dataset.html#cb839-8" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year.Release, <span class="at">y =</span> total.sales, <span class="at">color =</span> variable, <span class="at">group =</span> variable)) <span class="sc">+</span></span>
<span id="cb839-9"><a href="the-game-sales-dataset.html#cb839-9" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb839-10"><a href="the-game-sales-dataset.html#cb839-10" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb839-11"><a href="the-game-sales-dataset.html#cb839-11" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year Release&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total Sales Log Value&quot;</span>, <span class="at">color =</span> <span class="st">&quot;Region&quot;</span>) <span class="sc">+</span></span>
<span id="cb839-12"><a href="the-game-sales-dataset.html#cb839-12" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>),</span>
<span id="cb839-13"><a href="the-game-sales-dataset.html#cb839-13" tabindex="-1"></a>          <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill=</span><span class="st">&quot;pink&quot;</span>),</span>
<span id="cb839-14"><a href="the-game-sales-dataset.html#cb839-14" tabindex="-1"></a>          <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb839-15"><a href="the-game-sales-dataset.html#cb839-15" tabindex="-1"></a>          <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesRegion1"></span>
<img src="book_files/figure-html/game-SalesRegion1-1.png" alt="Year wise log global sales by region." width="864" />
<p class="caption">
Figure 9.8: Year wise log global sales by region.
</p>
</div>
<p>The trajectories of log sales in North America, Europe, and Other regions seem to be singing in harmony, while Japan performs its own unique symphony, reaffirming the conclusions drawn from our earlier cluster analysis.</p>
</div>
<div id="by-rating" class="section level3 hasAnchor" number="9.5.3">
<h3><span class="header-section-number">9.5.3</span> By Rating<a href="the-game-sales-dataset.html#by-rating" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="the-game-sales-dataset.html#cb840-1" tabindex="-1"></a>game<span class="sc">$</span>Rating.type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Rating.type)</span>
<span id="cb840-2"><a href="the-game-sales-dataset.html#cb840-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> game[, <span class="fu">c</span>(<span class="dv">6</span><span class="sc">:</span><span class="dv">10</span>)] <span class="co"># Sales across different regions</span></span>
<span id="cb840-3"><a href="the-game-sales-dataset.html#cb840-3" tabindex="-1"></a><span class="fu">matplot</span>(<span class="fu">t</span>(x), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">5</span>)[game<span class="sc">$</span>Rating.type])</span>
<span id="cb840-4"><a href="the-game-sales-dataset.html#cb840-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;center&quot;</span>, <span class="fu">levels</span>(game<span class="sc">$</span>Rating.type), <span class="at">fill =</span> <span class="fu">rainbow</span>(<span class="dv">5</span>), <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">pt.cex =</span> <span class="dv">1</span>)</span>
<span id="cb840-5"><a href="the-game-sales-dataset.html#cb840-5" tabindex="-1"></a><span class="fu">text</span>(<span class="fu">c</span>(<span class="fl">1.2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="fl">3.9</span>, <span class="fl">4.8</span>), <span class="dv">80000000</span>, <span class="fu">colnames</span>(x))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesRating1"></span>
<img src="book_files/figure-html/game-SalesRating1-1.png" alt="Sales by rating type." width="672" />
<p class="caption">
Figure 9.9: Sales by rating type.
</p>
</div>
<p>The line graph regales us with the tale of an “E for Everyone” title, predominantly purchased in North America and Europe, soaring to the lofty heights of 80 million in global sales—with North America accounting for half. A quick perusal of the data reveals the star of the show to be “Wii Sports” from 2006. Additionally, Mature games are popular in North America(green), Everyone games(red) have good sales in Europe, while Japan holds a torch for Teen(purple) and Everyone(red) games. The “Other” region samples a medley of ratings, not playing favorites.</p>
</div>
<div id="by-genre" class="section level3 hasAnchor" number="9.5.4">
<h3><span class="header-section-number">9.5.4</span> By Genre<a href="the-game-sales-dataset.html#by-genre" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="the-game-sales-dataset.html#cb841-1" tabindex="-1"></a>game <span class="sc">%&gt;%</span> </span>
<span id="cb841-2"><a href="the-game-sales-dataset.html#cb841-2" tabindex="-1"></a>  <span class="fu">select</span>(Year.Release, Global.Sales.Log, Genre) <span class="sc">%&gt;%</span></span>
<span id="cb841-3"><a href="the-game-sales-dataset.html#cb841-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Year.Release, Genre) <span class="sc">%&gt;%</span></span>
<span id="cb841-4"><a href="the-game-sales-dataset.html#cb841-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total.Sales.Log =</span> <span class="fu">sum</span>(Global.Sales.Log)) <span class="sc">%&gt;%</span></span>
<span id="cb841-5"><a href="the-game-sales-dataset.html#cb841-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year.Release, <span class="at">y =</span> Total.Sales.Log, <span class="at">group =</span> Genre, <span class="at">fill =</span> Genre)) <span class="sc">+</span></span>
<span id="cb841-6"><a href="the-game-sales-dataset.html#cb841-6" tabindex="-1"></a>         <span class="fu">geom_area</span>() <span class="sc">+</span></span>
<span id="cb841-7"><a href="the-game-sales-dataset.html#cb841-7" tabindex="-1"></a>         <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>, <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>),</span>
<span id="cb841-8"><a href="the-game-sales-dataset.html#cb841-8" tabindex="-1"></a>               <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>),</span>
<span id="cb841-9"><a href="the-game-sales-dataset.html#cb841-9" tabindex="-1"></a>               <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb841-10"><a href="the-game-sales-dataset.html#cb841-10" tabindex="-1"></a>               <span class="at">panel.grid.minor=</span><span class="fu">element_blank</span>()) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesGenre1"></span>
<img src="book_files/figure-html/game-SalesGenre1-1.png" alt="Year wise log global sales by Genre." width="672" />
<p class="caption">
Figure 9.10: Year wise log global sales by Genre.
</p>
</div>
<p>Behold the tapestry of sales across genres, with 2007-2009 as the golden era—years when the sales towered above 7000 (log value) annually. Action and sports genres have reigned supreme over the two-decade span, while adventure, puzzle, and strategy genres remained relatively niche.</p>
</div>
<div id="by-score" class="section level3 hasAnchor" number="9.5.5">
<h3><span class="header-section-number">9.5.5</span> by Score<a href="the-game-sales-dataset.html#by-score" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="the-game-sales-dataset.html#cb842-1" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> Critic.Score, <span class="at">y =</span> Global.Sales.Log)) <span class="sc">+</span> </span>
<span id="cb842-2"><a href="the-game-sales-dataset.html#cb842-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Genre)) <span class="sc">+</span> </span>
<span id="cb842-3"><a href="the-game-sales-dataset.html#cb842-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()  <span class="co"># Add a regression line</span></span>
<span id="cb842-4"><a href="the-game-sales-dataset.html#cb842-4" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> User.Score, <span class="at">y =</span> Global.Sales.Log)) <span class="sc">+</span> </span>
<span id="cb842-5"><a href="the-game-sales-dataset.html#cb842-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Rating)) <span class="sc">+</span> </span>
<span id="cb842-6"><a href="the-game-sales-dataset.html#cb842-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span>
<span id="cb842-7"><a href="the-game-sales-dataset.html#cb842-7" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1, p2, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesScore"></span>
<img src="book_files/figure-html/game-SalesScore-1.png" alt="Global sales in relation to critic and user scores." width="1152" />
<p class="caption">
Figure 9.11: Global sales in relation to critic and user scores.
</p>
</div>
<p>Regardless of Genre and Rating, a positive trend is noticeable between the Critic Score and the logarithm of Global Sales. Especially, when the Critic Score surpasses 9, Global Sales logarithm escalates sharply. In contrast, the logarithm of Global Sales increases at a snail’s pace in response to User Scores.</p>
<div class="sourceCode" id="cb843"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb843-1"><a href="the-game-sales-dataset.html#cb843-1" tabindex="-1"></a><span class="co"># Abbreviate a particularly lengthy game title</span></span>
<span id="cb843-2"><a href="the-game-sales-dataset.html#cb843-2" tabindex="-1"></a>game<span class="sc">$</span>Name <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">&quot;Brain Age: Train Your Brain in Minutes a Day&quot;</span>,</span>
<span id="cb843-3"><a href="the-game-sales-dataset.html#cb843-3" tabindex="-1"></a>                  <span class="st">&quot;Brain Age: Train Your Brain&quot;</span>, game<span class="sc">$</span>Name)</span>
<span id="cb843-4"><a href="the-game-sales-dataset.html#cb843-4" tabindex="-1"></a></span>
<span id="cb843-5"><a href="the-game-sales-dataset.html#cb843-5" tabindex="-1"></a><span class="co"># Analyze and plot the top 20 games by total sales</span></span>
<span id="cb843-6"><a href="the-game-sales-dataset.html#cb843-6" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span> </span>
<span id="cb843-7"><a href="the-game-sales-dataset.html#cb843-7" tabindex="-1"></a>  <span class="fu">select</span>(Name, User.Score, Critic.Score, Global.Sales) <span class="sc">%&gt;%</span></span>
<span id="cb843-8"><a href="the-game-sales-dataset.html#cb843-8" tabindex="-1"></a>  <span class="fu">group_by</span>(Name) <span class="sc">%&gt;%</span></span>
<span id="cb843-9"><a href="the-game-sales-dataset.html#cb843-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total.Sales =</span> <span class="fu">sum</span>(Global.Sales), <span class="at">Avg.User.Score =</span> <span class="fu">mean</span>(User.Score), </span>
<span id="cb843-10"><a href="the-game-sales-dataset.html#cb843-10" tabindex="-1"></a>            <span class="at">Avg.Critic.Score =</span> <span class="fu">mean</span>(Critic.Score)) <span class="sc">%&gt;%</span></span>
<span id="cb843-11"><a href="the-game-sales-dataset.html#cb843-11" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Total.Sales)) <span class="sc">%&gt;%</span></span>
<span id="cb843-12"><a href="the-game-sales-dataset.html#cb843-12" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">20</span>)</span>
<span id="cb843-13"><a href="the-game-sales-dataset.html#cb843-13" tabindex="-1"></a></span>
<span id="cb843-14"><a href="the-game-sales-dataset.html#cb843-14" tabindex="-1"></a><span class="co"># Create a bar chart with accompanying score lines</span></span>
<span id="cb843-15"><a href="the-game-sales-dataset.html#cb843-15" tabindex="-1"></a><span class="fu">ggplot</span>(p1, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Name, <span class="at">levels =</span> Name))) <span class="sc">+</span></span>
<span id="cb843-16"><a href="the-game-sales-dataset.html#cb843-16" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">y =</span> Total.Sales<span class="sc">/</span><span class="dv">10000000</span>), <span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb843-17"><a href="the-game-sales-dataset.html#cb843-17" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Avg.User.Score, <span class="at">group =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">&quot;Avg.User.Score&quot;</span>), <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb843-18"><a href="the-game-sales-dataset.html#cb843-18" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(<span class="at">y =</span> Avg.User.Score), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">&quot;Yellow&quot;</span> ) <span class="sc">+</span></span>
<span id="cb843-19"><a href="the-game-sales-dataset.html#cb843-19" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Avg.Critic.Score,  <span class="at">group =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>), <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb843-20"><a href="the-game-sales-dataset.html#cb843-20" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> Avg.Critic.Score), <span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb843-21"><a href="the-game-sales-dataset.html#cb843-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">size =</span> <span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb843-22"><a href="the-game-sales-dataset.html#cb843-22" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Top Global Sales Games with Scores&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Top-selling games&quot;</span> ) <span class="sc">+</span>  </span>
<span id="cb843-23"><a href="the-game-sales-dataset.html#cb843-23" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) </span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-468-1.png" width="672" /></p>
<p>Among these 20 top-selling games, the first two games, ‘Wii Sports’ and ‘Grand Theft Auto V’ tower over their competitors in sales. For a majority of games, the average critic scores are higher than the average user scores, echoing the findings of our density plot in Figure <a href="the-game-sales-dataset.html#fig:game-score">9.5</a>. “Call of Duty” titles, however, seem to be in the users’ bad books, fetching notably lower average user scores compared to other top-selling games.</p>
</div>
<div id="by-rating-genre-critic-score" class="section level3 hasAnchor" number="9.5.6">
<h3><span class="header-section-number">9.5.6</span> By Rating &amp; Genre &amp; Critic score<a href="the-game-sales-dataset.html#by-rating-genre-critic-score" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="the-game-sales-dataset.html#cb844-1" tabindex="-1"></a><span class="co"># Aggregate and summarize data for plotting</span></span>
<span id="cb844-2"><a href="the-game-sales-dataset.html#cb844-2" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span></span>
<span id="cb844-3"><a href="the-game-sales-dataset.html#cb844-3" tabindex="-1"></a>  <span class="fu">select</span>(Rating.type, Global.Sales, Genre, Critic.Score) <span class="sc">%&gt;%</span></span>
<span id="cb844-4"><a href="the-game-sales-dataset.html#cb844-4" tabindex="-1"></a>  <span class="fu">group_by</span>(Rating.type, Genre) <span class="sc">%&gt;%</span></span>
<span id="cb844-5"><a href="the-game-sales-dataset.html#cb844-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total.Sales =</span> <span class="fu">sum</span>(Global.Sales) <span class="sc">/</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">8</span>, <span class="at">Avg.Score =</span> <span class="fu">mean</span>(Critic.Score)) </span>
<span id="cb844-6"><a href="the-game-sales-dataset.html#cb844-6" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> p1 <span class="sc">%&gt;%</span> </span>
<span id="cb844-7"><a href="the-game-sales-dataset.html#cb844-7" tabindex="-1"></a>  <span class="fu">group_by</span>(Genre) <span class="sc">%&gt;%</span> </span>
<span id="cb844-8"><a href="the-game-sales-dataset.html#cb844-8" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Avg.Critic.Score =</span> <span class="fu">mean</span>(Avg.Score))</span>
<span id="cb844-9"><a href="the-game-sales-dataset.html#cb844-9" tabindex="-1"></a></span>
<span id="cb844-10"><a href="the-game-sales-dataset.html#cb844-10" tabindex="-1"></a><span class="co"># Create a bar chart with overlaid score lines</span></span>
<span id="cb844-11"><a href="the-game-sales-dataset.html#cb844-11" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb844-12"><a href="the-game-sales-dataset.html#cb844-12" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">data =</span> p1, <span class="fu">aes</span>(<span class="at">x =</span> Genre, <span class="at">y =</span> Total.Sales, <span class="at">fill =</span> Rating.type), </span>
<span id="cb844-13"><a href="the-game-sales-dataset.html#cb844-13" tabindex="-1"></a>           <span class="at">stat =</span> <span class="st">&quot;Identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span></span>
<span id="cb844-14"><a href="the-game-sales-dataset.html#cb844-14" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> p2, </span>
<span id="cb844-15"><a href="the-game-sales-dataset.html#cb844-15" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> Genre, <span class="at">y =</span> Avg.Critic.Score, <span class="at">group =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>), </span>
<span id="cb844-16"><a href="the-game-sales-dataset.html#cb844-16" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb844-17"><a href="the-game-sales-dataset.html#cb844-17" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> p2, <span class="fu">aes</span>(<span class="at">x =</span> Genre, <span class="at">y =</span> Avg.Critic.Score, <span class="at">shape =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>),</span>
<span id="cb844-18"><a href="the-game-sales-dataset.html#cb844-18" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;Blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb844-19"><a href="the-game-sales-dataset.html#cb844-19" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="st">&quot;Score&quot;</span>, <span class="at">breaks =</span> <span class="st">&quot;Avg.Critic.Score&quot;</span>, <span class="at">values =</span> <span class="st">&quot;yellow&quot;</span>) <span class="sc">+</span> </span>
<span id="cb844-20"><a href="the-game-sales-dataset.html#cb844-20" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="st">&quot;Score&quot;</span>, <span class="at">values =</span> <span class="dv">19</span>) <span class="sc">+</span>   <span class="co"># Add scale for line and point plot</span></span>
<span id="cb844-21"><a href="the-game-sales-dataset.html#cb844-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>), </span>
<span id="cb844-22"><a href="the-game-sales-dataset.html#cb844-22" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>,</span>
<span id="cb844-23"><a href="the-game-sales-dataset.html#cb844-23" tabindex="-1"></a>        <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;black&quot;</span>),</span>
<span id="cb844-24"><a href="the-game-sales-dataset.html#cb844-24" tabindex="-1"></a>        <span class="at">panel.grid.major =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb844-25"><a href="the-game-sales-dataset.html#cb844-25" tabindex="-1"></a>        <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-Sales1"></span>
<img src="book_files/figure-html/game-Sales1-1.png" alt="Total sales for genre and rating in accordance with critic score." width="1152" />
<p class="caption">
Figure 9.12: Total sales for genre and rating in accordance with critic score.
</p>
</div>
<p>Everyone*sports games are so popular, knocking it out of the sales park, with the critics’ nod of approval. Not to be outdone, ‘Mature’ rated Action and Shooter games follow closely, with a respectable critic score to match. An overlay of average critic scores on the bar chart reveals that Action and Role-Playing games lead the critic scores, while Fighting, adventure, and racing games get relatively lower average critic scores. However, higher critic scores do not always translate to higher sales; for example, Role-Playing games have higher critic scores but do not outsell Action games. Puzzle and strategy do sell less compared with other genres, though their critic scores are above the average.</p>
</div>
<div id="by-platform" class="section level3 hasAnchor" number="9.5.7">
<h3><span class="header-section-number">9.5.7</span> By Platform<a href="the-game-sales-dataset.html#by-platform" class="anchor-section" aria-label="Anchor link to header"></a></h3>

<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="the-game-sales-dataset.html#cb845-1" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb845-2"><a href="the-game-sales-dataset.html#cb845-2" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb845-3"><a href="the-game-sales-dataset.html#cb845-3" tabindex="-1"></a>p <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span></span>
<span id="cb845-4"><a href="the-game-sales-dataset.html#cb845-4" tabindex="-1"></a>  <span class="fu">group_by</span>(Platform.type, Year.Release) <span class="sc">%&gt;%</span></span>
<span id="cb845-5"><a href="the-game-sales-dataset.html#cb845-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(Global.Sales))</span>
<span id="cb845-6"><a href="the-game-sales-dataset.html#cb845-6" tabindex="-1"></a>p<span class="sc">$</span>Year.Release. <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(p<span class="sc">$</span>Year.Release))</span>
<span id="cb845-7"><a href="the-game-sales-dataset.html#cb845-7" tabindex="-1"></a><span class="fu">ggplot</span>(p, <span class="fu">aes</span>(<span class="at">x =</span> Year.Release., <span class="at">fill =</span> Platform.type)) <span class="sc">+</span></span>
<span id="cb845-8"><a href="the-game-sales-dataset.html#cb845-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">position =</span> <span class="st">&quot;fill&quot;</span>) <span class="sc">+</span></span>
<span id="cb845-9"><a href="the-game-sales-dataset.html#cb845-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Market Share&quot;</span>) <span class="sc">+</span></span>
<span id="cb845-10"><a href="the-game-sales-dataset.html#cb845-10" tabindex="-1"></a>  <span class="fu">scale_fill_viridis</span>(<span class="at">discrete =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb845-11"><a href="the-game-sales-dataset.html#cb845-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>()) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-SalesPlatform1"></span>
<img src="book_files/figure-html/game-SalesPlatform1-1.png" alt="Yearly market share by platform type." width="672" />
<p class="caption">
Figure 9.13: Yearly market share by platform type.
</p>
</div>
<p>It was a lonely landscape for PC and PlayStation before 1990, with PC reigning unchallenged in the gaming kingdom. As the clock ticked past 1995, newcomers Nintendo and Xbox burst onto the scene, hungrily carving out hefty slices of the market pie. Other platforms popped up like mushrooms in the early ’90s, only to vanish into the annals of gaming history after a brief 20-year cameo. Fast forward to 2010, and it’s a four-way dance-off with Nintendo, PC, PlayStation, and Xbox maintaining a harmonious market share equilibrium.</p>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="the-game-sales-dataset.html#cb846-1" tabindex="-1"></a><span class="co"># Compute 1-way ANOVA test for log value of global sales by Platform Type</span></span>
<span id="cb846-2"><a href="the-game-sales-dataset.html#cb846-2" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(Global.Sales.Log <span class="sc">~</span> Platform.type, <span class="at">data =</span> game)</span>
<span id="cb846-3"><a href="the-game-sales-dataset.html#cb846-3" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>##                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Platform.type    4   1283   320.8   181.2 &lt;2e-16 ***
## Residuals     6820  12077     1.8                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="the-game-sales-dataset.html#cb848-1" tabindex="-1"></a>tukey <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(model)</span>
<span id="cb848-2"><a href="the-game-sales-dataset.html#cb848-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb848-3"><a href="the-game-sales-dataset.html#cb848-3" tabindex="-1"></a><span class="fu">plot</span>(tukey, <span class="at">las =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-469-1.png" width="672" /></p>
<p>The ANOVA test confirms significant sales differences among platform types. Delving deeper, The Tukey post-hoc dance shows everyone stepping on its own toes, indicating notable differences across the board—except for Xbox versus Nintendo, and others versus Nintendo, who seem to be in step with one another, sharing a similar sales rhythm.</p>

<div class="sourceCode" id="cb849"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb849-1"><a href="the-game-sales-dataset.html#cb849-1" tabindex="-1"></a>game<span class="sc">$</span>Platform.type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(game<span class="sc">$</span>Platform.type)</span>
<span id="cb849-2"><a href="the-game-sales-dataset.html#cb849-2" tabindex="-1"></a><span class="fu">ggplot</span>(game, <span class="fu">aes</span>(<span class="at">x =</span> Platform.type, <span class="at">y =</span> Global.Sales.Log, <span class="at">fill =</span> Rating.type)) <span class="sc">+</span></span>
<span id="cb849-3"><a href="the-game-sales-dataset.html#cb849-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-PlatformRating"></span>
<img src="book_files/figure-html/game-PlatformRating-1.png" alt="Global sales log by platform and rating type." width="960" />
<p class="caption">
Figure 9.14: Global sales log by platform and rating type.
</p>
</div>
<p>In the global sales log arena, PCs tend to play the underdog. In contrast, PlayStation and Xbox punch above their weight, landing higher median sales across various rating categories. Titles rated ‘Everyone’ seem to be crowd-pleasers on all platforms, while the ‘Mature’ category particularly flourishes on PC, PlayStation, and Xbox.</p>

<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="the-game-sales-dataset.html#cb850-1" tabindex="-1"></a><span class="fu">ggplot</span>(game, <span class="fu">aes</span>(Critic.Score, Global.Sales.Log, <span class="at">color =</span> Platform.type)) <span class="sc">+</span> </span>
<span id="cb850-2"><a href="the-game-sales-dataset.html#cb850-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb850-3"><a href="the-game-sales-dataset.html#cb850-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Genre)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-PlatformScore"></span>
<img src="book_files/figure-html/game-PlatformScore-1.png" alt="Global sales log correlated with critic score across different platforms and genres." width="960" />
<p class="caption">
Figure 9.15: Global sales log correlated with critic score across different platforms and genres.
</p>
</div>
<p>Most genre plots in Figure <a href="the-game-sales-dataset.html#fig:game-PlatformScore">9.15</a> illustrate a universal truth: there is a positive correlation between Global.Sales.Log and Critic Score, the higher the critic score, the better the global sales log value. Most puzzle games were from Nintendo, while lots of stratege games are PC. For other genres, all platforms are distributed relatively evenly. PC sat in the corner of lower market share in different genres, while Nintendo’s sporty, racing, platform, and misc games, Playstation’s action, fighting, and racing games, Xbox’s misc, action, and shooter games shined with knockout global sales logs.</p>
</div>
</div>
<div id="effect-of-platform-type-on-principle-components" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Effect of platform type on principle components<a href="the-game-sales-dataset.html#effect-of-platform-type-on-principle-components" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To examine the influence of various gaming platforms on the variance in game sales, a principal component analysis (PCA) was conducted. When performing a PCA, it’s essential to scale the data, especially if the variables are measured on different scales.</p>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="the-game-sales-dataset.html#cb851-1" tabindex="-1"></a>st <span class="ot">&lt;-</span> game[, <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">13</span>, <span class="dv">17</span><span class="sc">:</span><span class="dv">23</span>)]</span>
<span id="cb851-2"><a href="the-game-sales-dataset.html#cb851-2" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(st, <span class="at">scale =</span> T)  <span class="co"># Normalization activated with scale = TRUE</span></span>
<span id="cb851-3"><a href="the-game-sales-dataset.html#cb851-3" tabindex="-1"></a>percentVar <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">summary</span>(pca)<span class="sc">$</span>importance[<span class="dv">2</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>], <span class="dv">0</span>)  <span class="co"># Compute % variances</span></span></code></pre></div>

<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb852-1"><a href="the-game-sales-dataset.html#cb852-1" tabindex="-1"></a>pcaData <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]) <span class="co"># Extract 1st and 2nd PC values</span></span>
<span id="cb852-2"><a href="the-game-sales-dataset.html#cb852-2" tabindex="-1"></a>pcaData <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pcaData, game<span class="sc">$</span>Platform.type)  <span class="co"># Add platform type for clustering</span></span>
<span id="cb852-3"><a href="the-game-sales-dataset.html#cb852-3" tabindex="-1"></a><span class="fu">colnames</span>(pcaData) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;PC1&quot;</span>, <span class="st">&quot;PC2&quot;</span>, <span class="st">&quot;Platform&quot;</span>)</span>
<span id="cb852-4"><a href="the-game-sales-dataset.html#cb852-4" tabindex="-1"></a><span class="fu">ggplot</span>(pcaData, <span class="fu">aes</span>(PC1, PC2, <span class="at">color =</span> Platform, <span class="at">shape =</span> Platform)) <span class="sc">+</span>  </span>
<span id="cb852-5"><a href="the-game-sales-dataset.html#cb852-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb852-6"><a href="the-game-sales-dataset.html#cb852-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">paste0</span>(<span class="st">&quot;PC1: &quot;</span>, percentVar[<span class="dv">1</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="sc">+</span>  <span class="co"># x-axis label</span></span>
<span id="cb852-7"><a href="the-game-sales-dataset.html#cb852-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="fu">paste0</span>(<span class="st">&quot;PC2: &quot;</span>, percentVar[<span class="dv">2</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="sc">+</span>  <span class="co"># y-axis label</span></span>
<span id="cb852-8"><a href="the-game-sales-dataset.html#cb852-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)  <span class="co"># Width and height ratio</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-pca"></span>
<img src="book_files/figure-html/game-pca-1.png" alt="PCA plot colored by platform type." width="672" />
<p class="caption">
Figure 9.16: PCA plot colored by platform type.
</p>
</div>
<p>Each platform—PC, Xbox, Playstation, and Nintendo—claims its territory on the PCA chart, demonstrating a unique role in the variance components of PC1 and PC2, showcasing its distinct influence on the gaming market’s variability.</p>

<div class="sourceCode" id="cb853"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb853-1"><a href="the-game-sales-dataset.html#cb853-1" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb853-2"><a href="the-game-sales-dataset.html#cb853-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb853-3"><a href="the-game-sales-dataset.html#cb853-3" tabindex="-1"></a><span class="fu">autoplot</span>(<span class="fu">kmeans</span>(st, <span class="dv">3</span>), <span class="at">data =</span> st, <span class="at">label =</span> <span class="cn">FALSE</span>, <span class="at">label.size =</span> <span class="fl">0.1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:game-Kmeans"></span>
<img src="book_files/figure-html/game-Kmeans-1.png" alt="K-means clustering on PCA components using ggfortify." width="672" />
<p class="caption">
Figure 9.17: K-means clustering on PCA components using ggfortify.
</p>
</div>
<p>Linking this with the PCA Figure <a href="the-game-sales-dataset.html#fig:game-pca">9.16</a>, we discover the 4 main actors: Playstation, Xbox, Nintendo, and PC. The first cluster is formed by all these four gaming giants. The second cluster is mostly comprised of Xbox, Nintendo and Playstation, while PC and Playstation dominate the third cluster.</p>
</div>
<div id="models-for-global-sales" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Models for global sales<a href="the-game-sales-dataset.html#models-for-global-sales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To manage the complexity of publisher and developer data, and to sidestep collinearity, we’ve streamlined the number of publisher levels to 12, relegating the rest to “Others.” We rely on critic scores over user scores, given their stronger correlation, and utilize the log value of user score count for its better relationship with global sales. Other sales log variables are omitted to avoid redundancy.</p>
<p>Here’s how we prepare our data:</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="the-game-sales-dataset.html#cb854-1" tabindex="-1"></a><span class="co"># Re-categorize publishers into 13 groups</span></span>
<span id="cb854-2"><a href="the-game-sales-dataset.html#cb854-2" tabindex="-1"></a>Publisher. <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">table</span>(game<span class="sc">$</span>Publisher), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)), <span class="dv">12</span>)</span>
<span id="cb854-3"><a href="the-game-sales-dataset.html#cb854-3" tabindex="-1"></a></span>
<span id="cb854-4"><a href="the-game-sales-dataset.html#cb854-4" tabindex="-1"></a>game <span class="ot">&lt;-</span> game <span class="sc">%&gt;%</span></span>
<span id="cb854-5"><a href="the-game-sales-dataset.html#cb854-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Publisher.type =</span> <span class="fu">ifelse</span>(Publisher <span class="sc">%in%</span> Publisher., <span class="fu">as.character</span>(Publisher), <span class="st">&quot;Others&quot;</span>)) </span>
<span id="cb854-6"><a href="the-game-sales-dataset.html#cb854-6" tabindex="-1"></a>game.lm <span class="ot">&lt;-</span> game[, <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">11</span>, <span class="dv">21</span>, <span class="dv">23</span><span class="sc">:</span><span class="dv">26</span>)] <span class="co"># Select relevant columns for linear model</span></span></code></pre></div>
<p>Now, let’s build a linear model to understand the factors affecting global sales:</p>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="the-game-sales-dataset.html#cb855-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Global.Sales.Log <span class="sc">~</span> ., <span class="at">data =</span> game.lm)</span>
<span id="cb855-2"><a href="the-game-sales-dataset.html#cb855-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ ., data = game.lm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.9221 -0.5558  0.0254  0.5789  4.1009 
## 
## Coefficients:
##                                             Estimate Std. Error t value
## (Intercept)                                10.187752   0.922104  11.048
## Year.Release1988                           -3.088268   1.300919  -2.374
## Year.Release1992                           -1.796072   1.300851  -1.381
## Year.Release1994                            2.930510   1.302000   2.251
## Year.Release1996                            1.488582   0.987461   1.507
## Year.Release1997                            1.188658   0.955613   1.244
## Year.Release1998                            0.744742   0.939532   0.793
## Year.Release1999                            0.653088   0.936406   0.697
## Year.Release2000                            0.785921   0.925467   0.849
## Year.Release2001                            0.772488   0.922728   0.837
## Year.Release2002                            0.570865   0.922008   0.619
## Year.Release2003                            0.340110   0.921843   0.369
## Year.Release2004                            0.550812   0.921901   0.597
## Year.Release2005                            0.210534   0.921694   0.228
## Year.Release2006                            0.141533   0.921703   0.154
## Year.Release2007                            0.373361   0.921629   0.405
## Year.Release2008                            0.529829   0.921677   0.575
## Year.Release2009                            0.446508   0.921648   0.484
## Year.Release2010                            0.596658   0.921889   0.647
## Year.Release2011                            0.389514   0.921944   0.422
## Year.Release2012                           -0.031458   0.922540  -0.034
## Year.Release2013                           -0.170252   0.922985  -0.184
## Year.Release2014                           -0.383671   0.923096  -0.416
## Year.Release2015                           -0.478979   0.923302  -0.519
## Year.Release2016                           -0.826950   0.923192  -0.896
## GenreAdventure                             -0.335989   0.063305  -5.307
## GenreFighting                               0.072835   0.055338   1.316
## GenreMisc                                   0.357196   0.054323   6.575
## GenrePlatform                              -0.184139   0.054854  -3.357
## GenrePuzzle                                -0.345253   0.091582  -3.770
## GenreRacing                                -0.097943   0.048451  -2.021
## GenreRole-Playing                          -0.357837   0.043093  -8.304
## GenreShooter                               -0.142624   0.040372  -3.533
## GenreSimulation                             0.405629   0.060887   6.662
## GenreSports                                 0.011217   0.046986   0.239
## GenreStrategy                              -0.483702   0.063838  -7.577
## Critic.Score                                0.114744   0.009865  11.632
## User.Count.Log                              0.615776   0.011589  53.134
## Platform.typeOthers                        -0.188799   0.066011  -2.860
## Platform.typePC                            -2.442802   0.051704 -47.246
## Platform.typePlaystation                    0.135254   0.033868   3.994
## Platform.typeXbox                          -0.106733   0.036927  -2.890
## Rating.typeE10+                            -0.058393   0.040759  -1.433
## Rating.typeM                               -0.467923   0.045704 -10.238
## Rating.typeOthers                           0.144593   0.545092   0.265
## Rating.typeT                               -0.331696   0.035692  -9.293
## Publisher.typeAtari                        -0.506235   0.082442  -6.141
## Publisher.typeCapcom                       -0.759855   0.078983  -9.620
## Publisher.typeElectronic Arts              -0.114754   0.053315  -2.152
## Publisher.typeKonami Digital Entertainment -0.705932   0.073042  -9.665
## Publisher.typeNamco Bandai Games           -0.569621   0.074819  -7.613
## Publisher.typeNintendo                      0.111592   0.074409   1.500
## Publisher.typeOthers                       -0.618870   0.046433 -13.328
## Publisher.typeSega                         -0.517708   0.069222  -7.479
## Publisher.typeSony Computer Entertainment  -0.585506   0.069125  -8.470
## Publisher.typeTake-Two Interactive         -0.276947   0.070848  -3.909
## Publisher.typeTHQ                          -0.117032   0.068824  -1.700
## Publisher.typeUbisoft                      -0.377192   0.059101  -6.382
##                                            Pr(&gt;|t|)    
## (Intercept)                                 &lt; 2e-16 ***
## Year.Release1988                           0.017628 *  
## Year.Release1992                           0.167420    
## Year.Release1994                           0.024432 *  
## Year.Release1996                           0.131733    
## Year.Release1997                           0.213591    
## Year.Release1998                           0.427996    
## Year.Release1999                           0.485550    
## Year.Release2000                           0.395791    
## Year.Release2001                           0.402522    
## Year.Release2002                           0.535836    
## Year.Release2003                           0.712180    
## Year.Release2004                           0.550211    
## Year.Release2005                           0.819326    
## Year.Release2006                           0.877964    
## Year.Release2007                           0.685409    
## Year.Release2008                           0.565410    
## Year.Release2009                           0.628070    
## Year.Release2010                           0.517516    
## Year.Release2011                           0.672679    
## Year.Release2012                           0.972799    
## Year.Release2013                           0.853660    
## Year.Release2014                           0.677690    
## Year.Release2015                           0.603940    
## Year.Release2016                           0.370418    
## GenreAdventure                             1.15e-07 ***
## GenreFighting                              0.188157    
## GenreMisc                                  5.22e-11 ***
## GenrePlatform                              0.000793 ***
## GenrePuzzle                                0.000165 ***
## GenreRacing                                0.043269 *  
## GenreRole-Playing                           &lt; 2e-16 ***
## GenreShooter                               0.000414 ***
## GenreSimulation                            2.91e-11 ***
## GenreSports                                0.811327    
## GenreStrategy                              4.01e-14 ***
## Critic.Score                                &lt; 2e-16 ***
## User.Count.Log                              &lt; 2e-16 ***
## Platform.typeOthers                        0.004248 ** 
## Platform.typePC                             &lt; 2e-16 ***
## Platform.typePlaystation                   6.58e-05 ***
## Platform.typeXbox                          0.003859 ** 
## Rating.typeE10+                            0.152006    
## Rating.typeM                                &lt; 2e-16 ***
## Rating.typeOthers                          0.790814    
## Rating.typeT                                &lt; 2e-16 ***
## Publisher.typeAtari                        8.69e-10 ***
## Publisher.typeCapcom                        &lt; 2e-16 ***
## Publisher.typeElectronic Arts              0.031403 *  
## Publisher.typeKonami Digital Entertainment  &lt; 2e-16 ***
## Publisher.typeNamco Bandai Games           3.04e-14 ***
## Publisher.typeNintendo                     0.133735    
## Publisher.typeOthers                        &lt; 2e-16 ***
## Publisher.typeSega                         8.44e-14 ***
## Publisher.typeSony Computer Entertainment   &lt; 2e-16 ***
## Publisher.typeTake-Two Interactive         9.36e-05 ***
## Publisher.typeTHQ                          0.089092 .  
## Publisher.typeUbisoft                      1.86e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9177 on 6767 degrees of freedom
## Multiple R-squared:  0.5735, Adjusted R-squared:  0.5699 
## F-statistic: 159.6 on 57 and 6767 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb857"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb857-1"><a href="the-game-sales-dataset.html#cb857-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">aov</span>(Global.Sales.Log <span class="sc">~</span> ., <span class="at">data =</span> game.lm)</span>
<span id="cb857-2"><a href="the-game-sales-dataset.html#cb857-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Year.Release     24    521    21.7   25.78 &lt;2e-16 ***
## Genre            11    527    47.9   56.87 &lt;2e-16 ***
## Critic.Score      1   1771  1771.3 2103.34 &lt;2e-16 ***
## User.Count.Log    1   1344  1344.0 1595.92 &lt;2e-16 ***
## Platform.type     4   2944   736.1  874.11 &lt;2e-16 ***
## Rating.type       4    165    41.2   48.93 &lt;2e-16 ***
## Publisher.type   12    389    32.4   38.53 &lt;2e-16 ***
## Residuals      6767   5699     0.8                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The log value of global sales is mostly influenced by factors of critic score, user count log, platform type, Publisher type, and genre in the linear model analysis. ANOVA shows every factor is a key player of significant contributor. Critic.Score and User.Count.Log are the lead actors in this statistical drama. They positively affect the global sales log, while other factors like Platform type and Genre either lift up or pull down the global sales according to their types. This model boasts an explanatory power with an R-Square of 0.57.</p>
<p>Given the nonlinear relationship indicated by our previous scatter plot about global sales versus critic scores (Figure <a href="the-game-sales-dataset.html#fig:game-SalesScore">9.11</a>) and the pronounced impact of critic scores in the linear model analysis, a polynomial model is entertained.</p>
<div class="sourceCode" id="cb859"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb859-1"><a href="the-game-sales-dataset.html#cb859-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Global.Sales.Log <span class="sc">~</span> </span>
<span id="cb859-2"><a href="the-game-sales-dataset.html#cb859-2" tabindex="-1"></a>           Critic.Score <span class="sc">+</span> <span class="fu">I</span>(Critic.Score<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(Critic.Score<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">I</span>(Critic.Score<span class="sc">^</span><span class="dv">4</span>), </span>
<span id="cb859-3"><a href="the-game-sales-dataset.html#cb859-3" tabindex="-1"></a>           <span class="at">data =</span> game.lm)</span>
<span id="cb859-4"><a href="the-game-sales-dataset.html#cb859-4" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ Critic.Score + I(Critic.Score^2) + 
##     I(Critic.Score^3) + I(Critic.Score^4), data = game.lm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.0029 -0.7972  0.0916  0.8801  5.6201 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       12.030638   1.468428   8.193 3.02e-16 ***
## Critic.Score      -0.840810   1.095444  -0.768   0.4428    
## I(Critic.Score^2)  0.385671   0.292104   1.320   0.1868    
## I(Critic.Score^3) -0.060971   0.033147  -1.839   0.0659 .  
## I(Critic.Score^4)  0.003434   0.001358   2.528   0.0115 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.281 on 6820 degrees of freedom
## Multiple R-squared:  0.1623, Adjusted R-squared:  0.1618 
## F-statistic: 330.4 on 4 and 6820 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We focus on the third and fourth degrees of the polynomial fit as the initial levels lacked statistical significance in our pre-analysis.</p>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb861-1"><a href="the-game-sales-dataset.html#cb861-1" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Global.Sales.Log <span class="sc">~</span> <span class="fu">I</span>(Critic.Score<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">I</span>(Critic.Score<span class="sc">^</span><span class="dv">4</span>),  <span class="at">data =</span> game.lm)</span>
<span id="cb861-2"><a href="the-game-sales-dataset.html#cb861-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Global.Sales.Log ~ I(Critic.Score^3) + I(Critic.Score^4), 
##     data = game.lm)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8634 -0.7892  0.0950  0.8837  5.5807 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        1.193e+01  7.115e-02 167.722  &lt; 2e-16 ***
## I(Critic.Score^3) -2.989e-03  7.972e-04  -3.749 0.000179 ***
## I(Critic.Score^4)  6.076e-04  8.224e-05   7.387 1.67e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.283 on 6822 degrees of freedom
## Multiple R-squared:  0.1597, Adjusted R-squared:  0.1595 
## F-statistic: 648.3 on 2 and 6822 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The coefficients are statistically significant — the simplified model with critic score to the third and fourth-degree terms, brings the drama with an R-squared of 0.16. Not quite a blockbuster hit, but certainly a critical darling.</p>
<p>To illustrate our findings:</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="the-game-sales-dataset.html#cb863-1" tabindex="-1"></a>ModelFunc <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {model<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> x<span class="sc">^</span><span class="dv">3</span><span class="sc">*</span>model<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">+</span></span>
<span id="cb863-2"><a href="the-game-sales-dataset.html#cb863-2" tabindex="-1"></a>                          x<span class="sc">^</span><span class="dv">4</span><span class="sc">*</span>model<span class="sc">$</span>coefficients[<span class="dv">3</span>]}</span>
<span id="cb863-3"><a href="the-game-sales-dataset.html#cb863-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> game.lm, <span class="fu">aes</span>(<span class="at">x =</span> Critic.Score, <span class="at">y =</span> Global.Sales.Log)) <span class="sc">+</span> </span>
<span id="cb863-4"><a href="the-game-sales-dataset.html#cb863-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb863-5"><a href="the-game-sales-dataset.html#cb863-5" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> ModelFunc, <span class="at">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="at">size =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-475-1.png" width="672" /></p>
<p>Here is the scatter plot of Global.Sales.Log versus Critic Score, along with the predictive curve based on the polynomial model, which forecasts the global sales log using critic score.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-476}</p>
</blockquote>
<blockquote>
<p>Visualize the distribution of NA_Sales in relation to Year_of_Release, Genre, Rating, and Platform using different plots, individually or combinedly. Interpret the relationship between NA_Sales with these factors. Hint: Consider applying log transformation to NA_Sales for better interpretability and potentially regroup platforms for a more consolidated view.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-477}</p>
</blockquote>
<blockquote>
<p>What is the correlation between NA_Sales and Critic_Score? Use scatter plot with smooth trend line or a fitted polynomial curve to show the relationship. Give me your findings.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-478}</p>
</blockquote>
<blockquote>
<p>Utilize linear modeling and ANOVA to analyze the contributing factors to the variance in NA_Sales. Provide a succinct interpretation of the results. Hint: Keep in mind the correlation patterns among those sales and scores highlighted in Figure <a href="the-game-sales-dataset.html#fig:game-corrplot">9.3</a>.
:::</p>
</blockquote>
</div>
<div id="conclusion-1" class="section level2 hasAnchor" number="9.8">
<h2><span class="header-section-number">9.8</span> Conclusion<a href="the-game-sales-dataset.html#conclusion-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While raw global and regional sales figures deviate from normality, their logarithmic counterparts dance closely with it. Patterns in regional sales harmonize with the global chorus.</p>
<p>Critic scores and user scores exhibit a sweet correlation, although the former typically trails the latter across most game titles. However, no clear-cut connection emerges between scores and the number of reviews.</p>
<p>Together, critic score, log-transformed user score count, genre, rating, platform, and publisher play their parts in the grand drama of log-transformation of global sales, with critic scores taking the star role, and the others in the supporting cast. Curtain call!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="state-dataset.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-messy-salary-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
