<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 The heart attack dataset (II) | Learn R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 The heart attack dataset (II) | Learn R through examples" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 The heart attack dataset (II) | Learn R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  

<meta name="author" content="Xijin Ge, Jianli Qi, and Rong Fan" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="the-heart-attack-data-set-i.html"/>
<link rel="next" href="advanced-topics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R programming:The iris flower dataset</a>
<ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting started</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-proper-way-of-using-rstudio"><i class="fa fa-check"></i><b>1.2</b> The proper way of using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.3</b> Data frames contain rows and columns: the iris flower dataset</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.4</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable"><i class="fa fa-check"></i><b>1.5</b> Analyzing a categorical variable</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables"><i class="fa fa-check"></i><b>1.6</b> The relationship between two numerical variables</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups"><i class="fa fa-check"></i><b>1.7</b> Testing the differences between two groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-differences-among-multiple-groups-anova"><i class="fa fa-check"></i><b>1.8</b> Testing differences among multiple groups (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html"><i class="fa fa-check"></i><b>2</b> Visualizing the iris flower data set</a>
<ul>
<li class="chapter" data-level="2.1" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#star-and-segment-diagrams"><i class="fa fa-check"></i><b>2.3</b> Star and segment diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#the-ggplot2-package-is-intuitive-and-powerful"><i class="fa fa-check"></i><b>2.4</b> The ggplot2 package is intuitive and powerful</a></li>
<li class="chapter" data-level="2.5" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#other-types-of-plots-with-ggplot2"><i class="fa fa-check"></i><b>2.5</b> Other types of plots with ggplot2</a></li>
<li class="chapter" data-level="2.6" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#hierarchical-clustering-and-heat-map"><i class="fa fa-check"></i><b>2.6</b> Hierarchical clustering and heat map</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.7</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#logistic-regression-for-binary-outcomes-prediction"><i class="fa fa-check"></i><b>2.8</b> Logistic Regression for Binary Outcomes Prediction</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#seeking-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Seeking help and example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.2</b> Matrices</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.5</b> Lists</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html"><i class="fa fa-check"></i><b>4</b> Importing data and managing files</a>
<ul>
<li class="chapter" data-level="4.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#project-oriented-workflow"><i class="fa fa-check"></i><b>4.1</b> Project-oriented workflow</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-project-in-a-new-folder"><i class="fa fa-check"></i><b>4.1.1</b> Create a project in a new folder</a></li>
<li class="chapter" data-level="4.1.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-script-file-and-comment-please"><i class="fa fa-check"></i><b>4.1.2</b> Create a script file (and Comment, Please!)</a></li>
<li class="chapter" data-level="4.1.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#copy-data-files-to-the-new-directory"><i class="fa fa-check"></i><b>4.1.3</b> Copy data files to the new directory</a></li>
<li class="chapter" data-level="4.1.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#import-data-files"><i class="fa fa-check"></i><b>4.1.4</b> Import data files</a></li>
<li class="chapter" data-level="4.1.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#check-and-convert-data-types"><i class="fa fa-check"></i><b>4.1.5</b> Check and convert data types</a></li>
<li class="chapter" data-level="4.1.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#close-a-project-when-you-are-done"><i class="fa fa-check"></i><b>4.1.6</b> Close a project when you are done</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#read-files-directly-using-read.table"><i class="fa fa-check"></i><b>4.2</b> Read files directly using read.table</a></li>
<li class="chapter" data-level="4.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.3</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#enter-data-manually"><i class="fa fa-check"></i><b>4.4</b> Enter data manually</a></li>
<li class="chapter" data-level="4.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-transformation-using-the-dplyr"><i class="fa fa-check"></i><b>4.6</b> Data transformation using the dplyr</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> The heart attack data set (I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-individually"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column individually</a></li>
<li class="chapter" data-level="5.2" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns</a></li>
<li class="chapter" data-level="5.3" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables</a></li>
<li class="chapter" data-level="5.4" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables</a></li>
<li class="chapter" data-level="5.5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html"><i class="fa fa-check"></i><b>6</b> The heart attack dataset (II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#statistical-models-easy-to-run-tricky-to-interpret"><i class="fa fa-check"></i><b>6.5</b> Statistical models: Easy to Run, tricky to interpret!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>7.1</b> Introduction to R Markdown</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> Tidyverse</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package"><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
<li class="chapter" data-level="7.4.4" data-path="advanced-topics.html"><a href="advanced-topics.html#publish-your-app"><i class="fa fa-check"></i><b>7.4.4</b> Publish your app</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-topics.html"><a href="advanced-topics.html#define-your-own-function"><i class="fa fa-check"></i><b>7.5</b> Define your own function</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="state-dataset.html"><a href="state-dataset.html"><i class="fa fa-check"></i><b>8</b> State dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="state-dataset.html"><a href="state-dataset.html#data-import-and-manipulation"><i class="fa fa-check"></i><b>8.1</b> Data Import and Manipulation</a></li>
<li class="chapter" data-level="8.2" data-path="state-dataset.html"><a href="state-dataset.html#visualizing-data"><i class="fa fa-check"></i><b>8.2</b> Visualizing data</a></li>
<li class="chapter" data-level="8.3" data-path="state-dataset.html"><a href="state-dataset.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="state-dataset.html"><a href="state-dataset.html#the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> The whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="state-dataset.html"><a href="state-dataset.html#linear-model-analysis"><i class="fa fa-check"></i><b>8.5</b> Linear model analysis</a></li>
<li class="chapter" data-level="8.6" data-path="state-dataset.html"><a href="state-dataset.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html"><i class="fa fa-check"></i><b>9</b> The game sales dataset</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#reading-in-data-and-managing-the-dataset"><i class="fa fa-check"></i><b>9.1</b> Reading in data and managing the dataset</a></li>
<li class="chapter" data-level="9.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#effect-of-platform-type-on-principle-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type on principle components</a></li>
<li class="chapter" data-level="9.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html"><i class="fa fa-check"></i><b>10</b> The messy salary data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#data-preparation-and-cleaning"><i class="fa fa-check"></i><b>10.1</b> Data Preparation and Cleaning</a></li>
<li class="chapter" data-level="10.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#variable-analysis"><i class="fa fa-check"></i><b>10.2</b> Variable Analysis</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income-types"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income types</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#defining-gross-income-types"><i class="fa fa-check"></i><b>10.4.1</b> Defining Gross income types</a></li>
<li class="chapter" data-level="10.4.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#the-intersection-of-ethnic-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> The Intersection of Ethnic, Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learn R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-heart-attack-dataset-ii" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> The heart attack dataset (II)<a href="the-heart-attack-dataset-ii.html#the-heart-attack-dataset-ii" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this chapter, we continue to investigate the heart attack dataset. First, let’s read in the data again and transform several variables into factors like in the previous chapter. Remember, you must set the working directory to where the data file is stored on your computer. Better yet, define a project associated with a folder, it’s like giving your data a cozy home.</p>
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb716-1"><a href="the-heart-attack-dataset-ii.html#cb716-1" tabindex="-1"></a><span class="co"># Set working directory. Skip if using a project.</span></span>
<span id="cb716-2"><a href="the-heart-attack-dataset-ii.html#cb716-2" tabindex="-1"></a><span class="co">#setwd(&quot;C:/YourPathHere&quot;)  </span></span>
<span id="cb716-3"><a href="the-heart-attack-dataset-ii.html#cb716-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;datasets/heartatk4R.txt&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)  <span class="co"># Ta-da! Data read</span></span>
<span id="cb716-4"><a href="the-heart-attack-dataset-ii.html#cb716-4" tabindex="-1"></a><span class="co"># Convert DRG, DIED, DIAGNOSIS, and SEX into factor</span></span>
<span id="cb716-5"><a href="the-heart-attack-dataset-ii.html#cb716-5" tabindex="-1"></a>df<span class="sc">$</span>DRG <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>DRG)</span>
<span id="cb716-6"><a href="the-heart-attack-dataset-ii.html#cb716-6" tabindex="-1"></a>df<span class="sc">$</span>DIED <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>DIED)</span>
<span id="cb716-7"><a href="the-heart-attack-dataset-ii.html#cb716-7" tabindex="-1"></a>df<span class="sc">$</span>DIAGNOSIS <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>DIAGNOSIS)</span>
<span id="cb716-8"><a href="the-heart-attack-dataset-ii.html#cb716-8" tabindex="-1"></a>df<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>SEX)</span>
<span id="cb716-9"><a href="the-heart-attack-dataset-ii.html#cb716-9" tabindex="-1"></a><span class="fu">str</span>(df)  <span class="co"># Double check to make sure everything looks good</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    12844 obs. of  8 variables:
##  $ Patient  : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ DIAGNOSIS: Factor w/ 9 levels &quot;41001&quot;,&quot;41011&quot;,..: 5 5 9 8 9 9 9 9 5 5 ...
##  $ SEX      : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 1 1 2 2 1 1 2 1 ...
##  $ DRG      : Factor w/ 3 levels &quot;121&quot;,&quot;122&quot;,&quot;123&quot;: 2 2 2 2 2 1 1 1 1 3 ...
##  $ DIED     : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ CHARGES  : num  4752 3941 3657 1481 1681 ...
##  $ LOS      : int  10 6 5 2 1 9 15 15 2 1 ...
##  $ AGE      : int  79 34 76 80 55 84 84 70 76 65 ...</code></pre>
<div id="scatter-plot-in-ggplot2" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Scatter plot in ggplot2<a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Did you know Hadley Wickham, our ggplot2 superhero, inspired by Leland Wilkinson’s “grammar of graphics”, wrote the ggplot2 package in 2005 providing a formal, structured way of visualizing data? Just like how R was originally written by Robert Gentleman and Ross Ihaka in the 1990s; Linux was developed by Linus Torvalds, a student, at the same period. A few superheroes can make computing much easier for millions of people. ggplot2 revolutionized data visualization in R.</p>
<div class="sourceCode" id="cb718"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb718-1"><a href="the-heart-attack-dataset-ii.html#cb718-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)  <span class="co"># Load the package</span></span>
<span id="cb718-2"><a href="the-heart-attack-dataset-ii.html#cb718-2" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES))  <span class="co"># Specify data frame and aesthetic mapping</span></span></code></pre></div>
<p>This line is just the opening act, setting the scene. It specifies the name of the data frame, which is the required input data type, and defines the so-called <strong>aesthetic mapping</strong>: LOS maps to x-axis while CHARGES maps to the y-axis. To bring the plot to life, we use the geom_point function to add data points, which is called <strong>geometric objects</strong>.</p>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="the-heart-attack-dataset-ii.html#cb719-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES)) <span class="sc">+</span> <span class="fu">geom_point</span>()   <span class="co"># Scatter plot</span></span></code></pre></div>
<p>Thus, it is a two-step process to generate a scatter plot. Initially, it may feel cumbersome with too many steps, but it is super handy to add additional features or customize the plot step by step. Let’s add a trend line with a confidence interval for good measure.</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb720-1"><a href="the-heart-attack-dataset-ii.html#cb720-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method =</span> lm)</span></code></pre></div>
<p>As we keep adding elements to the plot, this line of code gets longer. To keep it reader-friendly, let’s split it into multiple lines as below. The “+” at the end of the line signifies that the plot is not finished yet and tell R to keep reading the next line. I often use the tab key in the second line to remind myself that it is continued from the above line.</p>
<div class="sourceCode" id="cb721"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb721-1"><a href="the-heart-attack-dataset-ii.html#cb721-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES)) <span class="sc">+</span>  <span class="co"># Set aesthetic mapping</span></span>
<span id="cb721-2"><a href="the-heart-attack-dataset-ii.html#cb721-2" tabindex="-1"></a>         <span class="fu">geom_point</span>() <span class="sc">+</span>                <span class="co"># Add data points    </span></span>
<span id="cb721-3"><a href="the-heart-attack-dataset-ii.html#cb721-3" tabindex="-1"></a>       <span class="fu">stat_smooth</span>(<span class="at">method =</span> lm)          <span class="co"># Add trend line</span></span></code></pre></div>
<p>As you have seen from this code, it not only makes the code easier reading but also allows room for side comments for each step - a lifesaver when recycling code.</p>
<p>Let’s customize the plot by adding additional lines of code (Figure <a href="the-heart-attack-dataset-ii.html#fig:15-1">6.1</a>):</p>

<div class="sourceCode" id="cb722"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb722-1"><a href="the-heart-attack-dataset-ii.html#cb722-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES)) <span class="sc">+</span>                 <span class="co"># Set aesthetic mapping</span></span>
<span id="cb722-2"><a href="the-heart-attack-dataset-ii.html#cb722-2" tabindex="-1"></a>       <span class="fu">geom_point</span>() <span class="sc">+</span>                                   <span class="co"># Add data points    </span></span>
<span id="cb722-3"><a href="the-heart-attack-dataset-ii.html#cb722-3" tabindex="-1"></a>       <span class="fu">stat_smooth</span>(<span class="at">method =</span> lm) <span class="sc">+</span>                       <span class="co"># Add trend line</span></span>
<span id="cb722-4"><a href="the-heart-attack-dataset-ii.html#cb722-4" tabindex="-1"></a>       <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="sc">+</span>                                 <span class="co"># Adjust plot limits of x-axis </span></span>
<span id="cb722-5"><a href="the-heart-attack-dataset-ii.html#cb722-5" tabindex="-1"></a>       <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Length of stay&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Charges ($)&quot;</span>) <span class="sc">+</span>  <span class="co"># Change x and y labels</span></span>
<span id="cb722-6"><a href="the-heart-attack-dataset-ii.html#cb722-6" tabindex="-1"></a>       <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">3</span>, <span class="at">y =</span> <span class="dv">45000</span>, <span class="at">label =</span> (<span class="st">&quot;R = 0.74&quot;</span>))  <span class="co"># Add text to plot coordinates</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-1"></span>
<img src="book_files/figure-html/15-1-1.png" alt="Scatter plot using ggplot2." width="480" />
<p class="caption">
Figure 6.1: Scatter plot using ggplot2.
</p>
</div>
<p>For more customization ideas, a simple Google search can be your guide. For example, add title to the plot by using keyword “ggplot2 add title to plot”. It is easy for ggplot2 to represent other characteristics using additional aesthetic mappings, such as linetype, color, size, fill (“inside” color).</p>
<div class="sourceCode" id="cb723"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb723-1"><a href="the-heart-attack-dataset-ii.html#cb723-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES)) <span class="sc">+</span> <span class="fu">geom_point</span>()               <span class="co"># Create basic scatter plot</span></span>
<span id="cb723-2"><a href="the-heart-attack-dataset-ii.html#cb723-2" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES, <span class="at">color =</span> DRG)) <span class="sc">+</span> <span class="fu">geom_point</span>()  <span class="co"># Map DRG to color</span></span></code></pre></div>

<div class="sourceCode" id="cb724"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb724-1"><a href="the-heart-attack-dataset-ii.html#cb724-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> LOS, <span class="at">y =</span> CHARGES, <span class="at">color =</span> DRG, <span class="at">shape =</span> SEX)) <span class="sc">+</span>  <span class="co"># Map SEX to shape</span></span>
<span id="cb724-2"><a href="the-heart-attack-dataset-ii.html#cb724-2" tabindex="-1"></a>       <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-2"></span>
<img src="book_files/figure-html/15-2-1.png" alt="Changing color and shape to represent multivariate data in ggplot2." width="576" />
<p class="caption">
Figure 6.2: Changing color and shape to represent multivariate data in ggplot2.
</p>
</div>
<p>Each step lets us reveal additional information about these patients (Figure <a href="the-heart-attack-dataset-ii.html#fig:15-2">6.2</a>). With ggplot2, we can visualize complex, multivariate data by mapping different columns into diverse types of aesthetics. Figure <a href="the-heart-attack-dataset-ii.html#fig:15-1">6.1</a> shows a strong positive correlation between charges and length of hospital stay, which is expected as many itemized costs are billed daily. Note there are over 12,000 data points, many are plotted near or exactly at the same places, especially at the lower left corner. To decode this density, try stat_density2d().</p>
<p>When saving these masterpieces, remember that vector formats (like <strong>metafile</strong>) offer high resolution but can be hefty in size. If you have many such plots in a paper or thesis, your file size can be big. Consider the <strong>bitmap</strong> format for a lightweight alternative.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-370}</p>
</blockquote>
<blockquote>
<p>Generate a scatter plot of age vs. charges in the heart attack dataset using ggplot2. Represent DRG with different shapes of data points and color-code data points based on diagnosis.</p>
<p>heartatk4R &lt;- read.table(_______________________________)</p>
<p>ggplot(heartatk4R, aes(x = _______, y = ________, color = _________, shape = _________)) +</p>
<p>geom_point()
:::</p>
</blockquote>
</div>
<div id="histograms-and-density-plots" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Histograms and density plots<a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to data points(geom_points), there are many other <strong>geometric objects</strong>, such as histogram(geom_histogram), lines (geom_line), bars (geom_bar), and so on. We can use these geometric objects to generate different types of plots.
Let’s start with a histogram:</p>
<div class="sourceCode" id="cb725"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb725-1"><a href="the-heart-attack-dataset-ii.html#cb725-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p>Next, let’s refine it by adding a density curve (Figure <a href="the-heart-attack-dataset-ii.html#fig:15-3">6.3</a>):</p>

<div class="sourceCode" id="cb726"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb726-1"><a href="the-heart-attack-dataset-ii.html#cb726-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">y =</span> ..density..)) <span class="sc">+</span> </span>
<span id="cb726-2"><a href="the-heart-attack-dataset-ii.html#cb726-2" tabindex="-1"></a>       <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">&quot;cornsilk&quot;</span>, </span>
<span id="cb726-3"><a href="the-heart-attack-dataset-ii.html#cb726-3" tabindex="-1"></a>                      <span class="at">colour =</span> <span class="st">&quot;grey60&quot;</span>, <span class="at">size =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb726-4"><a href="the-heart-attack-dataset-ii.html#cb726-4" tabindex="-1"></a>       <span class="fu">geom_density</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-3"></span>
<img src="book_files/figure-html/15-3-1.png" alt="Histogram with density curve." width="576" />
<p class="caption">
Figure 6.3: Histogram with density curve.
</p>
</div>
<p>Combined density plots are useful in comparing the distribution of subgroups of data points. Start with a plot for all:</p>
<div class="sourceCode" id="cb727"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb727-1"><a href="the-heart-attack-dataset-ii.html#cb727-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># A density plot for all</span></span></code></pre></div>
<p>Add a splash of color to differentiate sex:</p>
<div class="sourceCode" id="cb728"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb728-1"><a href="the-heart-attack-dataset-ii.html#cb728-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">color =</span> SEX)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># Figure 6.4A</span></span></code></pre></div>
<p>Here, we split the dataset by gender, and plotted the density distribution on the same plot. Figure <a href="the-heart-attack-dataset-ii.html#fig:15-4">6.4</a>A shows that age distributions are very different between men and women. Women skew rightward, averaging over a decade older than men. This is surprising, given that this dataset contains all heart attack admissions in New York state in 1993.</p>
<p>The fill mapping changes the “inside” color:</p>
<div class="sourceCode" id="cb729"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb729-1"><a href="the-heart-attack-dataset-ii.html#cb729-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">fill =</span> SEX)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)  <span class="co"># Figure 6.4B</span></span></code></pre></div>
<p>This plot shows the same information. But it looks nicer, at least to me. We can also <strong>split the plot into multiple facets</strong> for even more depth:</p>
<div class="sourceCode" id="cb730"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb730-1"><a href="the-heart-attack-dataset-ii.html#cb730-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">fill =</span> SEX)) <span class="sc">+</span> </span>
<span id="cb730-2"><a href="the-heart-attack-dataset-ii.html#cb730-2" tabindex="-1"></a>       <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> <span class="fu">facet_grid</span>(DRG <span class="sc">~</span>.)  <span class="co"># Figure 6.4C</span></span></code></pre></div>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-4"></span>
<img src="images/img1504_density.png" alt="The art of density plots."  />
<p class="caption">
Figure 6.4: The art of density plots.
</p>
</div>
<p>Recall: DRG=121 represents patients who survived but developed complications; DRG=122 denotes those without complications and DRG=123 are patients who did not survive. Figure <a href="the-heart-attack-dataset-ii.html#fig:15-4">6.4</a>C indicates that women in all three groups are older than men. A closer look at the male patients’ age distribution across DRG facets suggests that the distribution skews to the right in deceased patients (DRG=123), indicating that older patients are less likely to survive a heart attack. Also, survivors without complications (DRG= 122) tend to be younger than those with complications.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-376}</p>
</blockquote>
<blockquote>
<p>Create density plots like Figure 6.5 to compare the distribution of length of hospital stay (LOS) for patients with different DRG groups, separated by gender. Offer interpretation in the context of the dataset. Limit the x-axis to 0 to 20.</p>
<p>ggplot(heartatk4R, aes(_________, _________)) + ______________(alpha = 0.3) +</p>
<p>_________(________ ~ .) + xlim(________, _____)
:::</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-377"></span>
<img src="book_files/figure-html/unnamed-chunk-377-1.png" alt="Distribution of LOS by DRG categories grouped by SEX" width="576" />
<p class="caption">
Figure 6.5: Distribution of LOS by DRG categories grouped by SEX
</p>
</div>
</blockquote>
</div>
<div id="box-plots-and-violin-plots" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Box plots and Violin plots<a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the symphony of ggplot2, boxplots and violin plots are like the string instruments - each offering a unique way to play out the data.
We can follow the same rule of <strong>geometric objects</strong> to generate boxplots using geom_boxplot(), and violin plots with geom_violin(). Let’s start with a basic version.</p>
<div class="sourceCode" id="cb731"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb731-1"><a href="the-heart-attack-dataset-ii.html#cb731-1" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> SEX, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()  <span class="co">#  Create basic boxplot </span></span>
<span id="cb731-2"><a href="the-heart-attack-dataset-ii.html#cb731-2" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> SEX, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(DRG <span class="sc">~</span> .)  <span class="co"># Figure 6.6A</span></span>
<span id="cb731-3"><a href="the-heart-attack-dataset-ii.html#cb731-3" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> SEX, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_violin</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(DRG <span class="sc">~</span> .)  <span class="co"># Figure 6.6B</span></span></code></pre></div>
<p>The violin plot reveals more details about the distribution. Essentially, violin plot is like a boxplot showing density plot’s elegance on either side of the “violin”.</p>
<p>Time to compose your own visual masterpiece:</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-379}</p>
</blockquote>
<blockquote>
<p>Generate a violin plot like Figure 6.6C to compare the distribution of length of hospital stay among patients with different prognosis outcomes (DRG), categorized by gender. Interpret your result. Note the axes labels are customized.</p>
<p>ggplot(heartatk4R, ___________________) + _____________ + ______________ +</p>
<p>labs(x = “DRG groups”, y = “Length of Stay(days)”) + ylim(0, 20)
:::</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-380"></span>
<img src="images/img1506_boxviolin.png" alt="Boxplot and violin plots using ggplot2"  />
<p class="caption">
Figure 6.6: Boxplot and violin plots using ggplot2
</p>
</div>
</blockquote>
</div>
<div id="bar-plot-with-error-bars" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Bar plot with error bars<a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Curious whether patients with certain diagnosis codes stay longer or shorter in the hospital after a heart attack? We could, of course, use the aggregate function to generate a table with mean LOS by diagnosis category.</p>
<div class="sourceCode" id="cb732"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb732-1"><a href="the-heart-attack-dataset-ii.html#cb732-1" tabindex="-1"></a><span class="fu">aggregate</span>(df, <span class="at">by =</span> <span class="fu">list</span>(df<span class="sc">$</span>DIAGNOSIS), <span class="at">FUN =</span> mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##   Group.1  Patient DIAGNOSIS SEX DRG DIED   CHARGES      LOS      AGE
## 1   41001 7130.229        NA  NA  NA   NA 10868.030 7.775161 65.56317
## 2   41011 6413.323        NA  NA  NA   NA 10631.803 7.728618 65.81305
## 3   41021 6482.808        NA  NA  NA   NA 10666.687 7.556000 63.96000
## 4   41031 6356.028        NA  NA  NA   NA  9908.118 6.679715 62.93950
## 5   41041 6259.752        NA  NA  NA   NA  9985.722 7.307692 63.73884
## 6   41051 6438.974        NA  NA  NA   NA  9062.423 7.298701 67.22078
## 7   41071 6949.627        NA  NA  NA   NA  9750.309 7.834997 69.01996
## 8   41081 8384.725        NA  NA  NA   NA  9633.123 7.048780 68.04181
## 9   41091 6165.481        NA  NA  NA   NA  9511.093 7.625743 67.10359</code></pre>
<p>We may be happy with this table and call it quits. However, tables are often not easy to interpret compared with well-crafted graphs. Instead of the aggregate function, we can use the powerful dplyr package to summarize the data and then to generate a bar plot showing both the means and standard errors. I’ve borrowed some nifty codes and ideas from R graphics cookbook and this informative website: <a href="http://environmentalcomputing.net/plotting-with-ggplot-bar-plots-with-error-bars/">http://environmentalcomputing.net/plotting-with-ggplot-bar-plots-with-error-bars/</a>.</p>
<div class="sourceCode" id="cb734"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb734-1"><a href="the-heart-attack-dataset-ii.html#cb734-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)  <span class="co"># Load the package</span></span></code></pre></div>
<p>To summarize data by groups/factors, the dplyr package uses a ggplot2-like grammar, where operations flow step by step. Similar to pipes in Unix, commands separated by “%&gt;%” are executed sequentially where the output of one step becomes the input of the next. The follow 6 lines form one command, consisting of three major steps.</p>
<div class="sourceCode" id="cb735"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb735-1"><a href="the-heart-attack-dataset-ii.html#cb735-1" tabindex="-1"></a>stats <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span>  <span class="co"># Name the new data frame and source data frame</span></span>
<span id="cb735-2"><a href="the-heart-attack-dataset-ii.html#cb735-2" tabindex="-1"></a>  <span class="fu">group_by</span>(DIAGNOSIS) <span class="sc">%&gt;%</span>  <span class="co"># Group by diagnosis</span></span>
<span id="cb735-3"><a href="the-heart-attack-dataset-ii.html#cb735-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(LOS),  <span class="co"># Calculate group means</span></span>
<span id="cb735-4"><a href="the-heart-attack-dataset-ii.html#cb735-4" tabindex="-1"></a>            <span class="at">sd   =</span> <span class="fu">sd</span>(LOS),    <span class="co"># And standard deviation of each group</span></span>
<span id="cb735-5"><a href="the-heart-attack-dataset-ii.html#cb735-5" tabindex="-1"></a>            <span class="at">n    =</span> <span class="fu">n</span>(),        <span class="co"># Count sample size per group</span></span>
<span id="cb735-6"><a href="the-heart-attack-dataset-ii.html#cb735-6" tabindex="-1"></a>            <span class="at">se   =</span> <span class="fu">sd</span>(LOS) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>()))  <span class="co"># Compute standard error of each group</span></span></code></pre></div>
<p>Here is a detailed summary by DIAGNOSIS:</p>
<div class="sourceCode" id="cb736"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb736-1"><a href="the-heart-attack-dataset-ii.html#cb736-1" tabindex="-1"></a>stats</span></code></pre></div>
<pre><code>## # A tibble: 9 × 5
##   DIAGNOSIS  mean    sd     n     se
##   &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
## 1 41001      7.78  5.69   467 0.263 
## 2 41011      7.73  5.34  1824 0.125 
## 3 41021      7.56  5.26   250 0.333 
## 4 41031      6.68  4.15   281 0.247 
## 5 41041      7.31  4.75  2665 0.0920
## 6 41051      7.30  4.54   154 0.366 
## 7 41071      7.83  5.28  1703 0.128 
## 8 41081      7.05  5.32   287 0.314 
## 9 41091      7.63  5.14  5213 0.0712</code></pre>
<p>Now let’s bring these statistics to life with ggplot2 (Figure <a href="the-heart-attack-dataset-ii.html#fig:15-7">6.7</a>):</p>

<div class="sourceCode" id="cb738"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb738-1"><a href="the-heart-attack-dataset-ii.html#cb738-1" tabindex="-1"></a><span class="fu">ggplot</span>(stats, <span class="fu">aes</span>(<span class="at">x =</span> DIAGNOSIS, <span class="at">y =</span> mean)) <span class="sc">+</span>   <span class="co"># Data &amp; aesthetic mapping</span></span>
<span id="cb738-2"><a href="the-heart-attack-dataset-ii.html#cb738-2" tabindex="-1"></a>         <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="sc">+</span>            <span class="co"># Bars represent average</span></span>
<span id="cb738-3"><a href="the-heart-attack-dataset-ii.html#cb738-3" tabindex="-1"></a>         <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> se, <span class="at">ymax =</span> mean <span class="sc">+</span> se), <span class="at">width =</span> <span class="fl">0.2</span>)  <span class="co"># Add error bars</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-7"></span>
<img src="book_files/figure-html/15-7-1.png" alt="Average LOS by DIAGNOSIS group with error bars representing standard error" width="576" />
<p class="caption">
Figure 6.7: Average LOS by DIAGNOSIS group with error bars representing standard error
</p>
</div>
<p>Notice how we define error bars with the mean-se and mean+se referring to the two columns in the “stats” data frame. Because we have an extremely large sample size, the standard errors are relatively small. Interestingly, patients with a diagnosis of 41031 stay shorter in the hospital. A peek at the IDC code in <a href="http://www.nuemd.com">http://www.nuemd.com</a> tells us this code represents “Acute myocardial infarction of inferoposterior wall, initial episode of care”, which probably makes sense.</p>
<p>As we did previously, now let’s define the LOS bars for men and women separately. First, we need to fresh stats and generate different summary statistics.</p>
<div class="sourceCode" id="cb739"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb739-1"><a href="the-heart-attack-dataset-ii.html#cb739-1" tabindex="-1"></a>stats2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb739-2"><a href="the-heart-attack-dataset-ii.html#cb739-2" tabindex="-1"></a>  <span class="fu">group_by</span>(DIAGNOSIS, SEX) <span class="sc">%&gt;%</span>   <span class="co"># Group by both diagnosis and sex</span></span>
<span id="cb739-3"><a href="the-heart-attack-dataset-ii.html#cb739-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(LOS),  </span>
<span id="cb739-4"><a href="the-heart-attack-dataset-ii.html#cb739-4" tabindex="-1"></a>            <span class="at">sd   =</span> <span class="fu">sd</span>(LOS), </span>
<span id="cb739-5"><a href="the-heart-attack-dataset-ii.html#cb739-5" tabindex="-1"></a>            <span class="at">n    =</span> <span class="fu">n</span>(),  </span>
<span id="cb739-6"><a href="the-heart-attack-dataset-ii.html#cb739-6" tabindex="-1"></a>            <span class="at">se   =</span> <span class="fu">sd</span>(LOS) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">n</span>())) </span></code></pre></div>
<p>The entire dataset is now divided into 18 groups according to all possible combinations of DIAGNOSIS and SEX. Each group’s LOS is summarized in terms of mean, standard deviation (sd), observations (n), and standard errors(se). Here’s the summarized data frame:</p>
<div class="sourceCode" id="cb740"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb740-1"><a href="the-heart-attack-dataset-ii.html#cb740-1" tabindex="-1"></a>stats2</span></code></pre></div>
<pre><code>## # A tibble: 18 × 6
## # Groups:   DIAGNOSIS [9]
##    DIAGNOSIS SEX    mean    sd     n     se
##    &lt;fct&gt;     &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
##  1 41001     F      8.74  6.03   175 0.456 
##  2 41001     M      7.20  5.41   292 0.316 
##  3 41011     F      8.41  6.23   692 0.237 
##  4 41011     M      7.31  4.66  1132 0.139 
##  5 41021     F      8.54  5.82   100 0.582 
##  6 41021     M      6.9   4.76   150 0.389 
##  7 41031     F      6.41  4.67    96 0.477 
##  8 41031     M      6.82  3.86   185 0.283 
##  9 41041     F      7.79  5.18   998 0.164 
## 10 41041     M      7.02  4.45  1667 0.109 
## 11 41051     F      7.93  5.64    69 0.679 
## 12 41051     M      6.79  3.34    85 0.362 
## 13 41071     F      8.65  5.76   727 0.214 
## 14 41071     M      7.23  4.80   976 0.154 
## 15 41081     F      7.58  5.60   130 0.492 
## 16 41081     M      6.61  5.04   157 0.402 
## 17 41091     F      8.34  5.76  2078 0.126 
## 18 41091     M      7.15  4.63  3135 0.0826</code></pre>
<p>Now we are ready to generate bar plot for men and women separately using the fill aesthetic mapping:</p>

<div class="sourceCode" id="cb742"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb742-1"><a href="the-heart-attack-dataset-ii.html#cb742-1" tabindex="-1"></a><span class="fu">ggplot</span>(stats2, <span class="fu">aes</span>(<span class="at">x =</span> DIAGNOSIS, <span class="at">y =</span> mean, <span class="at">fill =</span> SEX)) <span class="sc">+</span>  <span class="co"># Map the aesthetics</span></span>
<span id="cb742-2"><a href="the-heart-attack-dataset-ii.html#cb742-2" tabindex="-1"></a>       <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>) <span class="sc">+</span>    <span class="co"># Plot bars for mean of LOS</span></span>
<span id="cb742-3"><a href="the-heart-attack-dataset-ii.html#cb742-3" tabindex="-1"></a>       <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Diagnosis codes&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Length of Stay&quot;</span>) <span class="sc">+</span>  <span class="co"># Label axes</span></span>
<span id="cb742-4"><a href="the-heart-attack-dataset-ii.html#cb742-4" tabindex="-1"></a>       <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> mean <span class="sc">-</span> se, <span class="at">ymax =</span> mean <span class="sc">+</span> se),  <span class="co"># Add error bars</span></span>
<span id="cb742-5"><a href="the-heart-attack-dataset-ii.html#cb742-5" tabindex="-1"></a>       <span class="at">position =</span> <span class="fu">position_dodge</span>(.<span class="dv">9</span>), <span class="at">width =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-8"></span>
<img src="book_files/figure-html/15-8-1.png" alt="The length of stay summarized by diagnosis and sex. Error bars represent standard error." width="576" />
<p class="caption">
Figure 6.8: The length of stay summarized by diagnosis and sex. Error bars represent standard error.
</p>
</div>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:15-9"></span>
<img src="book_files/figure-html/15-9-1.png" alt="Mean ages for patients with different diagnosis and treatment outcome." width="576" />
<p class="caption">
Figure 6.9: Mean ages for patients with different diagnosis and treatment outcome.
</p>
</div>
<blockquote>
<p>::: {.exercise #unnamed-chunk-388}</p>
</blockquote>
<blockquote>
<p>Generate Figure <a href="the-heart-attack-dataset-ii.html#fig:15-9">6.9</a> and offer your interpretation. Modify both the summarizing script and the plotting script.</p>
<p>df &lt;- heartatk4R %&gt;%</p>
<p>_____________(DIAGNOSIS, DRG) %&gt;% # Group by both diagnosis and sex</p>
<p>_____________(mean = mean(AGE),</p>
<p>sd = sd(AGE),</p>
<p>n = n(),</p>
<p>se = sd(AGE) / sqrt(n()))</p>
<p>ggplot(df, aes(_________________________) + # Map the aesthetics</p>
<p>_______________(stat = “identity”, position = “dodge”) + # Plot bars</p>
<p>_______________(x = “Diagnosis codes”, y = “Age(yrs)”) + # Label axes</p>
<p>_______________(aes(__________________, ________________), # Add error bars</p>
<p>position = position_dodge(.9), width = 0.2)
:::</p>
</blockquote>
<p>Overall, our investigation uncovers that women are much older than men when admitted to hospital for heart attack, facing higher mortality and complication rates. It is not because they develop heart attack later in life, but their symptoms are subtler and often more easily get ignored. Remember, a heart attack might not always scream through chest pain; it could sometimes masquerade as back pain, numbness in the arm, or pain in the jaw or teeth! (Warning: Statistics professor is talking about medicine!)</p>
<p>As you could see from these plots, <strong>ggplot2</strong> generates attractive, publication-ready graphics. Moreover, it is a relatively structured way of customizing plots. That’s why it is becoming popular among R users.
Once again, there are many example codes and answered R coding questions online. Whatever you want to do, you can <strong>google it, try the example code</strong>, and modify it to fit your needs. Remember, Google is your friend for codes and solutions. And it’s all free! Enjoy coding!</p>
</div>
<div id="statistical-models-easy-to-run-tricky-to-interpret" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Statistical models: Easy to Run, tricky to interpret!<a href="the-heart-attack-dataset-ii.html#statistical-models-easy-to-run-tricky-to-interpret" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Navigating the complex world of statistical models is like solving a mystery – running the code is straightforward, but interpreting and verifying the results requires a detective’s eye!</p>
<p>By using pair-wised correlation analysis, here is a key finding: Women experience a higher mortality rate than men from heart attack, and tend to be older than men. However, this straightforward observation masks underlying confounding effects.
To unravel the mystery, we need to <strong>delineate the effects of multiple factors using multiple linear regression</strong>.</p>
<p>Here’s how we model the hospital charges as a function of all other factors:</p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="the-heart-attack-dataset-ii.html#cb743-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(CHARGES <span class="sc">~</span> SEX <span class="sc">+</span> LOS <span class="sc">+</span> AGE <span class="sc">+</span> DRG <span class="sc">+</span> DIAGNOSIS, <span class="at">data =</span> df)</span>
<span id="cb743-2"><a href="the-heart-attack-dataset-ii.html#cb743-2" tabindex="-1"></a><span class="fu">summary</span>(fit) </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = CHARGES ~ SEX + LOS + AGE + DRG + DIAGNOSIS, data = df)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -31486  -2453   -674   1766  32979 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     6863.753    314.515  21.823  &lt; 2e-16 ***
## SEXM             183.085     84.131   2.176  0.02956 *  
## LOS              989.717      8.268 119.700  &lt; 2e-16 ***
## AGE              -55.255      3.216 -17.180  &lt; 2e-16 ***
## DRG122          -916.531     86.851 -10.553  &lt; 2e-16 ***
## DRG123          1488.187    141.771  10.497  &lt; 2e-16 ***
## DIAGNOSIS41011  -136.097    230.312  -0.591  0.55458    
## DIAGNOSIS41021   137.118    349.948   0.392  0.69520    
## DIAGNOSIS41031   201.021    334.056   0.602  0.54735    
## DIAGNOSIS41041  -349.932    223.352  -1.567  0.11720    
## DIAGNOSIS41051 -1162.651    408.621  -2.845  0.00444 ** 
## DIAGNOSIS41071  -755.549    233.214  -3.240  0.00120 ** 
## DIAGNOSIS41081  -353.290    332.747  -1.062  0.28838    
## DIAGNOSIS41091 -1042.968    215.038  -4.850 1.25e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4308 on 12131 degrees of freedom
##   (699 observations deleted due to missingness)
## Multiple R-squared:  0.569,  Adjusted R-squared:  0.5685 
## F-statistic:  1232 on 13 and 12131 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In this model, one reference level for each factor(such as female) is used as a baseline for comparison, so it does not display. Interestingly, being male (SEXM), shows a marginally significant effect on charges; In detail, if everything else being equal, a male patient will incur $183 dollars more cost than female for the hospital stay. It is really small number compared to overall charges and also the p value is just marginally significant for this large sample(0.02956). However, this finding is in contrast to the <strong>t.test(CHARGES ~ SEX)</strong> shown below, where we got the opposite conclusion with much smaller p value of 4.573e-07. It is because the t-test did not account for other factors, while the regression model did.</p>
<div class="sourceCode" id="cb745"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb745-1"><a href="the-heart-attack-dataset-ii.html#cb745-1" tabindex="-1"></a><span class="fu">t.test</span>(CHARGES <span class="sc">~</span> SEX, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  CHARGES by SEX
## t = 5.047, df = 9355.3, p-value = 4.573e-07
## alternative hypothesis: true difference in means between group F and group M is not equal to 0
## 95 percent confidence interval:
##  384.9901 873.9597
## sample estimates:
## mean in group F mean in group M 
##       10260.660        9631.185</code></pre>
<p>Returning to our multiple linear regression model we can see that the most pronounced effect is LOS. This is not surprising, as many hospitals have charges on daily basis. Since the p values are cutoff at 2e-16, the <strong>t value</strong> is an indicator of significance. LOS has a t value of 119.7, which is way bigger than that for all other variables. If I am an insurance company CEO, I will do anything I can to push the hospitals to discharge patients as early as possible. The coefficient tells us, for the average patient, one extra day of stay in the hospital increases the charges by 989.7 dollars. Surprisingly, age has a negative effect. Which means, when other factors are controlled, older patients are actually charged less. Good news for the older demographic - there is no reason to charge older patients more in terms of insurance premiums. Also, there is a little evidence in gender differences in charges. Compared with patients who had complications (DRG = 121, the baseline), those have no complications (DRG = 122) incurred less charges on average by the amount of $916. Sadly, patients who died(DRG = 123) are likely to be charged more. Diagnosis codes also play a role: patients with diagnosis codes 41091, 41051 and 41071 incurred less charges compared with those with 41001.</p>
<p>Now let’s investigate mortality. It is a binary outcome, so we turn to <strong>logistic regression</strong>.</p>
<div class="sourceCode" id="cb747"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb747-1"><a href="the-heart-attack-dataset-ii.html#cb747-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(DIED <span class="sc">~</span> SEX <span class="sc">+</span> LOS <span class="sc">+</span> AGE <span class="sc">+</span> DIAGNOSIS, <span class="at">family =</span> <span class="fu">binomial</span>( ), <span class="at">data =</span> df)</span>
<span id="cb747-2"><a href="the-heart-attack-dataset-ii.html#cb747-2" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = DIED ~ SEX + LOS + AGE + DIAGNOSIS, family = binomial(), 
##     data = df)
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)    -5.359769   0.263001 -20.379  &lt; 2e-16 ***
## SEXM           -0.345084   0.064978  -5.311 1.09e-07 ***
## LOS            -0.248553   0.009197 -27.025  &lt; 2e-16 ***
## AGE             0.081122   0.002995  27.082  &lt; 2e-16 ***
## DIAGNOSIS41011 -0.404406   0.157454  -2.568  0.01022 *  
## DIAGNOSIS41021 -0.336452   0.254026  -1.324  0.18534    
## DIAGNOSIS41031 -0.784819   0.262089  -2.994  0.00275 ** 
## DIAGNOSIS41041 -0.991677   0.158059  -6.274 3.52e-10 ***
## DIAGNOSIS41051 -0.235784   0.279752  -0.843  0.39932    
## DIAGNOSIS41071 -1.719416   0.178522  -9.631  &lt; 2e-16 ***
## DIAGNOSIS41081 -0.484542   0.226713  -2.137  0.03258 *  
## DIAGNOSIS41091 -0.677723   0.145463  -4.659 3.18e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 8889.4  on 12843  degrees of freedom
## Residual deviance: 6844.2  on 12832  degrees of freedom
## AIC: 6868.2
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<p>Note that DIED is coded 1 for patients died, and 0 for survivors. A negative coefficient indicates less likely to die, hence more likely to survive. Males are more likely to survive heart attack, compared with females with the same age and diagnosis. patients with longer hospital stay have better survival chances, while older patients are more likely to die. Compared with patients with diagnosis code of 41001, those diagnosed with 41071, 41041, and 41091, are more likely to survive.</p>
<p>Now, it’s your turn to explore the factors influencing length of stay:</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-392}</p>
</blockquote>
<blockquote>
<p>Use multiple linear regression to investigate the factors affecting length of stay(LOS), excluding charges. Interpret your results.</p>
<p>fit &lt;- ___________(LOS ~ SEX + AGE + DRG + DIAGNOSIS, data = ___________)</p>
<p>___________(fit)
:::</p>
</blockquote>
<p>While not part of the exercise, another query we may interested in is identifying factors contributing to complications in surviving patients. Her, focusing only on the survivors and using logistic regression would be the way to go.</p>
<p>Remember, pair-wise examinations are crucial; including two highly correlated factors in the same model is a statistical faux pas. Happy data deciphering!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="the-heart-attack-data-set-i.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="advanced-topics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
