<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 The heart attack data set (I) | Learn R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 The heart attack data set (I) | Learn R through examples" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 The heart attack data set (I) | Learn R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  

<meta name="author" content="Xijin Ge, Jianli Qi, and Rong Fan" />


<meta name="date" content="2024-01-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="importing-data-and-managing-files.html"/>
<link rel="next" href="the-heart-attack-dataset-ii.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R programming:The iris flower dataset</a>
<ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting started</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-proper-way-of-using-rstudio"><i class="fa fa-check"></i><b>1.2</b> The proper way of using RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.3</b> Data frames contain rows and columns: the iris flower dataset</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.4</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable"><i class="fa fa-check"></i><b>1.5</b> Analyzing a categorical variable</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables"><i class="fa fa-check"></i><b>1.6</b> The relationship between two numerical variables</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups"><i class="fa fa-check"></i><b>1.7</b> Testing the differences between two groups</a></li>
<li class="chapter" data-level="1.8" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-differences-among-multiple-groups-anova"><i class="fa fa-check"></i><b>1.8</b> Testing differences among multiple groups (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html"><i class="fa fa-check"></i><b>2</b> Visualizing the iris flower data set</a>
<ul>
<li class="chapter" data-level="2.1" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#scatter-plot-matrix"><i class="fa fa-check"></i><b>2.2</b> Scatter plot matrix</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#star-and-segment-diagrams"><i class="fa fa-check"></i><b>2.3</b> Star and segment diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#the-ggplot2-package-is-intuitive-and-powerful"><i class="fa fa-check"></i><b>2.4</b> The ggplot2 package is intuitive and powerful</a></li>
<li class="chapter" data-level="2.5" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#other-types-of-plots-with-ggplot2"><i class="fa fa-check"></i><b>2.5</b> Other types of plots with ggplot2</a></li>
<li class="chapter" data-level="2.6" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#hierarchical-clustering-and-heat-map"><i class="fa fa-check"></i><b>2.6</b> Hierarchical clustering and heat map</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.7</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#logistic-regression-for-binary-outcomes-prediction"><i class="fa fa-check"></i><b>2.8</b> Logistic Regression for Binary Outcomes Prediction</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#seeking-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Seeking help and example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.2</b> Matrices</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.5</b> Lists</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html"><i class="fa fa-check"></i><b>4</b> Importing data and managing files</a>
<ul>
<li class="chapter" data-level="4.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#project-oriented-workflow"><i class="fa fa-check"></i><b>4.1</b> Project-oriented workflow</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-project-in-a-new-folder"><i class="fa fa-check"></i><b>4.1.1</b> Create a project in a new folder</a></li>
<li class="chapter" data-level="4.1.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-script-file-and-comment-please"><i class="fa fa-check"></i><b>4.1.2</b> Create a script file (and Comment, Please!)</a></li>
<li class="chapter" data-level="4.1.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#copy-data-files-to-the-new-directory"><i class="fa fa-check"></i><b>4.1.3</b> Copy data files to the new directory</a></li>
<li class="chapter" data-level="4.1.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#import-data-files"><i class="fa fa-check"></i><b>4.1.4</b> Import data files</a></li>
<li class="chapter" data-level="4.1.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#check-and-convert-data-types"><i class="fa fa-check"></i><b>4.1.5</b> Check and convert data types</a></li>
<li class="chapter" data-level="4.1.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#close-a-project-when-you-are-done"><i class="fa fa-check"></i><b>4.1.6</b> Close a project when you are done</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#read-files-directly-using-read.table"><i class="fa fa-check"></i><b>4.2</b> Read files directly using read.table</a></li>
<li class="chapter" data-level="4.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.3</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#enter-data-manually"><i class="fa fa-check"></i><b>4.4</b> Enter data manually</a></li>
<li class="chapter" data-level="4.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-transformation-using-the-dplyr"><i class="fa fa-check"></i><b>4.6</b> Data transformation using the dplyr</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> The heart attack data set (I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-individually"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column individually</a></li>
<li class="chapter" data-level="5.2" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns</a></li>
<li class="chapter" data-level="5.3" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables</a></li>
<li class="chapter" data-level="5.4" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables</a></li>
<li class="chapter" data-level="5.5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html"><i class="fa fa-check"></i><b>6</b> The heart attack dataset (II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#statistical-models-easy-to-run-tricky-to-interpret"><i class="fa fa-check"></i><b>6.5</b> Statistical models: Easy to Run, tricky to interpret!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>7.1</b> Introduction to R Markdown</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> Tidyverse</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package"><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
<li class="chapter" data-level="7.4.4" data-path="advanced-topics.html"><a href="advanced-topics.html#publish-your-app"><i class="fa fa-check"></i><b>7.4.4</b> Publish your app</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-topics.html"><a href="advanced-topics.html#define-your-own-function"><i class="fa fa-check"></i><b>7.5</b> Define your own function</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="state-dataset.html"><a href="state-dataset.html"><i class="fa fa-check"></i><b>8</b> State dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="state-dataset.html"><a href="state-dataset.html#data-import-and-manipulation"><i class="fa fa-check"></i><b>8.1</b> Data Import and Manipulation</a></li>
<li class="chapter" data-level="8.2" data-path="state-dataset.html"><a href="state-dataset.html#visualizing-data"><i class="fa fa-check"></i><b>8.2</b> Visualizing data</a></li>
<li class="chapter" data-level="8.3" data-path="state-dataset.html"><a href="state-dataset.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="state-dataset.html"><a href="state-dataset.html#the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> The whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="state-dataset.html"><a href="state-dataset.html#linear-model-analysis"><i class="fa fa-check"></i><b>8.5</b> Linear model analysis</a></li>
<li class="chapter" data-level="8.6" data-path="state-dataset.html"><a href="state-dataset.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html"><i class="fa fa-check"></i><b>9</b> The game sales dataset</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#reading-in-data-and-managing-the-dataset"><i class="fa fa-check"></i><b>9.1</b> Reading in data and managing the dataset</a></li>
<li class="chapter" data-level="9.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#effect-of-platform-type-on-principle-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type on principle components</a></li>
<li class="chapter" data-level="9.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html"><i class="fa fa-check"></i><b>10</b> The messy salary data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#data-preparation-and-cleaning"><i class="fa fa-check"></i><b>10.1</b> Data Preparation and Cleaning</a></li>
<li class="chapter" data-level="10.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#variable-analysis"><i class="fa fa-check"></i><b>10.2</b> Variable Analysis</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income-types"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income types</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#defining-gross-income-types"><i class="fa fa-check"></i><b>10.4.1</b> Defining Gross income types</a></li>
<li class="chapter" data-level="10.4.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#the-intersection-of-ethnic-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> The Intersection of Ethnic, Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learn R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-heart-attack-data-set-i" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> The heart attack data set (I)<a href="the-heart-attack-data-set-i.html#the-heart-attack-data-set-i" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The heart attack data set, accessible at (<a href="http://statland.org/R/RC/tables4R.htm" class="uri">http://statland.org/R/RC/tables4R.htm</a>) and included in the ActivStats<sup>1</sup> CD, contains all 12,844 cases of hospital discharges in New York State in 1993. These are patients admitted for heart attack but who did not have surgery. This information is essential for the interpretation of our results, as this is a purely <strong>observational study</strong>, not a random sample or <strong>controlled experiment</strong>.</p>
<p>The data set is neatly organized in a table format (see Table <a href="the-heart-attack-data-set-i.html#tab:4-01">5.1</a>), with rows representing cases and columns representing characteristics, a standard format for many datasets. If you download and open the file in NotePad++ or Excel, you will find that the columns are separated by tabs, with <strong>missing values</strong> marked by “NA”. Four columns (DIAGNOSIS, SEX, DRG, DIED) contain <strong>nominal</strong> values, representing labels of <strong>categories</strong>. A detailed explanation of data types can be found <a href="http://www.mymarketresearchmethods.com/types-of-data-nominal-ordinal-interval-ratio/">here</a>. DIAGNOSIS column contains codes defined in the International Classification of Diseases (IDC), 9th Edition. These are the codes that your doctors send to your insurance company for billing. The numbers, such as 41041, are actually codes for specific parts of the heart affected. Although these are numbers, but are not math-friendly. It does not make any sense to add or subtract or compute the mean. You wouldn’t average student IDs, would you? Such <strong>categorical data needs to be recognized as factors in R</strong>. Similarly, DRG column has three possible numbers, 121 for survivors with cardiovascular complications, 122 for survivors without complications, and 123 for deceased patients. Moreover, DIED are codes using 1 for deceased, and 0 for survived.</p>
<p>Here’s a snippet of code to get you started:</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="the-heart-attack-data-set-i.html#cb681-1" tabindex="-1"></a>URL <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/gexijin/learnR/master/datasets/heartatk4R.txt&quot;</span></span>
<span id="cb681-2"><a href="the-heart-attack-data-set-i.html#cb681-2" tabindex="-1"></a>heartatk4R <span class="ot">&lt;-</span> <span class="fu">read.table</span>(URL,</span>
<span id="cb681-3"><a href="the-heart-attack-data-set-i.html#cb681-3" tabindex="-1"></a>                         <span class="at">header =</span> <span class="cn">TRUE</span>, </span>
<span id="cb681-4"><a href="the-heart-attack-data-set-i.html#cb681-4" tabindex="-1"></a>                         <span class="at">sep =</span> <span class="st">&quot;</span><span class="sc">\t</span><span class="st">&quot;</span>, </span>
<span id="cb681-5"><a href="the-heart-attack-data-set-i.html#cb681-5" tabindex="-1"></a>                         <span class="at">colClasses =</span> <span class="fu">c</span>(<span class="st">&quot;character&quot;</span>, <span class="st">&quot;factor&quot;</span>, <span class="st">&quot;factor&quot;</span>, <span class="st">&quot;factor&quot;</span>, </span>
<span id="cb681-6"><a href="the-heart-attack-data-set-i.html#cb681-6" tabindex="-1"></a>                                        <span class="st">&quot;factor&quot;</span>, <span class="st">&quot;numeric&quot;</span>, <span class="st">&quot;numeric&quot;</span>, <span class="st">&quot;numeric&quot;</span>))</span></code></pre></div>
<table>
<caption><span id="tab:4-01">Table 5.1: </span>First 15 rows of the heart attack dataset</caption>
<thead>
<tr class="header">
<th align="left">Patient</th>
<th align="left">DIAGNOSIS</th>
<th align="left">SEX</th>
<th align="left">DRG</th>
<th align="left">DIED</th>
<th align="right">CHARGES</th>
<th align="right">LOS</th>
<th align="right">AGE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">41041</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">4752.00</td>
<td align="right">10</td>
<td align="right">79</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">41041</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">3941.00</td>
<td align="right">6</td>
<td align="right">34</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">41091</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">3657.00</td>
<td align="right">5</td>
<td align="right">76</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">41081</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">1481.00</td>
<td align="right">2</td>
<td align="right">80</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">41091</td>
<td align="left">M</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">1681.00</td>
<td align="right">1</td>
<td align="right">55</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">41091</td>
<td align="left">M</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">6378.64</td>
<td align="right">9</td>
<td align="right">84</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">41091</td>
<td align="left">F</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">10958.52</td>
<td align="right">15</td>
<td align="right">84</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">41091</td>
<td align="left">F</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">16583.93</td>
<td align="right">15</td>
<td align="right">70</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">41041</td>
<td align="left">M</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">4015.33</td>
<td align="right">2</td>
<td align="right">76</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">41041</td>
<td align="left">F</td>
<td align="left">123</td>
<td align="left">1</td>
<td align="right">1989.44</td>
<td align="right">1</td>
<td align="right">65</td>
</tr>
<tr class="odd">
<td align="left">11</td>
<td align="left">41041</td>
<td align="left">F</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">7471.63</td>
<td align="right">6</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="left">12</td>
<td align="left">41091</td>
<td align="left">M</td>
<td align="left">121</td>
<td align="left">0</td>
<td align="right">3930.63</td>
<td align="right">5</td>
<td align="right">72</td>
</tr>
<tr class="odd">
<td align="left">13</td>
<td align="left">41091</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">NA</td>
<td align="right">9</td>
<td align="right">83</td>
</tr>
<tr class="even">
<td align="left">14</td>
<td align="left">41091</td>
<td align="left">F</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">4433.93</td>
<td align="right">4</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="left">15</td>
<td align="left">41041</td>
<td align="left">M</td>
<td align="left">122</td>
<td align="left">0</td>
<td align="right">3318.21</td>
<td align="right">2</td>
<td align="right">53</td>
</tr>
</tbody>
</table>
<p>Ponder over these questions as you explore the dataset in Excel. What type of people are more likely to suffer from heart attacks? Who is more likely to survive a heart attack? Suppose your friend, a 65 years old lady with DIAGNOSIS code of 41081, was just admitted to hospital for heart attack. What is the odds that she survives without complication? Also, consider yourself as a CEO of an insurance company, would you like to know what types of patients rack up higher charges? Should a particular subgroup, such as men or those over 70, pay a higher premium?</p>
<p>To answer these questions, we will:</p>
<p>• Import data files into R</p>
<p>• Conduct Exploratory Data Analysis (EDA)</p>
<p>• Implement statistical modeling (regression)</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="the-heart-attack-data-set-i.html#cb682-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> heartatk4R  <span class="co"># Clone the data for manipulation, call it x. </span></span>
<span id="cb682-2"><a href="the-heart-attack-data-set-i.html#cb682-2" tabindex="-1"></a><span class="fu">str</span>(x)  <span class="co"># View data structure and data types</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    12844 obs. of  8 variables:
##  $ Patient  : chr  &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ DIAGNOSIS: Factor w/ 9 levels &quot;41001&quot;,&quot;41011&quot;,..: 5 5 9 8 9 9 9 9 5 5 ...
##  $ SEX      : Factor w/ 2 levels &quot;F&quot;,&quot;M&quot;: 1 1 1 1 2 2 1 1 2 1 ...
##  $ DRG      : Factor w/ 3 levels &quot;121&quot;,&quot;122&quot;,&quot;123&quot;: 2 2 2 2 2 1 1 1 1 3 ...
##  $ DIED     : Factor w/ 2 levels &quot;0&quot;,&quot;1&quot;: 1 1 1 1 1 1 1 1 1 2 ...
##  $ CHARGES  : num  4752 3941 3657 1481 1681 ...
##  $ LOS      : num  10 6 5 2 1 9 15 15 2 1 ...
##  $ AGE      : num  79 34 76 80 55 84 84 70 76 65 ...</code></pre>
<div id="begin-your-analysis-by-examining-each-column-individually" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Begin your analysis by examining each column individually<a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-individually" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Think of data like a first date. If you are single and meet someone in a bar, you typically start with small talks and learn some basic information about him/her. Similarly, before diving into hypothesis testing or model building, get to know your data.<br />
We are going to start by examining each column individually, for numeric column, including very basic things like mean, median, ranges, distributions, and normality. This is important because sometimes the data is so skewed or far from normal distribution. In such cases, before conducting further analyses, we need to use <strong>non-parametric tests</strong>, or to <strong>transform the raw data</strong> using log transformation, or more general box-cox transformation.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-336}</p>
</blockquote>
<blockquote>
<p>Perform the following analysis for the heartatk4R dataset. If you forgot the R commands, revisit our previous chapters, or ask the wise Dr. Google.</p>
<ol style="list-style-type: lower-alpha">
<li>Graphical EDA: Plot the distribution of <strong>charges</strong> using box plot, histogram, qqplot, lag plot, and sequence plot. Interpret your results in PLAIN English. Note that there are missing values in this column that may cause problems for some plots. You can remove missing values by defining a new variable with <strong>temp = CHARGES [ ! is.na (CHARGES) ]</strong> and then plot with <strong>temp</strong>.</li>
<li>Quantitative EDA: Conduct normality tests and calculate confidence intervals. If the Shapiro-Wilk normality test cannot handle data points over 12,000, try other tests in the nortest library or sample randomly with <strong>temp = sample( CHARGES, 4000)</strong>.
:::</li>
</ol>
</blockquote>
<p>For categorical columns like SEX and DIAGNOSIS, we want to count different levels, and their frequencies. In addition to quantitative analysis, we’ll visualize our findings with <strong>pie charts and bar plots</strong>, using the trusty <strong>table( )</strong> function followed by <strong>pie( )</strong> and <strong>barplot()</strong>.</p>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb684-1"><a href="the-heart-attack-data-set-i.html#cb684-1" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(x<span class="sc">$</span>DIAGNOSIS))</span></code></pre></div>
<p>This generates a bar plot of counts. It could be further refined with percentages:</p>

<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="the-heart-attack-data-set-i.html#cb685-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">table</span>(x<span class="sc">$</span>DIAGNOSIS), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)  <span class="co"># Tabulate &amp; sort </span></span>
<span id="cb685-2"><a href="the-heart-attack-data-set-i.html#cb685-2" tabindex="-1"></a>percentages <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> counts <span class="sc">/</span> <span class="fu">length</span>(x<span class="sc">$</span>DIAGNOSIS)  <span class="co"># Convert to %</span></span>
<span id="cb685-3"><a href="the-heart-attack-data-set-i.html#cb685-3" tabindex="-1"></a><span class="fu">barplot</span>(percentages, <span class="at">las =</span> <span class="dv">3</span>, <span class="at">ylab =</span> <span class="st">&quot;Percentage&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>)  <span class="co"># Figure 5.1</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:4-1"></span>
<img src="book_files/figure-html/4-1-1.png" alt="Barplot by percentage" width="672" />
<p class="caption">
Figure 5.1: Barplot by percentage
</p>
</div>
<p>Note that “las = 3” changes the orientation of the labels for x-axis to vertical. Try plot without it or set it to 2. You can even do all these in single line.</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="the-heart-attack-data-set-i.html#cb686-1" tabindex="-1"></a><span class="fu">barplot</span>(<span class="dv">100</span><span class="sc">*</span> <span class="fu">sort</span>(<span class="fu">table</span>(x<span class="sc">$</span>DIAGNOSIS), <span class="at">decreasing=</span>T) <span class="sc">/</span> <span class="fu">length</span>(x<span class="sc">$</span>DIAGNOSIS), <span class="at">las =</span> <span class="dv">3</span>, <span class="at">ylab =</span> <span class="st">&quot;Percentage&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>)</span></code></pre></div>

<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="the-heart-attack-data-set-i.html#cb687-1" tabindex="-1"></a><span class="fu">table</span>(x<span class="sc">$</span>SEX)  <span class="co"># Tally up the Ms and Fs</span></span></code></pre></div>
<pre><code>## 
##    F    M 
## 5065 7779</code></pre>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="the-heart-attack-data-set-i.html#cb689-1" tabindex="-1"></a><span class="fu">pie</span>(<span class="fu">table</span>(x<span class="sc">$</span>SEX))  <span class="co"># And turn it into a pie! Yum!</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:14-2"></span>
<img src="book_files/figure-html/14-2-1.png" alt="Pie chart of patients by SEX" width="50%" />
<p class="caption">
Figure 5.2: Pie chart of patients by SEX
</p>
</div>
<blockquote>
<div class="exercise">
<p><span id="exr:unnamed-chunk-339" class="exercise"><strong>Exercise 5.1  </strong></span>Compute the count and percentage of each level of DRG by filling the blanks below. Use bar plot and pie chart similar to Figure <a href="the-heart-attack-data-set-i.html#fig:4-1">5.1</a> and Figure <a href="the-heart-attack-data-set-i.html#fig:14-2">5.2</a> to visualize. Briefly discuss your results like you’re explaining it to a five-year-old.</p>
<p>drg &lt;- __________ # Import values of DRG</p>
<p>counts &lt;- sort(________(drg), decreasing = TRUE) # Tabulate &amp; sort</p>
<p>percentages &lt;- 100 * __________ # Compute the percentage and convert to %</p>
<p>barplot(percentages, ylab = “Percentage”, col = “blue”) # Barplot</p>
<p>_________(counts) # Pie chart</p>
</div>
</blockquote>
</div>
<div id="possible-correlation-between-two-numeric-columns" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Possible correlation between two numeric columns<a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To explore potential correlations between two numeric columns, various correlation coefficients can be employed, such as Pearson’s correlation coefficient (PPC). This is expressed by the formula:</p>
<p><span class="math display">\[r=∑_{i=1}^{n}(\frac{x_i-\bar{x}}{s_x}) (\frac{y_i-\bar{y}}{s_y})\]</span></p>
<p>where <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> represent the <span class="math inline">\(i^{th}\)</span> values, <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> are the sample means, and <span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span> are the sample standard deviations.</p>
<p>Pearson’s correlation ranges from -1 to 1, indicating perfect negative and positive correlation respectively. Remember, <strong>negative correlations are just as important and informative as positive ones</strong>.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:4-2"></span>
<img src="images/img0402_coefficient.png" alt="Interpretation of Pearson’s correlation coefficient" width="80%" />
<p class="caption">
Figure 5.3: Interpretation of Pearson’s correlation coefficient
</p>
</div>
<p>Figure <a href="the-heart-attack-data-set-i.html#fig:4-2">5.3</a> provides visual examples of Pearson’s correlation with various scatter plots. The numbers are Pearson’s correlation coefficient r. The second row illustrates that Pearson’s correlation, despite differing slopes, can be uniformly 1. This highlights that Pearson’s correlation only signifies the correlation degree, not the slope. The third row exposes a limitation: Pearson’s correlation cannot detect nonlinear correlations.</p>
<p>Table <a href="the-heart-attack-data-set-i.html#tab:4-02">5.2</a> below gives some guidelines for interpreting Pearson’s correlation coefficient.</p>
<table>
<caption><span id="tab:4-02">Table 5.2: </span>Interpretation of correlation coefficient</caption>
<thead>
<tr class="header">
<th align="left">Correlation</th>
<th align="left">Negative</th>
<th align="left">Positive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">-</td>
<td align="left">-0.09 to 0.0</td>
<td align="left">0.0 to 0.09</td>
</tr>
<tr class="even">
<td align="left">Small</td>
<td align="left">-0.3 to -0.1</td>
<td align="left">0.1 to 0.3</td>
</tr>
<tr class="odd">
<td align="left">Medium</td>
<td align="left">-0.5 to -0.3</td>
<td align="left">0.3 to 0.5</td>
</tr>
<tr class="even">
<td align="left">Large</td>
<td align="left">-1.0 to -0.5</td>
<td align="left">0.5 to 1.0</td>
</tr>
</tbody>
</table>
<p>There is a small, but statistically significant correlation between age and length of stay in the hospital after a heart attack. <strong>The interpretation in plain English(the explanation that could be understood by your grandmother)</strong>: Older people tend to stay slightly longer in the hospital after a heart attack.</p>
<div class="sourceCode" id="cb690"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb690-1"><a href="the-heart-attack-data-set-i.html#cb690-1" tabindex="-1"></a><span class="fu">cor.test</span>(x<span class="sc">$</span>AGE, x<span class="sc">$</span>LOS)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x$AGE and x$LOS
## t = 21.006, df = 12842, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.1654881 0.1989282
## sample estimates:
##       cor 
## 0.1822609</code></pre>
<p>Note that the correlation coefficient r and the p value serve two different purposes: r indicates the size of effect, while p value tells statistical significance. Based on the statistic sample, p value tells how certain we are about the difference being real, namely not due to random fluctuation. A large sample size allows us to detect even minor correlations as significant. Conversely, if we only have a few observations, a large r could have large p value, hence not significant. Distinguishing between effect size and significance is vital in statistical analyses.</p>
<p><img src="images/img0400_sample.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Like many commonly-used parametric statistical methods which rely on means and standard deviations, the Pearson’s correlation coefficient is not robust, meaning its value are sensitive to outliers and can be misleading. It is also very sensitive to distribution.</p>
<p><strong>Non-parametric</strong> approaches typically rank original data and do calculations on the ranks instead of raw data. They are often more robust but might lack sensitivity. There are corresponding non-parametric versions for most of the parametric tests.</p>
<p><strong>Spearman’s rank correlation coefficient <span class="math inline">\(\rho\)</span></strong> is a non-parametric correlation measure. The Spearman correlation coefficient ρ is often thought as the Pearson correlation coefficient for ranked variables. However, ρ is calculated more straightforwardly in practice. The n raw scores <span class="math inline">\(X_i\)</span>, <span class="math inline">\(Y_i\)</span> are converted to ranks <span class="math inline">\(R_{x_i}\)</span>, <span class="math inline">\(R_{y_i}\)</span>, and the differences <span class="math inline">\(d_i\)</span> = <span class="math inline">\(R_{x_i}\)</span>-<span class="math inline">\(R_{y_i}\)</span> between the ranks of each observation on the two variables are calculated.</p>
<p>If there are no tied ranks, <span class="math inline">\(\rho\)</span> is given by:<span class="math display">\[ρ=1-\frac{6∑d_{i}^{2}}{n(n_{}^{2}-1)}\]</span></p>
<p>In R, Spearman’s <span class="math inline">\(\rho\)</span> and its significance can be tested by customizing the cor.test() function:</p>
<div class="sourceCode" id="cb692"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb692-1"><a href="the-heart-attack-data-set-i.html#cb692-1" tabindex="-1"></a><span class="fu">cor.test</span>(x<span class="sc">$</span>AGE, x<span class="sc">$</span>LOS, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  x$AGE and x$LOS
## S = 2.9448e+11, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## 0.1661032</code></pre>
<p>Interpretation of Spearman’s <span class="math inline">\(\rho\)</span> parallels that of Pearson’s r. The statistical significance can also be determined similarly as demonstrated above.</p>
<p>Kendall tau rank correlation coefficient is an alternative non-parametric statistic for correlation.</p>
<p>We already know that scatter plots are great for visualizing correlation between two numeric columns. However, with many data points, such as our dataset with over 12,000 points, understanding these plots can be challenging, especially when the data is integers and there are a lot of overlapping data points. Yes, graphics can be misleading in such situation. This is where smoothed scatter plot, which uses color densities to represent overlapping data points, become useful.</p>
<div class="sourceCode" id="cb694"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb694-1"><a href="the-heart-attack-data-set-i.html#cb694-1" tabindex="-1"></a><span class="fu">plot</span>(x<span class="sc">$</span>AGE, x<span class="sc">$</span>LOS)  <span class="co"># Standard scatter plot    </span></span>
<span id="cb694-2"><a href="the-heart-attack-data-set-i.html#cb694-2" tabindex="-1"></a><span class="fu">smoothScatter</span>(x<span class="sc">$</span>AGE, x<span class="sc">$</span>LOS)  <span class="co"># Smoothed color density representation of a scatterplot  </span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-344"></span>
<img src="book_files/figure-html/unnamed-chunk-344-1.png" alt="Smoothed Scatter plots use colors to code for the density of data points" width="50%" /><img src="book_files/figure-html/unnamed-chunk-344-2.png" alt="Smoothed Scatter plots use colors to code for the density of data points" width="50%" />
<p class="caption">
Figure 5.4: Smoothed Scatter plots use colors to code for the density of data points
</p>
</div>
<blockquote>
<p>::: {.exercise #unnamed-chunk-345}</p>
</blockquote>
<blockquote>
<p>Investigate the correlation between length of stay(LOS) and charges by filling in the blanks below. Remember to include plain English interpretation of your results even your grandpa could understand.</p>
<p>LOS &lt;- ______________ # Load LOS data from the heart attack dataset</p>
<p>CHARGES &lt;- _____________ # Load CHARGES data</p>
<p>cor.test(LOS, CHARGES, method = ___________) # Conduct Pearson correlation</p>
<p>cor.test(LOS, CHARGES, method = __________) # Conduct Spearman correlation</p>
<p>plot(LOS, CHARGES) # Create a standard scatter plot</p>
<p>__________(LOS, CHARGES) # Create a smoothed color density representation of a scatterplot
:::</p>
</blockquote>
</div>
<div id="associations-between-categorical-variables" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Associations between categorical variables<a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the heart attack dataset, four columns—DIAGNOSIS, DRG, SEX, and DIED—contain categorical values. These columns could be associated with each other. For example, we might wonder if men and women are equally likely to survive a heart attack.</p>
<p>Let’s start by tabulating SEX and DIED variables:</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb695-1"><a href="the-heart-attack-data-set-i.html#cb695-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(x<span class="sc">$</span>SEX, x<span class="sc">$</span>DIED)  <span class="co"># Create a two-dimensional array of SEX and DIED</span></span>
<span id="cb695-2"><a href="the-heart-attack-data-set-i.html#cb695-2" tabindex="-1"></a>counts</span></code></pre></div>
<p>From these counts, we create a contingency table as seen in Table <a href="the-heart-attack-data-set-i.html#tab:5-01">5.3</a>:</p>
<table>
<caption><span id="tab:5-01">Table 5.3: </span>A 2x2 contingency table summarizing the distribution of DIED frequency by SEX</caption>
<thead>
<tr class="header">
<th align="left">Sex</th>
<th align="left">DIED_0</th>
<th align="left">DIED_1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">F</td>
<td align="left">4298</td>
<td align="left">767</td>
</tr>
<tr class="even">
<td align="left">M</td>
<td align="left">7136</td>
<td align="left">643</td>
</tr>
</tbody>
</table>
<p>To explore percentages of survival, we calculate:</p>
<div class="sourceCode" id="cb696"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb696-1"><a href="the-heart-attack-data-set-i.html#cb696-1" tabindex="-1"></a>counts <span class="sc">/</span> <span class="fu">rowSums</span>(counts) </span></code></pre></div>
<pre><code>##    
##              0          1
##   F 0.84856861 0.15143139
##   M 0.91734156 0.08265844</code></pre>
<p>It turns out that 15.1% of females, compared to 8.27% of males, died in the hospital. This gender difference is quite a surprise to me. But could this happen just by chance? To answer this question, we turn to a statistical test. Chi-square test can be used for testing the correlation of two categorical variables. The null hypothesis here is that men and women are equally likely to die from a heart attack.</p>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb698-1"><a href="the-heart-attack-data-set-i.html#cb698-1" tabindex="-1"></a><span class="fu">chisq.test</span>(counts)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  counts
## X-squared = 147.76, df = 1, p-value &lt; 2.2e-16</code></pre>
<p>Have you seen such a tiny p-value before? Probably! It is one of the smallest non-zero values R displays for many tests. This p is definitely small! Therefore, we reject the hypothesis that the mortality rate is the same for men and women. Looking at the data, it is higher for women. The chi-square test gives accurate p-values if expected observation is greater than 5. If not, the Fisher Exact test, more computationally intense but accurate for small datasets, is advisable. The chi-square test is an approximation to the Fisher Exact test. Karl Pearson developed the chi-square approximation before we had computers. Today’s computational power makes the Fisher Exact test feasible for small datasets.</p>
<p>You can also use the chi-square test for contingency tables that have more than two rows or two columns. For more complex contingency tables, the Chi-square approximation remains accurate if each cell’s expected observation is over 1, and less than 20% of cells have expectations under 5. Again, the Fisher Exact test can handle quite large data sets with today’s computers, without the Chi-square limitations.</p>
<div class="sourceCode" id="cb700"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb700-1"><a href="the-heart-attack-data-set-i.html#cb700-1" tabindex="-1"></a><span class="fu">fisher.test</span>(counts)  <span class="co"># Fisher’s Exact test</span></span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  counts
## p-value &lt; 2.2e-16
## alternative hypothesis: true odds ratio is not equal to 1
## 95 percent confidence interval:
##  0.4509331 0.5653197
## sample estimates:
## odds ratio 
##  0.5049435</code></pre>
<p>In this case, the result of fisher’s test is the same as chi-square test.</p>
<p>To present findings to a boss who is either stupid or too busy, you need a chart. Below, we display two types of bar plots: stacked and side by side.</p>

<div class="sourceCode" id="cb702"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb702-1"><a href="the-heart-attack-data-set-i.html#cb702-1" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(x<span class="sc">$</span>DIED, x<span class="sc">$</span>SEX) </span>
<span id="cb702-2"><a href="the-heart-attack-data-set-i.html#cb702-2" tabindex="-1"></a></span>
<span id="cb702-3"><a href="the-heart-attack-data-set-i.html#cb702-3" tabindex="-1"></a><span class="fu">barplot</span>(counts, <span class="at">legend =</span> <span class="fu">rownames</span>(counts), <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>), <span class="at">xlab =</span> <span class="st">&quot;DIED&quot;</span>, <span class="at">beside =</span> F) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-1"></span>
<img src="book_files/figure-html/5-1-1.png" alt="Barplot illustrating correlation of two categorical variables. A. Stacked; B. Side by side" width="50%" /><img src="book_files/figure-html/5-1-2.png" alt="Barplot illustrating correlation of two categorical variables. A. Stacked; B. Side by side" width="50%" />
<p class="caption">
Figure 5.5: Barplot illustrating correlation of two categorical variables. A. Stacked; B. Side by side
</p>
</div>
<p>To change the position of legend, add an argument such as “<em>args.legend = list(x = ”topleft”)</em>”, in the function barplot(). For example, we can move the legend to the top-left of Figure <a href="the-heart-attack-data-set-i.html#fig:5-1">5.5</a> A.</p>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb703-1"><a href="the-heart-attack-data-set-i.html#cb703-1" tabindex="-1"></a><span class="fu">barplot</span>(counts, <span class="at">legend =</span> <span class="fu">rownames</span>(counts), <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>), <span class="at">xlab =</span> <span class="st">&quot;DIED&quot;</span>, <span class="at">beside =</span> F,</span>
<span id="cb703-2"><a href="the-heart-attack-data-set-i.html#cb703-2" tabindex="-1"></a>        <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">&quot;topleft&quot;</span>))</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-351-1.png" width="672" /></p>
<p>Mosaic plots are another effective way to visualize proportions, where the size and color of blocks represent different combinations of categories.</p>

<div class="sourceCode" id="cb704"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb704-1"><a href="the-heart-attack-data-set-i.html#cb704-1" tabindex="-1"></a><span class="fu">mosaicplot</span>(<span class="fu">table</span>(x<span class="sc">$</span>SEX, x<span class="sc">$</span>DIED), <span class="at">color =</span> T, <span class="at">main =</span> <span class="st">&quot;&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-2"></span>
<img src="book_files/figure-html/5-2-1.png" alt="Mosaic plot of DIED by SEX" width="576" />
<p class="caption">
Figure 5.6: Mosaic plot of DIED by SEX
</p>
</div>
<p>The mosaic plot in Figure <a href="the-heart-attack-data-set-i.html#fig:5-2">5.6</a> is similar to the barplot in Figure <a href="the-heart-attack-data-set-i.html#fig:5-1">5.5</a>, but the bars are stretched to the same height, and the widths are defined by proportion of Male vs. Female. The size of the four blocks represents the counts of the corresponding combination. The blocks are also color-coded for different combination. Horizontally, the blocks are divided by SEX; There are more men than women in this dataset. Vertically, the blocks are divided by DIED (1 for died in hospital); Regardless of gender, only a small proportion of patients died in hospital. We also observe higher percentage of women died in hospital — a trend that raises questions and concerns.</p>
<p>Mosaic plots are also useful for visualizing relationships involving multiple factors.</p>

<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb705-1"><a href="the-heart-attack-data-set-i.html#cb705-1" tabindex="-1"></a><span class="fu">mosaicplot</span>(<span class="fu">table</span>(x<span class="sc">$</span>SEX, x<span class="sc">$</span>DIED, x<span class="sc">$</span>DRG), <span class="at">color =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>), <span class="at">main =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-3"></span>
<img src="book_files/figure-html/5-3-1.png" alt="Mosaic plot of three factors" width="672" />
<p class="caption">
Figure 5.7: Mosaic plot of three factors
</p>
</div>
<p>Here we nested the tabulate command inside the mosaic plot. As shown in Figure <a href="the-heart-attack-data-set-i.html#fig:5-3">5.7</a>, we further divided each of the 4 quadrants of Figure <a href="the-heart-attack-data-set-i.html#fig:5-2">5.6</a> into three parts in red, green and blue, according to DRG codes. Interestingly,a smaller proportion of surviving males developed complications, compared with females.</p>
<p>The Titanic dataset, built into R, offers another opportunity for mosaic plot to explore survival patterns.</p>
<div class="sourceCode" id="cb706"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb706-1"><a href="the-heart-attack-data-set-i.html#cb706-1" tabindex="-1"></a>? Titanic   <span class="co"># Access information on the famous Titanic dataset</span></span></code></pre></div>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb707-1"><a href="the-heart-attack-data-set-i.html#cb707-1" tabindex="-1"></a><span class="fu">mosaicplot</span>(<span class="sc">~</span> Sex <span class="sc">+</span> Age <span class="sc">+</span> Survived, <span class="at">data =</span> Titanic, <span class="at">color =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>))  </span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-353-1.png" width="672" /></p>
<p>Inspect the full dataset via a mosaic plot:</p>
<div class="sourceCode" id="cb708"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb708-1"><a href="the-heart-attack-data-set-i.html#cb708-1" tabindex="-1"></a><span class="fu">mosaicplot</span>(Titanic, <span class="at">color =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>)) </span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-354-1.png" width="672" /></p>
<p>Think about the questions: Were survival rates different between men and women? Did girls and women survive by equal proportion?</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-355}</p>
</blockquote>
<blockquote>
<p>The DIAGNOSIS column contains IDC codes that specify the parts of the affected hearts. Use a stacked bar plot and a mosaic plot to compare DIAGNOSIS frequency differences between men and women. Based on your observation, do you think men and women are equal in the diagnoses frequencies?</p>
<p>DIAGNOSIS &lt;- heartatk4R$DIAGNOSIS</p>
<p>SEX &lt;- heartatk4R$SEX</p>
<p>counts &lt;- _____________(DIAGNOSIS, SEX) # Take SEX as columns</p>
<p>barplot(_____________________________________________________)</p>
<p>legend(“topleft”, legend = rownames(counts), fill = rainbow(9), ncol = 3, cex = 0.75)</p>
<p>mosaicplot(_____________________________________________)
:::</p>
</blockquote>
</div>
<div id="associations-between-a-categorical-and-a-numeric-variables" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Associations between a categorical and a numeric variables<a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Exploring associations between different types of variables, like categorical and numeric, can offer valuable insights. Questions such as “Do women stay longer in hospitals?” or “Do charges vary with different diagnoses?” can be addressed with techniques like T-tests and ANOVA, akin to our analysis of the Iris flower dataset. For visualization, <strong>boxplots</strong> are straightforward, but the ggplot2 package allows a more detailed examination of variable distributions across groups.</p>

<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb709-1"><a href="the-heart-attack-data-set-i.html#cb709-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb709-2"><a href="the-heart-attack-data-set-i.html#cb709-2" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> AGE)) <span class="sc">+</span></span>
<span id="cb709-3"><a href="the-heart-attack-data-set-i.html#cb709-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">sum</span>(count) <span class="sc">*</span> <span class="dv">100</span>), <span class="at">fill =</span> <span class="fu">factor</span>(SEX)), </span>
<span id="cb709-4"><a href="the-heart-attack-data-set-i.html#cb709-4" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">6</span>, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb709-5"><a href="the-heart-attack-data-set-i.html#cb709-5" tabindex="-1"></a>  <span class="fu">facet_grid</span>(SEX <span class="sc">~</span> .) <span class="sc">+</span> <span class="co"># Split a graph according to panels defined by SEX</span></span>
<span id="cb709-6"><a href="the-heart-attack-data-set-i.html#cb709-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Percent of Total&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:new1"></span>
<img src="book_files/figure-html/new1-1.png" alt="Histogram of AGE by SEX" width="576" />
<p class="caption">
Figure 5.8: Histogram of AGE by SEX
</p>
</div>
<p>The histograms reveal that women’s ages are more skewed to the right, indicating that women in the dataset are considerably older than men. I am surprised at first by this huge difference, as the average age of women is bigger by 11. Further research aligns with this finding that heart attack symptoms in women are often milder and less noticeable.</p>
<p>We can further divide the population according to survival status by adding another factor:</p>

<div class="sourceCode" id="cb710"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb710-1"><a href="the-heart-attack-data-set-i.html#cb710-1" tabindex="-1"></a><span class="co"># Creating a new grouping variable &#39;GROUP&#39; as a combination of &#39;DIED&#39; and &#39;SEX&#39;</span></span>
<span id="cb710-2"><a href="the-heart-attack-data-set-i.html#cb710-2" tabindex="-1"></a>heartatk4R<span class="sc">$</span>GROUP <span class="ot">&lt;-</span> <span class="fu">paste</span>(heartatk4R<span class="sc">$</span>DIED, heartatk4R<span class="sc">$</span>SEX, <span class="at">sep =</span> <span class="st">&quot;-&quot;</span>)</span>
<span id="cb710-3"><a href="the-heart-attack-data-set-i.html#cb710-3" tabindex="-1"></a></span>
<span id="cb710-4"><a href="the-heart-attack-data-set-i.html#cb710-4" tabindex="-1"></a><span class="co"># Plot the histogram</span></span>
<span id="cb710-5"><a href="the-heart-attack-data-set-i.html#cb710-5" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">group =</span> GROUP)) <span class="sc">+</span></span>
<span id="cb710-6"><a href="the-heart-attack-data-set-i.html#cb710-6" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb710-7"><a href="the-heart-attack-data-set-i.html#cb710-7" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count <span class="sc">/</span> <span class="fu">tapply</span>(count, PANEL, sum)[PANEL] <span class="sc">*</span> <span class="dv">100</span>), <span class="at">fill =</span> GROUP), </span>
<span id="cb710-8"><a href="the-heart-attack-data-set-i.html#cb710-8" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span></span>
<span id="cb710-9"><a href="the-heart-attack-data-set-i.html#cb710-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb710-10"><a href="the-heart-attack-data-set-i.html#cb710-10" tabindex="-1"></a>  <span class="fu">facet_grid</span>(DIED <span class="sc">~</span> SEX) <span class="sc">+</span> <span class="co"># Split a graph according to a matrix of panels defined by DIED and SEX</span></span>
<span id="cb710-11"><a href="the-heart-attack-data-set-i.html#cb710-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;Percent of Total&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Age&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:new2"></span>
<img src="book_files/figure-html/new2-1.png" alt="Histogram of AGE by SEX and DIED" width="672" />
<p class="caption">
Figure 5.9: Histogram of AGE by SEX and DIED
</p>
</div>
<p>This analysis shows that older patients, regardless of sex, are less likely to survive a heart attack. This trend is even more apparent in a density plot. Instead of splitting into multiple panels, the curves are overlaid.</p>

<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb711-1"><a href="the-heart-attack-data-set-i.html#cb711-1" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">fill =</span> SEX)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:new3"></span>
<img src="book_files/figure-html/new3-1.png" alt="Density plot of AGE by SEX" width="576" />
<p class="caption">
Figure 5.10: Density plot of AGE by SEX
</p>
</div>
<p>The density plot reaffirms the age skew observed in the histograms <a href="the-heart-attack-data-set-i.html#fig:new1">5.8</a>.</p>
<p>Now for each gender, we further divide the patients by their survival status.</p>

<div class="sourceCode" id="cb712"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb712-1"><a href="the-heart-attack-data-set-i.html#cb712-1" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">fill =</span> DIED)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span> <span class="fu">facet_grid</span>(SEX <span class="sc">~</span> .) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:new4"></span>
<img src="book_files/figure-html/new4-1.png" alt="Density plot of AGE by SEX and DIED" width="576" />
<p class="caption">
Figure 5.11: Density plot of AGE by SEX and DIED
</p>
</div>
<p>Overlaying survival curves indicates a clear age-related trend in survival rates: younger patients tend to survive for both men and women.</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-356}</p>
</blockquote>
<blockquote>
<p>Use the ggplot2 package to compare the length of hospital stay distributions between survivors and non-survivors. Include both histogram plot and density plot. Interpret your results.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-357}</p>
</blockquote>
<blockquote>
<p>Separate the above analysis by gender, as demonstrated in Figure <a href="the-heart-attack-data-set-i.html#fig:new4">5.11</a>).
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-358}</p>
</blockquote>
<blockquote>
<p>Examine age distribution differences between survivors and non-survivors using t-tests, boxplots, histograms, and density plots.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-359}</p>
</blockquote>
<blockquote>
<p>Compare charge variations among different DRG codes using ANOVA, boxplots, histograms, and density plots.
:::</p>
</blockquote>
</div>
<div id="associations-between-multiple-columns" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Associations between multiple columns<a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The ggplot2 package can also shed light on correlations between multiple variables through multi-panel figures.</p>

<div class="sourceCode" id="cb713"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb713-1"><a href="the-heart-attack-data-set-i.html#cb713-1" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> DRG, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span> <span class="fu">facet_grid</span>(SEX <span class="sc">~</span> .)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-6"></span>
<img src="book_files/figure-html/5-6-1.png" alt="Multiple boxplots of AGE by DRG and SEX" width="480" />
<p class="caption">
Figure 5.12: Multiple boxplots of AGE by DRG and SEX
</p>
</div>
<p>Recall that 121 indicates survivors with complication, 122 for survivors with no complication, and 123 for died. This visualization suggests older patients are more likely to die in hospital and those with complications are generally older. It raises the question: Does this mean they also had longer hospital stays?</p>
<blockquote>
<p>::: {.exercise #unnamed-chunk-360}</p>
</blockquote>
<blockquote>
<p>Are the surviving women younger than the women who died? Similar question can be asked for men. Produce a figure to compare age distributions between spatients who died in the hospital and those who survived, separated by gender.
:::</p>
</blockquote>
<blockquote>
<p>::: {.exercise #unnamed-chunk-361}</p>
</blockquote>
<blockquote>
<p>Use ggplot2 to create boxplots comparing the lengths of stay across different DRG categories, differentiated by gender. The produced plots should be similar to Figure 5.13. Offer interpretation.
:::</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-362"></span>
<img src="book_files/figure-html/unnamed-chunk-362-1.png" alt="Multiple boxplots" width="576" />
<p class="caption">
Figure 5.13: Multiple boxplots
</p>
</div>
</blockquote>
<p>Scatterplots offer another dimension of analysis:</p>
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb714-1"><a href="the-heart-attack-data-set-i.html#cb714-1" tabindex="-1"></a><span class="co"># Scatterplot of LOS vs. AGE</span></span>
<span id="cb714-2"><a href="the-heart-attack-data-set-i.html#cb714-2" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> DRG, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_point</span>() </span>
<span id="cb714-3"><a href="the-heart-attack-data-set-i.html#cb714-3" tabindex="-1"></a><span class="co"># Scatterplot of LOS vs. AGE, divided by SEX</span></span>
<span id="cb714-4"><a href="the-heart-attack-data-set-i.html#cb714-4" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> DRG, <span class="at">y =</span> AGE)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(SEX <span class="sc">~</span> .)  </span>
<span id="cb714-5"><a href="the-heart-attack-data-set-i.html#cb714-5" tabindex="-1"></a><span class="co"># Scatterplot colored by DIED</span></span>
<span id="cb714-6"><a href="the-heart-attack-data-set-i.html#cb714-6" tabindex="-1"></a><span class="fu">ggplot</span>(heartatk4R, <span class="fu">aes</span>(<span class="at">x =</span> AGE, <span class="at">y =</span> LOS, <span class="at">color =</span> DIED)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">facet_grid</span>(SEX <span class="sc">~</span> .)  </span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-363-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Here we only show the figure for the third code.
Note that ggplot(heartatk4R, aes(x = DRG, y = AGE)) + geom_point() + facet_grid(SEX ~ .) generates multiple scatter plots of LOS ~ AGE according to different values of SEX, while color = DIED adds these two color-coded scatter plots into the same figure.</p>

<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-7"></span>
<img src="book_files/figure-html/5-7-1.png" alt="A scatter plot of LOS vs. AGE, using SEX and DIED as factors" width="672" />
<p class="caption">
Figure 5.14: A scatter plot of LOS vs. AGE, using SEX and DIED as factors
</p>
</div>
<p>Figure <a href="the-heart-attack-data-set-i.html#fig:5-7">5.14</a> suggests the positive association between age and length of stay in hospital for the survivors, regardless of sex. This is a statistician’s language. Try this instead that could be understood by both the statistician and his/her grandmother: Older patients tend to stay longer in the hospital after surviving a heart attack. This is true for both men and women.</p>
<p>Another way to visualize complex correlation is <strong>bubble plot</strong>. It’s an enhanced scatter plot, using an additional dimension of data to determine the size of the symbols. Check out the interesting video using bubble plot: <a href="http://youtu.be/jbkSRLYSojo">http://youtu.be/jbkSRLYSojo</a></p>

<div class="sourceCode" id="cb715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb715-1"><a href="the-heart-attack-data-set-i.html#cb715-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> x[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12844</span>, <span class="dv">200</span>), ]   <span class="co"># Randomly sample 200 patients</span></span>
<span id="cb715-2"><a href="the-heart-attack-data-set-i.html#cb715-2" tabindex="-1"></a><span class="fu">plot</span>(y<span class="sc">$</span>AGE, y<span class="sc">$</span>LOS, <span class="at">cex =</span> y<span class="sc">$</span>CHARGES <span class="sc">/</span> <span class="dv">6000</span>, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>)[y<span class="sc">$</span>SEX], <span class="at">xlab =</span> <span class="st">&quot;AGE&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;LOS&quot;</span>)</span>
<span id="cb715-3"><a href="the-heart-attack-data-set-i.html#cb715-3" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="fu">levels</span>(y<span class="sc">$</span>SEX), <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">2</span>), <span class="at">pch =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:5-8"></span>
<img src="book_files/figure-html/5-8-1.png" alt="Bubble plot example" width="672" />
<p class="caption">
Figure 5.15: Bubble plot example
</p>
</div>
<p>Figure <a href="the-heart-attack-data-set-i.html#fig:5-8">5.15</a> is a busy plot. Female patients are shown in red while males in blue. Size of the symbol is proportional to charges. So this plot offers a multi-dimensional view!</p>
<p>Additional common methods to detect complex correlations and structures include principal component analysis (PCA), Multidimensional scaling (MDS), hierarchical clustering etc.</p>
<p>All of these techniques we introduced so far enable us to <strong>LEARN</strong> about the dataset without any of priory hypothesis, ideas, and judgments. Many companies claim that they want to know their customers first as individuals and then do business. Same thing applies to data mining. You need to know you dataset as it is before making predictions, classifications, etc.</p>
<p>Remember, data analysis is a conversation with your dataset: <strong>INTERACT</strong> with your data by asking questions based on domain knowledge and common sense. Then generate lots and lots of plots to support or challenge the hypothesis you may have, and be open to surprising discoveries. This approach, exemplified with the heart attack dataset, is universally applicable. Sometimes, the insights you uncover are more important than the initial objectives.</p>
<ol style="list-style-type: decimal">
<li>Velleman, P. F.; Data Description Inc. ActivStats, 2000-2001 release.; A.W. Longman,: Glenview, IL, 2001.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="importing-data-and-managing-files.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="the-heart-attack-dataset-ii.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
