<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Visualizing the iris flower data set | Learn R through examples</title>
  <meta name="description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Visualizing the iris flower data set | Learn R through examples" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  <meta name="github-repo" content="gexijin/learnR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Visualizing the iris flower data set | Learn R through examples" />
  
  <meta name="twitter:description" content="This is a draft of a book for learning data analysis with the R language. This book emphasizes hands activities. Comments and suggestions are welcome." />
  

<meta name="author" content="Xijin Ge, Jianli Qi and Rong Fan" />


<meta name="date" content="2021-08-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="step-into-r-programmingthe-iris-flower-dataset.html"/>
<link rel="next" href="data-structures.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.4.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html"><i class="fa fa-check"></i><b>1</b> Step into R programming–the iris flower dataset</a>
<ul>
<li class="chapter" data-level="1.1" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting started</a></li>
<li class="chapter" data-level="1.2" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#data-frames-contain-rows-and-columns-the-iris-flower-dataset"><i class="fa fa-check"></i><b>1.2</b> Data frames contain rows and columns: the Iris flower dataset</a></li>
<li class="chapter" data-level="1.3" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-one-set-of-numbers"><i class="fa fa-check"></i><b>1.3</b> Analyzing one set of numbers</a></li>
<li class="chapter" data-level="1.4" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#analyzing-a-categorical-variable"><i class="fa fa-check"></i><b>1.4</b> Analyzing a categorical variable</a></li>
<li class="chapter" data-level="1.5" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#the-relationship-between-two-numerical-variables"><i class="fa fa-check"></i><b>1.5</b> The relationship between two numerical variables</a></li>
<li class="chapter" data-level="1.6" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-differences-between-two-groups"><i class="fa fa-check"></i><b>1.6</b> Testing the differences between two groups</a></li>
<li class="chapter" data-level="1.7" data-path="step-into-r-programmingthe-iris-flower-dataset.html"><a href="step-into-r-programmingthe-iris-flower-dataset.html#testing-the-difference-among-multiple-groups-anova"><i class="fa fa-check"></i><b>1.7</b> Testing the difference among multiple groups (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html"><i class="fa fa-check"></i><b>2</b> Visualizing the iris flower data set</a>
<ul>
<li class="chapter" data-level="2.1" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#basic-concepts-of-r-graphics"><i class="fa fa-check"></i><b>2.1</b> Basic concepts of R graphics</a></li>
<li class="chapter" data-level="2.2" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#scatter-plots-matrix"><i class="fa fa-check"></i><b>2.2</b> Scatter plots matrix</a></li>
<li class="chapter" data-level="2.3" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#star-and-segment-diagrams"><i class="fa fa-check"></i><b>2.3</b> Star and segment diagrams</a></li>
<li class="chapter" data-level="2.4" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#the-ggplot2-package-is-intuitive-and-powerful"><i class="fa fa-check"></i><b>2.4</b> The ggplot2 package is intuitive and powerful</a></li>
<li class="chapter" data-level="2.5" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#other-types-of-plots-with-ggplot2"><i class="fa fa-check"></i><b>2.5</b> Other types of plots with ggplot2</a></li>
<li class="chapter" data-level="2.6" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#hierarchical-clustering-and-heat-map"><i class="fa fa-check"></i><b>2.6</b> Hierarchical clustering and heat map</a></li>
<li class="chapter" data-level="2.7" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#principal-component-analysis-pca"><i class="fa fa-check"></i><b>2.7</b> Principal component analysis (PCA)</a></li>
<li class="chapter" data-level="2.8" data-path="visualizing-the-iris-flower-data-set.html"><a href="visualizing-the-iris-flower-data-set.html#classification-by-predicting-the-odds-of-binary-outcomes"><i class="fa fa-check"></i><b>2.8</b> Classification by predicting the odds of binary outcomes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#basic-concepts"><i class="fa fa-check"></i><b>3.1</b> Basic concepts</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-structures.html"><a href="data-structures.html#expressions"><i class="fa fa-check"></i><b>3.1.1</b> Expressions</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-structures.html"><a href="data-structures.html#logical-values"><i class="fa fa-check"></i><b>3.1.2</b> Logical Values</a></li>
<li class="chapter" data-level="3.1.3" data-path="data-structures.html"><a href="data-structures.html#variables"><i class="fa fa-check"></i><b>3.1.3</b> Variables</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-structures.html"><a href="data-structures.html#functions"><i class="fa fa-check"></i><b>3.1.4</b> Functions</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-structures.html"><a href="data-structures.html#looking-for-help-and-example-code"><i class="fa fa-check"></i><b>3.1.5</b> Looking for help and example Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-1"><i class="fa fa-check"></i><b>3.2</b> Data structures</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.2.1</b> Vectors</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-structures.html"><a href="data-structures.html#matrices"><i class="fa fa-check"></i><b>3.2.2</b> Matrices</a></li>
<li class="chapter" data-level="3.2.3" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.2.3</b> Data Frames</a></li>
<li class="chapter" data-level="3.2.4" data-path="data-structures.html"><a href="data-structures.html#strings-and-string-vectors"><i class="fa fa-check"></i><b>3.2.4</b> Strings and string vectors</a></li>
<li class="chapter" data-level="3.2.5" data-path="data-structures.html"><a href="data-structures.html#lists"><i class="fa fa-check"></i><b>3.2.5</b> Lists</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html"><i class="fa fa-check"></i><b>4</b> Importing data and managing files</a>
<ul>
<li class="chapter" data-level="4.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#project-oriented-workflow"><i class="fa fa-check"></i><b>4.1</b> Project-oriented workflow</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-project-in-a-new-folder"><i class="fa fa-check"></i><b>4.1.1</b> Create a project in a new folder</a></li>
<li class="chapter" data-level="4.1.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#create-a-script-file-and-comment"><i class="fa fa-check"></i><b>4.1.2</b> Create a script file and comment (!)</a></li>
<li class="chapter" data-level="4.1.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#copy-data-files-to-the-new-directory"><i class="fa fa-check"></i><b>4.1.3</b> Copy data files to the new directory</a></li>
<li class="chapter" data-level="4.1.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#import-data-files"><i class="fa fa-check"></i><b>4.1.4</b> Import data files</a></li>
<li class="chapter" data-level="4.1.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#check-and-convert-data-types"><i class="fa fa-check"></i><b>4.1.5</b> Check and convert data types</a></li>
<li class="chapter" data-level="4.1.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#close-a-project-when-you-are-done"><i class="fa fa-check"></i><b>4.1.6</b> Close a project when you are done</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#reading-files-directly-using-read.table"><i class="fa fa-check"></i><b>4.2</b> Reading files directly using read.table</a></li>
<li class="chapter" data-level="4.3" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#general-procedure-to-read-data-into-r"><i class="fa fa-check"></i><b>4.3</b> General procedure to read data into R:</a></li>
<li class="chapter" data-level="4.4" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#enter-data-manually"><i class="fa fa-check"></i><b>4.4</b> Enter data manually</a></li>
<li class="chapter" data-level="4.5" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-manipulation-in-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Data manipulation in a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="importing-data-and-managing-files.html"><a href="importing-data-and-managing-files.html#data-transformation-using-the-dplyr"><i class="fa fa-check"></i><b>4.6</b> Data transformation using the dplyr</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html"><i class="fa fa-check"></i><b>5</b> The heart attack data set (I)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#begin-your-analysis-by-examining-each-column-separately"><i class="fa fa-check"></i><b>5.1</b> Begin your analysis by examining each column separately</a></li>
<li class="chapter" data-level="5.2" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#possible-correlation-between-two-numeric-columns"><i class="fa fa-check"></i><b>5.2</b> Possible correlation between two numeric columns?</a></li>
<li class="chapter" data-level="5.3" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-categorical-variables"><i class="fa fa-check"></i><b>5.3</b> Associations between categorical variables?</a></li>
<li class="chapter" data-level="5.4" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-a-categorical-and-a-numeric-variables"><i class="fa fa-check"></i><b>5.4</b> Associations between a categorical and a numeric variables?</a></li>
<li class="chapter" data-level="5.5" data-path="the-heart-attack-data-set-i.html"><a href="the-heart-attack-data-set-i.html#associations-between-multiple-columns"><i class="fa fa-check"></i><b>5.5</b> Associations between multiple columns?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html"><i class="fa fa-check"></i><b>6</b> The heart attack dataset (II)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#scatter-plot-in-ggplot2"><i class="fa fa-check"></i><b>6.1</b> Scatter plot in ggplot2</a></li>
<li class="chapter" data-level="6.2" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#histograms-and-density-plots"><i class="fa fa-check"></i><b>6.2</b> Histograms and density plots</a></li>
<li class="chapter" data-level="6.3" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#box-plots-and-violin-plots"><i class="fa fa-check"></i><b>6.3</b> Box plots and Violin plots</a></li>
<li class="chapter" data-level="6.4" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#bar-plot-with-error-bars"><i class="fa fa-check"></i><b>6.4</b> Bar plot with error bars</a></li>
<li class="chapter" data-level="6.5" data-path="the-heart-attack-dataset-ii.html"><a href="the-heart-attack-dataset-ii.html#statistical-models-are-easy-interpretations-and-verifications-are-not"><i class="fa fa-check"></i><b>6.5</b> Statistical models are easy; interpretations and verifications are not!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-topics.html"><a href="advanced-topics.html"><i class="fa fa-check"></i><b>7</b> Advanced topics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="advanced-topics.html"><a href="advanced-topics.html#introduction-to-r-markdown"><i class="fa fa-check"></i><b>7.1</b> Introduction to R Markdown</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-topics.html"><a href="advanced-topics.html#tidyverse"><i class="fa fa-check"></i><b>7.2</b> Tidyverse</a></li>
<li class="chapter" data-level="7.3" data-path="advanced-topics.html"><a href="advanced-topics.html#interactive-plots-made-easy-with-plotly"><i class="fa fa-check"></i><b>7.3</b> Interactive plots made easy with Plotly</a></li>
<li class="chapter" data-level="7.4" data-path="advanced-topics.html"><a href="advanced-topics.html#shiny-apps"><i class="fa fa-check"></i><b>7.4</b> Shiny Apps</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-topics.html"><a href="advanced-topics.html#install-the-shiny-package-by-typing-this-in-the-console."><i class="fa fa-check"></i><b>7.4.1</b> Install the Shiny package by typing this in the console.</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-topics.html"><a href="advanced-topics.html#create-a-shiny-web-app-is-a-piece-of-cake"><i class="fa fa-check"></i><b>7.4.2</b> Create a Shiny web app is a piece of cake</a></li>
<li class="chapter" data-level="7.4.3" data-path="advanced-topics.html"><a href="advanced-topics.html#lets-play"><i class="fa fa-check"></i><b>7.4.3</b> Let’s play!</a></li>
<li class="chapter" data-level="7.4.4" data-path="advanced-topics.html"><a href="advanced-topics.html#pubish-your-app"><i class="fa fa-check"></i><b>7.4.4</b> Pubish your app</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-topics.html"><a href="advanced-topics.html#define-your-own-function"><i class="fa fa-check"></i><b>7.5</b> Define your own function</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="the-state-dataset.html"><a href="the-state-dataset.html"><i class="fa fa-check"></i><b>8</b> The state dataset</a>
<ul>
<li class="chapter" data-level="8.1" data-path="the-state-dataset.html"><a href="the-state-dataset.html#reading-in-and-manipulating-data"><i class="fa fa-check"></i><b>8.1</b> Reading in and manipulating data</a></li>
<li class="chapter" data-level="8.2" data-path="the-state-dataset.html"><a href="the-state-dataset.html#visualizing-data"><i class="fa fa-check"></i><b>8.2</b> Visualizing data</a></li>
<li class="chapter" data-level="8.3" data-path="the-state-dataset.html"><a href="the-state-dataset.html#analyzing-the-relationship-among-variables"><i class="fa fa-check"></i><b>8.3</b> Analyzing the relationship among variables</a></li>
<li class="chapter" data-level="8.4" data-path="the-state-dataset.html"><a href="the-state-dataset.html#the-whole-picture-of-the-data-set"><i class="fa fa-check"></i><b>8.4</b> The whole picture of the data set</a></li>
<li class="chapter" data-level="8.5" data-path="the-state-dataset.html"><a href="the-state-dataset.html#linear-model-analysis"><i class="fa fa-check"></i><b>8.5</b> Linear model analysis</a></li>
<li class="chapter" data-level="8.6" data-path="the-state-dataset.html"><a href="the-state-dataset.html#conclusion"><i class="fa fa-check"></i><b>8.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html"><i class="fa fa-check"></i><b>9</b> The game sales dataset</a>
<ul>
<li class="chapter" data-level="9.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#reading-in-data-and-manage-data"><i class="fa fa-check"></i><b>9.1</b> Reading in data and manage data</a></li>
<li class="chapter" data-level="9.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#visualization-of-categorical-variables"><i class="fa fa-check"></i><b>9.2</b> Visualization of categorical variables</a></li>
<li class="chapter" data-level="9.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#correlation-among-numeric-variables"><i class="fa fa-check"></i><b>9.3</b> Correlation among numeric variables</a></li>
<li class="chapter" data-level="9.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-score-and-count"><i class="fa fa-check"></i><b>9.4</b> Analysis of score and count</a></li>
<li class="chapter" data-level="9.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#analysis-of-sales"><i class="fa fa-check"></i><b>9.5</b> Analysis of sales</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-year.release"><i class="fa fa-check"></i><b>9.5.1</b> By Year.Release</a></li>
<li class="chapter" data-level="9.5.2" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-region"><i class="fa fa-check"></i><b>9.5.2</b> By Region</a></li>
<li class="chapter" data-level="9.5.3" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating"><i class="fa fa-check"></i><b>9.5.3</b> By Rating</a></li>
<li class="chapter" data-level="9.5.4" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-genre"><i class="fa fa-check"></i><b>9.5.4</b> By Genre</a></li>
<li class="chapter" data-level="9.5.5" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-score"><i class="fa fa-check"></i><b>9.5.5</b> by Score</a></li>
<li class="chapter" data-level="9.5.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-rating-genre-critic-score"><i class="fa fa-check"></i><b>9.5.6</b> By Rating &amp; Genre &amp; Critic score</a></li>
<li class="chapter" data-level="9.5.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#by-platform"><i class="fa fa-check"></i><b>9.5.7</b> By Platform</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#effect-of-platform-type-to-priciple-components"><i class="fa fa-check"></i><b>9.6</b> Effect of platform type to priciple components</a></li>
<li class="chapter" data-level="9.7" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#models-for-global-sales"><i class="fa fa-check"></i><b>9.7</b> Models for global sales</a></li>
<li class="chapter" data-level="9.8" data-path="the-game-sales-dataset.html"><a href="the-game-sales-dataset.html#conclusion-1"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html"><i class="fa fa-check"></i><b>10</b> The messy salary data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#read-in-and-clean-data"><i class="fa fa-check"></i><b>10.1</b> Read in and clean data</a></li>
<li class="chapter" data-level="10.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#information-about-the-variables"><i class="fa fa-check"></i><b>10.2</b> Information about the variables</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#income-and-age"><i class="fa fa-check"></i><b>10.2.1</b> Income and age</a></li>
<li class="chapter" data-level="10.2.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group"><i class="fa fa-check"></i><b>10.2.2</b> Ethnic group</a></li>
<li class="chapter" data-level="10.2.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex"><i class="fa fa-check"></i><b>10.2.3</b> Sex</a></li>
<li class="chapter" data-level="10.2.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#union-descreption"><i class="fa fa-check"></i><b>10.2.4</b> Union descreption</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income"><i class="fa fa-check"></i><b>10.3</b> Analysis of gross income</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#age"><i class="fa fa-check"></i><b>10.3.1</b> Age</a></li>
<li class="chapter" data-level="10.3.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#sex-1"><i class="fa fa-check"></i><b>10.3.2</b> Sex</a></li>
<li class="chapter" data-level="10.3.3" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-group-1"><i class="fa fa-check"></i><b>10.3.3</b> Ethnic Group</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#analysis-of-gross-income-type"><i class="fa fa-check"></i><b>10.4</b> Analysis of gross income type</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#gross-type"><i class="fa fa-check"></i><b>10.4.1</b> Gross Type</a></li>
<li class="chapter" data-level="10.4.2" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#ethnic-and-sex-and-age"><i class="fa fa-check"></i><b>10.4.2</b> Ethnic and Sex and age</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#lm-and-anova-analysis"><i class="fa fa-check"></i><b>10.5</b> LM and ANOVA analysis</a></li>
<li class="chapter" data-level="10.6" data-path="the-messy-salary-data.html"><a href="the-messy-salary-data.html#conclusion-2"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Learn R through examples</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="visualizing-the-iris-flower-data-set" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Visualizing the iris flower data set</h1>
<p>Learning objectives:</p>
<ul>
<li>Basic concepts of R graphics</li>
<li>Install and load R packages (ggplot2 and pheatmap)</li>
<li>Basic plots with ggplot2</li>
<li>Different ways to visualize the iris flower dataset</li>
</ul>
<div id="basic-concepts-of-r-graphics" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Basic concepts of R graphics</h2>
<p>We start with base R graphics. The first import distinction should be made about
high- and low-level graphics functions in base R. See this table below.
High-level graphics functions initiate new plots, to which new elements could be
added using the low-level functions.</p>
<table>
<caption>High-level graphics functions that can initiate a new plot.</caption>
<colgroup>
<col width="19%" />
<col width="80%" />
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Memo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>plot</td>
<td>Generic plotting function</td>
</tr>
<tr class="even">
<td>boxplot</td>
<td>boxplot. Can be applied to multiple columns of a matrix, or use equations boxplot( y ~ x)</td>
</tr>
<tr class="odd">
<td>hist</td>
<td>histogram</td>
</tr>
<tr class="even">
<td>qqnorm</td>
<td>Quantile-quantile (Q-Q) plot to check for normality</td>
</tr>
<tr class="odd">
<td>curve</td>
<td>Graph an arithmetic function</td>
</tr>
<tr class="even">
<td>barplot</td>
<td>Barplot</td>
</tr>
<tr class="odd">
<td>mosaicplot</td>
<td>Using mosaics to represent the frequencies of tabulated counts.</td>
</tr>
<tr class="even">
<td>heatmap</td>
<td>Using colors to visualize a matrix of numeric values.</td>
</tr>
</tbody>
</table>
<p>In contrast, low-level graphics functions do not wipe out the existing plot;
they add elements to it.</p>
<table>
<caption>Low-level graphics functions that add elements to an existing plot.</caption>
<thead>
<tr class="header">
<th>Function</th>
<th>Memo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>points</td>
<td>Add points to a plot</td>
</tr>
<tr class="even">
<td>lines</td>
<td>Add lines to a plot</td>
</tr>
<tr class="odd">
<td>abline</td>
<td>Add a straight line</td>
</tr>
<tr class="even">
<td>segments</td>
<td>Add line segments</td>
</tr>
<tr class="odd">
<td>text</td>
<td>Add text to a plot</td>
</tr>
<tr class="even">
<td>legend</td>
<td>Add a legend to a plot</td>
</tr>
<tr class="odd">
<td>arrows</td>
<td>Add arrows to a plot</td>
</tr>
</tbody>
</table>
<p>Sometimes we generate many graphics quickly for exploratory data analysis (EDA)
to get some sense of what the data looks like. We can achieve this by using
plotting functions with <strong>default settings</strong> to quickly generate a lot of
“plain” plots. R is a very powerful EDA tool. However, you have to know what
types of graphs are suitable for the data.</p>
<p>Occasionally we want to generate really “cool”-looking graphics for papers and
presentations. Making such plots typically requires a bit more coding, as you
have to customize different parameters. For me, it usually involves
some Google searches of example codes, and then I revise it via trial-and-error.
If I cannot make it work, I read the help document.</p>
<p>One of the open secrets of R programming is that you can start from a plain
figure and keep trying to <strong>refine it step by step</strong> while Googling. Let’s take
an example using the base R graphics. This produces a basic scatter plot with
the petal length on the x-axis and petal width on the y-axis. Since iris is a
data frame, we will use the <code>iris$Petal.Length</code> to refer to the Petal.Length
column. This avoids using the <em>attach</em> function.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="visualizing-the-iris-flower-data-set.html#cb55-1" aria-hidden="true" tabindex="-1"></a>PL <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Length</span>
<span id="cb55-2"><a href="visualizing-the-iris-flower-data-set.html#cb55-2" aria-hidden="true" tabindex="-1"></a>PW <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Width</span>
<span id="cb55-3"><a href="visualizing-the-iris-flower-data-set.html#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-47-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Let’s change the marker type.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="visualizing-the-iris-flower-data-set.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, <span class="at">pch =</span> <span class="dv">2</span>) <span class="co"># change to triangle</span></span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-48-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>The <strong>pch</strong> parameter can take values from 0 to 25, each corresponding to different types of marker. See a list <a href="http://www.sthda.com/english/wiki/r-plot-pch-symbols-the-different-point-shapes-available-in-r">here.</a></p>
<p>There are many other parameters to the <strong>plot</strong> function in R. You can get these
from the documentation</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="visualizing-the-iris-flower-data-set.html#cb57-1" aria-hidden="true" tabindex="-1"></a>? plot</span></code></pre></div>
<p>We can also change the color of the data points easily with the <strong>col</strong> parameter.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="visualizing-the-iris-flower-data-set.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, <span class="at">pch =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>) <span class="co"># change to green</span></span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-50-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Next, we want to use different markers according to species. First, lets get the information.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="visualizing-the-iris-flower-data-set.html#cb59-1" aria-hidden="true" tabindex="-1"></a>speciesID <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(iris<span class="sc">$</span>Species)</span>
<span id="cb59-2"><a href="visualizing-the-iris-flower-data-set.html#cb59-2" aria-hidden="true" tabindex="-1"></a>speciesID</span></code></pre></div>
<pre><code>##   [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
##  [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
##  [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3
## [112] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
## [149] 3 3</code></pre>
<p>This is possible because Species is a <strong>factor</strong> with 3 predefined levels and the individual elements take 1, 2 or 3. Now we can change the symbols based on species with this:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="visualizing-the-iris-flower-data-set.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, <span class="at">pch =</span> speciesID, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>) </span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-52-1.png" width="80%" style="display: block; margin: auto;" />
What happens here is that the 150 integers stored in the types vector are used
to alter symbols. The first 50 data points (setosa) are represented by open
circles. The next 50 (versicolor) are represented by triangles, while the last
50 in crosses.</p>
<p>Follow the same thinking, we also change the color according to species. We
generate 3 colors with rainbow() function and then alternate using the species.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="visualizing-the-iris-flower-data-set.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, <span class="at">pch =</span> speciesID, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[speciesID])</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-53-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>This figure starts to looks nice, as the three species are easily separated by
color and shape. But we are not done. Let us change the x- and y-labels, and also
add a main title.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="visualizing-the-iris-flower-data-set.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW,                               <span class="co">#x and y</span></span>
<span id="cb63-2"><a href="visualizing-the-iris-flower-data-set.html#cb63-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> speciesID,                      <span class="co">#marker type</span></span>
<span id="cb63-3"><a href="visualizing-the-iris-flower-data-set.html#cb63-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[speciesID],          <span class="co"># color</span></span>
<span id="cb63-4"><a href="visualizing-the-iris-flower-data-set.html#cb63-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Petal length (cm)&quot;</span>,           <span class="co"># x label</span></span>
<span id="cb63-5"><a href="visualizing-the-iris-flower-data-set.html#cb63-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Petal width (cm)&quot;</span>,            <span class="co"># y label</span></span>
<span id="cb63-6"><a href="visualizing-the-iris-flower-data-set.html#cb63-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Petal width vs. length&quot;</span>)      <span class="co"># main title</span></span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-54-1.png" width="80%" style="display: block; margin: auto;" />
Note that this command spans many lines. Very long lines make it hard to read.
The benefit of multiple lines is that we can clearly see each line contain a parameter.
When you are typing in the Console window, R knows that you are not done and
will be waiting for the second parenthesis.</p>
<p>It is essential to write your code so that it could be easily understood by others
(or your future self). See
<a href="http://adv-r.had.co.nz/Style.html">breif</a> and
<a href="https://style.tidyverse.org/">detailed</a> style guides. This is like checking the
dressing code before going to an event.</p>
<p>A true perfectionist never settles. We notice a strong linear correlation between petal length and width. Let’s add a trend line using <strong>abline</strong>, a low level graphics function.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="visualizing-the-iris-flower-data-set.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW, </span>
<span id="cb64-2"><a href="visualizing-the-iris-flower-data-set.html#cb64-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> speciesID,</span>
<span id="cb64-3"><a href="visualizing-the-iris-flower-data-set.html#cb64-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[speciesID],</span>
<span id="cb64-4"><a href="visualizing-the-iris-flower-data-set.html#cb64-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Petal length (cm)&quot;</span>,</span>
<span id="cb64-5"><a href="visualizing-the-iris-flower-data-set.html#cb64-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Petal width (cm)&quot;</span>,</span>
<span id="cb64-6"><a href="visualizing-the-iris-flower-data-set.html#cb64-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Petal width vs. length&quot;</span>)</span>
<span id="cb64-7"><a href="visualizing-the-iris-flower-data-set.html#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="fu">lm</span>(PW <span class="sc">~</span> PL) ) <span class="co"># the order is reversed as we need y ~ x.</span></span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-55-1.png" width="80%" style="display: block; margin: auto;" />
The <code>lm(PW ~ PL)</code> generates a linear model (lm) of petal width as a function petal
length. y ~ x is <strong>formula notation</strong> that used in many different situations.
This linear regression model is used to plot the trend line.</p>
<p>We calculate the Pearson’s correlation coefficient and mark it to the plot.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="visualizing-the-iris-flower-data-set.html#cb65-1" aria-hidden="true" tabindex="-1"></a>PCC <span class="ot">&lt;-</span> <span class="fu">cor</span>(PW, PL)  <span class="co"># Pearson&#39;s correlation coefficient</span></span>
<span id="cb65-2"><a href="visualizing-the-iris-flower-data-set.html#cb65-2" aria-hidden="true" tabindex="-1"></a>PCC <span class="ot">&lt;-</span> <span class="fu">round</span>(PCC, <span class="dv">2</span>) <span class="co"># round to the 2nd place after decimal point.</span></span>
<span id="cb65-3"><a href="visualizing-the-iris-flower-data-set.html#cb65-3" aria-hidden="true" tabindex="-1"></a>PCC</span></code></pre></div>
<pre><code>## [1] 0.96</code></pre>
<p>The <strong>text</strong> function is used to place strings created with the <em>paste</em> function at the location of coordinate of (x=5, y=0.5). To finish up this plot, we add a legend. Here is how we have everything together.</p>

<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="visualizing-the-iris-flower-data-set.html#cb67-1" aria-hidden="true" tabindex="-1"></a>PL <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Length</span>
<span id="cb67-2"><a href="visualizing-the-iris-flower-data-set.html#cb67-2" aria-hidden="true" tabindex="-1"></a>PW <span class="ot">&lt;-</span> iris<span class="sc">$</span>Petal.Width</span>
<span id="cb67-3"><a href="visualizing-the-iris-flower-data-set.html#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(PL, PW,  </span>
<span id="cb67-4"><a href="visualizing-the-iris-flower-data-set.html#cb67-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> speciesID,                <span class="co"># marker type</span></span>
<span id="cb67-5"><a href="visualizing-the-iris-flower-data-set.html#cb67-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[speciesID],    <span class="co"># color</span></span>
<span id="cb67-6"><a href="visualizing-the-iris-flower-data-set.html#cb67-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Petal length (cm)&quot;</span>,</span>
<span id="cb67-7"><a href="visualizing-the-iris-flower-data-set.html#cb67-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Petal width (cm)&quot;</span>,</span>
<span id="cb67-8"><a href="visualizing-the-iris-flower-data-set.html#cb67-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Petal width vs. length&quot;</span>)</span>
<span id="cb67-9"><a href="visualizing-the-iris-flower-data-set.html#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>( <span class="fu">lm</span>(PW <span class="sc">~</span> PL) )  <span class="co"># regression line</span></span>
<span id="cb67-10"><a href="visualizing-the-iris-flower-data-set.html#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">5</span>, <span class="fl">0.5</span>, <span class="fu">paste</span>(<span class="st">&quot;R=&quot;</span>, PCC) )  <span class="co"># add text annotation</span></span>
<span id="cb67-11"><a href="visualizing-the-iris-flower-data-set.html#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>, </span>
<span id="cb67-12"><a href="visualizing-the-iris-flower-data-set.html#cb67-12" aria-hidden="true" tabindex="-1"></a>       <span class="fu">levels</span>(iris<span class="sc">$</span>Species), </span>
<span id="cb67-13"><a href="visualizing-the-iris-flower-data-set.html#cb67-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, </span>
<span id="cb67-14"><a href="visualizing-the-iris-flower-data-set.html#cb67-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:23-5"></span>
<img src="book_files/figure-html/23-5-1.png" alt="A refined scatter plot using base R graphics." width="80%" />
<p class="caption">
Figure 2.1: A refined scatter plot using base R graphics.
</p>
</div>
<p>While <strong>plot</strong> is a high-level graphics function that starts a new plot, <strong>abline</strong>, <strong>text</strong>, and <strong>legend</strong> are all low-level functions that add to existing plot. This chunk of code is impressive! You should be proud of yourself if you are able to generate this plot. We know that we build it up step-by-step with some trial-and-error.</p>
<p>Another open secret of coding is that we frequently steal each other’s ideas and
code. The textbook <em>R Graphics Cookbook</em> includes all kinds of R plots and
example code. Some are online: <a href="http://www.cookbook-r.com/Graphs/" class="uri">http://www.cookbook-r.com/Graphs/</a>. There are
also websites lists all sorts of R graphics and example codes that you can use.
<a href="http://www.r-graph-gallery.com/" class="uri">http://www.r-graph-gallery.com/</a> contains more than 200 such examples. Another
one is here: <a href="http://bxhorn.com/r-graphics-gallery/" class="uri">http://bxhorn.com/r-graphics-gallery/</a>. If you know what types of
graphs you want, it is very easy to start with the template code and swap out
the dataset.</p>
</div>
<div id="scatter-plots-matrix" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Scatter plots matrix</h2>
<p>While data frames can have a mixture of numbers and characters in different
columns, a <strong>matrix often only contains numbers</strong>. Let’s extract the first 4
columns from the data frame iris and convert to a matrix:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="visualizing-the-iris-flower-data-set.html#cb68-1" aria-hidden="true" tabindex="-1"></a>ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])  <span class="co"># convert to matrix</span></span>
<span id="cb68-2"><a href="visualizing-the-iris-flower-data-set.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(ma)  <span class="co"># column means for matrix</span></span></code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##     5.843333     3.057333     3.758000     1.199333</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="visualizing-the-iris-flower-data-set.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(ma)</span></code></pre></div>
<pre><code>## Sepal.Length  Sepal.Width Petal.Length  Petal.Width 
##        876.5        458.6        563.7        179.9</code></pre>
<p>The same thing can be done with rows via <strong>rowMeans(x)</strong> and <strong>rowSums(x)</strong>.</p>
<p>We can generate a matrix of scatter plots simply by:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="visualizing-the-iris-flower-data-set.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(ma) </span></code></pre></div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="visualizing-the-iris-flower-data-set.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(ma, <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[iris<span class="sc">$</span>Species])  <span class="co"># Figure 2.4</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-59"></span>
<img src="book_files/figure-html/unnamed-chunk-59-1.png" alt="Scatter plot matrix." width="672" />
<p class="caption">
Figure 2.2: Scatter plot matrix.
</p>
</div>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-60" class="exercise"><strong>Exercise 2.1  </strong></span></p>
Look at this large plot for a moment. What do you see? Provide interpretation of these scatter plots.
</div>
</blockquote>
</div>
<div id="star-and-segment-diagrams" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Star and segment diagrams</h2>
<p><strong>Star plot uses stars to visualize multidimensional data.</strong> Radar chart is a useful way to display multivariate observations with an arbitrary number of variables. Each observation is represented as a star-shaped figure with one ray for each variable. For a given observation, the length of each ray is made proportional to the size of that variable. The star plot was first used by Georg von Mayr in 1877!</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="visualizing-the-iris-flower-data-set.html#cb74-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb74-2"><a href="visualizing-the-iris-flower-data-set.html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stars</span>(df)         <span class="co"># do I see any diamonds?</span></span>
<span id="cb74-3"><a href="visualizing-the-iris-flower-data-set.html#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stars</span>(df, <span class="at">key.loc =</span> <span class="fu">c</span>(<span class="dv">17</span>,<span class="dv">0</span>))    <span class="co"># What does this tell you?</span></span></code></pre></div>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-62" class="exercise"><strong>Exercise 2.2  </strong></span></p>
Based on the star plot, what is your overall impression regarding the differences among these 3 species of flowers?
</div>
</blockquote>
<p>The stars() function can also be used to generate segment diagrams, where each variable is used to generate colorful segments. The sizes of the segments are proportional to the measurements.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="visualizing-the-iris-flower-data-set.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stars</span>(df, <span class="at">key.loc =</span> <span class="fu">c</span>(<span class="dv">20</span>,<span class="fl">0.5</span>), <span class="at">draw.segments =</span> <span class="cn">TRUE</span> )    </span></code></pre></div>

<div class="figure" style="text-align: center"><span id="fig:12-4"></span>
<img src="images/img1204n_starsegment.png" alt="Star plots and segments diagrams." width="640" />
<p class="caption">
Figure 2.3: Star plots and segments diagrams.
</p>
</div>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-64" class="exercise"><strong>Exercise 2.3  </strong></span></p>
Produce the segments diagram of the state data (state.x77) and offer some interpretation regarding South Dakota compared with other states. Hints: Convert the matrix to data frame using df.state.x77 &lt;- as.data.frame(state.x77), then attach df.state.x77.
</div>
</blockquote>
</div>
<div id="the-ggplot2-package-is-intuitive-and-powerful" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> The ggplot2 package is intuitive and powerful</h2>
<p>In addition to the graphics functions in base R, there are many other packages
we can use to create graphics. The most widely used are lattice and ggplot2,
both implemented in additional packages. Together with base R graphics,
sometimes these are referred to as the three independent paradigms of R
graphics. The lattice package extends base R graphics and enables the creating
of graphs in multiple facets. The ggplot2 is developed based on a Grammar of
Graphics (hence the “gg”), a modular approach that builds complex graphics by
adding layers. Intuitive yet powerful, ggplot2 is becoming increasingly popular.</p>
<p>The ggplot2 functions is not included in the base distribution of R. These are available as an additional <strong>package</strong>, on the CRAN <a href="https://cran.r-project.org/web/packages/ggplot2/index.html">website</a>.
They need to be downloaded and installed. One of the main advantages of R is that it
is open, and users can contribute their code as packages. If you are using
<strong>Rstudio</strong>, you can choose <strong>Tools-&gt;Install packages</strong> from the main menu, and
then enter the name of the package. If you are using R software, you can install
additional packages, by clicking <strong>Packages</strong> in the main menu, and select a
mirror site. These mirror sites all work the same, but some may be faster. After
choosing a mirror and clicking “OK,” you can scroll down the long list to find
your package. Alternatively, you can type this command to install packages.</p>
<p>ggplot2 is a modular, intuitive system for plotting, as we use different functions to refine different aspects of a chart step-by-step:</p>
<ul>
<li><strong>Aesthetic mapping</strong> from variables to visual characteristics</li>
<li><strong>Geometric shapes</strong> (points, lines, boxes, bars, histograms, maps, etc)</li>
<li><strong>Scales</strong> and <strong>statistical transformations</strong> (log, reverse, count, etc)</li>
<li><strong>coordinate systems</strong><br />
</li>
<li><strong>facets</strong> ( multiple plots)</li>
<li><strong>Labels</strong> and <strong>annotations</strong></li>
</ul>
<p>Detailed tutorials on ggplot2 can be find <a href="https://uc-r.github.io/ggplot_intro">here</a> and by its <a href="https://r4ds.had.co.nz/data-visualisation.html">author</a>. Here we present a quick demo.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="visualizing-the-iris-flower-data-set.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the package. You can also do it through the Packages Tab</span></span>
<span id="cb76-2"><a href="visualizing-the-iris-flower-data-set.html#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span> (<span class="st">&quot;ggplot2&quot;</span>)  </span></code></pre></div>
<p>Packages only need to be installed once. But every time you need to use the <strong>functions or data</strong> in a package, you have to <strong>load</strong> it from your hard drive into memory.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="visualizing-the-iris-flower-data-set.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)  <span class="co"># load the ggplot2 package</span></span></code></pre></div>

<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="visualizing-the-iris-flower-data-set.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a canvas</span></span>
<span id="cb78-2"><a href="visualizing-the-iris-flower-data-set.html#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-1"></span>
<img src="book_files/figure-html/2-6-1.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.4: Basic scatter plot using the ggplot2 package.
</p>
</div>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="visualizing-the-iris-flower-data-set.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># map data to x and y coordinates </span></span>
<span id="cb79-2"><a href="visualizing-the-iris-flower-data-set.html#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris ) <span class="sc">+</span> </span>
<span id="cb79-3"><a href="visualizing-the-iris-flower-data-set.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width)  </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-2"></span>
<img src="book_files/figure-html/2-6-2.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.5: Basic scatter plot using the ggplot2 package.
</p>
</div>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="visualizing-the-iris-flower-data-set.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add data points</span></span>
<span id="cb80-2"><a href="visualizing-the-iris-flower-data-set.html#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb80-3"><a href="visualizing-the-iris-flower-data-set.html#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width) <span class="sc">+</span> </span>
<span id="cb80-4"><a href="visualizing-the-iris-flower-data-set.html#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-3"></span>
<img src="book_files/figure-html/2-6-3.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.6: Basic scatter plot using the ggplot2 package.
</p>
</div>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="visualizing-the-iris-flower-data-set.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change color &amp; marker type</span></span>
<span id="cb81-2"><a href="visualizing-the-iris-flower-data-set.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb81-3"><a href="visualizing-the-iris-flower-data-set.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width) <span class="sc">+</span> </span>
<span id="cb81-4"><a href="visualizing-the-iris-flower-data-set.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(<span class="at">color =</span> Species, <span class="at">shape =</span> Species) ) </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-4"></span>
<img src="book_files/figure-html/2-6-4.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.7: Basic scatter plot using the ggplot2 package.
</p>
</div>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="visualizing-the-iris-flower-data-set.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adds trend line</span></span>
<span id="cb82-2"><a href="visualizing-the-iris-flower-data-set.html#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb82-3"><a href="visualizing-the-iris-flower-data-set.html#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width) <span class="sc">+</span> </span>
<span id="cb82-4"><a href="visualizing-the-iris-flower-data-set.html#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(<span class="at">color =</span> Species, <span class="at">shape =</span> Species) ) <span class="sc">+</span></span>
<span id="cb82-5"><a href="visualizing-the-iris-flower-data-set.html#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span>lm)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-5"></span>
<img src="book_files/figure-html/2-6-5.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.8: Basic scatter plot using the ggplot2 package.
</p>
</div>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="visualizing-the-iris-flower-data-set.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># adds annotation text</span></span>
<span id="cb83-2"><a href="visualizing-the-iris-flower-data-set.html#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb83-3"><a href="visualizing-the-iris-flower-data-set.html#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width) <span class="sc">+</span> </span>
<span id="cb83-4"><a href="visualizing-the-iris-flower-data-set.html#cb83-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(<span class="at">color =</span> Species, <span class="at">shape =</span> Species) ) <span class="sc">+</span></span>
<span id="cb83-5"><a href="visualizing-the-iris-flower-data-set.html#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span>lm) <span class="sc">+</span></span>
<span id="cb83-6"><a href="visualizing-the-iris-flower-data-set.html#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fl">0.5</span>, <span class="at">label =</span> <span class="st">&quot;R=0.96&quot;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-6-6"></span>
<img src="book_files/figure-html/2-6-6.png" alt="Basic scatter plot using the ggplot2 package." width="100%" />
<p class="caption">
Figure 2.9: Basic scatter plot using the ggplot2 package.
</p>
</div>
<p>Some ggplot2 commands span multiple lines. The first line defines the plotting space. The ending “+” signifies that another layer ( data points) of plotting is added. Also, the ggplot2 package handles a lot of the details for us. We can easily generate many different types of plots.
It is also much easier to generate a plot like Figure <a href="visualizing-the-iris-flower-data-set.html#fig:23-5">2.1</a>.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="visualizing-the-iris-flower-data-set.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris) <span class="sc">+</span></span>
<span id="cb84-2"><a href="visualizing-the-iris-flower-data-set.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">y =</span> Petal.Width) <span class="sc">+</span>                 <span class="co"># define space</span></span>
<span id="cb84-3"><a href="visualizing-the-iris-flower-data-set.html#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="fu">aes</span>(<span class="at">color =</span> Species, <span class="at">shape =</span> Species) ) <span class="sc">+</span>    <span class="co"># add points</span></span>
<span id="cb84-4"><a href="visualizing-the-iris-flower-data-set.html#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span>lm) <span class="sc">+</span>                                <span class="co"># add trend line  </span></span>
<span id="cb84-5"><a href="visualizing-the-iris-flower-data-set.html#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="at">x =</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fl">0.5</span>, <span class="at">label =</span> <span class="st">&quot;R=0.96&quot;</span>) <span class="sc">+</span>     <span class="co"># annotate with text</span></span>
<span id="cb84-6"><a href="visualizing-the-iris-flower-data-set.html#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Petal length (cm)&quot;</span>) <span class="sc">+</span>                              <span class="co"># x-axis labels</span></span>
<span id="cb84-7"><a href="visualizing-the-iris-flower-data-set.html#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Petal width (cm)&quot;</span>) <span class="sc">+</span>                               <span class="co"># y-axis labels</span></span>
<span id="cb84-8"><a href="visualizing-the-iris-flower-data-set.html#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>( <span class="st">&quot;Correlation between petal length and width&quot;</span>)   <span class="co"># title</span></span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="book_files/figure-html/unnamed-chunk-67-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>As you can see, data visualization using ggplot2 is similar to painting: we first find a blank canvas, paint background, sketch outlines, and then add details.
<img src="https://github.com/gexijin/learnR/raw/master/images/drawing.gif" alt="The process of painting from GIPHY by (maluduque?)" /></p>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-69" class="exercise"><strong>Exercise 2.4  </strong></span></p>
Create a scatter plot of sepal length vs sepal width, change colors and shapes with species, and add trend line.
</div>
</blockquote>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-70" class="exercise"><strong>Exercise 2.5  </strong></span></p>
Use boxplot, multiple panel histograms, and density plots to investigate whether petal width is the same among three subspecies.
</div>
</blockquote>
</div>
<div id="other-types-of-plots-with-ggplot2" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Other types of plots with ggplot2</h2>
<p>Box plots can be generated by ggplot.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="visualizing-the-iris-flower-data-set.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb86-2"><a href="visualizing-the-iris-flower-data-set.html#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb86-3"><a href="visualizing-the-iris-flower-data-set.html#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Sepal.Length, <span class="at">color =</span> Species) <span class="sc">+</span></span>
<span id="cb86-4"><a href="visualizing-the-iris-flower-data-set.html#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-71-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Here we use Species, a categorical variable, as x-coordinate. Essentially, we
use it to define three groups of data. The y-axis is the sepal length, whose distribution we are interested in. The benefit of using ggplot2 is evident as we can easily refine it.</p>

<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="visualizing-the-iris-flower-data-set.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb87-2"><a href="visualizing-the-iris-flower-data-set.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Species, <span class="at">y =</span> Sepal.Length, <span class="at">color =</span> Species) <span class="sc">+</span></span>
<span id="cb87-3"><a href="visualizing-the-iris-flower-data-set.html#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb87-4"><a href="visualizing-the-iris-flower-data-set.html#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="fl">0.2</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-72"></span>
<img src="book_files/figure-html/unnamed-chunk-72-1.png" alt="Box plot with raw data points. This is getting increasingly popular." width="80%" />
<p class="caption">
Figure 2.10: Box plot with raw data points. This is getting increasingly popular.
</p>
</div>
<p>On top of the boxplot, we add another layer representing the raw data points for each of the species. Since lining up data points on a straight line is hard to see, we jittered the relative x-position within each subspecies randomly. We also color-coded three species simply by adding “color = Species.” Many of the low-level graphics details are handled for us by ggplot2 as the legend is generated automatically.</p>

<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="visualizing-the-iris-flower-data-set.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb88-2"><a href="visualizing-the-iris-flower-data-set.html#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">fill =</span> Species) <span class="sc">+</span> </span>
<span id="cb88-3"><a href="visualizing-the-iris-flower-data-set.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>( <span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:2-7"></span>
<img src="book_files/figure-html/2-7-1.png" alt="Density plot of petal length, grouped by species." width="60%" />
<p class="caption">
Figure 2.11: Density plot of petal length, grouped by species.
</p>
</div>

<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="visualizing-the-iris-flower-data-set.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> iris) <span class="sc">+</span></span>
<span id="cb89-2"><a href="visualizing-the-iris-flower-data-set.html#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Petal.Length, <span class="at">fill =</span> Species) <span class="sc">+</span> </span>
<span id="cb89-3"><a href="visualizing-the-iris-flower-data-set.html#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>( <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb89-4"><a href="visualizing-the-iris-flower-data-set.html#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Species, <span class="at">nrow =</span> <span class="dv">3</span>)  </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-73"></span>
<img src="book_files/figure-html/unnamed-chunk-73-1.png" alt="Density plot by subgroups using facets." width="80%" />
<p class="caption">
Figure 2.12: Density plot by subgroups using facets.
</p>
</div>
<p>The bar plot with error bar in (fig:22-1) we generated above is called dynamite plots for its similarity. <strong>“The dynamite plots must die!”</strong>, argued renowned statistician Rafael Irizarry in his <a href="https://simplystatistics.org/2019/02/21/dynamite-plots-must-die/">blog</a>. Dynamite plots give very little information; the mean and standard errors just could be printed out. The outliers and overall distribution is hidden. Many scientists have chosen to use this boxplot with jittered points.</p>
</div>
<div id="hierarchical-clustering-and-heat-map" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Hierarchical clustering and heat map</h2>
<p>Hierarchical clustering summarizes observations into trees representing the overall similarities.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="visualizing-the-iris-flower-data-set.html#cb90-1" aria-hidden="true" tabindex="-1"></a>ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]) <span class="co"># convert to matrix</span></span>
<span id="cb90-2"><a href="visualizing-the-iris-flower-data-set.html#cb90-2" aria-hidden="true" tabindex="-1"></a>disMatarix <span class="ot">&lt;-</span> <span class="fu">dist</span>(ma)</span>
<span id="cb90-3"><a href="visualizing-the-iris-flower-data-set.html#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( <span class="fu">hclust</span>(disMatarix) )</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p>We first calculate a distance matrix using the <strong>dist</strong> function with the default Euclidean distance method. The distance matrix is then used by the <strong>hclust</strong> function to generate a hierarchical clustering tree with the default complete linkage method, which is then plotted in a nested command.</p>
<p>The 150 samples of flowers are organized in this cluster dendrogram based on their Euclidean distance, which is labeled vertically by the bar to the left side. Highly similar flowers are grouped together in smaller branches, and their distances can be found according to the vertical position of the branching point. We are often more interested in looking at the overall structure of the dendrogram. For example, we see two big clusters.</p>
<p>First, each of the flower samples is treated as a cluster. The algorithm joins
the two most similar clusters based on a distance function. This is performed
iteratively until there is just a single cluster containing all 150 flowers. At
each iteration, the distances between clusters are recalculated according to one
of the methods—<em>Single linkage, complete linkage, average linkage, and so on</em>.
In the single-linkage method, the distance between two clusters is defined by
the smallest distance among the all possible object pairs. This approach puts
‘friends of friends’ into a cluster. On the contrary, the complete linkage
method defines the distance as the largest distance between object pairs. It
finds similar clusters. Between these two extremes, there are many options in
between. The linkage method I found the most robust is the average linkage
method, which uses the average of all distances. However, the default seems to
be the complete linkage. Thus we need to change that in our final version.</p>
<p><strong>Heat maps</strong> with hierarchical clustering are my favorite way of visualizing data matrices. The rows and columns are reorganized based on hierarchical clustering, and the values in the matrix are coded by colors. Heat maps can directly visualize millions of numbers in one plot. The hierarchical trees also show the similarity among rows and columns.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="visualizing-the-iris-flower-data-set.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(ma, </span>
<span id="cb91-2"><a href="visualizing-the-iris-flower-data-set.html#cb91-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">scale =</span> <span class="st">&quot;column&quot;</span>, </span>
<span id="cb91-3"><a href="visualizing-the-iris-flower-data-set.html#cb91-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">RowSideColors =</span> <span class="fu">rainbow</span>(<span class="dv">3</span>)[iris<span class="sc">$</span>Species] )</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-75-1.png" width="672" /></p>
<p>Scaling is handled by the <strong>scale</strong> function, which subtracts the mean from each
column and then divides by the standard division. Afterward, all the columns
have the same mean of approximately 0 and standard deviation of 1. This is also
called standardization. The default color scheme codes bigger numbers in yellow
and smaller numbers in red. The color bar on the left codes for different
species. But we still miss a legend and many other things can be polished.
Instead of going down the rabbit hole of adjusting dozens of parameters to
heatmap function (and it’s improved version heatmap.2 in the ggplots package), We
will refine this plot using another R package called pheatmap.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="visualizing-the-iris-flower-data-set.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;pheatmap&quot;</span>)</span></code></pre></div>

<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="visualizing-the-iris-flower-data-set.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pheatmap)</span>
<span id="cb93-2"><a href="visualizing-the-iris-flower-data-set.html#cb93-2" aria-hidden="true" tabindex="-1"></a>ma <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]) <span class="co"># convert to matrix</span></span>
<span id="cb93-3"><a href="visualizing-the-iris-flower-data-set.html#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(ma) <span class="ot">&lt;-</span> <span class="fu">row.names</span>(iris) <span class="co"># assign row names in the matrix</span></span>
<span id="cb93-4"><a href="visualizing-the-iris-flower-data-set.html#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">pheatmap</span>(ma, </span>
<span id="cb93-5"><a href="visualizing-the-iris-flower-data-set.html#cb93-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">scale =</span> <span class="st">&quot;column&quot;</span>,</span>
<span id="cb93-6"><a href="visualizing-the-iris-flower-data-set.html#cb93-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">clustering_method =</span> <span class="st">&quot;average&quot;</span>, <span class="co"># average linkage</span></span>
<span id="cb93-7"><a href="visualizing-the-iris-flower-data-set.html#cb93-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">annotation_row =</span> iris[, <span class="dv">5</span>, <span class="at">drop=</span><span class="cn">FALSE</span>], <span class="co"># the 5th column as color bar</span></span>
<span id="cb93-8"><a href="visualizing-the-iris-flower-data-set.html#cb93-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">show_rownames =</span> <span class="cn">FALSE</span> )</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:12-3"></span>
<img src="book_files/figure-html/12-3-1.png" alt="Heatmap for iris flower dataset." width="672" />
<p class="caption">
Figure 2.13: Heatmap for iris flower dataset.
</p>
</div>
<p>First, we convert the first 4 columns of the iris data frame into a matrix. Then
the row names are assigned to be the same, namely, “1” to “150.” This is
required because row names are used to match with the column annotation
information, specified by the annotation_row parameter. Even though we only
need the 5th column, i.e., Species, this has to be a data frame. To prevent R
from automatically converting a one-column data frame into a vector, we used
<em>drop = FALSE</em> option. Multiple columns can be contained in the column
annotation data frame to display multiple color bars. The rows could be
annotated the same way.</p>
<p>More information about the pheatmap function can be obtained by reading the help
document. But most of the times, I rely on the online tutorials. Beyond the
official documents prepared by the author, there are many documents created by R
users across the world. The R user community is uniquely open and supportive. I
was researching heatmap.2, a more refined version of heatmap part of the gplots
package and landed on Dave Tang’s
<a href="https://davetang.org/muse/2010/12/06/making-a-heatmap-with-r/">blog</a>, which
mentioned that there is a more user-friendly package called pheatmap described
in his other
<a href="https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/">blog</a>.
To figure out the code chuck above, I tried several times and also used Kamil
Slowikowski’s <a href="https://slowkow.com/notes/pheatmap-tutorial/">blog</a>.</p>
<p>We can gain many insights from Figure <a href="visualizing-the-iris-flower-data-set.html#fig:12-3">2.13</a>. The 150 flowers in the rows are organized into different clusters. <em>I. Setosa</em> samples obviously formed a unique cluster, characterized by smaller (blue) petal length, petal width, and sepal length. The other two subspecies are not clearly separated but we can notice that some <em>I. Virginica</em> samples form a small subcluster showing bigger petals. The columns are also organized into dendrograms, which clearly suggest that petal length and petal width are highly correlated.</p>
</div>
<div id="principal-component-analysis-pca" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Principal component analysis (PCA)</h2>
<p>This section can be skipped, as it contains more statistics than R programming. To visualize high-dimensional data, we use PCA to map data to l</p>
<p>PCA is a linear dimension-reduction method. As illustrated in Figure <a href="visualizing-the-iris-flower-data-set.html#fig:13-4">2.14</a>, it tries to define a new set of orthogonal coordinates to represent the data such that the new coordinates can be ranked by the amount of variation or information it captures in the dataset. After running PCA, you get many pieces of information:</p>
<ul>
<li>How the new coordinates are defined,</li>
<li>The percentage of variances captured by each of the new coordinates,</li>
<li>A representation of all the data points onto the new coordinates.</li>
</ul>

<div class="figure" style="text-align: center"><span id="fig:13-4"></span>
<img src="images/img1304_PCA.png" alt="Concept of PCA. Here the first component x’ gives a relatively accurate representation of the data." width="75%" />
<p class="caption">
Figure 2.14: Concept of PCA. Here the first component x’ gives a relatively accurate representation of the data.
</p>
</div>
<p>Here’s an example of running PCA on the first 4 columns of the iris data.
Note that “scale = TRUE” in the following
command means that the data is normalized before conduction PCA so that each
variable has unit variance.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="visualizing-the-iris-flower-data-set.html#cb94-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">=</span> <span class="fu">prcomp</span>(iris[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">scale =</span> <span class="cn">TRUE</span>)   </span>
<span id="cb94-2"><a href="visualizing-the-iris-flower-data-set.html#cb94-2" aria-hidden="true" tabindex="-1"></a>pca  <span class="co"># Have a look at the results.</span></span></code></pre></div>
<pre><code>## Standard deviations (1, .., p=4):
## [1] 1.7083611 0.9560494 0.3830886 0.1439265
## 
## Rotation (n x k) = (4 x 4):
##                     PC1         PC2        PC3        PC4
## Sepal.Length  0.5210659 -0.37741762  0.7195664  0.2612863
## Sepal.Width  -0.2693474 -0.92329566 -0.2443818 -0.1235096
## Petal.Length  0.5804131 -0.02449161 -0.1421264 -0.8014492
## Petal.Width   0.5648565 -0.06694199 -0.6342727  0.5235971</code></pre>
<p>The first principal component is positively correlated with Sepal length, petal length, and petal width. Recall that these three variables are highly correlated. Sepal width is the variable that is almost the same across three species with small standard deviation. PC2 is mostly determined by sepal width, less so by sepal length.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="visualizing-the-iris-flower-data-set.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pca)  <span class="co"># plot the amount of variance each principal components captures.</span></span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-78-1.png" width="50%" /></p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="visualizing-the-iris-flower-data-set.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(pca)   <span class="co"># this shows the structure of the object, listing all parts. </span></span></code></pre></div>
<pre><code>## List of 5
##  $ sdev    : num [1:4] 1.708 0.956 0.383 0.144
##  $ rotation: num [1:4, 1:4] 0.521 -0.269 0.58 0.565 -0.377 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:4] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot; &quot;Petal.Length&quot; &quot;Petal.Width&quot;
##   .. ..$ : chr [1:4] &quot;PC1&quot; &quot;PC2&quot; &quot;PC3&quot; &quot;PC4&quot;
##  $ center  : Named num [1:4] 5.84 3.06 3.76 1.2
##   ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot; &quot;Petal.Length&quot; &quot;Petal.Width&quot;
##  $ scale   : Named num [1:4] 0.828 0.436 1.765 0.762
##   ..- attr(*, &quot;names&quot;)= chr [1:4] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot; &quot;Petal.Length&quot; &quot;Petal.Width&quot;
##  $ x       : num [1:150, 1:4] -2.26 -2.07 -2.36 -2.29 -2.38 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : NULL
##   .. ..$ : chr [1:4] &quot;PC1&quot; &quot;PC2&quot; &quot;PC3&quot; &quot;PC4&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;prcomp&quot;</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="visualizing-the-iris-flower-data-set.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pca<span class="sc">$</span>x)  <span class="co"># the new coordinate values for each of the 150 samples</span></span></code></pre></div>
<pre><code>##            PC1        PC2         PC3          PC4
## [1,] -2.257141 -0.4784238  0.12727962  0.024087508
## [2,] -2.074013  0.6718827  0.23382552  0.102662845
## [3,] -2.356335  0.3407664 -0.04405390  0.028282305
## [4,] -2.291707  0.5953999 -0.09098530 -0.065735340
## [5,] -2.381863 -0.6446757 -0.01568565 -0.035802870
## [6,] -2.068701 -1.4842053 -0.02687825  0.006586116</code></pre>
<p>To plot the PCA results, we first construct a data frame with all information, as required by ggplot2.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="visualizing-the-iris-flower-data-set.html#cb101-1" aria-hidden="true" tabindex="-1"></a>pcaData <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(pca<span class="sc">$</span>x[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])  <span class="co"># extract first two columns and convert to data frame</span></span>
<span id="cb101-2"><a href="visualizing-the-iris-flower-data-set.html#cb101-2" aria-hidden="true" tabindex="-1"></a>pcaData <span class="ot">&lt;-</span> <span class="fu">cbind</span>(pcaData, iris<span class="sc">$</span>Species) <span class="co"># bind by columns</span></span>
<span id="cb101-3"><a href="visualizing-the-iris-flower-data-set.html#cb101-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(pcaData) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;PC1&quot;</span>, <span class="st">&quot;PC2&quot;</span>, <span class="st">&quot;Species&quot;</span>) <span class="co"># change column names</span></span>
<span id="cb101-4"><a href="visualizing-the-iris-flower-data-set.html#cb101-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-5"><a href="visualizing-the-iris-flower-data-set.html#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb101-6"><a href="visualizing-the-iris-flower-data-set.html#cb101-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pcaData) <span class="sc">+</span></span>
<span id="cb101-7"><a href="visualizing-the-iris-flower-data-set.html#cb101-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(PC1, PC2, <span class="at">color =</span> Species, <span class="at">shape =</span> Species) <span class="sc">+</span>   <span class="co"># define plot area</span></span>
<span id="cb101-8"><a href="visualizing-the-iris-flower-data-set.html#cb101-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>)                                <span class="co"># adding data points</span></span></code></pre></div>
<p>Now we have a basic plot. We are adding elements one by one using the “+” sign at the end of the first line. We will add details to this plot.</p>

<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="visualizing-the-iris-flower-data-set.html#cb102-1" aria-hidden="true" tabindex="-1"></a>percentVar <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">summary</span>(pca)<span class="sc">$</span>importance[<span class="dv">2</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="dv">0</span>)     <span class="co"># compute % variances</span></span>
<span id="cb102-2"><a href="visualizing-the-iris-flower-data-set.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pcaData, <span class="fu">aes</span>(PC1, PC2, <span class="at">color =</span> Species, <span class="at">shape =</span> Species)) <span class="sc">+</span>  <span class="co"># starting ggplot2</span></span>
<span id="cb102-3"><a href="visualizing-the-iris-flower-data-set.html#cb102-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span>                                       <span class="co"># add data points</span></span>
<span id="cb102-4"><a href="visualizing-the-iris-flower-data-set.html#cb102-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">xlab</span>(<span class="fu">paste0</span>(<span class="st">&quot;PC1: &quot;</span>, percentVar[<span class="dv">1</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="sc">+</span>         <span class="co"># x label</span></span>
<span id="cb102-5"><a href="visualizing-the-iris-flower-data-set.html#cb102-5" aria-hidden="true" tabindex="-1"></a>         <span class="fu">ylab</span>(<span class="fu">paste0</span>(<span class="st">&quot;PC2: &quot;</span>, percentVar[<span class="dv">2</span>], <span class="st">&quot;% variance&quot;</span>)) <span class="sc">+</span>         <span class="co"># y label</span></span>
<span id="cb102-6"><a href="visualizing-the-iris-flower-data-set.html#cb102-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">ggtitle</span>(<span class="st">&quot;Principal component analysis (PCA)&quot;</span>) <span class="sc">+</span>              <span class="co"># title            </span></span>
<span id="cb102-7"><a href="visualizing-the-iris-flower-data-set.html#cb102-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">theme</span>(<span class="at">aspect.ratio =</span> <span class="dv">1</span>)                                      <span class="co"># width and height ratio        </span></span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:13-5"></span>
<img src="book_files/figure-html/13-5-1.png" alt="PCA plot of the iris flower dataset using R base graphics (left) and ggplot2 (right)." width="80%" />
<p class="caption">
Figure 2.15: PCA plot of the iris flower dataset using R base graphics (left) and ggplot2 (right).
</p>
</div>
<p>The result (Figure <a href="visualizing-the-iris-flower-data-set.html#fig:13-5">2.15</a>) is a projection of the 4-dimensional iris flowering data on 2-dimensional space using the first two principal components. We can see that the first principal component alone is useful in distinguishing the three species. We could use simple rules like this: If PC1 &lt; -1, then Iris setosa. If PC1 &gt; 1.5 then Iris virginica. If -1 &lt; PC1 &lt; 1, then Iris versicolor.</p>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-81" class="exercise"><strong>Exercise 2.6  </strong></span></p>
Create PCA plot of the state.x77 data set (convert matrix to data frame). Use the state.region information to color code the states. Interpret your results. Hint: do not forget normalization using the scale option.
</div>
</blockquote>
</div>
<div id="classification-by-predicting-the-odds-of-binary-outcomes" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Classification by predicting the odds of binary outcomes</h2>
<p>This section can be skipped, as it contains more statistics than R programming.</p>
<p>It is easy to distinguish <em>I. setosa</em> from the other two species, just based on
petal length alone. Here we focus on building a predictive model that can
predict between <em>I. versicolor</em> and <em>I. virginica</em>. For this we use the logistic
regression to model the odds ratio of being <em>I. virginica</em> as a function of all
of the 4 measurements:</p>
<p><span class="math display">\[ln(odds)=ln(\frac{p}{1-p})
                     =a×Sepal.Length + b×Sepal.Width + c×Petal.Length + d×Petal.Width+c+e.\]</span></p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="visualizing-the-iris-flower-data-set.html#cb103-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> iris[<span class="dv">51</span><span class="sc">:</span><span class="dv">150</span>, ]  <span class="co"># removes the first 50 samples, which represent I. setosa</span></span>
<span id="cb103-2"><a href="visualizing-the-iris-flower-data-set.html#cb103-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(df)  <span class="co"># removes setosa, an empty levels of species.</span></span>
<span id="cb103-3"><a href="visualizing-the-iris-flower-data-set.html#cb103-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">glm</span>(Species <span class="sc">~</span> . ,  <span class="co"># Model: Species as a function of other variables</span></span>
<span id="cb103-4"><a href="visualizing-the-iris-flower-data-set.html#cb103-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&#39;logit&#39;</span>), </span>
<span id="cb103-5"><a href="visualizing-the-iris-flower-data-set.html#cb103-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> df)  </span>
<span id="cb103-6"><a href="visualizing-the-iris-flower-data-set.html#cb103-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Species ~ ., family = binomial(link = &quot;logit&quot;), 
##     data = df)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.01105  -0.00541  -0.00001   0.00677   1.78065  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept)   -42.638     25.707  -1.659   0.0972 .
## Sepal.Length   -2.465      2.394  -1.030   0.3032  
## Sepal.Width    -6.681      4.480  -1.491   0.1359  
## Petal.Length    9.429      4.737   1.991   0.0465 *
## Petal.Width    18.286      9.743   1.877   0.0605 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 138.629  on 99  degrees of freedom
## Residual deviance:  11.899  on 95  degrees of freedom
## AIC: 21.899
## 
## Number of Fisher Scoring iterations: 10</code></pre>
<p>Sepal length and width are not useful in distinguishing versicolor from
<em>virginica</em>. The most significant (P=0.0465) factor is Petal.Length. One unit
increase in petal length will increase the log-odds of being <em>virginica</em> by
9.429. A marginally significant effect is found for Petal.Width.</p>
<p>If you do not fully understand the mathematics behind linear regression or
logistic regression, do not worry about it too much. In this class, I
just want to show you how to do these analyses in R and interpret the results. I
do not understand how computers work. Yet I <strong>use</strong> it every day.</p>
<blockquote>

<div class="exercise">
<p><span id="exr:unnamed-chunk-83" class="exercise"><strong>Exercise 2.7  </strong></span></p>
<p>So far, we used a variety of techniques to investigate the iris flower dataset. Recall that in the very beginning, I asked you to eyeball the data and answer two questions:</p>
<ol style="list-style-type: lower-alpha">
<li>What distinguishes these three species?</li>
<li>If we have a flower with sepals of 6.5cm long and 3.0cm wide, petals of 6.2cm long, and 2.2cm wide, which species does it most likely belong to?</li>
</ol>
Review all the analysis we did, examine the raw data, and answer the above questions. Write a paragraph and provide evidence of your thinking. Do more analysis if needed.
</div>
</blockquote>
<p>References:
1 Beckerman, A. (2017). Getting started with r second edition. New York, NY, Oxford University Press.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="step-into-r-programmingthe-iris-flower-dataset.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-structures.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
